Repository angular/angular-cli, pull requests merged in 2018-09, with the labels that each got.

#11979 feat(@schematics/angular): add several prompts to ng-new
  packages/schematics/angular/ng-new/schema.json
Labels: PR target: master-only, cla: yes

#12037 refactor(@angular-devkit/build-angular): clean up style webpack config
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/postcss-cli-resources.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/webpack.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#11841 fix(@angular-devkit/schematics): throw `InvalidCollectionJsonExceptio…
  packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts
  packages/angular_devkit/schematics/tools/node-module-engine-host.ts
Labels: PR target: master & patch, cla: yes

#11978 fix(@angular-devkit/schematics): fix `generate` mangling files contai…
  packages/angular_devkit/schematics/src/tree/recorder.ts
  packages/angular_devkit/schematics/src/utility/update-buffer.ts
  packages/angular_devkit/schematics/src/utility/update-buffer_spec.ts
Labels: PR target: master & patch, cla: yes

#12071 docs(stories): update proxy.md with correct path
  docs/documentation/stories/proxy.md
Labels: PR target: master & patch, cla: yes

#12081 fix(@schematics/angular): app shell schematic does not use production configuration
  packages/schematics/angular/app-shell/index.ts
  packages/schematics/angular/app-shell/index_spec.ts
Labels: PR target: master & patch, cla: yes

#12187 fix(@schematics/angular): fix path for `ngswConfigPath` during migration
  packages/schematics/angular/migrations/update-6/index.ts
Labels: PR target: master & patch, cla: yes

#12176 ci: update CI to node 10
  .appveyor.yml
  .circleci/config.yml
  WORKSPACE
  package.json
Labels: PR target: master-only, cla: yes

#12005 feat(@angular/pwa): support customized workspace configurations with add
  packages/angular/pwa/BUILD
  packages/angular/pwa/package.json
  packages/angular/pwa/pwa/index.ts
  packages/angular/pwa/pwa/index_spec.ts
  packages/angular/pwa/utility/config.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#12185 feat: pin down all direct dependencies
  packages/angular/cli/package.json
  packages/angular/pwa/package.json
  packages/angular_devkit/architect/package.json
  packages/angular_devkit/architect/test/package.json
  packages/angular_devkit/architect_cli/package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_ng_packagr/package.json
  packages/angular_devkit/build_optimizer/package.json
  packages/angular_devkit/build_webpack/package.json
  packages/angular_devkit/core/package.json
  packages/angular_devkit/schematics/package.json
  packages/angular_devkit/schematics_cli/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/package.json
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/update/package.json
  tests/legacy-cli/e2e/tests/build/rebuild-replacements.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#12177 fix(@schematics/angular): `module` imports paths are incorrect when `flat` option is used
  packages/schematics/angular/module/index.ts
  packages/schematics/angular/module/index_spec.ts
Labels: PR target: master & patch, cla: yes

#12188 fix(@schematics/angular): use app root to set server paths in options
  packages/schematics/angular/migrations/update-6/index.ts
  packages/schematics/angular/migrations/update-6/index_spec.ts
Labels: PR target: master & patch, cla: yes

#12047 ci: add back angular snapshot e2e on master
  .circleci/config.yml
  tests/legacy-cli/e2e/setup/015-build.ts
  tests/legacy-cli/e2e/setup/500-create-project.ts
  tests/legacy-cli/e2e/tests/build/build-app-shell-with-schematic.ts
  tests/legacy-cli/e2e/tests/build/build-app-shell.ts
  tests/legacy-cli/e2e/tests/build/platform-server.ts
  tests/legacy-cli/e2e/tests/build/rebuild-replacements.ts
  tests/legacy-cli/e2e/tests/build/typescript/typescript-2_7.ts
  tests/legacy-cli/e2e/utils/project.ts
  tests/legacy-cli/e2e_runner.ts
Labels: PR target: master-only, cla: yes

#12229 refactor(@schematics/angular): make interaction with architect targets type safe
  packages/schematics/angular/app-shell/index.ts
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/class/index.ts
  packages/schematics/angular/component/index.ts
  packages/schematics/angular/directive/index.ts
  packages/schematics/angular/e2e/index.ts
  packages/schematics/angular/enum/index.ts
  packages/schematics/angular/guard/index.ts
  packages/schematics/angular/interface/index.ts
  packages/schematics/angular/library/index.ts
  packages/schematics/angular/module/index.ts
  packages/schematics/angular/pipe/index.ts
  packages/schematics/angular/service-worker/index.ts
  packages/schematics/angular/service-worker/schema.d.ts
  packages/schematics/angular/service/index.ts
  packages/schematics/angular/universal/index.ts
  packages/schematics/angular/utility/config.ts
  packages/schematics/angular/utility/project-targets.ts
  packages/schematics/angular/utility/project.ts
  packages/schematics/angular/utility/project_spec.ts
  packages/schematics/angular/utility/workspace-models.ts
Labels: PR target: master-only, cla: yes

#12172 fix(main): match styleguide catch callback
  packages/schematics/angular/application/files/src/main.ts
Labels: PR target: master & patch, cla: yes

#12235 docs: fix asset input path
  docs/documentation/stories/asset-configuration.md
Labels: PR target: master & patch, cla: yes

#12250 Global Angular Configuration Check
  packages/angular/cli/lib/cli/index.ts
  packages/angular/cli/models/command.ts
Labels: PR target: master-only, cla: yes

#12203 build: match engines with bazel and CI
  WORKSPACE
  package.json
Labels: PR target: master-only, cla: yes

#12232 fix(@angular/cli): fix issues in google3
  packages/angular/cli/BUILD
  packages/angular_devkit/core/src/json/schema/registry.ts
  packages/angular_devkit/schematics/tools/fallback-engine-host.ts
  packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts
Labels: PR target: master-only, cla: yes

#12202 build: use specific engines for built packages
  lib/packages.ts
  packages/angular/cli/package.json
  packages/angular_devkit/schematics_cli/package.json
  packages/ngtools/webpack/package.json
Labels: PR target: master & patch, cla: yes

#12271 build: update pidusage
  packages/angular_devkit/benchmark/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#12286 feat(@ngtools/webpack): add support for `traceResolution`
  packages/ngtools/webpack/src/compiler_host.ts
  tests/legacy-cli/e2e/tests/misc/trace-resolution.ts
Labels: PR target: master-only, cla: yes

#12269 docs: add jsdoc instead of comments
  packages/angular_devkit/benchmark/src/interfaces.ts
Labels: PR target: master-only, cla: yes

#12277 refactor(@schematics/angular): Parameterize findModule
  packages/schematics/angular/utility/find-module.ts
  packages/schematics/angular/utility/find-module_spec.ts
Labels: PR target: master & patch, cla: yes

#12291 feat(@angular-devkit/build-angular): enable sourcemaps by default when using karma
  packages/angular_devkit/build_angular/src/karma/schema.json
Labels: PR target: master-only, cla: yes

#12293 docs: remove `--prod` as it's no longer needed
  docs/documentation/stories/create-library.md
Labels: PR target: master & patch, cla: yes

#12267 fix(@angular-devkit/build-angular): fully remove url inlining
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#12297 fix(@angular/cli): support `--version` option
  packages/angular/cli/models/command-runner.ts
  tests/legacy-cli/e2e/tests/misc/version.ts
Labels: PR target: master-only, cla: yes

#12301 build: update nvmrc to use node 10
  .nvmrc
Labels: PR target: master-only, cla: yes

#12303 feat(@angular-devkit/build-angular): update webpack dependencies
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#12204 fix(@angular/cli): fix schema error Property `targets` is not allowed
  packages/angular/cli/lib/config/schema.json
Labels: PR target: master & patch, cla: yes

#11278 fix(@schematics/angular): remove module test
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/library/index.ts
  packages/schematics/angular/module/files/__name@dasherize@if-flat__/__name@dasherize__.module.spec.ts
  packages/schematics/angular/module/index.ts
  packages/schematics/angular/module/index_spec.ts
  packages/schematics/angular/module/schema.json
Labels: PR target: master-only, cla: yes

#12253 Updated generate doc to include aliases
  docs/documentation/generate.md
  docs/documentation/generate/app-shell.md
  docs/documentation/generate/application.md
  docs/documentation/generate/class.md
  docs/documentation/generate/component.md
  docs/documentation/generate/directive.md
  docs/documentation/generate/enum.md
  docs/documentation/generate/guard.md
  docs/documentation/generate/interface.md
  docs/documentation/generate/library.md
  docs/documentation/generate/module.md
  docs/documentation/generate/pipe.md
  docs/documentation/generate/service.md
  docs/documentation/generate/universal.md
Labels: PR target: master & patch, cla: yes

#12331 Remove --help-json leftovers.
  packages/angular/cli/models/architect-command.ts
  packages/angular/cli/models/command.ts
  packages/angular/cli/models/interface.ts
  scripts/snapshots.ts
Labels: cla: yes

#12330 feat(@angular-devkit/schematics): allow workflow impl to define their own sinks
  packages/angular_devkit/schematics/src/sink/sink.ts
  packages/angular_devkit/schematics/src/workflow/base.ts
Labels: PR target: master-only, cla: yes

#12327 fix(@angular/cli): cannot use same target name in when having multiple projects
  packages/angular/cli/models/architect-command.ts
  tests/legacy-cli/e2e/tests/misc/multiple-targets.ts
Labels: PR target: master-only, cla: yes

#12328 ci: add size check of new project production build
  .circleci/config.yml
  .github/angular-robot.yml
  tests/legacy-cli/e2e/tests/basic/build.ts
  tests/legacy-cli/e2e/utils/fs.ts
Labels: PR target: master-only, cla: yes

#12334 docs: example command to generate library
  docs/documentation/generate/library.md
Labels: PR target: master & patch, cla: yes

#12341 ci: fix parallelism for e2e node 8.x job
  .circleci/config.yml
Labels: PR target: master-only, cla: yes

#11649 fix: suggest windows-compatible typescript install command
  packages/angular/cli/upgrade/version.ts
Labels: PR target: master & patch, cla: yes

#11335 docs(@angular-devkit/schematics): extended Schematics README regarding templating
  packages/angular_devkit/schematics/README.md
Labels: PR target: master-only, cla: yes

#11407 fix(@angular-devkit/build-angular): support of tsx files in aot mode
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts
Labels: cla: yes

#11450 fix(@angular-devkit/build-angular): support of tsx absolute path import
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/ngtools/webpack/src/paths-plugin.ts
  packages/ngtools/webpack/src/transformers/ast_helpers.ts
Labels: cla: yes

#11574 fix(@angular-devkit/core): fix cannot delete directory in memory of virtual-fs
  packages/angular_devkit/core/src/virtual-fs/host/memory.ts
  packages/angular_devkit/core/src/virtual-fs/host/memory_spec.ts
Labels: cla: yes

#12358 test: add unit test to cover `subdirs`
  packages/angular_devkit/schematics/src/tree/host-tree_spec.ts
Labels: PR target: master & patch, cla: yes

#12355 docs: initial schematic prompts documentation
  docs/specifications/schematic-prompts.md
Labels: PR target: master-only, cla: yes

#12356 fix(@angular/cli): allow global config command outside project
  packages/angular/cli/commands/config-impl.ts
  packages/angular/cli/commands/config.json
  packages/angular/cli/models/command.ts
  tests/legacy-cli/e2e/tests/commands/config/config-global.ts
Labels: PR target: master & patch, cla: yes

#11599 fix(@schematics/angular): dasherize library package name
  packages/schematics/angular/library/index.ts
Labels: PR target: master-only, cla: yes

#12367 fix(@angular/cli): `--verbose` is an unknown option of `serve`
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/dev-server/schema.json
  packages/angular_devkit/build_angular/test/dev-server/works_spec_large.ts
Labels: PR target: master & patch, cla: yes

#11864 docs: add local installation and specific version installation instructions for angular-cli
  packages/angular/cli/README.md
Labels: PR target: master-only, cla: yes

#12014 feat(@schematics/angular): add default budget of 2mb/5mb
  packages/schematics/angular/application/index.ts
Labels: cla: yes

#12068 docs: convert console image in microsite to css
  etc/cli.angular.io/cli-logo.svg
  etc/cli.angular.io/index.html
  etc/cli.angular.io/main.css
  etc/cli.angular.io/theme.css
Labels: PR target: master-only, cla: yes

#12373 build: fix build
  packages/schematics/angular/e2e/index.ts
  packages/schematics/angular/utility/workspace-models.ts
Labels: PR target: master-only, cla: yes

#12284 Set of fixes for better npmrc parameters support
  packages/schematics/update/update/npm.ts
Labels: PR target: master-only, cla: yes

#12002 build: ensure @ngtools/webpack uses consistent TS version
  package.json
Labels: PR target: master-only, cla: yes

#12370 refactor(@angular-devkit/build-angular): clean up overriding of options
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: PR target: master-only, cla: yes

#12371 fix(@angular-devkit/build-angular) karma builder now serves global st…
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma-context.html
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma-debug.html
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma.ts
  packages/angular_devkit/build_angular/test/karma/styles_spec_large.ts
Labels: PR target: master & patch, cla: yes

#12380 style: remove redundant async in tests
  packages/schematics/angular/application/other-files/app.component.spec.ts
Labels: PR target: master & patch, cla: yes

#12376 Parsing fixes
  packages/angular/cli/models/parser.ts
  packages/angular/cli/models/parser_spec.ts
Labels: PR target: master-only, cla: yes

#12085 feat(@angular/cli): add `--defaults` option to `ng new`
  packages/angular/cli/commands/definitions.json
  packages/angular/cli/models/schematic-command.ts
Labels: PR target: master-only, cla: yes, need: further discussion

#11815 Fix(@schematics/angular): support `Fetch as Google`（Google bot)
  packages/schematics/angular/application/files/src/polyfills.ts
Labels: cla: yes
