Repository angular/angular-cli, pull requests merged in 2018-11, with the labels that each got.

#12721 build: Use fine-grained node_module deps
  .bazelignore
  .bazelrc
  .circleci/config.yml
  BUILD
  WORKSPACE
  package.json
  packages/angular/cli/BUILD
  packages/angular/pwa/BUILD
  packages/angular_devkit/architect/BUILD
  packages/angular_devkit/architect_cli/BUILD
  packages/angular_devkit/benchmark/BUILD
  packages/angular_devkit/build_optimizer/BUILD
  packages/angular_devkit/core/BUILD
  packages/angular_devkit/core/node/resolve.ts
  packages/angular_devkit/schematics/BUILD
  packages/angular_devkit/schematics_cli/BUILD
  packages/schematics/angular/BUILD
  packages/schematics/schematics/BUILD
  packages/schematics/update/BUILD
  scripts/validate-licenses.ts
  tests/angular_devkit/schematics/tools/file-system-engine-host/BUILD
  tools/BUILD
  tools/build_event_protocol/BUILD
  tools/ts_json_schema.bzl
  tsconfig-test.json
  tsconfig.json
  yarn.lock
Labels: PR target: master & patch, cla: yes

#12730 feat(@schematics/angular): install packages when creating a new application
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/ng-new/index.ts
Labels: PR target: master-only, cla: yes

#12735 Enable Webpack E2Es
  packages/ngtools/webpack/src/virtual_file_system_decorator.ts
  tests/legacy-cli/e2e_runner.ts
Labels: PR target: master-only, cla: yes

#12748 fix(@angular-devkit/build-angular): improve bundle size value displaying
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
Labels: PR target: master & patch, cla: yes

#12749 fix(@schematics/angular) order of `module` properties is inconsistent
  packages/schematics/angular/module/files/__name@dasherize@if-flat__/__name@dasherize__.module.ts
Labels: PR target: master & patch, cla: yes

#12758 build: Add module_name for @schematics/angular
  packages/schematics/angular/BUILD
Labels: PR target: master & patch, cla: yes

#12759 style: fix indentation in tslint.json
  packages/schematics/angular/library/files/__projectRoot__/tslint.json
Labels: PR target: master & patch, cla: yes

#12764 fix(@ngtools/webpack): print error message on new line
  packages/angular/cli/models/architect-command.ts
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master & patch, cla: yes

#12767 fix(@angular/cli): errors and warnings are hard to read in windows cmd
  packages/angular/cli/lib/cli/index.ts
  packages/angular_devkit/core/node/cli-logger.ts
Labels: PR target: master & patch, cla: yes

#12786 fix(@schematics/angular): minimal workspace flag leaves blank line in …
  packages/schematics/angular/workspace/files/package.json
Labels: PR target: master & patch, cla: yes

#12788 docs: update descriptions for builders
  packages/angular_devkit/build_angular/src/dev-server/schema.json
  packages/angular_devkit/build_angular/src/server/schema.json
Labels: PR target: master & patch, cla: yes

#12802 refactor: fix english in update message
  packages/schematics/update/update/index.ts
Labels: PR target: master & patch, cla: yes

#12812 docs: remove UglifyJS mention
  packages/angular_devkit/build_optimizer/README.md
Labels: PR target: master & patch, cla: yes

#12813 docs: production build configuration for app-shell
  docs/documentation/stories/app-shell.md
Labels: PR target: master & patch, cla: yes

#12826 build: Fix webpack dependencies for patch branch
  yarn.lock
Labels: PR target: patch-only, cla: yes

#12768 fix(@schematics/angular): update `@angular-devkit/build-ng-packagr` w…
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-7/devkit-ng-packagr.ts
  packages/schematics/angular/migrations/update-7/devkit-ng-packagr_spec.ts
  packages/schematics/angular/migrations/update-7/index.ts
Labels: PR target: master & patch, cla: yes

#12811 feat(@schematics/angular): add profiling files to gitignore
  packages/schematics/angular/workspace/files/__dot__gitignore
Labels: PR target: master-only, cla: yes

#12820 fix(@angular-devkit/schematics-cli): dryRun is not set by default when using a local collection
  packages/angular_devkit/schematics_cli/bin/schematics.ts
  packages/angular_devkit/schematics_cli/bin/schematics_spec.ts
Labels: PR target: master-only, cla: yes

#12836 test(@angular/cli): fix implicit import
  packages/angular/cli/utilities/json-schema_spec.ts
Labels: PR target: master & patch, cla: yes

#12819 fix(@schematics/angular): add serverTarget to app shell production configuration
  packages/schematics/angular/app-shell/index.ts
  packages/schematics/angular/app-shell/index_spec.ts
Labels: PR target: master & patch, cla: yes

#12742 fix(@schematics/angular): --minimal should prevent generating e2e
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/ng-new/index.ts
  packages/schematics/angular/ng-new/index_spec.ts
Labels: PR target: master & patch, cla: yes

#12870 fix(@angular-devkit/build-angular): allow only patch version of webpack
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: patch-only, cla: yes

#12879 build: add external block for tsconfig in test targets
  packages/angular_devkit/benchmark/BUILD
  packages/angular_devkit/build_optimizer/BUILD
  packages/angular_devkit/core/BUILD
  packages/angular_devkit/schematics/BUILD
  packages/schematics/angular/BUILD
  packages/schematics/schematics/BUILD
  packages/schematics/update/BUILD
Labels: cla: yes

#12884 ci: fix 1.7 e2e test project by pinning jasmine typings version
  tests/legacy-cli/e2e/assets/1.7-project/package.json
Labels: cla: yes

#12881 build: fix BUILD files for g3 sync
  packages/angular/cli/BUILD
  packages/angular_devkit/architect/BUILD
  packages/angular_devkit/core/BUILD
  packages/angular_devkit/schematics/BUILD
  packages/schematics/angular/BUILD
Labels: cla: yes

#12873 fix(@angular-devkit/core): fix 'this' check
  packages/angular_devkit/core/src/json/schema/registry.ts
Labels: PR target: master-only, cla: yes

#12753 feat(@angular/cli): autodetect default package manager
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/models/schematic-command.ts
  packages/angular/cli/utilities/check-package-manager.ts
  packages/angular/cli/utilities/config.ts
  packages/angular/cli/utilities/package-manager.ts
Labels: PR target: master-only, cla: yes

#12783 fix(@angular/cli): support all single dashes prefixed arguments
  packages/angular/cli/models/parser.ts
  packages/angular/cli/models/parser_spec.ts
Labels: PR target: master & patch, cla: yes

#12801 feat(@angular-devkit/build-angular): update webpack
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#12833 feat(@angular-devkit/build-angular): improve verbose output
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/stats.ts
Labels: PR target: master-only, cla: yes

#12848 refactor: remove `experimentalAngularNext`
  packages/schematics/angular/workspace/files/package.json
  packages/schematics/angular/workspace/schema.json
Labels: PR target: master & patch, cla: yes

#12849 build: update typescript to 3.1.6
  package.json
  packages/angular_devkit/build_optimizer/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/package.json
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/schematics/blank/project-files/package.json
  packages/schematics/schematics/schematic/files/package.json
  yarn.lock
Labels: PR target: master & patch, cla: yes

#12850 Minimal flag
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/workspace/index.ts
  packages/schematics/angular/workspace/index_spec.ts
Labels: PR target: master & patch, cla: yes

#12890 feat(@angular-devkit/build-angular): update node-sass
  packages/angular_devkit/build_angular/package.json
Labels: PR target: master-only, cla: yes

#12787 refactor: use `createConsoleLogger` and remove duplicate code
  packages/angular/cli/lib/cli/index.ts
  packages/angular/cli/models/architect-command.ts
  packages/angular_devkit/core/node/cli-logger.ts
  tests/legacy-cli/e2e/tests/build/bundle-budgets.ts
  tests/legacy-cli/e2e/tests/misc/circular-dependency.ts
Labels: PR target: master-only, cla: yes

#12503 fix(@ngtools/webpack): replace resources should effect only class dec…
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/ngtools/webpack/src/transformers/find_resources.ts
  packages/ngtools/webpack/src/transformers/find_resources_spec.ts
  packages/ngtools/webpack/src/transformers/index.ts
  packages/ngtools/webpack/src/transformers/replace_resources.ts
  packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
Labels: PR target: master-only, cla: yes

#12593 feat(@ngtools/webpack): allow custom lazy module resource
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master-only, cla: yes

#12785 feat(@angular-devkit/build-angular): update webpack dependencies
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#12854 ci: fast track docs-preview snapshot
  .circleci/config.yml
Labels: cla: yes

#12889 fix(@angular-devkit/build-angular): add a base href to karma context
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma-context.html
Labels: PR target: master & patch, cla: yes

#12902 feat(@ngtools/webpack): disable sourcefile cache when not in watch mode
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/ngtools/webpack/src/compiler_host.ts
  packages/ngtools/webpack/src/transformers/ast_helpers.ts
  packages/ngtools/webpack/src/type_checker.ts
Labels: PR target: master-only, cla: yes

#12843 feat(@angular/cli): allow flags to have deprecation
  packages/angular/cli/models/architect-command.ts
  packages/angular/cli/models/command-runner.ts
  packages/angular/cli/models/interface.ts
  packages/angular/cli/models/parser.ts
  packages/angular/cli/models/parser_spec.ts
  packages/angular/cli/models/schematic-command.ts
  packages/angular/cli/utilities/json-schema.ts
Labels: PR target: master-only, cla: yes

#12871 fix(@schematics/update): improve npmrc discovery
  package.json
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/models/schematic-command.ts
  packages/schematics/update/BUILD
  packages/schematics/update/package.json
  packages/schematics/update/update/index.ts
  packages/schematics/update/update/npm.ts
  packages/schematics/update/update/schema.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#12512 fix(@schematics/angular): rename e2e PO utility function
  packages/schematics/angular/e2e/files/src/app.e2e-spec.ts
  packages/schematics/angular/e2e/files/src/app.po.ts
  tests/angular_devkit/build_angular/hello-world-app/e2e/app.e2e-spec.ts
  tests/angular_devkit/build_angular/hello-world-app/e2e/app.po.ts
Labels: PR target: master & patch, cla: yes

#12789 style: add comments in tslint.json
  tslint.json
Labels: PR target: master & patch, cla: yes

#12899 tests: use `toContain` instead of `indexOf`
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/class/index_spec.ts
  packages/schematics/angular/component/index_spec.ts
  packages/schematics/angular/directive/index_spec.ts
  packages/schematics/angular/e2e/index_spec.ts
  packages/schematics/angular/enum/index_spec.ts
  packages/schematics/angular/guard/index_spec.ts
  packages/schematics/angular/interface/index_spec.ts
  packages/schematics/angular/library/index_spec.ts
  packages/schematics/angular/module/index_spec.ts
  packages/schematics/angular/ng-new/index_spec.ts
  packages/schematics/angular/pipe/index_spec.ts
  packages/schematics/angular/service/index_spec.ts
  packages/schematics/angular/workspace/index_spec.ts
Labels: PR target: master & patch, cla: yes

#12911 fix(@ngtools/webpack): update error message to reference templateUrl
  packages/ngtools/webpack/src/resource_loader.ts
Labels: PR target: master & patch, cla: yes

#12913 refactor(@ngtools/webpack): cleanup/optimize emit logic
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master-only, cla: yes

#12935 style: update editorconfig website url
  .editorconfig
  packages/schematics/angular/workspace/files/__dot__editorconfig
  tests/angular_devkit/build_angular/hello-world-app/.editorconfig
  tests/legacy-cli/e2e/assets/1.0-project/.editorconfig
  tests/legacy-cli/e2e/assets/1.7-project/.editorconfig
Labels: PR target: master & patch, cla: yes

#12937 docs: update long descriptions for test, e2e and lint
  packages/angular/cli/commands/e2e-long.md
  packages/angular/cli/commands/lint-long.md
  packages/angular/cli/commands/test-long.md
  packages/angular/cli/commands/test.json
Labels: PR target: master & patch, cla: yes

#12941 fix(@angular/cli): silence package manager not found messages
  packages/angular/cli/utilities/package-manager.ts
Labels: PR target: master-only, cla: yes

#12945 Fix lazy loading
  packages/angular_devkit/build_angular/test/browser/lazy-module_spec_large.ts
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master-only, cla: yes

#12951 fix(@angular-devkit/core): handle drive only paths in windows
  packages/angular_devkit/core/src/virtual-fs/path.ts
  packages/angular_devkit/core/src/virtual-fs/path_spec.ts
Labels: PR target: master & patch, cla: yes

#12953 fix(@schematics/angular): `addSymbolToNgModuleMetadata` metadata with…
  packages/schematics/angular/utility/ast-utils.ts
  packages/schematics/angular/utility/ast-utils_spec.ts
Labels: PR target: master & patch, cla: yes

#12957 docs: typo in library command docs
  packages/schematics/angular/library/library-long.md
Labels: PR target: master-only, cla: yes

#12959 fix(@angular/cli): add missing `ngswConfigPath` to schema
  packages/angular/cli/lib/config/schema.json
Labels: PR target: master & patch, cla: yes

#12966 refactor: deprecate `evalSourceMap`
  packages/angular_devkit/build_angular/src/browser/schema.d.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/dev-server/schema.json
  packages/angular_devkit/build_angular/src/karma/schema.json
  packages/angular_devkit/build_angular/src/server/schema.json
Labels: PR target: master-only, cla: yes

#12965 fix(@angular-devkit/build-angular): remove `skipAppShell` as it has no effect in browser builder
  packages/angular_devkit/build_angular/src/browser/schema.d.ts
  packages/angular_devkit/build_angular/src/browser/schema.json
Labels: PR target: master-only, cla: yes

#12942 test(@angular-devkit/build-angular): update angular test dependencies
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_ng_packagr/package.json
  packages/ngtools/webpack/package.json
  yarn.lock
Labels: PR target: master & patch, cla: yes

#12627 fix(@angular/cli): improve architect command project parsing
  packages/angular/cli/models/architect-command.ts
  tests/legacy-cli/e2e/tests/basic/build.ts
Labels: PR target: master-only, cla: yes

#12793 fix(@angular/cli): handle case senstive aliases
  packages/angular/cli/models/parser.ts
  packages/angular/cli/models/parser_spec.ts
Labels: PR target: master & patch, cla: yes

#12973 ci: packages script should list public packages
  scripts/packages.ts
Labels: PR target: master-only, cla: yes

#12972 feat(@angular-devkit/schematics-cli): add prompt support using Inquirer
  packages/angular_devkit/schematics_cli/BUILD
  packages/angular_devkit/schematics_cli/bin/schematics.ts
  packages/angular_devkit/schematics_cli/package.json
Labels: PR target: master-only, cla: yes

#13002 feat(@schematics/angular): add .history directory to gitignore
  packages/schematics/angular/workspace/files/__dot__gitignore
Labels: PR target: master-only, cla: yes

#12992 docs: typo in library command docs
  packages/schematics/angular/library/library-long.md
Labels: PR target: master-only, cla: yes

#12976 feat(@angular/cli): add warning for overriding flags in arguments
  packages/angular/cli/models/parser.ts
  packages/angular/cli/models/parser_spec.ts
Labels: PR target: master-only, cla: yes

#12961 docs: point root README to branch-relative links
  .monorepo.json
  README.md
Labels: PR target: master & patch, cla: yes

#13025 fix(@schematics/update): replace environment variables in npm/yarn rc
  packages/schematics/update/update/npm.ts
Labels: PR target: master-only, cla: yes

#13045 docs: remove spurious character(s) in update-long.md
  packages/angular/cli/commands/update-long.md
Labels: PR target: master & patch, cla: yes

#12920 ci: run minimal tests on PRs and original set on release branches
  .appveyor.yml
  appveyor-e2e.bat
Labels: PR target: master-only, cla: yes

#12995 feat(@schematics/update): add initial verbose option
  packages/schematics/update/update/index.ts
  packages/schematics/update/update/npm.ts
  packages/schematics/update/update/schema.json
Labels: PR target: master-only, cla: yes

#12994 fix(@ngtools/webpack): cleanup resources after modules are loaded
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master & patch, cla: yes

#13022 docs: point root README to branch-relative links
  .monorepo.json
  README.md
Labels: PR target: LTS-only, cla: yes

#13031 Feature: Added support for multiselect list prompt
  packages/angular/cli/models/schematic-command.ts
  packages/angular_devkit/core/src/json/schema/interface.ts
  packages/angular_devkit/core/src/json/schema/prompt_spec.ts
  packages/angular_devkit/core/src/json/schema/registry.ts
  packages/angular_devkit/schematics_cli/bin/schematics.ts
Labels: PR target: master-only, cla: yes

#13039 docs: fix config name in update Fixes #13028
  docs/documentation/stories/1.0-update.md
Labels: PR target: master & patch, cla: yes

#13051 docs(@angular/cli): change default test watch flag
  packages/angular/cli/lib/config/schema.json
Labels: PR target: master & patch, cla: yes

#13057 ci: packages now can list version numbers too
  scripts/packages.ts
Labels: PR target: master & patch, cla: yes

#13062 feat(@angular-devkit/build-angular): fine grain settings for sourceMaps
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/utils.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/browser/schema.d.ts
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/dev-server/schema.json
  packages/angular_devkit/build_angular/src/karma/index.ts
  packages/angular_devkit/build_angular/src/karma/schema.d.ts
  packages/angular_devkit/build_angular/src/karma/schema.json
  packages/angular_devkit/build_angular/src/server/index.ts
  packages/angular_devkit/build_angular/src/server/schema.d.ts
  packages/angular_devkit/build_angular/src/server/schema.json
  packages/angular_devkit/build_angular/src/utils/index.ts
  packages/angular_devkit/build_angular/src/utils/normalize-source-maps.ts
  packages/angular_devkit/build_angular/test/browser/source-map_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/vendor-source-map_spec_large.ts
  packages/angular_devkit/build_angular/test/server/base_spec_large.ts
Labels: PR target: master-only, cla: yes

#13063 refactor: deprecate `evalSourceMap`
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/server/schema.d.ts
Labels: PR target: master & patch, cla: yes

#13065 docs: add documentation for API guardian
  CONTRIBUTING.md
  scripts/templates/contributing.ejs
Labels: PR target: master-only, cla: yes

#13074 feat(@schematics/angular): account for root level assets and `resourcesOutputPath`
  packages/angular_devkit/build_angular/test/browser/service-worker_spec_large.ts
  packages/schematics/angular/service-worker/files/ngsw-config.json
  packages/schematics/angular/service-worker/index.ts
  packages/schematics/angular/service-worker/index_spec.ts
  packages/schematics/angular/utility/workspace-models.ts
Labels: PR target: master-only, cla: yes

#13081 fix(@schematics/angular): addProviderToModule bug: add providers into inner Object
  packages/schematics/angular/utility/ast-utils.ts
  packages/schematics/angular/utility/ast-utils_spec.ts
Labels: PR target: master & patch, cla: yes

#13086 style: add .gitattributes file
  .gitattributes
Labels: PR target: master & patch, cla: yes

#13089 fix(@ngtools/webpack): files are not being updated when using `allowJs` or `resolveJsonModule`
  packages/angular_devkit/build_angular/test/browser/allow-js_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/resolve-json-module_spec_large.ts
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/ngtools/webpack/src/compiler_host.ts
Labels: PR target: master & patch, cla: yes

#13101 fix(@schematics/angular): let tslint resolve codelyzer
  packages/schematics/angular/workspace/files/tslint.json
Labels: PR target: master & patch, cla: yes
