Repository angular/angular-cli, pull requests merged in 2018-12, with the labels that each got.

#13105 test: update golden api for devkit core
  etc/api/angular_devkit/core/src/_golden-api.d.ts
Labels: PR target: master-only, cla: yes

#12673 fix(@angular/cli): pass arguments to all targets
  packages/angular/cli/models/parser.ts
  packages/angular/cli/models/parser_spec.ts
Labels: PR target: master & patch, cla: yes

#13127 refactor: remove webpack 3 code from cleancss plugin
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/cleancss-webpack-plugin.ts
Labels: PR target: master-only, cla: yes

#13135 refactor: script webpack plugin remove webpack 3 code
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/scripts-webpack-plugin.ts
Labels: PR target: master-only, cla: yes

#13108 docs: change link for CLI readme to be relative
  README.md
  scripts/templates/readme.ejs
Labels: PR target: LTS-only, PR target: master & patch, cla: yes

#13121 test: remove debounce as it's causing flakes
  packages/angular_devkit/build_angular/test/browser/allow-js_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/resolve-json-module_spec_large.ts
Labels: PR target: master & patch, cla: yes

#13133 fix(@ngtools/webpack): avoid checking watchMode in environment hook
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master & patch, cla: yes

#13134 style: add spacing to error message
  packages/angular/cli/lib/init.ts
Labels: PR target: master & patch, cla: yes

#13141 fix(@angular/cli): show full path to project definition when already exists
  packages/angular/cli/models/command.ts
Labels: PR target: master & patch, cla: yes

#13146 build: update unstable release numbers for 7.2 beta
  packages/schematics/angular/utility/latest-versions.ts
Labels: PR target: master-only, cla: yes

#13152 style(@angular-devkit/build-angular): typo in stylesSourceMap
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Labels: PR target: master-only, cla: yes

#13156 docs: remove space for webpack-bundle-analyzer url
  docs/documentation/build.md
  packages/angular_devkit/build_angular/src/browser/schema.d.ts
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/server/schema.d.ts
  packages/angular_devkit/build_angular/src/server/schema.json
Labels: PR target: master & patch, cla: yes

#13132 fix(@schematics/angular): fix #12886, import zone related flags in other file.
  packages/schematics/angular/application/files/src/polyfills.ts
Labels: PR target: master & patch, cla: yes

#13159 refactor: add time logs in `_listLazyRoutesFromProgram`
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master & patch, cla: yes

#13168 fix(@angular-devkit/build-angular): output non human readable lint re…
  packages/angular_devkit/build_angular/src/tslint/index.ts
  packages/angular_devkit/build_angular/test/tslint/works_spec_large.ts
Labels: PR target: master & patch, cla: yes

#13175 Removed invalid option of ProgressPlugin
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Labels: PR target: master & patch, cla: yes

#13189 docs(@schematics/angular): add note about older chrome in polyfills
  packages/schematics/angular/application/files/src/polyfills.ts
Labels: PR target: master & patch, cla: yes

#13177 Build snapshots path in readme
  scripts/snapshots.ts
Labels: PR target: master & patch, cla: yes

#12938 feat(@schematics/angular): add `lintFix` to several other schematics
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/class/index.ts
  packages/schematics/angular/class/schema.json
  packages/schematics/angular/library/index.ts
  packages/schematics/angular/library/schema.json
  packages/schematics/angular/module/index.ts
  packages/schematics/angular/module/schema.json
Labels: PR target: master-only, cla: yes

#13197 fix(@angular/cli): remove redundant period in deprecation warning
  packages/angular/cli/models/parser.ts
Labels: PR target: master & patch, cla: yes

#13196 fix(@schematics/angular): cannot create pipe in sub-directory if mod…
  packages/schematics/angular/pipe/index.ts
  packages/schematics/angular/pipe/index_spec.ts
Labels: PR target: master & patch, cla: yes

#13117 fix(@schematics/angular): set `optimization` and `sourceMap` in universal production config
  packages/schematics/angular/universal/index.ts
  packages/schematics/angular/utility/workspace-models.ts
Labels: PR target: master-only, cla: yes

#13124 feat(@schematics/update): add packageGroup version map support
  packages/schematics/update/update/index.ts
  packages/schematics/update/update/index_spec.ts
  tests/schematics/update/packages/README.md
  tests/schematics/update/packages/update-package-group-1/package.json
  tests/schematics/update/packages/update-package-group-2/package.json
Labels: PR target: master-only, cla: yes

#13178 ci: add renovate configuration
  renovate.json
Labels: PR target: master-only, cla: yes

#13214 style(@schematics/angular): format jsdoc in polyfills.ts
  packages/schematics/angular/application/files/src/polyfills.ts
Labels: PR target: master & patch, cla: yes

#13167 fix(@schematics/update): ignore npm 404 error
  packages/schematics/update/update/npm.ts
Labels: PR target: master & patch, cla: yes

#13231 ci: add labels to Prs opened by renovate
  renovate.json
Labels: PR target: master-only, cla: yes

#13234 fix(schematics/angular): assert no error logs in e2e
  packages/schematics/angular/e2e/files/src/app.e2e-spec.ts
Labels: PR target: master-only, cla: yes

#13250 ci: temporarily disable size check comments
  .github/angular-robot.yml
Labels: PR target: master-only, cla: yes

#13271 ci: disable major `devDependencies` updates
  renovate.json
Labels: PR target: master-only, cla: yes

#13273 build: update several dependencies
  package.json
  packages/angular_devkit/benchmark/package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_optimizer/package.json
  packages/ngtools/webpack/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#13210 docs: edit ng serve option doc
  packages/angular/cli/lib/config/schema.json
Labels: PR target: master & patch, cla: yes, comp: angular/cli, effort1: easy (hours), freq1: low, priority: 3 (nice to have), severity1: confusing, type: docs

#13280 docs: remove autocomplete link
  docs/documentation/stories.md
Labels: PR target: master-only, cla: yes

#13213 feat(@schematics/angular): extend tslint:recommended
  packages/schematics/angular/workspace/files/tslint.json
Labels: PR target: master-only, cla: yes

#12919 refactor(@angular/pwa): rename manifest.json to manifest.webmanifest
  packages/angular/pwa/pwa/files/root/manifest.webmanifest
  packages/angular/pwa/pwa/index.ts
  packages/angular/pwa/pwa/index_spec.ts
Labels: PR target: master-only, cla: yes
