Repository angular/angular-cli, pull requests merged in 2018-10, with the labels that each got.

#12405 docs: sort changelog by feature first, then fixes
  scripts/templates/changelog.ejs
Labels: PR target: master & patch, cla: yes

#12404 feat(@angular-devkit/build-angular): add --reporters option to test
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/karma/index.ts
  packages/angular_devkit/build_angular/src/karma/schema.d.ts
  packages/angular_devkit/build_angular/src/karma/schema.json
Labels: PR target: master-only, cla: yes

#12387 ci: enable size check comments
  .github/angular-robot.yml
Labels: PR target: master-only, cla: yes

#12397 refactor: remove code that was needed for `eject`
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Labels: PR target: master-only, cla: yes

#12402 fix(@angular-devkit/build-angular): don't rerun tests on unchanged co…
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma.ts
  packages/angular_devkit/build_angular/test/karma/rebuilds_spec_large.ts
Labels: PR target: master-only, cla: yes

#12429 feat(@schematics/angular): update `TypeScript` to `3.1`
  packages/schematics/angular/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#12450 style: remove trailing whitespace
  packages/ngtools/webpack/package.json
Labels: PR target: master-only, cla: yes

#12461 refactor(@ngtools/webpack): reduce amount of filesystem calls
  packages/ngtools/webpack/src/compiler_host.ts
Labels: PR target: master-only, cla: yes

#12460 fix(@angular-devkit/build-angular): `ng test` without `reporters` no …
  packages/angular_devkit/build_angular/src/karma/index.ts
Labels: PR target: master-only, cla: yes

#12443 ci: publish script now checks that master has next tag
  scripts/publish.ts
Labels: PR target: master-only, cla: yes

#12438 style: remove unused locals and imports
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Labels: PR target: master-only, cla: yes

#12428 fix(@angular/cli): `ng update` remove duplicate `dryRun` in help
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/commands/update.json
Labels: PR target: master-only, cla: yes

#12411 Fix cpu profiling
  package.json
  packages/angular/cli/lib/init.ts
  yarn.lock
Labels: cla: yes

#12427 test: update snapshots TS version
  tests/legacy-cli/e2e/utils/project.ts
Labels: PR target: master-only, cla: yes

#12425 build: add check yarn preinstall script
  package.json
  tools/yarn/check-yarn.js
Labels: PR target: master-only, cla: yes

#12437 fix(@angular-devkit/build-angular): resolve assets in styles relative to importee
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/postcss-cli-resources.ts
  packages/angular_devkit/build_angular/test/browser/styles_spec_large.ts
Labels: PR target: master-only, cla: yes

#12440 style(@schematics/angular): remove extra whitespace in EOF
  packages/schematics/angular/application/files/src/main.ts
Labels: PR target: master & patch, cla: yes

#12386 Cleanup application polyfill comments
  packages/schematics/angular/application/files/src/polyfills.ts
Labels: PR target: master-only, cla: yes

#12470 fix(@angular/cli): `ng update --help` shows `--packages` twice
  packages/angular/cli/commands/update.json
  packages/schematics/update/update/schema.json
Labels: PR target: master-only, cla: yes

#12473 ci: exit with `0` error code when running templates
  CONTRIBUTING.md
  scripts/templates.ts
  scripts/templates/contributing.ejs
Labels: PR target: master-only, cla: yes

#12496 docs: start rewriting docs
  packages/angular/cli/commands/build-long.md
  packages/angular/cli/commands/build.json
  packages/angular/cli/commands/definitions.json
  packages/angular_devkit/build_angular/src/browser/schema.json
Labels: cla: yes

#12493 fix(@schematics/angular): tweak the `ng new` routing prompt
  packages/schematics/angular/ng-new/schema.json
Labels: PR target: master-only, cla: yes

#12494 fix(@schematics/angular): use proper project root for e2e
  packages/schematics/angular/application/index.ts
Labels: PR target: master & patch, cla: yes

#12521 fix(@schematics/angular): ast utils - handle NgModule with no newlines
  packages/schematics/angular/utility/ast-utils.ts
  packages/schematics/angular/utility/ast-utils_spec.ts
Labels: PR target: master & patch, cla: yes

#12500 refactor(@angular/schematics): Add an extra option to not use dasheri…
  packages/schematics/angular/utility/find-module.ts
  packages/schematics/angular/utility/find-module_spec.ts
Labels: PR target: master-only, cla: yes

#12495 Change npm install to yarn to install dependencies
  packages/angular/cli/README.md
  yarn.lock
Labels: PR target: master-only, cla: yes

#12497 test: cleanup poll CLI E2E test
  packages/angular_devkit/build_angular/test/browser/poll_spec_large.ts
  tests/legacy-cli/e2e/tests/build/poll.ts
Labels: PR target: master-only, cla: yes

#12498 Add `--minimal` flag to enable barebones project.
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/ng-new/index.ts
  packages/schematics/angular/ng-new/schema.json
  packages/schematics/angular/workspace/files/package.json
  packages/schematics/angular/workspace/schema.json
  tests/legacy-cli/e2e_runner.ts
Labels: PR target: master-only, cla: yes

#12507 fix(@angular-devkit/build-angular): don't override missing options in…
  packages/angular_devkit/build_angular/src/protractor/index.ts
Labels: PR target: master & patch, cla: yes

#12511 fix(@angular-devkit/build-angular): passing `specs` to protractor builder has no effect
  packages/angular_devkit/build_angular/src/protractor/index.ts
  packages/angular_devkit/build_angular/test/protractor/works_spec_large.ts
Labels: PR target: master & patch, cla: yes

#12513 fix(@schematics/angular): codeCoverage exclude is not being migrated
  packages/schematics/angular/migrations/update-6/index.ts
  packages/schematics/angular/migrations/update-6/index_spec.ts
Labels: PR target: master & patch, cla: yes

#12518 fix(@schematics/angular): migrate existing packages for 7.0
  packages/schematics/angular/migrations/update-7/index.ts
Labels: PR target: master-only, cla: yes

#12519 feat(@schematics/angular): add prompts for all name options
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/class/schema.json
  packages/schematics/angular/component/schema.json
  packages/schematics/angular/directive/schema.json
  packages/schematics/angular/enum/schema.json
  packages/schematics/angular/guard/schema.json
  packages/schematics/angular/interface/schema.json
  packages/schematics/angular/library/schema.json
  packages/schematics/angular/module/schema.json
  packages/schematics/angular/pipe/schema.json
  packages/schematics/angular/service/schema.json
Labels: PR target: master-only, cla: yes

#12525 refactor(@angular/cli): update eject command message
  packages/angular/cli/commands/eject-impl.ts
Labels: PR target: master-only, cla: yes

#12546 fix(@angular-devkit/build-angular): fix extractLicenses default
  packages/angular_devkit/build_angular/src/browser/schema.json
Labels: PR target: master & patch, cla: yes

#12547 fix(@angulat-devkit/build-angular): dont serve files on cwd
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/test/dev-server/works_spec_large.ts
Labels: PR target: master-only, cla: yes

#12548 fix(@angular-devkit/core): make JSON schema required work with prompts
  packages/angular_devkit/core/src/json/schema/prompt_spec.ts
  packages/angular_devkit/core/src/json/schema/registry.ts
Labels: PR target: master-only, cla: yes

#12520 Update doc strings for command reference
  packages/angular/cli/commands/config.json
  packages/angular/cli/commands/definitions.json
  packages/angular/cli/commands/doc.json
  packages/angular/cli/commands/e2e.json
  packages/angular/cli/commands/help.json
  packages/angular/cli/commands/lint-long.md
  packages/angular/cli/commands/lint.json
Labels: PR target: master-only, cla: yes, type: docs

#12482 ci: add header to snapshot build README
  scripts/snapshots.ts
Labels: PR target: master-only, cla: yes

#12561 docs(@angular/cli): correct e2e long description field
  packages/angular/cli/commands/e2e-long.md
  packages/angular/cli/commands/e2e.json
Labels: PR target: master-only, cla: yes

#12569 fix(@ngtools/webpack): output consistent filename
  packages/angular_devkit/build_angular/test/browser/lazy-module_spec_large.ts
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master-only, cla: yes

#12571 fix(@ngtools/webpack): remove usage of private compiler API
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master-only, cla: yes

#12558 fix(@angular/cli): use stderr for all diagnostic related log messages
  packages/angular/cli/lib/cli/index.ts
Labels: PR target: master & patch, cla: yes

#12567 fix(@ngtools/webpack): barrel files fail on windows
  packages/ngtools/webpack/src/entry_resolver.ts
  tests/legacy-cli/e2e/tests/build/barrel-file.ts
Labels: PR target: master & patch, cla: yes

#12625 fix(@schematics/angular): avoid using 6.2+ only features in migrations
  packages/schematics/angular/migrations/update-7/polyfill-metadata.ts
Labels: PR target: master & patch, cla: yes

#12634 docs: improve command option descriptions
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/karma/schema.json
  packages/angular_devkit/build_angular/src/server/schema.json
Labels: PR target: master & patch, cla: yes

#12565 fix(@angular-devkit/build-webpack): skip transition property optimization
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/cleancss-webpack-plugin.ts
Labels: PR target: master & patch, cla: yes

#12626 fix(@schematics/angular): update codelyzer for new projects
  packages/schematics/angular/workspace/files/package.json
Labels: PR target: master & patch, cla: yes

#12591 Fix virtual file invalidation
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/src/compiler_host.ts
  yarn.lock
Labels: PR target: master & patch, cla: yes

#12643 fix(@schematics/angular): update `@angular` `peerDependencies` when g…
  packages/schematics/angular/library/files/__projectRoot__/package.json
  packages/schematics/angular/library/index.ts
  packages/schematics/angular/library/index_spec.ts
Labels: PR target: master & patch, cla: yes

#12418 fix(@ngtools/webpack): emit lazy routes errors on rebuilds
  packages/angular_devkit/build_angular/test/browser/lazy-module_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/ngtools/webpack/src/lazy_routes.ts
  packages/ngtools/webpack/src/transformers/export_lazy_module_map.ts
Labels: PR target: master-only, cla: yes

#12449 feat(@angular-devkit/build-angular): expose `buildWebpackConfig` method in `KarmaBuilder`
  packages/angular_devkit/build_angular/src/karma/index.ts
Labels: PR target: master-only, cla: yes

#12542 feat(@schematics/angular): add `text-summary` to code coverage reporters
  packages/schematics/angular/application/files/root/karma.conf.js
  tests/legacy-cli/e2e/tests/misc/coverage.ts
Labels: PR target: master-only, cla: yes

#12564 feat(@schematics/update) import user-agent from NPM config
  packages/schematics/update/update/npm.ts
Labels: PR target: master-only, cla: yes

#12598 feat(@schematics/angular): enable typescript helpers in workspace
  packages/schematics/angular/library/index.ts
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-7/index.ts
  packages/schematics/angular/migrations/update-7/typescript-helpers.ts
  packages/schematics/angular/migrations/update-7/typescript-helpers_spec.ts
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/angular/workspace/files/package.json
  packages/schematics/angular/workspace/files/tsconfig.json
Labels: PR target: master-only, cla: yes

#12601 build: add utility for reading build event protocol
  third_party/github.com/bazelbuild/bazel/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/BUILD
  third_party/github.com/bazelbuild/bazel/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto
  third_party/github.com/bazelbuild/bazel/src/main/protobuf/BUILD
  third_party/github.com/bazelbuild/bazel/src/main/protobuf/command_line.proto
  third_party/github.com/bazelbuild/bazel/src/main/protobuf/invocation_policy.proto
  third_party/github.com/bazelbuild/bazel/src/main/protobuf/option_filters.proto
  tools/build_event_protocol/BUILD
  tools/build_event_protocol/README.md
  tools/build_event_protocol/parse_bep.ts
  tsconfig.json
Labels: PR target: master-only, cla: yes

#12543 fix(@angular-devkit/build-angular): update `copy-webpack-plugin` dependency
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: master & patch, cla: yes

#12559 fix(@ngtools/webpack): report a warning when lazy route discovery is disabled
  packages/angular_devkit/build_angular/test/browser/no-entry-module_spec_large.ts
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/ngtools/webpack/src/entry_resolver.ts
Labels: PR target: master & patch, cla: yes

#12580 Update Autoprefixer and PostCSS
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: master & patch, cla: yes

#12585 Docs: fix budgets story
  docs/documentation/stories/budgets.md
Labels: PR target: master & patch, cla: yes

#12586 fix(@angular-devkit/build-optimizer): add tslib replacement at top of…
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
  packages/angular_devkit/build_optimizer/src/transforms/import-tslib.ts
  packages/angular_devkit/build_optimizer/src/transforms/import-tslib_spec.ts
Labels: PR target: master & patch, cla: yes

#12587 docs: update universal rendering story
  docs/documentation/stories/universal-rendering.md
Labels: PR target: master & patch, cla: yes

#12606 fix(@schematics/schematics): should not have test node_modules specs
  packages/schematics/schematics/schematic/files/package.json
Labels: PR target: master & patch, cla: yes

#12608 fix(@angular-devkit/schematics-cli): inconsistency in referencing collection
  packages/angular_devkit/schematics_cli/bin/schematics.ts
  tests/legacy-cli/e2e/tests/schematics_cli/basic.ts
Labels: PR target: master & patch, cla: yes

#12615 fix(@schematics/angular): module is not being located correctly when using `flat`
  packages/schematics/angular/utility/find-module.ts
  packages/schematics/angular/utility/find-module_spec.ts
Labels: PR target: master & patch, cla: yes

#12651 fix(@angular-devkit/build-angular): error when using protocol-relative url
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/postcss-cli-resources.ts
  packages/angular_devkit/build_angular/test/browser/styles_spec_large.ts
Labels: PR target: master & patch, cla: yes

#12655 Various QoL with TSLint and Docs
  bin/README.md
  docs/README.md
  etc/README.md
  etc/rules/README.md
  etc/rules/Rule.ts
  etc/rules/defocusRule.ts
  etc/rules/importGroupsRule.ts
  etc/rules/noGlobalTslintDisableRule.ts
  etc/rules/singleEofLineRule.ts
  etc/rules/tsconfig.json
  lib/README.md
  packages/README.md
  packages/ngtools/webpack/src/type_checker_messages.ts
  scripts/lint.ts
  tests/README.md
  tsconfig.json
  tslint.json
Labels: PR target: master & patch, cla: yes

#12681 fix(@angular/cli): multiline help descriptions are not aligned
  packages/angular/cli/models/command.ts
Labels: PR target: master & patch, cla: yes

#12687 fix(@angular-devkit/build-angular): Updated package.json with newer v…
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: master & patch, cla: yes

#12701 docs: update cli readme for version 7
  packages/angular/cli/README.md
Labels: PR target: master & patch, cla: yes

#12703 refactor(@angular-devkit/build-angular): cleanup/fix linting of webpack configs
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/index.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts
Labels: PR target: master & patch, cla: yes

#12716 feat(@angular-devkit/build-angular): update webpack dependencies
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#12712 docs: update descriptions
  packages/angular/cli/lib/config/schema.json
  packages/schematics/angular/component/schema.json
  packages/schematics/angular/directive/schema.json
  packages/schematics/angular/guard/schema.json
  packages/schematics/angular/module/schema.json
  packages/schematics/angular/pipe/schema.json
  packages/schematics/angular/service/schema.json
  packages/schematics/angular/utility/config.ts
  tests/angular_devkit/core/json/schema/serializers/schema_benchmark.json
Labels: PR target: master & patch, cla: yes

#12526 refactor(@schematics/update): cleanup/optimize npm fetch
  packages/schematics/update/package.json
  packages/schematics/update/update/npm.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#12697 fix(@schematics/angular): migrate build-angular for 7.0 RC users
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-7/index.ts
Labels: PR target: master & patch, cla: yes

#12709 fix(@schematics/angular): experimentalIvy creates project using `next` packages
  packages/schematics/angular/ng-new/index.ts
Labels: PR target: master & patch, cla: yes

#12715 fix(@angular-devkit/schematics): upgrade using tslint output has too …
  packages/angular_devkit/schematics/tasks/tslint-fix/executor.ts
Labels: PR target: master & patch, cla: yes
