Repository angular/angular-cli, pull requests merged in 2019-02, with the labels that each got.

#13548 test: ensure add material test has clean material package
  tests/legacy-cli/e2e/tests/commands/add/add-material.ts
Labels: PR target: master & patch, cla: yes

#13549 Fully resolve correct `@ngtools/webpack` loader
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts
  packages/ngtools/webpack/src/index.ts
Labels: PR target: master & patch, cla: yes

#13552 fix(@schematics/angular): set config when using sass as preprocessor
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/index_spec.ts
Labels: PR target: master & patch, cla: yes

#13554 fix(@schematics/angular): update typescript to 3.2.4
  packages/schematics/angular/package.json
Labels: PR target: master & patch, cla: yes

#13556 refactor: add `allowAdditionalArgs` to be able to bypass extra params…
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/models/schematic-command.ts
Labels: PR target: master-only, cla: yes

#13565 fix(@angular-devkit/build-angular): add missing open parenthesis in s…
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma.ts
Labels: PR target: master & patch, cla: yes

#13566 build: update karma and jasmine dependencies
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/schematics/angular/app-shell/index_spec.ts
  packages/schematics/angular/workspace/files/package.json.template
  yarn.lock
Labels: PR target: master-only, cla: yes

#13567 fix(@angular-devkit/build-angular): remove deprecated `istanbul` from…
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: master & patch, cla: yes

#13584 fix(@angular-devkit/build-angular): use sourcemap object in karma plugin
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma.ts
Labels: PR target: master & patch, cla: yes

#13589 fix(@angular/cli): update terser-webpack-plugin
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: master & patch, cla: yes

#13596 docs: link to angular.io/cli instead of old wiki
  etc/cli.angular.io/index.html
Labels: PR target: master-only, cla: yes

#13604 fix(@angular/cli): Add an error message when we call `ng doc` without…
  packages/angular/cli/commands/doc-impl.ts
Labels: PR target: master & patch, cla: yes

#13613 fix(@angular-devkit/build-optimizer): prefix renamed extended classes
  packages/angular_devkit/build_optimizer/src/transforms/prefix-classes.ts
  packages/angular_devkit/build_optimizer/src/transforms/prefix-classes_spec.ts
Labels: PR target: master & patch, cla: yes

#13625 fix(@schematics/angular): update latest version of devkit
  packages/schematics/angular/utility/latest-versions.ts
Labels: PR target: master-only, cla: yes

#13493 fix(@schematics/angular): e2e test fails strict TS config
  packages/schematics/angular/e2e/files/src/app.e2e-spec.ts.template
Labels: PR target: master & patch, cla: yes

#13615 fix(@angular/cli): change strategy for opening the browser when we ca…
  packages/angular/cli/commands/doc-impl.ts
Labels: PR target: master & patch, cla: yes

#13630 fix(@schematics/angular): set restartOnFileChange to true in karma.conf templates
  packages/schematics/angular/application/files/root/karma.conf.js.template
  packages/schematics/angular/library/files/__projectRoot__/karma.conf.js.template
Labels: PR target: master & patch, cla: yes

#13637 fix(@schematics/angular): Include bazel-out in .gitignore
  packages/schematics/angular/workspace/files/__dot__gitignore.template
Labels: PR target: master & patch, cla: yes

#13571 fix(@angular-devkit/build-angular): throw error when multiple bundles…
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/package-chunk-sort.ts
Labels: PR target: master-only, cla: yes

#13620 fix(@angular-devkit/build-angular): remove unneeded script element type
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/index-html-webpack-plugin.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma-context.html
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma-debug.html
  packages/angular_devkit/build_angular/test/browser/index_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/scripts-array_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/service-worker_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/styles_spec_large.ts
  tests/legacy-cli/e2e/tests/basic/scripts-array.ts
  tests/legacy-cli/e2e/tests/basic/styles-array.ts
  tests/legacy-cli/e2e/tests/build/polyfills.ts
  tests/legacy-cli/e2e/tests/build/styles/extract-css.ts
  tests/legacy-cli/e2e/tests/misc/support-ie.ts
  tests/legacy-cli/e2e/tests/third-party/bootstrap.ts
Labels: PR target: master-only, cla: yes

#13643 fix(@angular-devkit/build-angular): added warning for ES2017
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Labels: PR target: master & patch, cla: yes

#13644 refactor(@schematics/angular): remove redundant branchAndMerge rules
  packages/schematics/angular/class/index.ts
  packages/schematics/angular/component/index.ts
  packages/schematics/angular/directive/index.ts
  packages/schematics/angular/enum/index.ts
  packages/schematics/angular/guard/index.ts
  packages/schematics/angular/interface/index.ts
  packages/schematics/angular/library/files/README.md.template
  packages/schematics/angular/library/files/karma.conf.js.template
  packages/schematics/angular/library/files/ng-package.json.template
  packages/schematics/angular/library/files/package.json.template
  packages/schematics/angular/library/files/src/__entryFile__.ts.template
  packages/schematics/angular/library/files/src/test.ts.template
  packages/schematics/angular/library/files/tsconfig.lib.json.template
  packages/schematics/angular/library/files/tsconfig.spec.json.template
  packages/schematics/angular/library/files/tslint.json.template
  packages/schematics/angular/library/index.ts
  packages/schematics/angular/module/index.ts
  packages/schematics/angular/pipe/index.ts
Labels: PR target: master & patch, cla: yes

#13653 docs: remove analyse link from statsJson description
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/server/schema.json
Labels: PR target: master & patch, cla: yes

#13655 fix(angular-devkit/schematics): use `join` instead of normal string concatenation
  packages/angular_devkit/schematics/src/rules/move.ts
Labels: PR target: master & patch, cla: yes

#13669 fix(@schematics/angular): respect the flag when we create a guard wit…
  packages/schematics/angular/guard/index.ts
  packages/schematics/angular/guard/index_spec.ts
Labels: PR target: master & patch, cla: yes

#13672 build: fix invalid commits that made it through
  scripts/validate-commits.ts
Labels: PR target: master-only, cla: yes

#13647 refactor: clean up library tsconfig
  packages/schematics/angular/library/files/tsconfig.lib.json.template
  tests/angular_devkit/build_ng_packagr/ng-packaged/projects/lib/tsconfig.lib.json
Labels: PR target: master-only, cla: yes

#13605 feat(@angular/cli): Add VsCode extension recommendations
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-vscode-recommendations/ast-utils.ts
  packages/schematics/angular/migrations/update-vscode-recommendations/update-8.0.0.ts
  packages/schematics/angular/migrations/update-vscode-recommendations/update-8.0.0_spec.ts
  packages/schematics/angular/workspace/files/__dot__vscode/extensions.json.template
Labels: PR target: master-only, cla: yes

#13671 fix(@angular-devkit/core): remove static initialization using process…
  packages/angular_devkit/core/src/terminal/caps.ts
  packages/angular_devkit/core/src/terminal/text.ts
Labels: PR target: master-only, cla: yes

#13667 fix(@ngtools/webpack): don't load ngfactories for lazy routes with Ivy
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  tests/legacy-cli/e2e/tests/experimental/ivy-lazy-load.ts
  tests/legacy-cli/e2e_runner.ts
Labels: PR target: master-only, cla: yes

#13513 fix(@angular-devkit/schematics): add missing aliases to collection-schema.json
  packages/angular_devkit/schematics/collection-schema.json
Labels: PR target: master & patch, cla: yes

#13691 feat(@schematics/angular): Update rxjs to 6.4.0
  packages/schematics/angular/utility/latest-versions.ts
Labels: PR target: master-only, cla: yes

#13684 fix(@angular-devkit/build-angular): disable by default stylesheet root relative URL rebasing
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/postcss-cli-resources.ts
  packages/angular_devkit/build_angular/src/browser/schema.d.ts
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/test/browser/styles_spec_large.ts
  tests/legacy-cli/e2e/tests/build/css-urls.ts
Labels: PR target: master-only, cla: yes

#13639 fix(@angular-devkit/build-angular): minimum threshold
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/bundle-calculator.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/bundle-calculator_spec.ts
Labels: PR target: master & patch, cla: yes

#13687 fix(@angular-devkit/build-angular): improve webpack loader resolution
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/find-up.ts
Labels: PR target: master & patch, cla: yes

#13690 fix(@schematics/angular): fixes issue that `viewEncapsulation` is not…
  packages/schematics/angular/application/files/src/main.ts.template
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/application/other-files/app.component.ts.template
Labels: PR target: master & patch, cla: yes

#13710 fix(@schematics/angular): add file extensions to style prompt
  packages/schematics/angular/ng-new/schema.json
Labels: PR target: master & patch, cla: yes

#13712 fix(@angular/cli): remove redundant typescript/compiler-cli compatibility check
  packages/angular/cli/commands/build-impl.ts
  packages/angular/cli/commands/config-impl.ts
  packages/angular/cli/commands/serve-impl.ts
  packages/angular/cli/lib/config/schema.json
  packages/angular/cli/upgrade/version.ts
  packages/angular/cli/utilities/config.ts
  packages/schematics/angular/migrations/update-6/index.ts
  tests/angular_devkit/core/json/schema/serializers/schema_benchmark.json
  tests/legacy-cli/e2e/tests/commands/config/config-set.ts
  tests/legacy-cli/e2e/tests/misc/typescript-warning.ts
Labels: PR target: master-only, cla: yes

#13716 fix(@schematics/angular): fix missing semicolons in extensions.json.template
  packages/schematics/angular/workspace/files/__dot__vscode/extensions.json.template
Labels: PR target: master-only, cla: yes

#13704 fix(@schematics/angular): undefined is used as newProjectRoot when no…
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/library/index.ts
Labels: PR target: master & patch, cla: yes

#13720 fix(@schematics/angular): `findModuleFromOptions` not handling proper…
  packages/schematics/angular/utility/find-module.ts
  packages/schematics/angular/utility/find-module_spec.ts
Labels: PR target: master & patch, cla: yes

#13731 fix(@schematics/angular): update karma to version 4
  packages/schematics/angular/workspace/files/package.json.template
Labels: PR target: patch-only, cla: yes

#13736 fix(schematics/angular): JsonUtils should respect indent
  packages/schematics/angular/utility/json-utils.ts
  packages/schematics/angular/utility/json-utils_spec.ts
Labels: PR target: master & patch, cla: yes

#13738 fix(@angular-devkit/build-angular): add promise polyfill to --es5BrowserSupport provided polyfills
  packages/angular_devkit/build_angular/src/angular-cli-files/models/es2015-polyfills.js
Labels: PR target: master-only, cla: yes

#13626 fix(@schematics/angular): use enableIvy as true
  packages/schematics/angular/application/files/root/tsconfig.app.json.template
  tests/legacy-cli/e2e/tests/experimental/ivy.ts
Labels: PR target: master-only, cla: yes

#13740 fix(@schematics/angular): remove extra comma in component schematic
  packages/schematics/angular/application/other-files/app.component.ts.template
Labels: PR target: master & patch, cla: yes

#13771 build: update to rxjs 6.4
  package.json
  packages/angular/pwa/package.json
  packages/angular_devkit/architect/builders/all-of.ts
  packages/angular_devkit/architect/package.json
  packages/angular_devkit/architect/test/package.json
  packages/angular_devkit/architect_cli/package.json
  packages/angular_devkit/benchmark/package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/app-shell/index.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/karma/index.ts
  packages/angular_devkit/build_angular/src/tslint/index.ts
  packages/angular_devkit/build_ng_packagr/package.json
  packages/angular_devkit/build_webpack/package.json
  packages/angular_devkit/core/node/host.ts
  packages/angular_devkit/core/package.json
  packages/angular_devkit/core/src/json/schema/registry.ts
  packages/angular_devkit/core/src/virtual-fs/host/record.ts
  packages/angular_devkit/schematics/package.json
  packages/angular_devkit/schematics/src/tree/host-tree.ts
  packages/angular_devkit/schematics/src/workflow/base.ts
  packages/angular_devkit/schematics_cli/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/update/package.json
  packages/schematics/update/update/npm.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#13770 fix(@angular-devkit/build-angular): sourceMap option not working in t…
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
  tests/legacy-cli/e2e/tests/test/test-sourcemap.ts
Labels: PR target: master & patch, cla: yes

#13754 fix(@schematics/angular): default newProjectRoot to current directory
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/library/index.ts
Labels: PR target: master & patch, cla: yes

#13676 feat(@angular/cli): Add VsCode recommendation for Angular Console
  packages/schematics/angular/migrations/update-vscode-recommendations/update-8.0.0.ts
  packages/schematics/angular/migrations/update-vscode-recommendations/update-8.0.0_spec.ts
  packages/schematics/angular/workspace/files/__dot__vscode/extensions.json.template
Labels: PR target: master-only, cla: yes

#13773 feat(@schematics/angular): rename experimentalIvy to enableIvy
  packages/schematics/angular/application/files/root/tsconfig.app.json.template
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/ng-new/index.ts
  packages/schematics/angular/ng-new/schema.json
  tests/legacy-cli/e2e/setup/500-create-project.ts
  tests/legacy-cli/e2e/tests/experimental/ivy-lazy-load.ts
  tests/legacy-cli/e2e/tests/experimental/ivy.ts
  tests/legacy-cli/e2e/utils/project.ts
Labels: PR target: master-only, cla: yes

#13713 docs: Update release process for microsite
  docs/process/release.md
Labels: PR target: master-only, cla: yes

#13776 feat(@angular/cli): recommend plugins that John Papa recommends
  packages/schematics/angular/migrations/update-vscode-recommendations/update-8.0.0.ts
  packages/schematics/angular/migrations/update-vscode-recommendations/update-8.0.0_spec.ts
  packages/schematics/angular/workspace/files/__dot__vscode/extensions.json.template
Labels: PR target: master-only, cla: yes

#13779 Use fallback cache and correct post checkout on CI
  .circleci/config.yml
Labels: PR target: master-only, cla: yes

#13782 build: add bootstrap debug logs
  lib/bootstrap-local.js
  package.json
  yarn.lock
Labels: PR target: master-only, cla: yes
