Repository angular/angular-cli, pull requests merged in 2019-03, with the labels that each got.

#13787 fix(@angular-devkit/architect-cli): fix paths to support Windows
  packages/angular_devkit/architect_cli/bin/architect.ts
Labels: PR target: master & patch, cla: yes

#13792 docs: add how to create a minimal repo in bug report template
  .github/ISSUE_TEMPLATE/1-bug-report.md
Labels: PR target: master-only, cla: yes

#13797 fix(@schematic/angular): kebab case prefix causes lint errors in new …
  packages/schematics/angular/application/files/lint/__tsLintRoot__/tslint.json.template
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/library/files/tslint.json.template
  packages/schematics/angular/library/index_spec.ts
Labels: PR target: master & patch, cla: yes

#13809 feat(@angular-devkit/build-angular): change es5BrowserSupport output filename to `polyfills.es5.js`
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/package-chunk-sort.ts
  tests/legacy-cli/e2e/tests/basic/scripts-array.ts
  tests/legacy-cli/e2e/tests/basic/styles-array.ts
  tests/legacy-cli/e2e/tests/build/polyfills.ts
  tests/legacy-cli/e2e/tests/build/styles/extract-css.ts
  tests/legacy-cli/e2e/tests/misc/support-ie.ts
  tests/legacy-cli/e2e/tests/third-party/bootstrap.ts
Labels: PR target: master-only, cla: yes

#13812 test: fix new tslint architect test large on windows
  packages/angular_devkit/build_angular/test/tslint/works2_spec_large.ts
Labels: PR target: master-only, cla: yes

#13284 feat(@ngtools/webpack): allow .svg files as templates
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/test/browser/svg_spec_large.ts
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/ngtools/webpack/src/compiler_host.ts
  packages/ngtools/webpack/src/transformers/replace_resources.ts
  packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
Labels: PR target: master-only, cla: yes

#13826 build: update husky to 1.3.1
  package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#13830 feat(@schematics/angular): relocate `ng g service-worker` files
  packages/schematics/angular/service-worker/index.ts
  packages/schematics/angular/service-worker/index_spec.ts
Labels: PR target: master-only, cla: yes

#13819 fix(@angular-devkit/build-angular): respect `preserveSymlinks` when using `bundleDependencies` in server builder
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts
  tests/legacy-cli/e2e/tests/misc/universal-bundle-dependencies.ts
Labels: PR target: master & patch, cla: yes

#13839 test: fix paths for ivy lazy loading tests
  tests/legacy-cli/e2e/tests/experimental/ivy-lazy-load.ts
Labels: PR target: master-only, cla: yes

#13660 feat(@angular-devkit/schematics): support basic promise/async based rules
  etc/api/angular_devkit/schematics/src/_golden-api.d.ts
  packages/angular_devkit/schematics/src/engine/interface.ts
  packages/angular_devkit/schematics/src/rules/call.ts
Labels: PR target: master-only, cla: yes

#13837 feat(@angular-devkit/schematics): support unicode character HTML element names
  packages/angular_devkit/schematics/src/formats/html-selector.ts
  packages/angular_devkit/schematics/src/formats/html-selector_spec.ts
Labels: PR target: master-only, cla: yes

#13850 test: ignore platform-server tests for ivy
  tests/legacy-cli/e2e_runner.ts
Labels: PR target: master-only, cla: yes

#13325 feat(@schematics/angular): JSON schema for service worker config
  packages/schematics/angular/service-worker/files/ngsw-config.json.template
  packages/schematics/angular/service-worker/index.ts
  packages/schematics/angular/service-worker/index_spec.ts
Labels: PR target: master-only, cla: yes

#13866 fix(@schematics/angular): change entry file name of the library schem…
  packages/schematics/angular/library/index_spec.ts
  packages/schematics/angular/library/schema.json
  tests/angular_devkit/build_ng_packagr/ng-packaged/projects/lib/ng-package.json
  tests/angular_devkit/build_ng_packagr/ng-packaged/projects/lib/src/public-api.ts
Labels: PR target: master & patch, cla: yes

#13868 fix(angular-devkit/build-angular): fix check for absolute paths in wi…
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts
Labels: PR target: master & patch, cla: yes

#13869 fix(@angular-devkit/build-angular): fix base href insertion when HTML…
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/index-html-webpack-plugin.ts
  packages/angular_devkit/build_angular/test/browser/base-href2_spec_large.ts
Labels: PR target: master & patch, cla: yes

#13871 fix(@angular-devkit/build-optimizer): don't add pure comments inside …
  packages/angular_devkit/build_optimizer/src/transforms/prefix-functions.ts
  packages/angular_devkit/build_optimizer/src/transforms/prefix-functions_spec.ts
Labels: PR target: master & patch, cla: yes

#13875 ci: rebase PRs on target branch
  .appveyor.yml
  .circleci/config.yml
  tools/rebase-pr.js
Labels: PR target: master & patch, cla: yes

#13884 fix(@angular-devkit/build-angular): fix base href insertion when HTML…
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/index-html-webpack-plugin.ts
  packages/angular_devkit/build_angular/test/browser/base-href_spec_large.ts
Labels: PR target: patch-only, cla: yes

#13897 feat(@angular/cli): add `@nguniversal/*` to ng version
  packages/angular/cli/commands/version-impl.ts
Labels: PR target: master-only, cla: yes

#13900 Remove dependency from @angular-devkit/core to chokidar
  packages/angular_devkit/core/BUILD
  packages/angular_devkit/core/node/host.ts
  packages/angular_devkit/core/package.json
  packages/angular_devkit/schematics/BUILD
  packages/schematics/angular/BUILD
  packages/schematics/update/BUILD
Labels: PR target: master-only, cla: yes

#13905 feat(@angular-devkit/build-angular): remove Closure compiler i18n code for ivy
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Labels: PR target: master-only, cla: yes, comp: devkit/build-angular

#13906 Minor Webpack Configuration Cleanup
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/browser/index2.ts
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/karma/index.ts
  packages/angular_devkit/build_angular/src/server/index.ts
Labels: PR target: master-only, cla: yes

#13909 feat(@schematics/angular): allow ember, ember-cli, vendor, app and test names
  packages/schematics/angular/utility/validation.ts
Labels: PR target: master-only, cla: yes

#13911 test: comment out broken assertion
  packages/angular_devkit/architect/src/index2_spec.ts
Labels: PR target: master-only, cla: yes

#13913 build: run all tests on appveyor
  .appveyor.yml
Labels: cla: yes

#13914 test: pin Angular snapshot versions
  .circleci/config.yml
  tests/legacy-cli/e2e/ng-snapshot/package.json
  tests/legacy-cli/e2e/utils/project.ts
  tests/legacy-cli/e2e_runner.ts
Labels: PR target: master-only, cla: yes

#13916 ci: add legacy cli snapshot paths to renovated paths
  renovate.json
Labels: PR target: master-only, cla: yes

#13921 test: skip snapshot e2e tests except for upstream/master and renovate…
  .circleci/config.yml
Labels: PR target: master-only, cla: yes

#13926 feat(@angular-devkit/build-angular): deprecate `profile` option in build
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/browser/index2.ts
  packages/angular_devkit/build_angular/src/browser/schema.json
Labels: PR target: master-only, cla: yes

#13912 test: fix invalid architect tests
  packages/angular_devkit/architect/src/index2_spec.ts
Labels: PR target: master-only, cla: yes

#13934 ci: run e2e snapshots for renovate user
  .circleci/config.yml
Labels: PR target: master-only, cla: yes

#13877 feat(@angular-devkit/build-ng-packagr): implement stable architect API
  packages/angular_devkit/build_ng_packagr/builders.json
  packages/angular_devkit/build_ng_packagr/package.json
  packages/angular_devkit/build_ng_packagr/src/build/index2.ts
  packages/angular_devkit/build_ng_packagr/src/build/index_spec_large.ts
  packages/angular_devkit/build_ng_packagr/src/build/schema.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#13919 fix(@angular-devkit/build-angular): passing port 0 when using serve w…
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: PR target: master & patch, cla: yes

#13925 feat(@angular-devkit/build-angular): enable webpack profile when usin…
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/test/browser/stats-json_spec_large.ts
Labels: PR target: master-only, cla: yes

#13929 build: fixes exclude list of file on windows
  scripts/lint.ts
Labels: PR target: master & patch, cla: yes

#13938 fix(@schematics/angular): remove baseUrl from universal tsconfig
  packages/schematics/angular/universal/files/root/__tsconfigFileName__.json.template
  packages/schematics/angular/universal/index_spec.ts
Labels: PR target: master-only, cla: yes

#13945 fix(@angular-devkit/build-angular): update speed-measure-webpack-plug…
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/test/browser/profile_spec_large.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#13946 fix(@angular-devkit/build-angular): update speed-measure-webpack-plug…
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/test/browser/profile_spec_large.ts
  yarn.lock
Labels: PR target: patch-only, cla: yes

#13428 feat(@schematics/angular): use more codelyzer rules
  packages/schematics/angular/workspace/files/tslint.json.template
Labels: PR target: master-only, cla: yes

#13951 build: Upgrade rules_nodejs to 0.27.7 and angular to 7.2.9
  WORKSPACE
Labels: PR target: master & patch, cla: yes

#13778 Dependency updates for Angular 8 and TS 3.3.3333
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/test/browser/service-worker_spec_large.ts
  packages/angular_devkit/build_ng_packagr/package.json
  packages/angular_devkit/build_optimizer/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/schematics/schematic/files/package.json
  tests/angular_devkit/build_angular/hello-world-app/package.json
  tests/legacy-cli/e2e/ng-snapshot/package.json
  tests/legacy-cli/e2e/tests/ivy/ivy.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#13928 feat(@angular-devkit/build-webpack): report emitted files
  packages/angular_devkit/build_webpack/src/index.ts
  packages/angular_devkit/build_webpack/src/utils.ts
  packages/angular_devkit/build_webpack/src/webpack-dev-server/index2.ts
  packages/angular_devkit/build_webpack/src/webpack-dev-server/index2_spec_large.ts
  packages/angular_devkit/build_webpack/src/webpack/index2.ts
  packages/angular_devkit/build_webpack/src/webpack/index2_spec_large.ts
Labels: PR target: master-only, cla: yes

#13936 feat(@angular-devkit/build-angular): implement stable architect API for karma
  package.json
  packages/angular_devkit/build_angular/builders.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/karma/index.ts
  packages/angular_devkit/build_angular/src/karma/index2.ts
  packages/angular_devkit/build_angular/src/karma/schema.d.ts
  packages/angular_devkit/build_angular/src/karma/schema.json
  packages/angular_devkit/build_angular/src/utils/normalize-karma-schema.ts
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
  packages/angular_devkit/build_angular/test/karma/assets_spec_large.ts
  packages/angular_devkit/build_angular/test/karma/code-coverage_spec_large.ts
  packages/angular_devkit/build_angular/test/karma/rebuilds_spec_large.ts
  packages/angular_devkit/build_angular/test/karma/replacements_spec_large.ts
  packages/angular_devkit/build_angular/test/karma/styles_spec_large.ts
  packages/angular_devkit/build_angular/test/karma/works_spec_large.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#13957 feat(@schematics/angular): add type checking for protractor.conf.js file
  packages/schematics/angular/e2e/files/protractor.conf.js.template
Labels: PR target: master-only, cla: yes

#13961 ci: remove hardcoded typescript version for snapshots
  tests/legacy-cli/e2e/utils/project.ts
Labels: PR target: master-only, cla: yes

#13962 test: add filter, seed and better diff checking to test script
  scripts/test.ts
Labels: PR target: master-only, cla: yes

#13979 fix(@angular/cli): fix import path for TimingOptions
  packages/angular/cli/models/analytics.ts
Labels: PR target: master-only, cla: yes

#13969 feat(@angular-devkit/build-angular): implement stable architect API for extract-i18n
  packages/angular_devkit/build_angular/builders.json
  packages/angular_devkit/build_angular/src/extract-i18n/index2.ts
  packages/angular_devkit/build_angular/src/extract-i18n/schema.json
  packages/angular_devkit/build_angular/test/extract-i18n/works_spec_large.ts
Labels: PR target: master-only, cla: yes

#13465 docs(bazel): Explain yarn workspaces vs Bazel
  docs/process/bazel.md
Labels: PR target: master-only, cla: yes

#13898 docs: add example for `ng add`
  packages/angular/cli/commands/add.md
Labels: PR target: master-only, cla: yes

#13801 feat(@schematics/angular): tslint migration for 8
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-8/index.ts
  packages/schematics/angular/migrations/update-8/index_spec.ts
Labels: PR target: master-only, cla: yes

#14020 docs: add breaking changes to changelog
  scripts/templates/changelog-breaking-changes.ejs
  scripts/templates/changelog.ejs
Labels: PR target: master-only, cla: yes

#14006 refactor(@angular-devkit/build-ng-packagr): cleanup experimental architect API
  packages/angular_devkit/build_ng_packagr/builders.json
  packages/angular_devkit/build_ng_packagr/package.json
  packages/angular_devkit/build_ng_packagr/src/build/index.ts
  packages/angular_devkit/build_ng_packagr/src/build/index2.ts
  packages/angular_devkit/build_ng_packagr/src/build/index_spec_large.ts
Labels: PR target: master-only, cla: yes

#13977 fix(@ngtools/webpack): changes in non module code are not picked up w…
  packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/ngtools/webpack/src/loader.ts
  packages/ngtools/webpack/src/transformers/ast_helpers.ts
Labels: PR target: master & patch, cla: yes

#13838 fix(@angular-devkit/build-angular): ensure correct dev server path with public host option
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: PR target: master & patch, cla: yes

#14004 feat(@schematics/angular): drop es6 from modern polyfills
  packages/angular_devkit/schematics/src/index.ts
  packages/schematics/angular/migrations/update-8/codelyzer-5.ts
  packages/schematics/angular/migrations/update-8/codelyzer-5_spec.ts
  packages/schematics/angular/migrations/update-8/drop-es6-polyfills.ts
  packages/schematics/angular/migrations/update-8/drop-es6-polyfills_spec.ts
  packages/schematics/angular/migrations/update-8/index.ts
Labels: PR target: master-only, cla: yes

#14028 test(@angular-devkit/build-angular): use experimental API For rebuild barrel test
  packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
Labels: PR target: patch-only, cla: yes

#14027 fix(@angular-devkit/build-angular): ensure correct dev server path with public host option
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: PR target: patch-only, cla: yes

#14029 refactor(@angular/cli): use standard node resolution methods where possible
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/lib/init.ts
  packages/angular/cli/upgrade/version.ts
Labels: PR target: master-only, cla: yes

#14005 feat(@schematics/angular): update to codelyzer 5
  packages/angular_devkit/build_angular/package.json
  packages/schematics/angular/workspace/files/package.json.template
  packages/schematics/angular/workspace/files/tslint.json.template
  tests/angular_devkit/build_angular/hello-world-app/package.json
  tests/angular_devkit/build_angular/hello-world-app/tslint.json
  yarn.lock
Labels: PR target: master-only, cla: yes
