Repository angular/angular-cli, pull requests merged in 2019-06, with the labels that each got.

#14537 feat(@schematics/angular): default Ivy apps to AOT true
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/index_spec.ts
  tests/legacy-cli/e2e/tests/build/polyfills.ts
  tests/legacy-cli/e2e/tests/build/script-target.ts
Labels: PR target: master & patch, cla: yes

#14538 Update doc to make connection of live-reload and public-host explicit
  packages/angular_devkit/build_angular/src/dev-server/schema.json
Labels: PR target: master & patch, cla: yes, effort1: easy (hours), type: docs

#14575 refactor: use standard node resolution and use async/await instead of…
  packages/angular_devkit/schematics/tasks/tslint-fix/executor.ts
Labels: PR target: master-only, cla: yes

#14598 fix(@angular/cli): add analytics option to options schema
  packages/angular/cli/lib/config/schema.json
Labels: PR target: master & patch, cla: yes

#14607 refactor: deprecate `isSupported` static in `AngularCompilerPlugin`
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master & patch, cla: yes

#14611 refactor(@schematics/angular): remove non-useful or operator
  packages/schematics/angular/ng-new/index.ts
Labels: PR target: master-only, cla: yes

#14622 fix(@angular/cli): resolve update migrations from referenced package root
  packages/angular/cli/commands/update-impl.ts
Labels: PR target: master & patch, cla: yes

#14630 ci: disable TypeScript patch updates for different major and minor versions
  renovate.json
Labels: PR target: master-only, cla: yes

#14649 fix(@angular/cli): avoid updating when package is already up to date
  packages/angular/cli/commands/update-impl.ts
Labels: PR target: master & patch, cla: yes

#14658 fix(@ngtools/webpack): rebuilding project with errors reports cannot …
  packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master & patch, cla: yes

#14664 fix(@angular-devkit/build-angular): server build is generating un-need…
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/test/server/base_spec_large.ts
Labels: PR target: master & patch, cla: yes

#14677 fix(@ngtools/webpack): always strip BOM when reading files
  packages/ngtools/webpack/src/compiler_host.ts
Labels: PR target: master & patch, cla: yes

#14678 fix(@angular/cli): use recommended TTY check logic
  packages/angular/cli/utilities/tty.ts
Labels: PR target: master & patch, cla: yes

#14688 fix(@schematics/angular): move browserslist even when no sourceRoot i…
  packages/schematics/angular/migrations/update-8/differential-loading.ts
  packages/schematics/angular/migrations/update-8/differential-loading_spec.ts
Labels: PR target: master & patch, cla: yes

#14693 fix(@angular-devkit/build-angular): re-order ES5 polyfills in karma H…
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma-context.html
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma-debug.html
Labels: PR target: master & patch, cla: yes

#14698 fix(@schematics/angular): enable tsc `downlevelIteration`
  packages/schematics/angular/migrations/update-8/differential-loading.ts
  packages/schematics/angular/migrations/update-8/differential-loading_spec.ts
  packages/schematics/angular/workspace/files/tsconfig.json.template
Labels: PR target: master-only, cla: yes

#14710 Patch version of #14303
  packages/angular_devkit/architect_cli/package.json
  yarn.lock
Labels: PR target: patch-only, cla: yes

#14708 ci: use matching openssl key digest
  .circleci/config.yml
Labels: PR target: master & patch, cla: yes

#14676 fix(@angular-devkit/architect): error out when invalid configurations are provided
  packages/angular_devkit/architect/node/node-modules-architect-host.ts
  packages/angular_devkit/architect/src/architect.ts
  packages/angular_devkit/architect/src/index_spec.ts
  tests/legacy-cli/e2e/tests/commands/unknown-configuration.ts
Labels: PR target: master & patch, cla: yes

#14720 fix(@ngtools/webpack): avoid resetting emit skipped flag before emit
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master & patch, cla: yes

#14713 fix(@schematics/angular): enable tsc `downlevelIteration`
  packages/schematics/angular/migrations/update-8/differential-loading.ts
  packages/schematics/angular/migrations/update-8/differential-loading_spec.ts
  packages/schematics/angular/workspace/files/tsconfig.json.template
Labels: PR target: patch-only, cla: yes

#14725 fix(@angular/cli): allow update when git is unclean outside the workspace
  packages/angular/cli/commands/update-impl.ts
Labels: PR target: master & patch, cla: yes

#14728 test: fix flakes of `rebuilds TS worker`
  packages/angular_devkit/build_angular/test/browser/web-worker_spec_large.ts
Labels: PR target: master & patch, cla: yes

#14734 style: remove extra whitespaces for circleci config
  .circleci/config.yml
Labels: PR target: master-only, cla: yes

#14729 fix(@schematics/angular): remove `lint` target from minimal projects
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/e2e/index_spec.ts
Labels: PR target: master & patch, cla: yes

#14740 fix(@angular/cli): only enable CLI 1.x update handling when no new config
  packages/angular/cli/commands/update-impl.ts
Labels: PR target: master & patch, cla: yes

#14752 refactor: Add explict type to allow RxJS to be updated
  packages/angular_devkit/core/src/experimental/workspace/workspace.ts
Labels: PR target: master & patch, cla: yes, comp: angular/cli

#14753 fix(@ngtools/webpack): implement getModifiedResourceFiles for Ivy AOT
  packages/ngtools/webpack/src/compiler_host.ts
  packages/ngtools/webpack/src/resource_loader.ts
Labels: PR target: master-only, cla: yes

#14760 fix(@schematics/update): remove update all suggestion message
  packages/schematics/update/update/index.ts
Labels: PR target: master & patch, cla: yes

#14665 feat(@angular-devkit/build-angular): move milliseconds time audit at …
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
Labels: PR target: master-only, cla: yes

#14778 fix(@ngtools/webpack): avoid resetting emit skipped flag when no Type…
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master & patch, cla: yes

#14771 fix(@angular-devkit/build-angular): emit warning when using extract-i…
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/read-tsconfig.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
Labels: PR target: master & patch, cla: yes

#14765 fix(@angular/cli): ensure analytics prompt exceptions are caught
  packages/angular/cli/bin/postinstall/analytics-prompt.js
Labels: PR target: master & patch, cla: yes

#14784 Patch version of #14771
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/read-tsconfig.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
Labels: PR target: patch-only, cla: yes

#14800 feat(@schematics/angular): add `fullTemplateTypeCheck` and `strictInj…
  packages/schematics/angular/workspace/files/tsconfig.json.template
Labels: PR target: master-only, cla: yes

#14789 feat(@ngtools/webpack): improved TypeScript diagnostic reporting
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master-only, cla: yes

#14788 feat(@angular/cli): ng doc accepts a version flag
  packages/angular/cli/commands/doc-impl.ts
  packages/angular/cli/commands/doc.json
Labels: PR target: master-only, cla: yes

#14780 refactor(@angular/cli): standardize color handling and support checking
  package.json
  packages/angular/cli/BUILD
  packages/angular/cli/lib/cli/index.ts
  packages/angular/cli/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#14799 fix(@schematics/angular): support adding web-worker to pre version 8 …
  packages/schematics/angular/web-worker/index.ts
  packages/schematics/angular/web-worker/index_spec.ts
Labels: PR target: master & patch, cla: yes

#14802 feat(@angular/cli): log unhandled exceptions
  packages/angular/cli/lib/cli/index.ts
Labels: PR target: master-only, cla: yes

#14817 fix(@schematics/angular): remove indentation in component html
  packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
Labels: PR target: master & patch, cla: yes

#14810 fix(@angular-devkit/build-optimizer): wrap TypeScript string enums in…
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums_spec.ts
Labels: PR target: master & patch, cla: yes

#14773 fix(@angular-devkit/build-optimizer): incorrectly augmented ES2015 de…
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums_spec.ts
Labels: PR target: master & patch, cla: yes

#14824 refactor(@angular-devkit/build-angular): cleanup compatible Angular version check
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/karma/index.ts
  packages/angular_devkit/build_angular/src/server/index.ts
  packages/angular_devkit/build_angular/src/utils/version.ts
Labels: PR target: master-only, cla: yes

#14831 fix(@angular/cli): correct git branch in ng version
  packages/angular/cli/commands/version-impl.ts
Labels: PR target: master & patch, cla: yes

#14829 fix(@angular-devkit/build-angular): browser builder should not swollo…
  packages/angular/cli/models/architect-command.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/service-worker/index.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
Labels: PR target: master & patch, cla: yes

#14828 fix(@angular-devkit/build-angular): karma cannot read property 'succe…
  packages/angular_devkit/build_angular/src/karma/index.ts
Labels: PR target: master & patch, cla: yes

#14818 fix(@angular-devkit/build-angular): remove certain redundant build st…
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
Labels: PR target: master & patch, cla: yes

#14785 fix(@schematics/angular): improve pipe signature
  packages/schematics/angular/pipe/files/__name@dasherize@if-flat__/__name@dasherize__.pipe.ts.template
  packages/schematics/angular/pipe/index_spec.ts
Labels: PR target: master & patch, cla: yes

#14782 feat(@schematics/angular): add skipSelector property to the component generator
  packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
  packages/schematics/angular/component/index_spec.ts
  packages/schematics/angular/component/schema.json
Labels: PR target: master-only, cla: yes

#14755 fix(@ngtools/webpack): NGCC workspace libraries module resolution
  packages/ngtools/webpack/src/ngcc_processor.ts
  tests/legacy-cli/e2e_runner.ts
Labels: PR target: master-only, cla: yes

#14023 build: integrate prettier code formatting
  .circleci/config.yml
  .lintstagedrc
  .prettierrc
  package.json
  tslint.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#14840 fix(@angular-devkit/build-angular): re-order reporters to set code coverage at the very end
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma.ts
  packages/angular_devkit/build_angular/test/karma/code-coverage_spec_large.ts
Labels: PR target: master & patch, cla: yes

#14792 refactor(@angular/pwa): update to use new workspace rules
  packages/angular/pwa/pwa/index.ts
Labels: PR target: master-only, cla: yes

#14853 refactor: ES5 no longer have css files
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/write-index-html.ts
Labels: PR target: patch-only, cla: yes

#13423 feat(@angular-devkit/build-angular): option to build and test only specified spec files
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/single-test-transform.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/find-tests.ts
  packages/angular_devkit/build_angular/src/karma/index.ts
  packages/angular_devkit/build_angular/src/karma/schema.json
  packages/angular_devkit/build_angular/test/karma/selected_spec_large.ts
Labels: PR target: master-only, cla: yes

#14848 refactor(@angular/cli): unify color handling and support
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/commands/easter-egg-impl.ts
  packages/angular/cli/commands/generate-impl.ts
  packages/angular/cli/commands/help-impl.ts
  packages/angular/cli/commands/version-impl.ts
  packages/angular/cli/lib/cli/index.ts
  packages/angular/cli/lib/init.ts
  packages/angular/cli/models/analytics.ts
  packages/angular/cli/models/command.ts
  packages/angular/cli/models/schematic-command.ts
  packages/angular/cli/tasks/npm-install.ts
  packages/angular/cli/utilities/color.ts
Labels: PR target: master-only, cla: yes

#14858 fix(@angular/cli): validate version in doc command
  packages/angular/cli/commands/doc-impl.ts
  packages/angular/cli/commands/doc.json
  packages/angular/cli/models/parser.ts
Labels: PR target: master-only, cla: yes

#14864 fix: fix BUILD file filter for npm package to include both BUILD and BUILD.bazel file
  scripts/build.ts
Labels: PR target: master & patch, cla: yes

#14877 fix(@angular-devkit/build-angular): force event category to be something
  packages/angular_devkit/build_angular/src/browser/index.ts
Labels: PR target: master & patch, cla: yes

#14854 fix(@angular/cli): log file path normalization
  packages/angular/cli/lib/cli/index.ts
Labels: PR target: master-only, cla: yes

#14885 fix(@schematics/angular): Remove duplicate entries for module and moduleResolution
  packages/schematics/angular/workspace/files/tsconfig.json.template
Labels: PR target: patch-only, cla: yes

#14887 fix(@schematics/angular): replace forked `web-animations-js` with latest version
  packages/schematics/angular/migrations/update-8/update-dependencies.ts
Labels: PR target: master & patch, cla: yes

#14891 fix(@ngtools/webpack): skip non-runtime types when transforming constructors
  packages/ngtools/webpack/src/transformers/ctor-parameters.ts
  packages/ngtools/webpack/src/transformers/ctor-parameters_spec.ts
Labels: PR target: master & patch, cla: yes

#14345 feat(@schematics/angular): route generator
  packages/schematics/angular/library/index.ts
  packages/schematics/angular/module/files/__name@dasherize@if-flat__/__name@dasherize__-routing.module.ts.template
  packages/schematics/angular/module/files/__name@dasherize@if-flat__/__name@dasherize__.module.ts.template
  packages/schematics/angular/module/index.ts
  packages/schematics/angular/module/index_spec.ts
  packages/schematics/angular/module/schema.json
  packages/schematics/angular/utility/ast-utils.ts
  packages/schematics/angular/utility/ast-utils_spec.ts
Labels: PR target: master-only, cla: yes

#14796 fix(@angular-devkit/build-angular): add `type="module"` on script tag…
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/index-html-webpack-plugin.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/test/browser/differential_loading_spec_large.ts
  packages/angular_devkit/build_angular/test/dev-server/index_spec_large.ts
Labels: PR target: master-only, cla: yes

#14865 fix(@angular-devkit/schematics): fix use `install` subcommand when override package manager to yarn
  packages/angular_devkit/schematics/tasks/node-package/executor.ts
Labels: PR target: master & patch, cla: yes

#14912 feat(@angular/cli): report RAM in gigabytes instead of megabytes
  docs/design/analytics.md
  etc/api/angular_devkit/core/src/_golden-api.d.ts
  packages/angular/cli/models/analytics.ts
  packages/angular_devkit/core/src/analytics/index.ts
Labels: PR target: master-only, cla: yes

#14926 feat(@angular/cli): ng doc uses angular core version by default
  packages/angular/cli/commands/doc-impl.ts
  packages/angular/cli/commands/doc.json
Labels: PR target: master-only, cla: yes

#14915 fix(@schematics/angular): set proper severity of the tslint deprecation rule
  packages/schematics/angular/workspace/files/tslint.json.template
Labels: PR target: master & patch, cla: yes

#14917 fix(@angular-devkit/build-angular): add Symbol.iterator polyfill for legacy browsers
  packages/angular_devkit/build_angular/src/angular-cli-files/models/es5-polyfills.js
Labels: PR target: master & patch, cla: yes

#14904 style: enable `no-debugger` and `no-console` tslint rules
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/lib/cli/index.ts
  packages/angular/cli/lib/init.ts
  packages/angular/cli/models/analytics.ts
  packages/angular_devkit/architect_cli/bin/architect.ts
  packages/angular_devkit/build_optimizer/src/build-optimizer/cli.ts
  packages/angular_devkit/build_optimizer/src/build-optimizer/rollup-plugin.ts
  packages/ngtools/webpack/src/benchmark.ts
  packages/ngtools/webpack/src/compiler_host.ts
  packages/schematics/angular/utility/ast-utils.ts
  scripts/benchmark.ts
  scripts/changelog.ts
  scripts/lint.ts
  scripts/publish-docs.ts
  scripts/test.ts
  tslint.json
Labels: PR target: master-only, cla: yes

#14844 feat(@angular-devkit/build-angular): add crossorigin options
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/index-html-webpack-plugin.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/augment-index-html.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/write-index-html.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/test/browser/cross-origin_spec_large.ts
Labels: PR target: master-only, cla: yes

#14898 test: disable max line length linting for constructor parameters transformer unit tests
  packages/ngtools/webpack/src/transformers/ctor-parameters_spec.ts
Labels: PR target: patch-only, cla: yes

#14913 fix(@angular/cli): pass in metrics to the pageview for commands
  packages/angular/cli/models/command.ts
Labels: PR target: master-only, cla: yes

#14934 fix(@ngtools/webpack): NGCC should process secondary entry-points
  packages/ngtools/webpack/src/ngcc_processor.ts
  tests/legacy-cli/e2e/tests/ivy/ivy.ts
Labels: PR target: master-only, cla: yes, comp: ngtools/webpack, effort1: easy (hours), freq2: medium, priority: 2 (required), severity2: inconvenient, type: bug/fix

#14940 build: stop code formatting with prettier
  .circleci/config.yml
  .lintstagedrc
  package.json
  yarn.lock
Labels: PR target: master-only, cla: yes
