Repository angular/angular-cli, pull requests merged in 2019-01, with the labels that each got.

#13286 [6.2.x] fix(@angular/cli): 'ng add' selects supported version via peer dependencies
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/package.json
  packages/angular/cli/tasks/npm-install.ts
  packages/angular/cli/utilities/package-metadata.ts
  tests/legacy-cli/e2e/assets/add-collection-peer-bad/collection.json
  tests/legacy-cli/e2e/assets/add-collection-peer-bad/index.js
  tests/legacy-cli/e2e/assets/add-collection-peer-bad/package.json
  tests/legacy-cli/e2e/assets/add-collection-peer-good/collection.json
  tests/legacy-cli/e2e/assets/add-collection-peer-good/index.js
  tests/legacy-cli/e2e/assets/add-collection-peer-good/package.json
  tests/legacy-cli/e2e/assets/add-collection.tgz
  tests/legacy-cli/e2e/assets/add-collection/package.json
  tests/legacy-cli/e2e/tests/build/styles/material-import.ts
  tests/legacy-cli/e2e/tests/commands/add/add-material.ts
  tests/legacy-cli/e2e/tests/commands/add/add-pwa.ts
  tests/legacy-cli/e2e/tests/commands/add/base.ts
  tests/legacy-cli/e2e/tests/commands/add/dir.ts
  tests/legacy-cli/e2e/tests/commands/add/file.ts
  tests/legacy-cli/e2e/tests/commands/add/peer.ts
  yarn.lock
Labels: PR target: LTS-only, cla: yes

#13290 docs(fontawesome): add documentation for using font awesome and scss …
  docs/documentation/stories/include-font-awesome.md
Labels: PR target: master-only, cla: yes

#13292 refactor(@angular-devkit/build-angular): improve check port
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/check-port.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#13331 feat(@schematics/angular): generate a library with a README.md file
  packages/schematics/angular/library/files/__projectRoot__/README.md
  packages/schematics/angular/library/index_spec.ts
Labels: PR target: master-only, cla: yes

#13332 build: update license-webpack-plugin to version 2.0.4
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: patch-only, cla: yes

#13337 docs: fix license badge url
  packages/angular/cli/README.md
Labels: PR target: master & patch, cla: yes

#13346 feat(@schematics/angular): generate ngsw-config.json under the project
  packages/schematics/angular/service-worker/index.ts
  packages/schematics/angular/service-worker/index_spec.ts
  packages/schematics/angular/utility/workspace-models.ts
Labels: PR target: master-only, cla: yes

#13347 build: update webpack-dev-server to version 3.1.14
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: LTS-only, PR target: patch-only, cla: yes

#13353 docs: fix grammar error
  CONTRIBUTING.md
  scripts/templates/contributing.ejs
Labels: PR target: master-only, cla: yes

#13356 feat(@schematics/angular): add support for `tslint.yaml` in lint fix
  packages/schematics/angular/utility/lint-fix.ts
Labels: PR target: master-only, cla: yes

#13366 docs: add deprecation and pr note
  docs/documentation/add.md
  docs/documentation/angular-workspace.md
  docs/documentation/build.md
  docs/documentation/config.md
  docs/documentation/doc.md
  docs/documentation/e2e.md
  docs/documentation/eject.md
  docs/documentation/generate.md
  docs/documentation/generate/app-shell.md
  docs/documentation/generate/application.md
  docs/documentation/generate/class.md
  docs/documentation/generate/component.md
  docs/documentation/generate/directive.md
  docs/documentation/generate/enum.md
  docs/documentation/generate/guard.md
  docs/documentation/generate/interface.md
  docs/documentation/generate/library.md
  docs/documentation/generate/module.md
  docs/documentation/generate/pipe.md
  docs/documentation/generate/service.md
  docs/documentation/generate/universal.md
  docs/documentation/help.md
  docs/documentation/lint.md
  docs/documentation/new.md
  docs/documentation/run.md
  docs/documentation/serve.md
  docs/documentation/stories/1.0-update.md
  docs/documentation/stories/app-shell.md
  docs/documentation/stories/application-environments.md
  docs/documentation/stories/asset-configuration.md
  docs/documentation/stories/autoprefixer.md
  docs/documentation/stories/budgets.md
  docs/documentation/stories/code-coverage.md
  docs/documentation/stories/configure-hmr.md
  docs/documentation/stories/continuous-integration.md
  docs/documentation/stories/create-library.md
  docs/documentation/stories/css-preprocessors.md
  docs/documentation/stories/disk-serve.md
  docs/documentation/stories/github-pages.md
  docs/documentation/stories/global-lib.md
  docs/documentation/stories/global-scripts.md
  docs/documentation/stories/global-styles.md
  docs/documentation/stories/include-angular-flex.md
  docs/documentation/stories/include-angular-material.md
  docs/documentation/stories/include-angularfire.md
  docs/documentation/stories/include-bootstrap.md
  docs/documentation/stories/include-font-awesome.md
  docs/documentation/stories/internationalization.md
  docs/documentation/stories/multiple-projects.md
  docs/documentation/stories/proxy.md
  docs/documentation/stories/routing.md
  docs/documentation/stories/third-party-lib.md
  docs/documentation/stories/universal-rendering.md
  docs/documentation/test.md
  docs/documentation/update.md
  docs/documentation/version.md
  docs/documentation/xi18n.md
Labels: PR target: master-only, cla: yes

#13377 fix(@schematics/angular): remove properties which are set by default …
  packages/schematics/angular/service-worker/schema.json
Labels: PR target: master & patch, cla: yes

#13389 fix(@schematics/update): check if replace is a function
  packages/schematics/update/update/npm.ts
Labels: PR target: master & patch, cla: yes

#13396 fix(@schematics/angular): fix syntax error in main.ts after generating universal
  packages/schematics/angular/universal/index.ts
  packages/schematics/angular/universal/index_spec.ts
Labels: PR target: master & patch, cla: yes

#13401 feat(@schematics/angular): add UrlTree to CanActivate method signature
  packages/schematics/angular/guard/files/__name@dasherize__.guard.ts
Labels: PR target: master-only, cla: yes

#13404 fix(@angular-devkit/build-optimizer): support windows paths in rollup…
  packages/angular_devkit/build_optimizer/src/build-optimizer/rollup-plugin.ts
Labels: PR target: master & patch, cla: yes, comp: devkit/build-optimizer, type: bug/fix

#13407 build: terminate process with non zero error code when build fails
  bin/devkit-admin
Labels: PR target: master & patch, cla: yes

#13408 docs: add clause that states the `minimal` projects are for learning …
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/ng-new/schema.json
  packages/schematics/angular/workspace/schema.json
Labels: PR target: master & patch, cla: yes

#13406 fix(@schematics/angular): Add types to AppPage in e2e
  packages/schematics/angular/e2e/files/src/app.po.ts
Labels: PR target: master-only, cla: yes

#13275 feat(@angular-devkit/schematics): support executing a schematic rule on a subtree
  etc/api/angular_devkit/schematics/src/_golden-api.d.ts
  packages/angular_devkit/schematics/src/engine/interface.ts
  packages/angular_devkit/schematics/src/engine/schematic.ts
  packages/angular_devkit/schematics/src/engine/schematic_spec.ts
  packages/angular_devkit/schematics/src/tree/scoped.ts
  packages/angular_devkit/schematics/src/tree/scoped_spec.ts
Labels: PR target: master-only, cla: yes

#13417 fix(@angular-devkit/build-angular): prints a warning on --host on serve
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: PR target: master & patch, cla: yes

#13421 fix(@angular-devkit/build-angular): add missing declaration types …
  packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
  packages/angular_devkit/build_angular/src/browser/schema.d.ts
  packages/angular_devkit/build_angular/src/karma/schema.d.ts
  packages/angular_devkit/build_angular/src/server/schema.d.ts
  packages/angular_devkit/build_angular/src/utils/normalize-optimization.ts
  packages/angular_devkit/build_angular/src/utils/normalize-source-maps.ts
Labels: PR target: master & patch, cla: yes

#13427 feat(@schematics/angular): activate recommended tslint rules
  packages/schematics/angular/workspace/files/tslint.json
Labels: PR target: master-only, cla: yes

#13430 fix(@angular-devkit/build-angular): only show production warning when…
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: PR target: master & patch, cla: yes

#13431 fix(@angular-devkit/build-angular): `vendorSourceMap` not being recognized w…
  packages/angular_devkit/build_angular/src/utils/normalize-builder-schema.ts
  packages/angular_devkit/build_angular/test/browser/vendor-source-map_spec_large.ts
Labels: PR target: master & patch, cla: yes

#13202 feat(@angular-devkit/schematics): support calling a task by file path when using a FileSystemEngineHost
  etc/api/angular_devkit/schematics/tools/index.d.ts
  packages/angular_devkit/schematics/tools/file-system-engine-host.ts
  packages/angular_devkit/schematics/tools/file-system-engine-host_spec.ts
  tests/angular_devkit/schematics/tools/file-system-engine-host/BUILD
  tests/angular_devkit/schematics/tools/file-system-engine-host/file-tasks/collection.json
  tests/angular_devkit/schematics/tools/file-system-engine-host/file-tasks/factory.ts
  tests/angular_devkit/schematics/tools/file-system-engine-host/file-tasks/file-task.js
Labels: PR target: master-only, cla: yes

#13224 fix(@angular-devkit/build-angular): script chunk in angular.json return false then calling isInitial
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/scripts-webpack-plugin.ts
  packages/angular_devkit/build_angular/test/browser/scripts-array_spec_large.ts
Labels: PR target: master & patch, cla: yes

#13432 build: update `webpack` and `postcss`
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/postcss-cli-resources.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#13109 feat(@schematics/angular): Added multiselect guard implements option
  packages/schematics/angular/guard/files/__name@dasherize__.guard.ts
  packages/schematics/angular/guard/index.ts
  packages/schematics/angular/guard/index_spec.ts
  packages/schematics/angular/guard/schema.json
Labels: PR target: master-only, cla: yes

#13444 fix(@schematics/angular): stop offering SASS option for ng new
  packages/ngtools/webpack/README.md
  packages/schematics/angular/ng-new/schema.json
Labels: PR target: master-only, cla: yes

#13436 build: update `webpack` and `postcss`
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/postcss-cli-resources.ts
  yarn.lock
Labels: PR target: patch-only, cla: yes

#13443 Make default and info message log messages use terminal default colors
  packages/angular_devkit/core/node/cli-logger.ts
Labels: PR target: master & patch, cla: yes

#13450 build: Update Bazel workspace
  WORKSPACE
  etc/api/angular_devkit/schematics/src/_golden-api.d.ts
  package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#13472 fix(@schematics/angular): update latest version of devkit
  packages/schematics/angular/utility/latest-versions.ts
Labels: PR target: master-only, cla: yes

#13468 build: pin typescript and webpack
  package.json
  packages/angular_devkit/build_optimizer/package.json
  packages/angular_devkit/build_webpack/package.json
  packages/ngtools/webpack/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#13461 docs: new GitHub Issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-feature-request.md
  .github/ISSUE_TEMPLATE/3-docs-bug.md
  .github/ISSUE_TEMPLATE/4-security-issue-disclosure.md
  .github/ISSUE_TEMPLATE/5-support-request.md
  .github/ISSUE_TEMPLATE/6-angular-framework.md
  .github/ISSUE_TEMPLATE/7-angular-material.md
Labels: PR target: master-only, cla: yes

#13442 build: add Alan to the mailmap file
  .mailmap
Labels: PR target: master-only, cla: yes

#13462 docs(@angular-devkit/schematics): include npm link
  packages/angular_devkit/schematics/README.md
Labels: PR target: master & patch, cla: yes

#13302 site, upd current date
  etc/cli.angular.io/index.html
Labels: PR target: master & patch, cla: yes

#13496 feat(@angular-devkit/build-optimizer): also fold ES2015 classes
  packages/angular_devkit/build_optimizer/src/transforms/class-fold.ts
  packages/angular_devkit/build_optimizer/src/transforms/class-fold_spec.ts
Labels: PR target: master-only, cla: yes

#13495 feat(@angular-devkit/build-optimizer): add support for es2015 enums e…
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums_spec.ts
Labels: PR target: master-only, cla: yes

#13494 feat(@angular-devkit/build-angular): update webpack to 4.29
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_webpack/package.json
  packages/ngtools/webpack/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#13482 fix(@schematics/angular): add non deprecated `style` as default
  packages/schematics/angular/application/index.ts
Labels: PR target: master & patch, cla: yes

#13499 refactor: create helper functions for pure comments
  packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts
  packages/angular_devkit/build_optimizer/src/transforms/class-fold.ts
  packages/angular_devkit/build_optimizer/src/transforms/prefix-classes.ts
  packages/angular_devkit/build_optimizer/src/transforms/prefix-functions.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
Labels: PR target: master-only, cla: yes

#13500 docs: fix typo in index.html
  etc/cli.angular.io/index.html
Labels: PR target: master & patch, cla: yes

#13510 fix(@angular-devkit/core): remove colors for info messages
  packages/angular_devkit/benchmark/src/main.ts
  packages/angular_devkit/core/node/cli-logger.ts
Labels: PR target: master & patch, cla: yes

#13511 fix(@schematics/angular): Add types annotations to e2e AppPage
  packages/schematics/angular/e2e/files/src/app.po.ts
Labels: cla: yes

#13512 ci: checkout existing branch on snapshots
  scripts/snapshots.ts
Labels: PR target: master & patch, cla: yes

#13517 docs: update release process
  docs/process/release.md
Labels: cla: yes

#13514 docs: remove non existing format command
  etc/cli.angular.io/index.html
Labels: PR target: master-only, cla: yes

#13475 refactor(@angular-devkit/schematics): remove unused VirtualTree classes
  etc/api/angular_devkit/schematics/src/_golden-api.d.ts
  packages/angular_devkit/schematics/src/index.ts
  packages/angular_devkit/schematics/src/rules/base.ts
  packages/angular_devkit/schematics/src/tree/filesystem.ts
  packages/angular_devkit/schematics/src/tree/filesystem_spec.ts
  packages/angular_devkit/schematics/src/tree/filtered.ts
  packages/angular_devkit/schematics/src/tree/filtered_spec.ts
  packages/angular_devkit/schematics/src/tree/host-tree_spec.ts
  packages/angular_devkit/schematics/src/tree/static.ts
  packages/angular_devkit/schematics/src/tree/virtual.ts
  packages/angular_devkit/schematics/src/tree/virtual_spec.ts
Labels: PR target: master-only, blocked, cla: yes

#13536 fix(@angular/cli): ng-add should resolve package.json
  packages/angular/cli/commands/add-impl.ts
Labels: PR target: master & patch, cla: yes, comp: angular/cli

#13532 fix(@ngtools/webpack): provide a TS-like path to ngProgram.listLazyRo…
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master-only, cla: yes

#13546 feat(@schematics/angular): renove `annotateForClosureCompiler` in libraries tsconfig
  packages/schematics/angular/library/files/__projectRoot__/tsconfig.lib.json.template
  tests/angular_devkit/build_ng_packagr/ng-packaged/projects/lib/tsconfig.lib.json
Labels: PR target: master-only, cla: yes

#13528 fix(@schematics/angular): remove leading comments when removing `core…
  packages/schematics/angular/migrations/update-7/polyfill-metadata.ts
  packages/schematics/angular/migrations/update-7/polyfill-metadata_spec.ts
Labels: PR target: master & patch, cla: yes

#13523 Use baseUrl for default e2e test
  packages/schematics/angular/e2e/files/src/app.po.ts.template
  tests/angular_devkit/build_angular/hello-world-app/e2e/app.po.ts
Labels: PR target: master & patch, cla: yes

#13522 fix(@angular/cli): remove unsupported `dryRun` and `force` from `ng add`
  packages/angular/cli/commands/add.json
  packages/angular/cli/commands/definitions.json
  packages/angular/cli/commands/generate.json
  packages/angular/cli/commands/new.json
Labels: PR target: master & patch, cla: yes

#13509 fix(@schematics/schematics): use correct collection.json path
  packages/schematics/schematics/schematic/files/src/collection.json
Labels: PR target: master & patch, cla: yes

#13480 fix(@angular/cli): schematics commands should fail on unknown options
  packages/angular/cli/models/schematic-command.ts
  tests/legacy-cli/e2e/tests/commands/unknown-option.ts
Labels: PR target: master-only, cla: yes
