Repository angular/angular-cli, pull requests merged in 2019-08, with the labels that each got.

#15207 fix(@schematics/angular): the `ng-new` schematic should not prompt for style nor for routing
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/ng-new/schema.json
Labels: PR target: master-only, cla: yes

#15231 refactor: cleancss-webpack-plugin to use async/await
  package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/cleancss-webpack-plugin.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#15221 fix(@angular-devkit/build-angular): various breakpoints issues
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/utils.ts
Labels: PR target: master & patch, cla: yes

#15222 fix(@angular-devkit/core): add schema defaults when value is undefined
  packages/angular_devkit/core/src/json/schema/registry_spec.ts
  packages/angular_devkit/core/src/json/schema/transforms.ts
Labels: PR target: master & patch, cla: yes

#15249 refactor(@schematics/angular): remove unused schema properties from w…
  packages/schematics/angular/workspace/schema.json
Labels: PR target: master-only, cla: yes

#15217 fix(@angular-devkit/build-angular): use GLOBAL_DEFS_FOR_TERSER_WITH_A…
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Labels: PR target: master & patch, cla: yes

#15224 fix(@ngtools/webpack): display unused file warning once per file
  packages/angular_devkit/build_angular/test/browser/unused-files-warning_spec_large.ts
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master & patch, cla: yes

#15241 ci: add flake jail
  .circleci/config.yml
  scripts/test.ts
Labels: PR target: master & patch, cla: yes

#15243 test: fix failing prod build snapshots
  tests/legacy-cli/e2e/tests/build/prod-build.ts
Labels: PR target: master & patch, cla: yes

#15244 fix(@ngtools/webpack): gracefully show error when compiling broken co…
  packages/angular_devkit/build_angular/test/browser/aot_spec_large.ts
  packages/ngtools/webpack/src/resource_loader.ts
Labels: PR target: master & patch, cla: yes

#15245 refactor(@schematics/angular): remove hardcoded default values
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/library/index.ts
Labels: PR target: master-only, cla: yes

#15269 test: remove use of deprecated synchronous test helper `runSchematic`
  packages/angular/pwa/pwa/index_spec.ts
  packages/schematics/angular/app-shell/index_spec.ts
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/class/index_spec.ts
  packages/schematics/angular/component/index_spec.ts
  packages/schematics/angular/directive/index_spec.ts
  packages/schematics/angular/e2e/index_spec.ts
  packages/schematics/angular/enum/index_spec.ts
  packages/schematics/angular/guard/index_spec.ts
  packages/schematics/angular/interface/index_spec.ts
  packages/schematics/angular/library/index_spec.ts
  packages/schematics/angular/migrations/update-6/index_spec.ts
  packages/schematics/angular/migrations/update-8/codelyzer-5_spec.ts
  packages/schematics/angular/migrations/update-8/differential-loading_spec.ts
  packages/schematics/angular/migrations/update-8/drop-es6-polyfills_spec.ts
  packages/schematics/angular/migrations/update-8/remove-angular-http_spec.ts
  packages/schematics/angular/migrations/update-8/update-lazy-module-paths_spec.ts
  packages/schematics/angular/migrations/update-9/update-workspace-config_spec.ts
  packages/schematics/angular/module/index_spec.ts
  packages/schematics/angular/pipe/index_spec.ts
  packages/schematics/angular/service-worker/index_spec.ts
  packages/schematics/angular/service/index_spec.ts
  packages/schematics/angular/universal/index_spec.ts
  packages/schematics/angular/web-worker/index_spec.ts
  packages/schematics/angular/workspace/index_spec.ts
Labels: PR target: master-only, cla: yes

#15266 fix(@angular-devkit/build-angular): consider local decl in angular co…
  packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts
Labels: PR target: master-only, cla: yes

#15276 fix(@angular-devkit/build-angular): avoid defer attribute for Safari nomodule polyfill
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/augment-index-html.ts
  tests/legacy-cli/e2e/tests/misc/support-safari-10.1.ts
Labels: PR target: patch-only, cla: yes

#15311 feat(@ngtools/webpack): add support for raw-loader 2 and 3
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/src/resource_loader.ts
  packages/ngtools/webpack/src/transformers/replace_resources.ts
  packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#15262 Ivy build_ng_packagr
  .circleci/config.yml
  packages/angular_devkit/build_angular/test/browser/web-worker_spec_large.ts
  packages/angular_devkit/build_angular/test/utils.ts
  packages/angular_devkit/build_ng_packagr/package.json
  packages/angular_devkit/build_ng_packagr/src/build/index_spec_large.ts
  packages/schematics/angular/utility/latest-versions.ts
  scripts/test.ts
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/.gitignore
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/angular.json
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/projects/lib/karma.conf.js
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/projects/lib/ng-package.json
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/projects/lib/package.json
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/projects/lib/src/lib/lib.component.spec.ts
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/projects/lib/src/lib/lib.component.ts
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/projects/lib/src/lib/lib.module.ts
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/projects/lib/src/lib/lib.service.spec.ts
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/projects/lib/src/lib/lib.service.ts
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/projects/lib/src/public-api.ts
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/projects/lib/src/test.ts
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/projects/lib/tsconfig.lib.json
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/projects/lib/tsconfig.lib.prod.json
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/projects/lib/tsconfig.spec.json
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/tsconfig.json
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/tslint.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#15289 refactor(@angular-devkit/architect-cli): minor package cleanup
  packages/angular_devkit/architect_cli/bin/architect.ts
  packages/angular_devkit/architect_cli/package.json
  packages/angular_devkit/architect_cli/src/progress.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#15292 fix(@ngtools/webpack): cleanup more resources after modules are loaded
  etc/api/angular_devkit/core/src/_golden-api.d.ts
  packages/angular_devkit/core/src/virtual-fs/host/memory.ts
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/ngtools/webpack/src/compiler_host.ts
Labels: PR target: master-only, cla: yes

#15293 ci: add e2e-cli-ng-ivy-snapshots job
  .circleci/config.yml
Labels: PR target: master-only, cla: yes

#15277 fix(@schematics/angular): add `manifest.webmanifest` to the list of p…
  packages/schematics/angular/service-worker/files/ngsw-config.json.template
Labels: PR target: master & patch, cla: yes

#15238 fix(@angular-devkit/build-angular): never use component css sourcemap…
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
Labels: PR target: master & patch, cla: yes

#15303 fix(@angular-devkit/build-optimizer): don't add pure comments to tslib helpers
  packages/angular_devkit/build_optimizer/BUILD
  packages/angular_devkit/build_optimizer/package.json
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
  packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts
  packages/angular_devkit/build_optimizer/src/transforms/import-tslib.ts
  packages/angular_devkit/build_optimizer/src/transforms/prefix-functions.ts
  packages/angular_devkit/build_optimizer/src/transforms/prefix-functions_spec.ts
Labels: PR target: master & patch, cla: yes

#15291 build: update bazel dependencies and configuration
  .bazelignore
  .bazelrc
  WORKSPACE
  package.json
  packages/angular_devkit/core/BUILD
  tools/BUILD
  yarn.lock
Labels: PR target: master-only, cla: yes

#15314 fix(@angular-devkit/build-optimizer): don't add pure comments to tsli…
  packages/angular_devkit/build_optimizer/BUILD
  packages/angular_devkit/build_optimizer/package.json
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
  packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts
  packages/angular_devkit/build_optimizer/src/transforms/import-tslib.ts
  packages/angular_devkit/build_optimizer/src/transforms/prefix-functions.ts
  packages/angular_devkit/build_optimizer/src/transforms/prefix-functions_spec.ts
  yarn.lock
Labels: PR target: patch-only, cla: yes

#14403 feat(@schematics/angular): cli app redesign
  packages/schematics/angular/application/files/src/favicon.ico.template
  packages/schematics/angular/application/files/src/index.html.template
  packages/schematics/angular/application/other-files/app.component.html.template
  packages/schematics/angular/application/other-files/app.component.spec.ts.template
  packages/schematics/angular/e2e/files/src/app.e2e-spec.ts.template
  packages/schematics/angular/e2e/files/src/app.po.ts.template
  tests/legacy-cli/e2e/tests/build/platform-server.ts
  tests/legacy-cli/e2e/tests/build/prod-build.ts
Labels: cla: yes

#15321 fix(@ngtools/webpack): add more details to the unused files warnings
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master & patch, cla: yes

#15322 test: add E2E test for only ES2015 ngcc with differential loading
  tests/legacy-cli/e2e/tests/ivy/ngcc-es2015-only.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#15324 fix(@schematics/angular): handle the inlineTemplate case for ng new
  packages/schematics/angular/application/other-files/app.component.ts.template
Labels: PR target: master-only, cla: yes

#15334 refactor(@angular-devkit/build-angular): update webpack typings
  package.json
  packages/angular_devkit/build_angular/plugins/webpack/analytics.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/cleancss-webpack-plugin.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/index-html-webpack-plugin.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_webpack/src/webpack-dev-server/index.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#15332 build: enable verbose_failures for bazel in ci
  .circleci/bazel.rc
Labels: PR target: master & patch, cla: yes

#15331 docs: update CONTRIBUTING.md to reflect default PR branch
  CONTRIBUTING.md
  scripts/templates/contributing.ejs
Labels: PR target: master & patch, cla: yes

#15329 fix(@schematics/schematics): exclude typescript sources from published files
  packages/schematics/schematics/schematic/files/package.json
Labels: PR target: master & patch, cla: yes

#15328 fix(@angular-devkit/build-angular): serve option merging is being overridden by defaults in schema
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/dev-server/schema.json
  packages/angular_devkit/build_angular/test/dev-server/works_spec_large.ts
Labels: PR target: master & patch, cla: yes

#15330 refactor(@angular-devkit/schematics): remove optimize from host-tree
  etc/api/angular_devkit/schematics/src/_golden-api.d.ts
  packages/angular_devkit/schematics/src/tree/host-tree.ts
Labels: PR target: master-only, cla: yes

#15346 build: update angular packages to version 9
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_ng_packagr/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  tests/legacy-cli/e2e/assets/webpack/test-app/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#15344 build: add bazel_toolchains to bazel renovate group
  renovate.json
Labels: PR target: master-only, cla: yes

#15313 fix(@schematics/angular): default interface for guard
  packages/schematics/angular/guard/index.ts
  packages/schematics/angular/guard/index_spec.ts
  packages/schematics/angular/guard/schema.json
Labels: PR target: master & patch, cla: yes

#15356 fix(@schematics/angular): handle existence of un-referenced library p…
  packages/schematics/angular/migrations/update-9/ivy-libraries.ts
  packages/schematics/angular/migrations/update-9/ivy-libraries_spec.ts
Labels: PR target: master-only, cla: yes

#15363 build: update @types/jasmine to version ~3.4.0
  package.json
  packages/schematics/angular/workspace/files/package.json.template
  packages/schematics/schematics/blank/project-files/package.json.template
  packages/schematics/schematics/schematic/files/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#15362 test: add replace_resources tests without helpers
  packages/ngtools/webpack/src/transformers/ast_helpers.ts
  packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
Labels: PR target: master & patch, cla: yes

#15364 refactor(@angular-devkit/build-angular): cache downlevel bundles
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
  tests/legacy-cli/e2e/tests/build/differential-cache.ts
  yarn.lock
Labels: PR target: master & patch, cla: yes

#15381 feat(@angular-devkit/build-angular): collect test coverage from JSX/TSX files
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
Labels: PR target: master-only, cla: yes

#15385 fix(@schematics/angular): add twitter link icon
  packages/schematics/angular/application/other-files/app.component.html.template
Labels: PR target: master & patch, cla: yes

#15390 build: update zone.js to ~0.10.1
  packages/schematics/angular/utility/latest-versions.ts
Labels: PR target: master-only, cla: yes

#15377 docs: ng add configures project in cwd
  packages/angular/cli/commands/add.md
Labels: PR target: master & patch, cla: yes, comp: angular/cli, effort1: easy (hours), freq1: low, priority: 3 (nice to have), severity1: confusing, type: docs

#15391 build: bump angular dev packages to latest next versions
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_ng_packagr/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/angular/workspace/files/tsconfig.json.template
  tests/angular_devkit/build_angular/hello-world-app-ivy/tsconfig.json
  tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/tsconfig.json
  tests/angular_devkit/build_webpack/angular-app/tsconfig.json
  tests/legacy-cli/e2e/assets/webpack/test-app/package.json
  tests/legacy-cli/e2e/assets/webpack/test-app/tsconfig.json
  tests/legacy-cli/e2e/tests/packages/webpack/test-app.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#15402 Add deploy command doc
  packages/angular/cli/commands/deploy-long.md
  packages/angular/cli/commands/deploy.json
Labels: PR target: master & patch, cla: yes, comp: angular/cli, effort1: easy (hours), freq1: low, priority: 3 (nice to have), severity1: confusing, type: docs

#15420 test: fix ng update test for version 7
  tests/legacy-cli/e2e/tests/update/update-7.0.ts
Labels: PR target: master-only, cla: yes

#15421 feat(@schematics/angular): add migration for dependencies
  packages/schematics/angular/migrations/update-9/index.ts
  packages/schematics/angular/migrations/update-9/update-dependencies.ts
Labels: PR target: master-only, cla: yes

#15416 fix(@ngtools/webpack): only add ctor params to decorated classes
  packages/ngtools/webpack/src/transformers/ctor-parameters.ts
  packages/ngtools/webpack/src/transformers/ctor-parameters_spec.ts
Labels: PR target: master & patch, cla: yes

#15400 fix(@angular-devkit/build-optimizer): replace multiple tslib helpers
  packages/angular_devkit/build_optimizer/src/transforms/import-tslib.ts
  packages/angular_devkit/build_optimizer/src/transforms/import-tslib_spec.ts
Labels: PR target: master & patch, cla: yes

#15412 fix(@schematics/angular): implements items type for guard schematic
  packages/schematics/angular/guard/schema.json
  tests/legacy-cli/e2e/tests/generate/guard/guard-basic.ts
  tests/legacy-cli/e2e/tests/generate/guard/guard-implements.ts
Labels: PR target: master & patch, cla: yes

#15413 fix(@angular-devkit/core): track workspace targets with no original collection
  etc/api/angular_devkit/core/src/_golden-api.d.ts
  packages/angular_devkit/core/src/workspace/definitions.ts
  packages/angular_devkit/core/src/workspace/json/reader.ts
  packages/angular_devkit/core/src/workspace/json/reader_spec.ts
Labels: PR target: master & patch, cla: yes

#15417 fix(@angular-devkit/build-angular): default poll value when not present
  packages/angular_devkit/build_angular/src/utils/normalize-builder-schema.ts
Labels: PR target: master-only, cla: yes

#15430 fix(@schematics/angular): update tsickle to 0.37.0
  packages/schematics/angular/utility/latest-versions.ts
Labels: PR target: master & patch, cla: yes

#15459 feat(@angular/cli): add support for custom npmrc path
  packages/angular/cli/utilities/package-metadata.ts
Labels: PR target: master-only, cla: yes

#15457 feat(@angular-devkit/build-angular): exclude TSX test files from test coverage
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
Labels: PR target: master-only, cla: yes

#15470 fix(@angular-devkit/build-angular): ensure generator polyfills are present for ES5
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/es5-polyfills.js
  yarn.lock
Labels: PR target: master & patch, cla: yes

#15473 refactor(@angular-devkit/build-angular): add debug no mangle environment variable
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/utils/mangle-options.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR target: master & patch, cla: yes

#15479 fix(@angular-devkit/build-angular): remove deprecation of `baseUrl` i…
  packages/angular_devkit/build_angular/src/protractor/schema.json
Labels: PR target: master & patch, cla: yes

#15480 test: add `selected_spec_large` to flake jail
  .circleci/config.yml
  scripts/test.ts
Labels: PR target: master-only, cla: yes

#15485 ci: change resource_class for flake jail to medium
  .circleci/config.yml
Labels: PR target: master-only, cla: yes
