Repository angular/angular-cli, pull requests merged in 2019-05, with the labels that each got.

#14182 fix(@angular-devkit/architect): architect should use provided registry
  etc/api/angular_devkit/architect/src/index.d.ts
  packages/angular_devkit/architect/src/architect.ts
Labels: PR target: master-only, cla: yes

#14165 fix(@angular-devkit/build-angular): e2e does not respect dev-server `…
  packages/angular_devkit/build_angular/src/protractor/index.ts
  packages/angular_devkit/build_angular/src/protractor/schema.json
  tests/legacy-cli/e2e/tests/misc/e2e-host.ts
Labels: PR target: master & patch, cla: yes

#14285 feat(@angular/cli): implement --registry for ng add
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/commands/add.json
Labels: PR target: master-only, cla: yes

#14303 remove unused ascii-progress library, resolve toplevel browserslist to 4.5.5
  packages/angular_devkit/architect_cli/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#14306 docs(@angular/cli): fix typo with service schema
  packages/schematics/angular/service/schema.json
Labels: PR target: master & patch, cla: yes

#14313 refactor(@angular-devkit/schematics): minor rule cleanup
  packages/angular_devkit/schematics/src/rules/base.ts
  packages/angular_devkit/schematics/src/rules/call.ts
Labels: PR target: master-only, cla: yes

#14315 fix(@angular-devkit/architect): error run on input schema error
  packages/angular_devkit/architect/src/architect.ts
  packages/angular_devkit/architect/src/index_spec.ts
Labels: PR target: master & patch, cla: yes

#14320 fix(@ngtools/webpack): log ngcc info messages
  packages/ngtools/webpack/src/ngcc_processor.ts
Labels: PR target: master & patch, cla: yes

#14324 fix(@schematics/angular): reduce package installs for 8.0 migrations
  packages/schematics/angular/migrations/update-8/codelyzer-5.ts
  packages/schematics/angular/migrations/update-8/index.ts
  packages/schematics/angular/migrations/update-8/remove-angular-http.ts
  packages/schematics/angular/migrations/update-8/update-builders.ts
Labels: PR target: master & patch, cla: yes

#14358 fix(@angular-devkit/build-angular): update node-sass to 4.12.0
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: LTS-only, cla: yes

#14359 ci: test on node 12
  .circleci/config.yml
Labels: PR target: LTS-only, cla: yes

#14323 fix(@schematics/angular): avoid tslint overhead for lazy module migration
  packages/schematics/angular/migrations/update-8/rules/noLazyModulePathsRule.ts
  packages/schematics/angular/migrations/update-8/update-lazy-module-paths.ts
  packages/schematics/angular/migrations/update-8/update-lazy-module-paths_spec.ts
Labels: PR target: master & patch, cla: yes

#14325 fix(@ngtools/webpack): fixes ngcc error when project name is the same…
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/ngtools/webpack/src/ngcc_processor.ts
Labels: PR target: master & patch, cla: yes

#14327 fix(@angular-devkit/build-angular): used named chunks for dynamic imp…
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/named-chunks-plugin.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/webpack.ts
  packages/angular_devkit/build_angular/test/browser/lazy-module_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/output-hashing_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
  packages/angular_devkit/build_angular/test/utils.ts
Labels: PR target: master & patch, cla: yes

#14328 fix(@schematics/angular): older projects are not migrated to support …
  packages/schematics/angular/migrations/update-8/differential-loading.ts
  packages/schematics/angular/migrations/update-8/differential-loading_spec.ts
Labels: PR target: master & patch, cla: yes

#14330 fix(@schematics/angular): project name option in the library schematic index
  packages/schematics/angular/library/index.ts
Labels: PR target: master & patch, cla: yes

#14331 fix(@angular-devkit/build-angular): relax typescript peerDep
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/utils.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/tslint/index.ts
  packages/angular_devkit/build_angular/src/utils/differential-loading.ts
  tests/legacy-cli/e2e/tests/basic/update-7.0.ts
Labels: PR target: master & patch, cla: yes

#14352 docs: edit reference doc for update command
  packages/angular/cli/commands/update-long.md
  packages/schematics/update/update/schema.json
Labels: PR target: master & patch, cla: yes, effort1: easy (hours), type: docs

#14314 refactor(@angular-devkit/architect): support stable workspaces API
  packages/angular_devkit/architect/node/node-modules-architect-host.ts
Labels: PR target: master-only, cla: yes

#14363 docs: fixes the changelog commits format
  scripts/templates/changelog-feat.ejs
  scripts/templates/changelog-fix.ejs
Labels: PR target: master-only, cla: yes

#14349 ci: test on node 12
  .circleci/config.yml
Labels: PR target: master & patch, cla: yes

#14365 fix(@angular/cli): honor builder schema additional properties option
  packages/angular/cli/models/architect-command.ts
  tests/legacy-cli/e2e/tests/commands/additional-properties.ts
Labels: PR target: master & patch, cla: yes

#14370 fix(@schematics/angular): remove old GoogleBot browserslist setting
  packages/schematics/angular/application/files/browserslist.template
  packages/schematics/angular/migrations/update-8/differential-loading.ts
  packages/schematics/angular/migrations/update-8/differential-loading_spec.ts
Labels: PR target: master & patch, cla: yes

#14372 fix(@schematics/angular): tsconfig with comments breaks universal sch…
  packages/schematics/angular/universal/index.ts
  packages/schematics/angular/universal/index_spec.ts
Labels: PR target: master & patch, cla: yes

#14374 fix(@angular-devkit/core): NodeJSAsyncHost.isFile should check for a file
  packages/angular_devkit/core/node/host.ts
Labels: PR target: master & patch, cla: yes

#14377 fix(@angular-devkit/build-angular): stop dev server fallback outside of serve path
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/test/dev-server/serve-path_spec_large.ts
Labels: PR target: master & patch, cla: yes

#14381 refactor(@angular-devkit/schematics): update rxjs usage in rules
  etc/api/angular_devkit/schematics/src/_golden-api.d.ts
  packages/angular_devkit/schematics/src/rules/base.ts
  packages/angular_devkit/schematics/src/rules/call.ts
Labels: PR target: master-only, cla: yes

#14385 fix(@angular-devkit/build-angular): propagate protractor errors during execution
  packages/angular_devkit/build_angular/src/protractor/index.ts
Labels: PR target: master & patch, cla: yes

#14388 fix(@angular/cli): print full error when package is not found
  packages/angular/cli/tasks/npm-install.ts
Labels: PR target: master & patch, cla: yes

#14391 build: fix external block in BUILD files
  packages/angular_devkit/core/BUILD
  packages/angular_devkit/schematics/BUILD
Labels: PR target: master-only, cla: yes

#14312 refactor(@angular/cli): avoid aggressive eager command loading
  packages/angular/cli/commands/help-impl.ts
  packages/angular/cli/models/command-runner.ts
  packages/angular/cli/models/command.ts
Labels: PR target: master-only, cla: yes

#14375 fix(@angular-devkit/core): handle async host exceptions for workspace isDirectory/isFile
  packages/angular_devkit/core/src/workspace/host.ts
Labels: PR target: master & patch, cla: yes

#14380 docs: describe prod flag more explicitly
  packages/angular/cli/commands/definitions.json
Labels: PR target: master & patch, cla: yes

#14382 fix(@angular-devkit/build-ng-packagr): propogate errors during execution
  packages/angular_devkit/build_ng_packagr/src/build/index.ts
Labels: PR target: master & patch, cla: yes

#14383 fix(@angular-devkit/build-angular): extract i18n should only show warnings/errors
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
  packages/angular_devkit/build_angular/test/extract-i18n/works_spec_large.ts
Labels: PR target: master & patch, cla: yes

#14395 fix(@angular/cli): enable analytics for safe builders
  packages/angular/cli/models/architect-command.ts
Labels: PR target: master & patch, cla: yes

#14406 fix(@angular-devkit/build-optimizer): remove deprecated test functions from public API
  etc/api/angular_devkit/build_optimizer/src/_golden-api.d.ts
  packages/angular_devkit/build_optimizer/src/index.ts
Labels: PR target: master & patch, cla: yes

#14407 refactor(@angular-devkit/build-angular): remove unused utility functions
  packages/angular_devkit/build_angular/src/utils/index.ts
  packages/angular_devkit/build_angular/src/utils/normalize-karma-schema.ts
  packages/angular_devkit/build_angular/src/utils/normalize-webpack-server-schema.ts
  packages/angular_devkit/build_angular/src/utils/webpack-file-system-host-adapter.ts
Labels: PR target: master & patch, cla: yes

#14408 fix(@angular-devkit/core): remove unimplemented prompt priority
  etc/api/angular_devkit/core/src/_golden-api.d.ts
  packages/angular_devkit/core/src/json/schema/interface.ts
  packages/angular_devkit/core/src/json/schema/registry.ts
Labels: PR target: master & patch, cla: yes

#14411 fix(@schematics/angular): differential loading migration should run o…
  packages/schematics/angular/migrations/update-8/differential-loading.ts
  packages/schematics/angular/migrations/update-8/differential-loading_spec.ts
Labels: PR target: master & patch, cla: yes

#14415 fix(@schematics/angular): update zone.js to 0.9.1
  packages/angular_devkit/build_angular/package.json
  packages/schematics/angular/utility/latest-versions.ts
  yarn.lock
Labels: PR target: master & patch, cla: yes

#14419 feat(@angular-devkit/build-angular): add a post transformation hook to index generation
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/index-html-webpack-plugin.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/augment-index-html.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/augment-index-html_spec.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/write-index-html.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/server/index.ts
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
  packages/angular_devkit/build_angular/test/browser/index_spec_large.ts
Labels: PR target: master-only, cla: yes

#14412 fix(@angular-devkit/schematics): deprecate synchronous testing methods
  packages/angular_devkit/schematics/testing/schematic-test-runner.ts
Labels: PR target: master & patch, cla: yes

#14417 fix(@angular/cli): prevent nested schematic execution from generating analytics
  packages/angular/cli/models/schematic-command.ts
Labels: PR target: master & patch, cla: yes

#14422 refactor(@angular-devkit/build-angular): simplify webpack stats output
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#14423 refactor(@angular-devkit/build-angular): use standard node resolution methods where possible
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/read-tsconfig.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/require-project-module.ts
  packages/angular_devkit/build_angular/src/app-shell/index.ts
Labels: PR target: master-only, cla: yes

#14435 fix(@angular-devkit/build-angular): show error for missing modules
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/test/browser/errors_spec_large.ts
Labels: PR target: master & patch, cla: yes

#14426 fix(@angular/cli): @bazel/* are not shown in `ng version`
  packages/angular/cli/commands/version-impl.ts
Labels: PR target: master & patch, cla: yes

#14437 test: update update-7.0 E2E to reflect 8.0-rc.4 changes
  tests/legacy-cli/e2e/tests/basic/update-7.0.ts
Labels: PR target: master & patch, cla: yes

#14452 refactor(@schematics/angular): optimize insertAfterLastOccurrence AST util
  packages/schematics/angular/utility/ast-utils.ts
Labels: PR target: master-only, cla: yes

#14448 fix(@schematics/angular): polyfills migration leaving broken code in …
  packages/schematics/angular/migrations/update-8/drop-es6-polyfills.ts
Labels: PR target: master & patch, cla: yes

#14441 fix(@schematics/angular): update or add module and target to non extend…
  packages/schematics/angular/migrations/update-8/differential-loading.ts
  packages/schematics/angular/migrations/update-8/differential-loading_spec.ts
Labels: PR target: master & patch, cla: yes

#14466 fix for #14457 - fix(@angular-devkit/build-angular): normalize sourceMap options in ka…
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma.ts
  tests/legacy-cli/e2e/tests/test/test-sourcemap.ts
Labels: PR target: master & patch, cla: yes

#14468 fix for #14467 - fix(@schematics/angular): webworker snippet should not generate to module
  packages/schematics/angular/web-worker/index.ts
  packages/schematics/angular/web-worker/index_spec.ts
Labels: PR target: master & patch, cla: yes

#14475 ci: trim the appveyor tests
  appveyor-e2e.bat
Labels: PR target: master & patch, cla: yes

#14478 fix(@angular-devkit/build-angular): absolute outputPath outputs index…
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/test/browser/output-path_spec_large.ts
Labels: PR target: master & patch, cla: yes

#14479 fix(docs): don't reference next.angular.io
  docs/documentation/stories/multiple-projects.md
  docs/documentation/stories/third-party-lib.md
  packages/angular/cli/commands/analytics.json
  packages/ngtools/webpack/src/transformers/import_factory.ts
Labels: PR target: master & patch, cla: yes

#14480 refactor(@angular/pwa): remove unneeded rxjs dependency
  packages/angular/pwa/package.json
  packages/angular/pwa/pwa/index.ts
Labels: PR target: master-only, cla: yes

#14482 docs: update project description to full application instead of app
  packages/angular/cli/commands/definitions.json
Labels: PR target: master & patch, cla: yes

#14481 fix(@angular/cli): show error when using x18n command on Node.js 12.0
  packages/angular/cli/commands/xi18n-impl.ts
Labels: PR target: master & patch, cla: yes

#14492 fix(@angular/cli): ensure git repository is clean before updates
  packages/angular/cli/commands/update-impl.ts
  tests/legacy-cli/e2e/tests/misc/update-git-clean.ts
Labels: PR target: master & patch, cla: yes

#14493 fix(@angular/core): properly replace an added value in workspace API
  packages/angular_devkit/core/src/workspace/json/metadata.ts
  packages/angular_devkit/core/src/workspace/json/reader_spec.ts
Labels: PR target: master & patch, cla: yes

#14496 fix(@schematics/angular): handle newline after `@` of a decorator
  packages/schematics/angular/utility/ast-utils.ts
  packages/schematics/angular/utility/ast-utils_spec.ts
Labels: PR target: master & patch, cla: yes

#14500 fix(@angular-devkit/build-angular): dev-server port number mismatches…
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/test/dev-server/works_spec_large.ts
Labels: PR target: master & patch, cla: yes

#14524 ci: add bazel workspace file to renovate `packageFiles`
  renovate.json
Labels: PR target: master-only, cla: yes

#14526 fix(@schematics/angular): drop the worker alias
  packages/schematics/angular/collection.json
Labels: PR target: master & patch, cla: yes

#14530 fix(@angular/cli): ng generate --help shows the wrong collection
  packages/angular/cli/commands/generate-impl.ts
  packages/angular/cli/commands/new-impl.ts
  packages/angular/cli/models/schematic-command.ts
  tests/legacy-cli/e2e/tests/generate/help-output.ts
Labels: PR target: master & patch, cla: yes

#14533 refactor(@angular-devkit/architect): remove index2 from testing folder
  packages/angular_devkit/architect/testing/index2.ts
Labels: PR target: master & patch, cla: yes

#14535 fix(@angular/cli): ng config doesn't parse positional array
  packages/angular/cli/commands/config-impl.ts
  tests/legacy-cli/e2e/tests/commands/config/config-get.ts
Labels: PR target: master & patch, cla: yes

#14539 fix(@schematics/angular): add migration to update `web-animations-js`…
  packages/schematics/angular/migrations/update-8/index.ts
  packages/schematics/angular/migrations/update-8/update-dependencies.ts
Labels: PR target: master & patch, cla: yes, hotlist: release-blocker

#14571 ci: remove duplicate anchor keys in circleci cfg
  .circleci/config.yml
Labels: PR target: master & patch, cla: yes

#14572 fix(@angular/cli): check for CI environment variable in tty helper
  packages/angular/cli/utilities/tty.ts
Labels: PR target: master & patch, cla: yes

#14567 fix(@angular/cli): ng-update migrations not running with --migrate-only
  packages/angular_devkit/schematics/tools/node-module-engine-host.ts
  packages/angular_devkit/schematics/tools/node-module-engine-host_spec.ts
Labels: PR target: master & patch, cla: yes, comp: devkit/schematics, priority: 1 (urgent)

#14569 fix(@schematics/update): respect semver rules for migration from & to
  packages/schematics/update/migrate/index.ts
  packages/schematics/update/migrate/index_spec.ts
Labels: PR target: master & patch, cla: yes

#14556 fix(@schematics/angular): TypeScript related migrations should cater …
  packages/schematics/angular/migrations/update-8/drop-es6-polyfills.ts
  packages/schematics/angular/migrations/update-8/update-lazy-module-paths.ts
  packages/schematics/angular/migrations/update-8/update-lazy-module-paths_spec.ts
Labels: PR target: master & patch, cla: yes

#14550 ci: add `build_bazel` packages in `bazel` package group
  renovate.json
Labels: PR target: master-only, cla: yes

#14578 fix(@schematics/update): improve error message when finding incompati…
  packages/schematics/update/update/index.ts
Labels: PR target: master & patch, cla: yes, need: further discussion

#14586 fix(@angular-devkit/architect): support all observable types as build results
  etc/api/angular_devkit/architect/src/index.d.ts
  packages/angular_devkit/architect/src/api.ts
  packages/angular_devkit/architect/src/create-builder.ts
Labels: PR target: master & patch, cla: yes

#14017 fix(@angular-devkit/build-angular): exclude map files from 'bundle' budgets
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/bundle-calculator.ts
  packages/angular_devkit/build_angular/test/browser/bundle-budgets_spec_large.ts
Labels: PR target: master & patch, cla: yes

#14601 test: fix prelease CLI E2E check
  tests/legacy-cli/e2e/utils/project.ts
Labels: PR target: master & patch, cla: yes
