Repository angular/angular-cli, pull requests merged in 2019-10, with the labels that each got.

#15705 fix(@angular-devkit/build-optimizer): fix error when `__decorate` has…
  packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts
  packages/angular_devkit/build_optimizer/src/transforms/scrub-file_spec.ts
Labels: PR target: master & patch, cla: yes

#15721 build: g3 sync for angular_devkit
  BUILD
  packages/angular_devkit/core/BUILD
  packages/angular_devkit/core/node/host.ts
  packages/angular_devkit/core/src/json/schema/visitor.ts
  packages/angular_devkit/schematics/BUILD
  packages/angular_devkit/schematics_cli/BUILD
Labels: PR target: master-only, cla: yes

#15737 fix(@angular-devkit/build-optimizer): fix error when `__decorate` has…
  packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts
  packages/angular_devkit/build_optimizer/src/transforms/scrub-file_spec.ts
Labels: PR target: patch-only, cla: yes

#15718 feat(@angular-devkit/build-angular): set document locale with i18n
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/index-html-webpack-plugin.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/augment-index-html.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/augment-index-html_spec.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/write-index-html.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  tests/legacy-cli/e2e/tests/i18n/build-locale.ts
Labels: PR target: master-only, cla: yes

#15732 build: use import instead of require for fast-json-stable-stringify
  package.json
  packages/angular_devkit/core/BUILD
  packages/angular_devkit/core/src/experimental/jobs/strategy.ts
  packages/angular_devkit/core/src/workspace/json/utilities.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#15720 feat(@angular-devkit/build-angular): add analytics for ivy/non-ivy builds
  docs/design/analytics.md
  etc/api/angular_devkit/core/src/_golden-api.d.ts
  packages/angular_devkit/build_angular/plugins/webpack/analytics.ts
  packages/angular_devkit/core/src/analytics/index.ts
Labels: PR target: master-only, cla: yes

#15731 build: g3 sync for packages/schematics and packages/angular
  packages/angular/cli/BUILD
  packages/angular/cli/commands/add-impl.ts
  packages/angular_devkit/core/BUILD
  packages/schematics/angular/service-worker/index.ts
  packages/schematics/angular/web-worker/index.ts
Labels: PR target: master-only, cla: yes

#15751 fix(@angular-devkit/build-angular): re-introduce pure_getters
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Labels: PR target: master-only, cla: yes

#15738 fix(@angular/cli): initialize baseUrl variable
  packages/angular_devkit/build_angular/src/protractor/index.ts
Labels: PR target: master & patch, cla: yes

#15752 feat(@angular/cli): allow subclass to override default collection name
  packages/angular/cli/models/schematic-command.ts
Labels: PR target: master-only, cla: yes

#15753 refactor(@angular/cli): Simplify retrieval of collection name
  packages/angular/cli/commands/new-impl.ts
Labels: PR target: master-only, cla: yes

#15714 fix(@schematics/angular): scroll issue on new app
  packages/schematics/angular/application/other-files/app.component.html.template
Labels: PR action: cleanup, PR target: master & patch, cla: yes

#15755 build: update BUILD files for g3 sync
  packages/angular/cli/BUILD
  packages/angular_devkit/core/BUILD
Labels: PR target: master-only, cla: yes

#15777 Backport additional differential loading improvements
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/browser/action-cache.ts
  packages/angular_devkit/build_angular/src/browser/action-executor.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
  yarn.lock
Labels: PR target: patch-only, cla: yes

#15800 feat(@schematics/angular): add migration ensure that `tslib` is insta…
  packages/schematics/angular/migrations/update-9/add-tslib.ts
  packages/schematics/angular/migrations/update-9/index.ts
  packages/schematics/angular/migrations/update-9/update-dependencies.ts
Labels: PR target: master-only, cla: yes

#15798 test: add second language to aot-i18n e2e
  tests/legacy-cli/e2e/tests/build/aot/aot-i18n.ts
Labels: PR target: master-only, cla: yes

#15797 Update several dependencies
  packages/schematics/angular/workspace/files/package.json.template
  packages/schematics/schematics/blank/project-files/package.json.template
  packages/schematics/schematics/schematic/files/package.json
Labels: PR target: master-only, cla: yes

#15796 feat(@angular-devkit/build-angular): add support for i18n extraction …
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
  packages/angular_devkit/build_angular/test/extract-i18n/works_spec_large.ts
  tests/legacy-cli/e2e_runner.ts
Labels: PR target: master-only, cla: yes

#15788 refactor(@angular-devkit/build-angular): initial copy-on-write asset processing support
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/copy-assets.ts
  packages/angular_devkit/build_angular/src/utils/copy-file.ts
Labels: PR target: master-only, cla: yes

#15786 refactor(@schematics/update): missing space in usageMessage output
  packages/schematics/update/update/index.ts
Labels: PR target: master-only, cla: yes

#15776 refactor(@angular-devkit/build-angular): reorganize bundle processing for browser builder
  packages/angular_devkit/build_angular/src/browser/action-cache.ts
  packages/angular_devkit/build_angular/src/browser/action-executor.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
Labels: PR target: master-only, cla: yes

#15760 New i18n schema
  etc/api/angular_devkit/core/src/_golden-api.d.ts
  packages/angular/cli/commands/xi18n.json
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/extract-i18n/schema.json
  packages/angular_devkit/build_angular/src/server/schema.json
  packages/angular_devkit/build_angular/test/extract-i18n/works_spec_large.ts
  packages/angular_devkit/core/src/experimental/workspace/workspace-schema.json
  packages/angular_devkit/core/src/experimental/workspace/workspace-schema.ts
  packages/angular_devkit/core/src/experimental/workspace/workspace_spec.ts
  tests/legacy-cli/e2e/tests/i18n/extract-xmb.ts
Labels: PR target: master-only, cla: yes

#15801 feat(@schematics/angular): use ngcc on postinstall
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_ng_packagr/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/angular/workspace/files/package.json.template
  yarn.lock
Labels: PR target: master-only, cla: yes

#15756 build: set minimum Node.js version to 10.13
  lib/packages.ts
  package.json
  packages/angular/cli/bin/ng
  packages/angular_devkit/benchmark/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#15690 feat(@angular-devkit/build-angular): add experimentalRollupPass
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/webpack-rollup-loader.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/webpack.ts
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
  packages/angular_devkit/build_angular/test/browser/rollup_spec_large.ts
  packages/angular_devkit/build_angular/test/utils.ts
  tests/legacy-cli/e2e/tests/build/rollup.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#15780 fix(@angular-devkit/build-angular): remove prerelease @angular/compiler-cli peer dependency
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
Labels: PR target: patch-only, cla: yes

#15805 test: additional i18n e2e tests
  tests/legacy-cli/e2e/tests/build/aot/aot-i18n.ts
Labels: PR target: master-only, cla: yes

#15818 fix(@angular-devkit/build-angular): avoid attempting to copy directories
  packages/angular_devkit/build_angular/src/utils/copy-assets.ts
  packages/angular_devkit/build_angular/test/browser/assets_spec_large.ts
Labels: PR target: master-only, cla: yes

#15826 test: fix i18n extraction e2e test (Make master green)
  tests/legacy-cli/e2e/tests/build/aot/aot-i18n.ts
Labels: PR target: master-only, cla: yes

#15795 feat(@schematics/angular): add migration to add new i18n options for Ivy
  packages/schematics/angular/migrations/update-9/update-workspace-config.ts
  packages/schematics/angular/migrations/update-9/update-workspace-config_spec.ts
  packages/schematics/angular/migrations/update-9/utils.ts
Labels: PR target: master-only, cla: yes

#15827 fix(@angular-devkit/build-webpack): proxy config with windows authent…
  packages/angular_devkit/build_webpack/package.json
  packages/angular_devkit/build_webpack/src/webpack-dev-server/index.ts
  packages/angular_devkit/build_webpack/src/webpack/index.ts
Labels: PR target: master & patch, cla: yes

#15828 refactor(@schematics/angular): remove redundant quotes from protracto…
  packages/schematics/angular/e2e/files/protractor.conf.js.template
  tests/angular_devkit/build_angular/hello-world-app-ve/protractor.conf.js
  tests/legacy-cli/e2e/assets/1.0-project/protractor.conf.js
  tests/legacy-cli/e2e/assets/1.7-project/protractor.conf.js
  tests/legacy-cli/e2e/assets/7.0-project/e2e/protractor.conf.js
  tests/legacy-cli/e2e/utils/project.ts
Labels: PR target: master & patch, cla: yes

#15830 fix(@angular-devkit/build-angular): only copy assets outside of webpa…
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
Labels: PR target: master-only, cla: yes

#15838 refactor(@angular-devkit/build-angular): remove differential loading version 1.0
  packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/karma/index.ts
  packages/angular_devkit/build_angular/src/server/index.ts
  packages/angular_devkit/build_angular/src/utils/build-browser-features.ts
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
Labels: PR target: master-only, cla: yes

#15842 fix(@angular/cli): ng update log messages printed twice
  packages/angular/cli/commands/update-impl.ts
Labels: PR target: master & patch, cla: yes

#15837 fix(@schematics/angular): update ngcc postinstall command
  packages/schematics/angular/workspace/files/package.json.template
Labels: PR target: master-only, cla: yes

#15864 test: add jit-prod e2e
  tests/legacy-cli/e2e/tests/build/jit-prod.ts
Labels: PR target: master-only, cla: yes

#15866 fix(@ngtools/webpack): don't set ngprogram to null
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  tests/angular_devkit/build_webpack/angular-app/tsconfig.json
Labels: PR target: master-only, cla: yes

#15833 Determine relative paths correctly
  packages/angular/cli/commands/update-impl.ts
  tests/legacy-cli/e2e/tests/misc/update-git-clean-subdirectory.ts
Labels: PR target: master & patch, cla: yes

#15895 fix(@angular/cli): logic to determine if the installed CLI is out of …
  etc/api/angular_devkit/core/node/_golden-api.d.ts
  package.json
  packages/angular/cli/BUILD
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/lib/cli/index.ts
  packages/angular/cli/lib/init.ts
  packages/angular/cli/package.json
  packages/angular/cli/tasks/install-package.ts
  packages/angular/cli/tasks/npm-install.ts
  packages/angular/cli/utilities/package-manager.ts
  packages/angular_devkit/core/node/resolve.ts
  yarn.lock
Labels: PR target: patch-only, cla: yes

#15894 refactor(@ngtools/webpack): remove unneeded tree-kill dependency
  packages/ngtools/webpack/package.json
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master-only, cla: yes

#15897 docs: include major-verson update advice
  packages/angular/cli/commands/update-long.md
Labels: PR target: master & patch, cla: yes, comp: angular/cli, effort1: easy (hours), freq1: low, priority: 3 (nice to have), severity1: confusing, type: docs

#15912 refactor(@angular-devkit/core): deprecate old terminal and resolve APIs
  packages/angular_devkit/core/node/resolve.ts
  packages/angular_devkit/core/src/index.ts
Labels: PR target: master & patch, cla: yes

#15914 refactor(@schematics/angular): remove deprecated `spec` and `styleext` options
  packages/angular/cli/lib/config/schema.json
  packages/schematics/angular/class/index.ts
  packages/schematics/angular/class/index_spec.ts
  packages/schematics/angular/class/schema.json
  packages/schematics/angular/component/index.ts
  packages/schematics/angular/component/index_spec.ts
  packages/schematics/angular/component/schema.json
  packages/schematics/angular/directive/index.ts
  packages/schematics/angular/directive/schema.json
  packages/schematics/angular/pipe/index.ts
  packages/schematics/angular/pipe/index_spec.ts
  packages/schematics/angular/pipe/schema.json
  packages/schematics/angular/service/index.ts
  packages/schematics/angular/service/schema.json
  tests/legacy-cli/e2e/tests/commands/new/new-style.ts
Labels: PR target: master-only, cla: yes

#15883 fix(@angular-devkit/build-angular): sockPath for custom path
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: PR target: master & patch, cla: yes

#15900 refactor(@angular-devkit/build-angular): allow control of cache location
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/browser/action-cache.ts
  packages/angular_devkit/build_angular/src/browser/action-executor.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/cache-path.ts
  packages/angular_devkit/build_angular/src/utils/environment-options.ts
  packages/angular_devkit/build_angular/src/utils/mangle-options.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR target: master-only, cla: yes

#15905 docs: corrected spelling of Globally under Installation section
  packages/angular/cli/README.md
Labels: PR target: master & patch, cla: yes

#15906 refactor: use require.resolve instead of custom `resolve`
  etc/api/angular_devkit/schematics/tools/index.d.ts
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/tasks/install-package.ts
  packages/angular_devkit/schematics/tools/node-module-engine-host.ts
  packages/angular_devkit/schematics/tools/node-module-engine-host_spec.ts
Labels: PR target: master-only, cla: yes

#15925 refactor(@schematics/angular): remove hardcoded value of `newProjectR…
  packages/schematics/angular/ng-new/index.ts
Labels: PR target: master-only, cla: yes

#15918 fix(@angular-devkit/build-angular): set locale identifier when localizing
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/i18n-inlining.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-es2015.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-es5.ts
Labels: PR target: master-only, cla: yes

#15927 docs: state in the README that minimum Node.js version is 10.13
  README.md
  scripts/templates/readme.ejs
Labels: PR target: master-only, cla: yes

#15924 refactor(@angular-devkit/schematics): remove several deprecated APIs
  etc/api/angular_devkit/schematics/src/_golden-api.d.ts
  etc/api/angular_devkit/schematics/tools/index.d.ts
  packages/angular_devkit/schematics/src/engine/interface.ts
  packages/angular_devkit/schematics/src/index.ts
  packages/angular_devkit/schematics/src/sink/dryrun.ts
  packages/angular_devkit/schematics/src/sink/dryrun_spec.ts
  packages/angular_devkit/schematics/src/sink/filesystem.ts
  packages/angular_devkit/schematics/src/sink/host_spec.ts
  packages/angular_devkit/schematics/src/tree/static.ts
  packages/angular_devkit/schematics/src/workflow/base.ts
  packages/angular_devkit/schematics/tools/fallback-engine-host.ts
  packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts
Labels: PR target: master-only, cla: yes

#15934 test: fix webdriver errors
  tests/legacy-cli/e2e/tests/commands/add/add-pwa-yarn.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl.ts
Labels: PR target: master-only, cla: yes

#15876 Add package manager option to the CLI
  packages/schematics/angular/ng-new/index.ts
  packages/schematics/angular/ng-new/index_spec.ts
  packages/schematics/angular/ng-new/schema.json
  packages/schematics/angular/workspace/files/angular.json.template
  packages/schematics/angular/workspace/schema.json
Labels: PR target: master-only, cla: yes

#15885 Cleanup architect node host
  packages/angular_devkit/architect/node/node-modules-architect-host.ts
Labels: PR target: master-only, cla: yes

#15938 Test platform server tests - snapshots
  tests/legacy-cli/e2e/ng-snapshot/package.json
  tests/legacy-cli/e2e/tests/build/build-app-shell-with-schematic.ts
  tests/legacy-cli/e2e/tests/build/build-app-shell.ts
  tests/legacy-cli/e2e/tests/build/platform-server.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-server.ts
Labels: PR target: master-only, cla: yes

#15937 fix(@angular-devkit/build-angular): keep licenses if extraction is disabled
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/test/browser/bundle-budgets_spec_large.ts
  tests/legacy-cli/e2e/tests/build/extract-licenses.ts
Labels: PR target: master & patch, cla: yes

#15581 fix(@angular/cli): support the sublevel names of projects
  packages/angular/cli/lib/config/schema.json
Labels: PR target: master & patch, cla: yes

#15956 fix(@schematics/update): handle peerDependenciesMeta
  packages/schematics/update/update/index.ts
  packages/schematics/update/update/index_spec.ts
Labels: PR target: master-only, cla: yes

#15960 fix(@angular-devkit/schematics): use NodeWorkflow root to resolve collections
  etc/api/angular_devkit/schematics/tools/index.d.ts
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/models/schematic-command.ts
  packages/angular_devkit/schematics/tools/node-module-engine-host.ts
  packages/angular_devkit/schematics/tools/workflow/node-workflow.ts
Labels: PR target: master-only, cla: yes

#15973 fix(@angular/cli): updated CLI should not have analytics enabled
  packages/angular/cli/tasks/install-package.ts
Labels: PR target: master & patch, cla: yes

#15980 fix(@angular-devkit/build-angular): enable locale data transform for single localization
  packages/angular_devkit/build_angular/src/utils/i18n-options.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl.ts
Labels: PR target: master-only, cla: yes

#15971 fix(@angular-devkit/build-angular): augment with service worker during localization
  packages/angular_devkit/build_angular/src/browser/index.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-serviceworker.ts
Labels: PR target: master-only, cla: yes

#15988 fix(@schematics/angular): disable i18n migrations
  packages/schematics/angular/migrations/update-9/update-workspace-config.ts
  packages/schematics/angular/migrations/update-9/update-workspace-config_spec.ts
Labels: PR target: master-only, cla: yes

#15983 fix(@angular-devkit/build-angular): temporarily disable localize for multiple locales
  packages/angular_devkit/build_angular/src/utils/i18n-options.ts
  tests/legacy-cli/e2e/tests/build/aot/aot-i18n.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-app-shell.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-es2015.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-es5.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-server.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-serviceworker.ts
Labels: PR target: master-only, cla: yes

#15997 fix(@angular-devkit/build-angular): update terser to 4.3.9 to address…
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: patch-only, cla: yes
