Repository angular/angular-cli, pull requests merged in 2019-12, with the labels that each got.

#16334 refactor: strip leading slash to prevent confusion
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/models/schematic-command.ts
  packages/angular_devkit/schematics_cli/bin/schematics.ts
  packages/angular_devkit/schematics_cli/bin/schematics_spec.ts
Labels: PR target: master & patch, cla: yes

#16186 feat(@angular/pwa): support for maskable icons
  packages/angular/pwa/pwa/files/root/manifest.webmanifest
Labels: PR target: master-only, cla: yes

#16317 fix(@angular-devkit/build-angular): pass webpack factor to runWebpack…
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_webpack/src/webpack-dev-server/index.ts
Labels: PR target: master & patch, cla: yes

#16306 fix(@schematics/angular): update @types/jasmine to 3.5 to match versi…
  packages/schematics/angular/workspace/files/package.json.template
  packages/schematics/schematics/blank/project-files/package.json.template
Labels: PR target: master & patch, cla: yes

#16302 fix(@angular-devkit/build-angular): ensure HTML lang attribute is set when localizing
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/server/index.ts
  packages/angular_devkit/build_angular/src/utils/output-paths.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl-xliff2.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-es2015.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-es5.ts
  tests/legacy-cli/e2e/tests/i18n/legacy.ts
  tests/legacy-cli/e2e/tests/i18n/ve-localize-es2015.ts
Labels: PR target: master & patch, cla: yes

#16290 fix(@angular-devkit/build-angular): support differential loading for web workers
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
  tests/legacy-cli/e2e/tests/build/worker.ts
Labels: PR target: master & patch, cla: yes

#16337 fix(@angular-devkit/build-angular): pass webpack factor to runWebpack
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_webpack/src/webpack-dev-server/index.ts
Labels: PR target: patch-only, cla: yes

#16310 refactor(@schematics/angular): clean up module schematic template
  packages/schematics/angular/module/files/__name@dasherize@if-flat__/__name@dasherize__.module.ts.template
  packages/schematics/angular/module/index.ts
Labels: PR target: master-only, cla: yes

#16343 Library imports patch
  packages/schematics/angular/library/index.ts
  packages/schematics/angular/library/index_spec.ts
  packages/schematics/angular/workspace/files/tsconfig.json.template
Labels: PR target: patch-only, cla: yes

#16350 ci: update saucelabs to use angular-tooling account
  .circleci/env.sh
Labels: PR target: master & patch, cla: yes, comp: etc/misc

#16358 refactor: deprecated unused server builder options
  packages/angular_devkit/build_angular/src/server/schema.json
Labels: PR target: master & patch, cla: yes

#16349 fix(@angular-devkit/build-angular): suppress duplicate 3rdpartylicenses.txt warning
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
Labels: PR target: master & patch, cla: yes

#16368 fix(@angular/cli): remove alias for deploy command
  packages/angular/cli/commands/deploy.json
Labels: PR target: master & patch, cla: yes

#16344 fix(@angular-devkit/build-angular): add notice when using bundleDepen…
  packages/angular_devkit/build_angular/src/server/index.ts
Labels: PR target: master & patch, cla: yes

#16351 fix(@angular-devkit/build-angular): localize service worker base href
  packages/angular_devkit/build_angular/src/browser/index.ts
Labels: PR target: master & patch, cla: yes

#16374 ci: update windows image to avoid using choco
  .circleci/config.yml
  .circleci/windows-env.ps1
Labels: PR target: master & patch, cla: yes

#16394 fix(@angular-devkit/build-angular): ensure source locale data is injected when localizing
  packages/angular_devkit/build_angular/src/utils/i18n-options.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-sourcelocale.ts
Labels: PR target: master & patch, cla: yes

#16387 refactor(@angular-devkit/build-angular): export executeExtractI18nBuilder
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/index.ts
Labels: PR target: master & patch, cla: yes

#16409 ci: use windows-server-2019-vs2019:stable
  .circleci/config.yml
  .circleci/windows-env.ps1
Labels: PR target: master & patch, cla: yes

#16412 fix(@schematics/angular): improve i18n output path option migration
  packages/schematics/angular/migrations/update-9/update-workspace-config.ts
  packages/schematics/angular/migrations/update-9/update-workspace-config_spec.ts
Labels: PR target: master & patch, cla: yes

#16416 revert: fix(@angular-devkit/build-angular): sockPath for custom path
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: PR target: master & patch, cla: yes

#16417 Fix audit vulnerability warnings for 8.3.x
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR action: merge, PR target: LTS-only, cla: yes

#16424 fix(@ngtools/webpack): invalidate ngcc processor cache
  packages/ngtools/webpack/src/compiler_host.ts
  packages/ngtools/webpack/src/ngcc_processor.ts
Labels: PR target: master & patch, cla: yes

#16413 doc: adds "PR action: merge" label
  CONTRIBUTING.md
  docs/process/release.md
  scripts/templates/contributing.ejs
Labels: PR target: master-only, cla: yes

#16443 build: update copy-webpack-plugin to version 5.1.1
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: patch-only, cla: yes

#16400 docs: add build system doc
  docs/design/build-system.md
Labels: PR target: master-only, cla: yes

#16415 revert: fix(@angular-devkit/build-angular): sockPath for custom path
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: PR action: merge, PR target: LTS-only, cla: yes

#16442 fix(@angular-devkit/build-angular): optimize web worker differential loading processing
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16446 fix(@schematics/angular): blank root leads to wrong tsconfig.lib.prod…
  packages/schematics/angular/migrations/update-9/ivy-libraries.ts
  packages/schematics/angular/migrations/update-9/ivy-libraries_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16475 Backport terser and babel dependencies to 9.0.x
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: patch-only, cla: yes

#16377 fix(@schematics/angular): handle aliased or existing environment import
  packages/schematics/angular/service-worker/index.ts
  packages/schematics/angular/service-worker/index_spec.ts
  packages/schematics/angular/utility/ast-utils.ts
Labels: PR target: master & patch, cla: yes

#16466 fix(@angular/cli): inform user and error if schematics package is in unreachable location
  packages/angular/cli/commands/update-impl.ts
Labels: PR target: master & patch, cla: yes
