Repository angular/angular-cli, pull requests merged in 2019-07, with the labels that each got.

#14929 fix(@angular-devkit/architect): fix for newest version of rxjs
  packages/angular_devkit/architect/src/architect.ts
Labels: PR target: master-only, cla: yes

#14907 test: add initial ivy large test support
  .circleci/config.yml
  packages/angular_devkit/build_angular/test/browser/aot_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/errors_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/i18n_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/lazy-module_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/no-entry-module_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/svg_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/vendor-source-map_spec_large.ts
  packages/angular_devkit/build_angular/test/utils.ts
  tests/angular_devkit/build_angular/hello-world-app-ivy/.editorconfig
  tests/angular_devkit/build_angular/hello-world-app-ivy/.gitignore
  tests/angular_devkit/build_angular/hello-world-app-ivy/README.md
  tests/angular_devkit/build_angular/hello-world-app-ivy/angular.json
  tests/angular_devkit/build_angular/hello-world-app-ivy/browserslist
  tests/angular_devkit/build_angular/hello-world-app-ivy/e2e/app.e2e-spec.ts
  tests/angular_devkit/build_angular/hello-world-app-ivy/e2e/app.po.ts
  tests/angular_devkit/build_angular/hello-world-app-ivy/e2e/tsconfig.e2e.json
  tests/angular_devkit/build_angular/hello-world-app-ivy/karma.conf.js
  tests/angular_devkit/build_angular/hello-world-app-ivy/package.json
  tests/angular_devkit/build_angular/hello-world-app-ivy/protractor.conf.js
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/app/app.component.css
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/app/app.component.html
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/app/app.component.spec.ts
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/app/app.component.ts
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/app/app.module.ts
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/app/app.server.module.ts
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/assets/.gitkeep
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/environments/environment.prod.ts
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/environments/environment.ts
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/favicon.ico
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/index.html
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/main.server.ts
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/main.ts
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/polyfills.ts
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/spectrum.png
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/src/locale/messages.xlf
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/styles.css
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/test.ts
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/tsconfig.app.json
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/tsconfig.server.json
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/tsconfig.spec.json
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/typings.d.ts
  tests/angular_devkit/build_angular/hello-world-app-ivy/tsconfig.json
  tests/angular_devkit/build_angular/hello-world-app-ivy/tslint.json
Labels: PR target: master-only, cla: yes

#14951 fix(@angular-devkit/build-angular): IE11 errors when using scripts an…
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
Labels: PR target: master & patch, cla: yes

#14958 build: remove serialize script and @ngtool/json-schema deps
  package.json
  scripts/serialize.ts
Labels: PR target: master-only, cla: yes

#14968 refactor(@angular/cli): simplify unhandled exception message
  packages/angular/cli/lib/cli/index.ts
Labels: PR target: master-only, cla: yes

#14969 test: ensure Node.js 10 E2E has latest npm version
  .circleci/config.yml
Labels: PR target: master-only, cla: yes

#14970 fix(@angular-devkit/architect): one more fix for newest version of rxjs
  packages/angular_devkit/core/src/experimental/jobs/simple-scheduler.ts
Labels: PR target: master-only, cla: yes

#14972 build: support publishing on windows
  scripts/publish.ts
Labels: PR target: master-only, cla: yes

#14984 test: update ngtools/webpack size check
  tests/legacy-cli/e2e/tests/packages/webpack/test-app.ts
Labels: PR target: master & patch, cla: yes

#14941 refactor(@angular/cli): use stable workspace API
  packages/angular/cli/models/architect-command.ts
  packages/angular/cli/models/schematic-command.ts
  packages/angular/cli/models/workspace-loader.ts
Labels: PR target: master-only, cla: yes

#14897 ci: setup RBE on CI
  .bazelrc
  .circleci/config.yml
  .circleci/gcp_token
  WORKSPACE
  packages/angular_devkit/core/BUILD
  packages/schematics/update/BUILD
  tools/BUILD
Labels: PR target: master & patch, cla: yes

#14979 fix(@schematics/angular): update sass documentation links
  packages/schematics/angular/ng-new/schema.json
Labels: PR target: master & patch, cla: yes

#14985 fix(@angular-devkit/build-angular): only add module script types to actual module scripts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/test/dev-server/index_spec_large.ts
Labels: PR target: master & patch, cla: yes

#14989 fix(@angular-devkit/build-optimizer): wrap classes with a let variable
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums_spec.ts
Labels: PR target: master & patch, cla: yes

#14996 fix(@schematics/update): update `@angular/pwa` when migrating to 8
  packages/schematics/angular/migrations/update-8/update-dependencies.ts
  packages/schematics/angular/utility/latest-versions.ts
Labels: PR target: master & patch, cla: yes

#15000 fix(@angular/cli): add `verbose` option to `update` and `add`
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/commands/add.json
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/commands/update.json
Labels: PR target: master & patch, cla: yes

#15003 fix(@angular-devkit/build-angular): use query option to set sockJS path in dev-server
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: PR target: master & patch, cla: yes

#15009 fix(@schematics/angular): add `text-summary` to code coverage reporter
  packages/schematics/angular/library/files/karma.conf.js.template
Labels: PR target: master & patch, cla: yes

#15022 fix(@schematics/angular): ignore nested arrays in route declarations
  packages/schematics/angular/utility/ast-utils.ts
  packages/schematics/angular/utility/ast-utils_spec.ts
Labels: PR target: master & patch, cla: yes

#15010 feat(@angular-devkit/build-angular): allow control of index output path
  packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/write-index-html.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
  packages/angular_devkit/build_angular/test/browser/index_spec_large.ts
Labels: PR target: master-only, cla: yes

#15026 fix(@angular/cli): display a more detailed error message when workspa…
  packages/angular/cli/utilities/config.ts
Labels: PR target: master & patch, cla: yes

#14995 fix(@angular-devkit/build-angular): fix sourcemaps paths
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/utils.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma.ts
Labels: PR target: master & patch, cla: yes

#15021 build: update webpack to version 4.35.3
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/test/browser/resolve-json-module_spec_large.ts
  packages/angular_devkit/build_webpack/package.json
  packages/ngtools/webpack/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#15020 refactor(@angular-devkit/build-optimizer): refactor wrap enums
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
Labels: PR target: master-only, cla: yes

#15054 feat(@angular/cli): report telemetry opt-ins
  packages/angular/cli/models/analytics.ts
Labels: PR target: master-only, cla: yes

#15065 test: integrate browser testing for differential loading
  .circleci/config.yml
  package.json
  scripts/saucelabs/start-tunnel.sh
  scripts/saucelabs/stop-tunnel.sh
  scripts/saucelabs/wait-for-tunnel.sh
  tests/legacy-cli/e2e/assets/protractor-saucelabs.conf.js
  tests/legacy-cli/e2e/tests/misc/browsers.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#15052 test: use locally published version in E2E project setup
  tests/legacy-cli/e2e/setup/015-build.ts
  tests/legacy-cli/e2e/setup/100-global-cli.ts
  tests/legacy-cli/e2e/utils/project.ts
  tests/legacy-cli/verdaccio.yaml
Labels: PR target: master-only, cla: yes

#15044 feat(@schematic/angular): enable ivy in tests
  packages/schematics/angular/application/files/tsconfig.spec.json.template
Labels: PR target: master-only, cla: yes

#15085 test: fix safari 10.1 e2e differential loading browser test
  tests/legacy-cli/e2e/assets/protractor-saucelabs.conf.js
Labels: PR target: master-only, cla: yes

#15039 Document possible values of analytics command
  packages/angular/cli/commands/analytics-long.md
  packages/angular/cli/commands/analytics.json
Labels: PR target: master & patch, cla: yes, comp: angular/cli, effort1: easy (hours), freq1: low, priority: 3 (nice to have), severity2: inconvenient, type: docs

#15041 fix(@angular/cli): use correct schematic defaults considering workspace
  etc/api/angular_devkit/schematics/tools/index.d.ts
  packages/angular/cli/models/schematic-command.ts
  packages/angular_devkit/schematics/tools/description.ts
  packages/angular_devkit/schematics/tools/workflow/node-workflow.ts
  packages/angular_devkit/schematics/tools/workflow/node-workflow_spec.ts
  packages/angular_devkit/schematics_cli/bin/schematics.ts
Labels: PR target: master-only, cla: yes

#15087 feat(@angular-devkit/build-angular): add defer attributes to classic scripts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/augment-index-html.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/augment-index-html_spec.ts
  packages/angular_devkit/build_angular/test/browser/cross-origin_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/index_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/scripts-array_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/service-worker_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/styles_spec_large.ts
  packages/angular_devkit/build_angular/test/dev-server/index_spec_large.ts
  tests/legacy-cli/e2e/tests/basic/scripts-array.ts
  tests/legacy-cli/e2e/tests/basic/styles-array.ts
  tests/legacy-cli/e2e/tests/build/polyfills.ts
  tests/legacy-cli/e2e/tests/build/styles/extract-css.ts
  tests/legacy-cli/e2e/tests/misc/support-ie.ts
  tests/legacy-cli/e2e/tests/misc/support-safari-10.1.ts
  tests/legacy-cli/e2e/tests/third-party/bootstrap.ts
Labels: PR target: master-only, cla: yes

#15090 fix(@schematics/angular): add commonjs module to universal tsconfig
  packages/schematics/angular/universal/files/root/__tsconfigFileName__.json.template
  packages/schematics/angular/universal/index_spec.ts
Labels: PR target: master & patch, cla: yes

#15030 fix(@schematics/angular): exclusively list the files in tsconfigs
  packages/angular_devkit/build_angular/test/browser/errors_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/lazy-module_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/output-hashing_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
  packages/schematics/angular/application/files/tsconfig.app.json.template
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/universal/files/root/__tsconfigFileName__.json.template
  packages/schematics/angular/universal/index_spec.ts
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/tsconfig.app.json
  tests/angular_devkit/build_angular/hello-world-app-ivy/src/tsconfig.server.json
  tests/angular_devkit/build_angular/hello-world-app/src/tsconfig.app.json
  tests/angular_devkit/build_angular/hello-world-app/src/tsconfig.server.json
  tests/legacy-cli/e2e/tests/basic/rebuild.ts
  tests/legacy-cli/e2e/tests/build/build-app-shell.ts
  tests/legacy-cli/e2e/tests/build/build-errors.ts
  tests/legacy-cli/e2e/tests/build/dynamic-import.ts
  tests/legacy-cli/e2e/tests/build/lazy-load-syntax.ts
  tests/legacy-cli/e2e/tests/build/platform-server.ts
  tests/legacy-cli/e2e/tests/misc/lazy-module.ts
Labels: PR target: master-only, cla: yes

#14704 fix(@schematics/angular): the required 'alt' attribute is missing
  packages/schematics/angular/application/other-files/app.component.ts.template
Labels: PR target: master & patch, cla: yes

#15051 fix(@angular-devkit/build-angular): support pnpm with ng serve
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: PR target: master & patch, cla: yes

#15061 feat(@ngtools/webpack): show warning when a TS compilations contains …
  packages/angular_devkit/build_angular/test/browser/unused-files-warning_spec_large.ts
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR target: master-only, cla: yes

#15128 fix(@schematics/angular): add differential loading profiling file to gi…
  packages/schematics/angular/workspace/files/__dot__gitignore.template
Labels: PR target: master & patch, cla: yes

#15129 fix(@angular-devkit/build-angular): fix sourcemaps for vscode breakpo…
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/utils.ts
  packages/angular_devkit/build_angular/test/browser/source-map_spec_large.ts
Labels: PR target: master & patch, cla: yes

#15142 fix(@schematics/angular): change `findNodes` to stop recursive lookup…
  packages/schematics/angular/utility/ast-utils.ts
  packages/schematics/angular/utility/ast-utils_spec.ts
Labels: PR target: master & patch, cla: yes

#15144 fix(@ngtools/webpack): delete all virtual files for styles on change
  packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
  packages/ngtools/webpack/src/compiler_host.ts
Labels: PR target: master & patch, cla: yes

#15148 test: ensure E2E locally published packages are used
  tests/legacy-cli/e2e/utils/project.ts
Labels: PR target: master & patch, cla: yes

#15151 fix(@ngtools/webpack): use a single module resolution cache
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/ngtools/webpack/src/compiler_host.ts
Labels: PR target: master & patch, cla: yes

#15159 style: clean up existing lint errors
  packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/scripts-array_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/unused-files-warning_spec_large.ts
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/utility/json-utils.ts
Labels: PR target: master-only, cla: yes

#15164 fix(@angular-devkit/build-angular): rollback sass to version `1.22.7`
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#15173 test: add local npm registry to failing tests
  tests/legacy-cli/e2e/tests/misc/ask-analytics.ts
  tests/legacy-cli/e2e/tests/schematics_cli/basic.ts
  tests/legacy-cli/e2e/tests/update/update-1.0.ts
  tests/legacy-cli/e2e/tests/update/update-1.7-longhand.ts
  tests/legacy-cli/e2e/utils/assets.ts
Labels: PR target: master-only, cla: yes

#14638 fix(@schematics/angular): application schematic should prompt for --ro…
  packages/schematics/angular/application/schema.json
Labels: PR target: master-only, cla: yes

#15163 fix(@angular/cli): don't add leftovers when there are none
  packages/angular/cli/models/parser.ts
Labels: PR target: master & patch, cla: yes

#15165 fix(@angular-devkit/build-optimizer): don't wrap enum like nodes whic…
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums_spec.ts
Labels: PR target: master & patch, cla: yes

#15169 ci: enable snapshot e2e for renovate PRs
  .circleci/config.yml
Labels: PR target: master-only, cla: yes

#15171 test: add library consumption protractor test
  tests/legacy-cli/e2e/tests/generate/library/library-consumption.ts
Labels: PR target: master & patch, cla: yes

#15177 test: follow up comments from #15173
  tests/legacy-cli/e2e/tests/misc/ask-analytics.ts
  tests/legacy-cli/e2e/tests/schematics_cli/basic.ts
Labels: PR target: master-only, cla: yes

#15189 fix(@ngtools/webpack): find aliased lazy route factories
  packages/ngtools/webpack/src/transformers/import_factory.ts
  packages/ngtools/webpack/src/transformers/import_factory_spec.ts
Labels: PR target: master & patch, cla: yes

#15190 test: remove defer from script tag
  packages/angular_devkit/build_angular/test/browser/scripts-array_spec_large.ts
Labels: PR target: patch-only, cla: yes

#15191 test: increase/add debounceTime to reduce flakiness
  packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
Labels: PR target: master-only, cla: yes

#15201 fix(@angular-devkit/build-optimizer): don't wrap classes which static…
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
Labels: PR target: master & patch, cla: yes

#15202 fix(@angular-devkit/build-angular): escape dot in js extensions to match literally
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Labels: PR target: master & patch, cla: yes

#15105 feat(@angular/cli): implement deploy command
  packages/angular/cli/BUILD
  packages/angular/cli/commands.json
  packages/angular/cli/commands/deploy-impl.ts
  packages/angular/cli/commands/deploy-long.md
  packages/angular/cli/commands/deploy.json
  packages/angular/cli/models/architect-command.ts
  packages/angular/cli/models/command-runner.ts
Labels: PR target: master-only, cla: yes

#15082 Pass target to a builder called through `context.scheduleBuilder`
  packages/angular_devkit/architect/src/api.ts
  packages/angular_devkit/architect/src/create-builder.ts
Labels: PR target: master & patch, cla: yes
