Repository angular/angular-cli, pull requests merged in 2020-11, with the labels that each got.

#19228 fix(@ngtools/webpack): show zone.js incompatibility warning when using ES2017+
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/ngtools/webpack/README.md
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/ngtools/webpack/src/interfaces.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19256 docs(@angular/cli): use application instead of app
  packages/angular/cli/commands/new.json
  packages/angular/cli/commands/new.md
  packages/schematics/angular/application/schema.json
Labels: PR action: merge, PR target: master & patch, cla: yes

#19260 fix(@angular-devkit/build-optimizer): mark rxjs add imports as having side effects
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19262 fix(@angular-devkit/build-angular): improve network error message during fonts inlining
  packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19266 Validate extracted i18n messages for duplicates
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/extract-i18n/works_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19275 fix(@angular-devkit/build-angular): remove title attribute from inlined fonts style tag
  packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19282 build: update sass-loader to version 10.0.5
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR action: merge, PR target: patch-only, cla: yes

#19281 test(@angular-devkit/build-angular): pin node-sass to version 4
  tests/legacy-cli/e2e/tests/build/styles/node-sass.ts
Labels: PR action: merge, PR target: lts-only, cla: yes

#19280 test(@angular-devkit/build-angular): pin node-sass to version 4
  tests/legacy-cli/e2e/tests/build/styles/node-sass.ts
Labels: PR action: merge, PR target: lts-only, cla: yes

#19279 test(@angular-devkit/build-angular): pin node-sass to version 4
  tests/legacy-cli/e2e/tests/build/styles/node-sass.ts
Labels: PR action: merge, PR target: lts-only, cla: yes

#19274 refactor(@angular-devkit/build-angular): use custom babel preset to configure babel-loader
  packages/angular_devkit/build_angular/src/babel/presets/application.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19255 Bundle output stats fixes
  packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19292 fix(@angular-devkit/build-angular): reduce clutter in dev-server logs
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19295 fix(@angular/cli): correctly read transitive dependency
  packages/angular/cli/commands/update-impl.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19296 Revert "fix(@angular-devkit/build-angular): don't generate `vendor.js…
  packages/angular_devkit/build_angular/src/browser/specs/differential_loading_spec.ts
  packages/angular_devkit/build_angular/src/browser/specs/vendor-source-map_spec.ts
  packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
  packages/angular_devkit/build_angular/src/webpack/configs/server.ts
  packages/angular_devkit/build_angular/src/webpack/configs/test.ts
  packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
  tests/legacy-cli/e2e/tests/build/sourcemap.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19297 fix(@angular-devkit/build-angular): add default value to progress option
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/karma/schema.json
  packages/angular_devkit/build_angular/src/server/schema.json
Labels: PR action: merge, PR target: master & patch, cla: yes

#19315 test(@angular-devkit/build-angular): update platform server devkit packages
  tests/legacy-cli/e2e/tests/build/platform-server.ts
Labels: PR target: master & patch, cla: yes

#19310 fix(@angular-devkit/build-angular): add validation to fileReplacement values
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/server/schema.json
Labels: PR action: merge, PR target: master & patch, cla: yes

#19324 test(@angular-devkit/build-angular): refactor platform server test to use universal schematic
  tests/legacy-cli/e2e/tests/build/platform-server.ts
Labels: PR target: master & patch, cla: yes

#19336 fix(@angular-devkit/build-angular): Downgrade Karma to 5.1.x
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/webpack/plugins/karma.ts
  packages/schematics/angular/workspace/files/package.json.template
Labels: PR action: merge, PR target: patch-only, cla: yes, comp: devkit/build-angular

#19342 test(@angular-devkit/build-angular): add E2E test for i18n locale data augmentation
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-locale-data-augment.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19352 fix(@angular-devkit/build-angular): properly handle comment removal during font inlining
  packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
  packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19333 fix(@angular-devkit/build-angular): separate initial total size in build output
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
  tests/legacy-cli/e2e/tests/basic/build.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19358 fix(@schematics/angular): remove trailing comma in karma conf
  packages/schematics/angular/application/files/karma.conf.js.template
  packages/schematics/angular/library/files/karma.conf.js.template
Labels: PR action: merge, PR target: master & patch, cla: yes

#19361 fix(@angular-devkit/build-angular): show missing karma-coverage error when it's not configured
  packages/angular_devkit/build_angular/src/webpack/plugins/karma.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19362 fix(@angular-devkit/build-angular): show missing karma-coverage error…
  packages/angular_devkit/build_angular/src/webpack/plugins/karma.ts
Labels: PR target: patch-only, cla: yes

#19376 [patch] fix(@angular-devkit/build-angular): rollback css-loader to version 4
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: patch-only, cla: yes

#19356 fix(@schematics/angular): remove duplicated Karma traces
  integration/angular_cli/karma.conf.js
  packages/angular_devkit/build_angular/test/hello-world-app/karma.conf.js
  packages/angular_devkit/build_angular/test/hello-world-lib/projects/lib/karma.conf.js
  packages/schematics/angular/application/files/karma.conf.js.template
  packages/schematics/angular/library/files/karma.conf.js.template
Labels: PR action: merge, PR target: master & patch, cla: yes

#19379 fix(@angular-devkit/build-angular) allow json files in fileReplacement
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/server/schema.json
Labels: PR action: merge, PR target: master & patch, cla: yes

#19392 fix(@angular/cli): remove @angular-devkit/build-ng-packagr from update
  packages/angular/cli/package.json
Labels: PR action: merge, PR target: master & patch, cla: yes

#19396 fix(@angular-devkit/build-angular): remove workaround for Webpack 5 sourcemaps
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19382 refactor(@angular-devkit/build-angular): support postcss 8
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/webpack/plugins/postcss-cli-resources.ts
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#19343 refactor(@angular-devkit/architect): abstract workspace access from architect
  packages/angular_devkit/architect/node/node-modules-architect-host.ts
Labels: PR target: master-only, cla: yes

#19323 refactor(@angular-devkit/build-angular): clean up index generation part 3
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html.ts
  packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html_spec.ts
  packages/angular_devkit/build_angular/src/utils/index-file/index-html-generator.ts
  packages/angular_devkit/build_angular/src/utils/index-file/transforms.ts
  packages/angular_devkit/build_angular/src/utils/index-file/write-index-html.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/index-html-webpack-plugin.ts
Labels: PR target: master-only, cla: yes

#19386 fix(@angular-devkit/build-angular): ignore hidden inputs with hmr
  packages/angular_devkit/build_angular/src/dev-server/hmr_spec.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/hmr/hmr-accept.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19399 fix(@ngtools/webpack): only use `require.resolve` as a fallback in NGCC processing
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/ngtools/webpack/src/ivy/plugin.ts
  packages/ngtools/webpack/src/ngcc_processor.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19404 fix(@angular-devkit/build-angular): remove unneeded update package group
  packages/angular_devkit/build_angular/package.json
Labels: PR action: merge, PR target: master & patch, cla: yes

#19413 fix(@schematics/update): ignore `@angular-devkit/build-ng-packagr` incompatible peer dependency
  packages/schematics/update/update/index.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19412 fix(@angular-devkit/build-angular): ERR_SSL_PROTOCOL_ERROR when using HTTPS reverse proxy
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/src/dev-server/live-reload_spec.ts
  packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
  tests/legacy-cli/e2e/tests/misc/live-reload.ts
  yarn.lock
Labels: PR action: merge, PR target: master & patch, cla: yes

#19405 fix(@ngtools/webpack): remove use of Webpack 5 deprecated compilationDependencies
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19417 fix(@angular-devkit/build-webpack): properly shutdown webpack 5 compilation
  packages/angular_devkit/build_webpack/src/webpack/index.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19421 test(@angular-devkit/build-angular): add test to simulate dotnet proxy
  packages/angular_devkit/build_angular/src/dev-server/live-reload_spec.ts
Labels: PR target: master & patch, cla: yes

#19422 fix(@angular-devkit/schematics-cli): remove `_` property from options
  packages/angular_devkit/schematics_cli/bin/schematics.ts
Labels: PR target: master & patch, cla: yes

#19357 fix(@schematics/angular): document jasmine options
  packages/schematics/angular/application/files/karma.conf.js.template
  packages/schematics/angular/library/files/karma.conf.js.template
Labels: PR action: merge, PR target: master & patch, cla: yes

#19423 fix(@angular-devkit/build-angular): disable output hashing when running dev-server
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  tests/legacy-cli/e2e/tests/basic/ivy.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19437 fix(@angular-devkit/build-angular): handle HTML file with no body and head tags
  packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html.ts
  packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19463 ci: add Node.js 14 E2E job
  .circleci/config.yml
Labels: PR action: merge, PR target: master-only, cla: yes

#19465 test(@angular-devkit/buid-angular): rename augmentIndexHtml parameter…
  packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html_spec.ts
Labels: PR action: merge, PR target: patch-only, cla: yes

#19446 fix(@angular-devkit/build-angular): apply local libraries sourcemap without `vendor: true`
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19477 test(@angular/cli): pin @angular/material package to version 9
  tests/legacy-cli/e2e/tests/commands/add/add-material.ts
Labels: PR action: merge, PR target: lts-only, cla: yes

#19474 docs: improve description for optimization and target options.
  packages/angular/cli/commands/definitions.json
  packages/angular/cli/commands/deploy.json
  packages/angular/cli/commands/run.json
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/app-shell/schema.json
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/dev-server/schema.json
  packages/angular_devkit/build_angular/src/extract-i18n/schema.json
  packages/angular_devkit/build_angular/src/protractor/schema.json
  packages/angular_devkit/build_angular/src/server/schema.json
Labels: PR action: merge, PR target: master & patch, cla: yes

#19476 ci: disable 8.3 nightly build
  .circleci/config.yml
Labels: PR action: merge, PR target: lts-only, cla: yes

#19480 fix(@angular-devkit/build-angular): allow default Webpack 5 caching
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19503 fix(@ngtools/webpack): remove use of Webpack compilation fileTimestamps property
  packages/ngtools/webpack/src/ivy/cache.ts
  packages/ngtools/webpack/src/ivy/plugin.ts
  packages/ngtools/webpack/src/resource_loader.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19507 fix(@angular-devkit/build-angular): resolve partial SCSS files in sourcemaps
  packages/angular_devkit/build_angular/src/browser/specs/source-map_spec.ts
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19508 fix(@angular-devkit/core): correctly handle null prototype in deepCopy
  packages/angular_devkit/core/src/utils/object.ts
  packages/angular_devkit/core/src/utils/object_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19512 docs: add description to `localize` option
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/server/schema.json
Labels: PR action: merge, PR target: master & patch, cla: yes

#19515 build: establish current version in package.json
  package.json
Labels: PR action: merge, PR target: master-only, cla: yes, comp: build & ci

#19516 build: establish current version in package.json
  package.json
Labels: PR action: merge, PR target: patch-only, cla: yes, comp: build & ci

#19517 build: establish current version in package.json
  package.json
Labels: PR action: merge, PR target: lts-only, cla: yes, comp: build & ci
