Repository angular/angular-cli, pull requests merged in 2020-01, with the labels that each got.

#16352 fix(@ngtools/webpack): format Ivy diagnostics properly
  packages/ngtools/webpack/src/diagnostics.ts
Labels: PR target: master & patch, cla: yes

#16440 fix(@angular-devkit/schematics): fix the `isBinary` function
  packages/angular_devkit/schematics/src/rules/template.ts
  packages/angular_devkit/schematics/src/rules/utils/is-binary.ts
Labels: PR target: master & patch, cla: yes

#16477 fix(@angular/cli): migrate and inform users about @angular-devkit/[schematics, core] packages
  packages/angular/cli/package.json
  packages/schematics/angular/migrations/update-9/update-dependencies.ts
Labels: PR target: master & patch, cla: yes

#16512 fix(@angular/cli): allow users to use `additionalProperties` in their…
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/models/schematic-command.ts
  tests/legacy-cli/e2e/tests/commands/add/add-material.ts
Labels: PR target: master & patch, cla: yes

#16524 fix(@angular-devkit/build-angular): add sourceMappingURL comment for …
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/action-cache.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
  tests/legacy-cli/e2e/tests/build/no-sourcemap.ts
  tests/legacy-cli/e2e/tests/build/sourcemap.ts
Labels: PR target: master & patch, blocked, cla: yes

#16528 fix(@angular-devkit/build-angular): prevent differential loading double sourcemap search
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR target: master & patch, cla: yes

#16504 build: update fast-json-stable-stringify to 2.1
  package.json
  packages/angular_devkit/core/BUILD
  packages/angular_devkit/core/package.json
  packages/angular_devkit/core/src/experimental/jobs/strategy.ts
  packages/angular_devkit/core/src/workspace/json/utilities.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#16521 [8.3.x] fix(@angular-devkit/build-angular): prevent differential loading double sourcemap search
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR action: merge, PR target: LTS-only, cla: yes

#16543 refactor(@angular/cli): allow update version check to be disabled
  packages/angular/cli/commands/update-impl.ts
Labels: PR target: master & patch, cla: yes

#16538 fix(@angular-devkit/build-optimizer): wrap classes which contain empt…
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums_spec.ts
Labels: PR target: master & patch, cla: yes

#16529 fix(@angular-devkit/build-angular): account for hashed and non hashed…
  packages/angular_devkit/build_angular/src/utils/action-cache.ts
  tests/legacy-cli/e2e/tests/build/sourcemap.ts
Labels: PR target: master & patch, cla: yes

#16555 build: update terser to version 4.5.1
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: patch-only, cla: yes

#16566 fix(@angular-devkit/build-angular): update browserslist and caniuse-lite
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: patch-only, cla: yes

#16567 ci: allow renovate to update devDependencies major versions
  renovate.json
Labels: PR target: master-only, cla: yes

#16570 docs: update feature request template to be tick-able
  .github/ISSUE_TEMPLATE/2-feature-request.md
Labels: PR target: master & patch, cla: yes

#16565 fix(@angular-devkit/build-angular): update browserslist and caniuse-lite
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: LTS-only, cla: yes

#16593 fix(@angular/cli): disable Browserslist old data warning
  packages/angular/cli/lib/init.ts
Labels: PR target: master & patch, cla: yes

#16597 [LTS] fix(@angular/cli): disable Browserslist old data warning
  packages/angular/cli/lib/init.ts
Labels: PR target: LTS-only, cla: yes

#16608 fix(@angular-devkit/build-angular): replace istanbul-instrumenter-loa…
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
  yarn.lock
Labels: PR target: master-only, cla: yes

#16607 fix(@angular-devkit/build-angular): replace istanbul-instrumenter-loa…
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
  yarn.lock
Labels: PR target: patch-only, cla: yes

#16624 build: pin down direct cli dependencies
  packages/angular/cli/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#16634 [8.3.x] fix(@angular-devkit/build-angular): update tree-kill dependency to 1.2.2
  package.json
  packages/angular_devkit/benchmark/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  yarn.lock
Labels: PR target: LTS-only, cla: yes

#16636 [9.0.x] fix(@angular-devkit/build-angular): update tree-kill dependency to 1.2.2
  package.json
  packages/angular_devkit/benchmark/package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR target: patch-only, cla: yes

#16639 build: update tree-kill to version ^1.2.2
  package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#16671 ci: add "PR action: merge" label to renovate bot PRs
  renovate.json
Labels: PR action: merge, PR target: master-only, cla: yes

#16666 fix(@angular-devkit/build-angular): emit error when a script is not found.
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/test/browser/scripts-array_spec_large.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16652 build: remove pnpm engine value due to lack of yarn support
  lib/packages.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16675 build: update @types/jasmine to ~3.5.0
  package.json
  yarn.lock
Labels: PR action: merge, PR target: patch-only, cla: yes

#16678 test: add test for strict workspace
  tests/legacy-cli/e2e/tests/build/no-implicit-any.ts
  tests/legacy-cli/e2e/tests/build/strict-workspace.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16690 revert "fix(@angular-devkit/build-optimizer): wrap classes which cont…
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16692 ci: use branch filtering to run `e2e-cli-ng-snapshots` and `e2e-cli-ng-ve-snapshots
  .circleci/config.yml
Labels: PR action: merge, PR target: master-only, cla: yes

#16703 ci: update ignore_pull_requests to only include release-able branches
  .circleci/config.yml
Labels: PR action: merge, PR target: master-only, cla: yes

#16573 docs: address remaining review items
  docs/design/build-system-overview.dot
  docs/design/build-system.md
Labels: PR action: merge, PR target: master-only, cla: yes

#16698 refactor(@angular-devkit/build-angular): remove nonexistent argument from rxjs path mapping call
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16673 fix(@angular/cli): prevent postinstall script errors from blocking install
  packages/angular/cli/bin/postinstall/script.js
Labels: PR action: merge, PR target: master & patch, cla: yes

#16722 ci: reduce ci time for renovate PRs
  .circleci/config.yml
Labels: PR action: merge, PR target: master-only, cla: yes

#16726 docs: add NPM login details to releasing docs.
  docs/process/release.md
Labels: PR action: merge, PR target: master-only, cla: yes, priority: 3 (nice to have), type: docs

#16727 fix(@angular/cli): ensure built-in Angular schematics package can be found
  packages/angular/cli/models/schematic-command.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16738 test: add snapshot material e2e tests
  tests/legacy-cli/e2e/ng-snapshot/package.json
  tests/legacy-cli/e2e/tests/build/material.ts
  tests/legacy-cli/e2e/tests/build/styles/material-import.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#16739 Update jest worker
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/action-executor.ts
  packages/angular_devkit/build_angular/src/utils/i18n-inlining.ts
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#16709 fix(@schematics/angular): regression tsconfig.json #16708
  packages/schematics/angular/library/index.ts
  packages/schematics/angular/library/index_spec.ts
  packages/schematics/angular/workspace/files/tsconfig.json.template
Labels: PR action: merge, PR target: master & patch, cla: yes

#16735 fix(@angular-devkit/build-angular): ensure output is ASCII only
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/test/browser/optimization-level_spec_large.ts
  tests/legacy-cli/e2e/tests/basic/ivy.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16736 refactor(@angular-devkit/build-angular): add additional debug build environment variables
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/utils/environment-options.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16743 fix(@ngtools/webpack): correctly determine resource dependencies
  packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/ngtools/webpack/src/loader.ts
  packages/ngtools/webpack/src/resource_loader.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16753 test: fix material snapshot iterator
  tests/legacy-cli/e2e/tests/build/material.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#16740 build: update nodejs rules to 1.0+
  WORKSPACE
  package.json
  packages/angular_devkit/architect/BUILD
  packages/angular_devkit/benchmark/BUILD
  packages/angular_devkit/build_optimizer/BUILD
  packages/angular_devkit/core/BUILD
  packages/angular_devkit/schematics/BUILD
  tools/BUILD
  tools/build_event_protocol/BUILD
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#16744 fix(@angular-devkit/build-angular): re-introduce fast sourcemap path
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16755 fix(@schematics/angular): add compliance with call-signature lint rule
  packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
  packages/schematics/angular/e2e/files/src/app.po.ts.template
Labels: PR action: merge, PR target: master & patch, cla: yes

#16772 docs: Reorganize release docs to emphasize updating release notes
  docs/process/release.md
Labels: PR target: master-only, cla: yes

#16782 fix(@angular-devkit/build-angular): pass filename to `parseSync`
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16745 ci: reduce resource classes
  .circleci/config.yml
Labels: PR action: merge, PR target: master & patch, cla: yes

#16783 fix(@angular-devkit/build-angular): ensure babel configurations are isolated
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16787 [Patch] build: update terser-webpack-plugin to version 2.3.3
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR action: merge, PR target: patch-only, cla: yes

#16771 fix(@schematics/angular): add compliance with no-any lint rule
  packages/schematics/angular/application/files/src/test.ts.template
  packages/schematics/angular/e2e/files/src/app.po.ts.template
  packages/schematics/angular/library/files/src/test.ts.template
  packages/schematics/angular/pipe/files/__name@dasherize@if-flat__/__name@dasherize__.pipe.ts.template
  packages/schematics/angular/pipe/index_spec.ts
  tests/angular_devkit/build_angular/hello-world-app-ve/e2e/app.po.ts
  tests/angular_devkit/build_angular/hello-world-app-ve/src/test.ts
  tests/angular_devkit/build_angular/hello-world-app/e2e/app.po.ts
  tests/angular_devkit/build_angular/hello-world-app/src/test.ts
  tests/angular_devkit/build_ng_packagr/ng-packaged-ve/projects/lib/src/test.ts
  tests/angular_devkit/build_ng_packagr/ng-packaged/projects/lib/src/test.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16788 fix(@schematics/angular): update protractor version for new projects
  packages/schematics/angular/workspace/files/package.json.template
Labels: PR action: merge, PR target: master & patch, cla: yes

#16794 refactor(@angular-devkit/build-angular): improve debug optimize environment variables
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/utils/action-cache.ts
  packages/angular_devkit/build_angular/src/utils/environment-options.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16571 docs: add build system differential loading theory of operation overview
  docs/design/build-system.md
Labels: PR target: master-only, cla: yes

#16795 fix(@angular-devkit/build-angular): remove unneeded regex polyfills
  packages/angular_devkit/build_angular/src/angular-cli-files/models/es5-polyfills.js
Labels: PR action: merge, PR target: LTS-only, PR target: master & patch, cla: yes
