Repository angular/angular-cli, pull requests merged in 2020-09, with the labels that each got.

#18669 fix(@schematics/angular): update karma for new workspaces to 5.2.0
  packages/schematics/angular/workspace/files/package.json.template
Labels: PR action: merge, PR target: master-only, cla: yes

#18679 refactor(@angular-devkit/core): remove resolve methods and options
  etc/api/angular_devkit/core/node/_golden-api.d.ts
  lib/bootstrap-local.js
  packages/angular_devkit/core/node/_golden-api.ts
  packages/angular_devkit/core/node/index.ts
  packages/angular_devkit/core/node/resolve.ts
  packages/angular_devkit/core/node/resolve_spec.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18069 fix(@angular-devkit/build-angular): don't generate `vendor.js.map` when vendor sourcemaps is disabled
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/utils.ts
  packages/angular_devkit/build_angular/src/browser/specs/differential_loading_spec.ts
  packages/angular_devkit/build_angular/src/browser/specs/vendor-source-map_spec.ts
  tests/legacy-cli/e2e/tests/build/sourcemap.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18674 fix(@angular-devkit/build-angular): correct i18n function parameter type
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18681 refactor(@angular/cli): remove node module directory assumption during initialization
  packages/angular/cli/lib/cli/index.ts
  packages/angular/cli/lib/init.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18684 test: support prelease versions in platform server E2E
  tests/legacy-cli/e2e/tests/build/platform-server.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18610 refactor(@angular/cli): improve update package discovery
  package.json
  packages/angular/cli/BUILD.bazel
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/package.json
  packages/angular/cli/utilities/package-tree.ts
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/package.json
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/.angular-cli.json
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/.editorconfig
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/.gitignore
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/README.md
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/e2e/app.e2e-spec.ts
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/e2e/app.po.ts
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/e2e/tsconfig.e2e.json
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/karma.conf.js
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/package.json
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/protractor.conf.js
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/app/app.component.css
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/app/app.component.html
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/app/app.component.spec.ts
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/app/app.component.ts
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/app/app.module.ts
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/assets/.gitkeep
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/environments/environment.prod.ts
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/environments/environment.ts
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/favicon.ico
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/index.html
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/main.ts
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/polyfills.ts
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/styles.css
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/test.ts
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/tsconfig.app.json
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/tsconfig.spec.json
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/src/typings.d.ts
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/tsconfig.json
  tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/tslint.json
  tests/legacy-cli/e2e/tests/update/update-1.0-yarn.ts
  tests/legacy-cli/e2e/utils/assets.ts
  tests/legacy-cli/e2e/utils/process.ts
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#18686 fix(@angular-devkit/build-angular): consider ascii_only terser setting when counting components in analytics
  packages/angular_devkit/build_angular/plugins/webpack/analytics.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17901 feat(@angular-devkit/build-angular): Switch to karma-coverage
  integration/angular_cli/karma.conf.js
  integration/angular_cli/package.json
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma.ts
  packages/angular_devkit/build_angular/src/karma/code-coverage_spec.ts
  packages/angular_devkit/build_angular/src/karma/index.ts
  packages/angular_devkit/build_angular/test/hello-world-app/karma.conf.js
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/karma.conf.js
  packages/schematics/angular/application/files/karma.conf.js.template
  packages/schematics/angular/library/files/karma.conf.js.template
  packages/schematics/angular/workspace/files/package.json.template
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#18708 refactor(@schematics/angular): Brackets formatting in angular.json
  packages/schematics/angular/workspace/files/angular.json.template
Labels: PR action: merge, PR target: master-only, cla: yes

#18714 docs: update testing chapter with general test commands
  README.md
  scripts/templates/readme.ejs
Labels: PR action: merge, PR target: master-only, cla: yes

#18727 refactor(@angular-devkit/schematics): deprecate isAction
  packages/angular_devkit/schematics/src/sink/sink.ts
  packages/angular_devkit/schematics/src/tree/action.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18725 refactor(@angular-devkit/build-angular): lazy require autoprefixer, m…
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18724 Build-angular package sync
  package.json
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#18697 docs: add space between icon and text in issue template
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-feature-request.md
  .github/ISSUE_TEMPLATE/4-security-issue-disclosure.md
  .github/ISSUE_TEMPLATE/5-support-request.md
  .github/ISSUE_TEMPLATE/7-angular-material.md
Labels: PR action: merge, PR target: master-only, cla: yes

#18719 fix(@ngtools/webpack): emit `require` in replace resources when using CommonJS as module
  packages/ngtools/webpack/src/transformers/replace_resources.ts
  packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18711 fix(@angular-devkit/build-optimizer): remove decorators calls when tslib helpers are inlined
  packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts
  packages/angular_devkit/build_optimizer/src/transforms/scrub-file_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18732 fix(@angular-devkit/build-angular): filter unactionable System.import webpack warning
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18733 refactor(@angular-devkit/build-angular): support dedupe plugin with Webpack 5
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/dedupe-module-resolve-plugin.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18723 build: update postcss-loader to version 4.0
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/postcss-cli-resources.ts
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#18745 test: ensure schematics CLI E2E tests use local package registry
  tests/legacy-cli/e2e/tests/schematics_cli/basic.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18748 refactor(@angular-devkit/build-angular): use common logging function for webpack stats
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/server/index.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18749 fix(@angular-devkit/build-angular): set logging level to verbose when using `--vebose`
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/stats.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18753 test: support Webpack 5 in deployUrl E2E test
  tests/legacy-cli/e2e/tests/build/deploy-url.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18752 refactor(@angular-devkit/build-angular): use Webpack ChunkGraph API in SuppressExtractedTextChunksWebpackPlugin
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/suppress-entry-chunks-webpack-plugin.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18754 ci: update sauce-connect-proxy to latest
  package.json
  yarn.lock
Labels: PR action: merge, PR target: master & patch, cla: yes

#18729 build: remove experimental build event protocol
  WORKSPACE
  package.json
  packages/angular/cli/commands/build-impl.ts
  packages/angular/cli/commands/build.json
  packages/angular/cli/commands/serve-impl.ts
  packages/angular/cli/commands/serve.json
  packages/angular/cli/models/architect-command.ts
  packages/angular/cli/utilities/bep.ts
  packages/angular_devkit/core/src/analytics/index.ts
  tests/legacy-cli/e2e/tests/experimental/bep.ts
  third_party/README.md
  third_party/github.com/bazelbuild/bazel/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/BUILD.bazel
  third_party/github.com/bazelbuild/bazel/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto
  third_party/github.com/bazelbuild/bazel/src/main/protobuf/BUILD.bazel
  third_party/github.com/bazelbuild/bazel/src/main/protobuf/command_line.proto
  third_party/github.com/bazelbuild/bazel/src/main/protobuf/invocation_policy.proto
  third_party/github.com/bazelbuild/bazel/src/main/protobuf/option_filters.proto
  tools/build_event_protocol/BUILD.bazel
  tools/build_event_protocol/README.md
  tools/build_event_protocol/parse_bep.ts
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#18756 fix(@schematics/angular): canLoad guard signature
  packages/schematics/angular/guard/files/__name@dasherize__.guard.ts.template
Labels: PR action: merge, PR target: master & patch, cla: yes

#18761 refactor(@schematics/angular): remove lcov from coverage reporters
  packages/schematics/angular/application/files/karma.conf.js.template
  packages/schematics/angular/library/files/karma.conf.js.template
Labels: PR target: master-only, cla: yes

#18766 docs: remove Docker design doc
  docs/design/docker-deploy.md
Labels: PR target: master-only, cla: yes

#18767 refactor: delete unused AIO benchmark
  benchmark/aio/.gitignore
  benchmark/aio/package.json
Labels: PR action: merge, PR target: master & patch, cla: yes

#18765 fix(@angular/cli): remove version command node module assumptions
  packages/angular/cli/commands/version-impl.ts
Labels: PR target: master & patch, cla: yes

#18778 style(@schematics/angular): fix formatting of coverage reporters
  packages/schematics/angular/application/files/karma.conf.js.template
  packages/schematics/angular/library/files/karma.conf.js.template
Labels: PR action: merge, PR target: master-only, cla: yes

#18776 refactor(@angular-devkit/build-angular): support Webpack 5 errors/warnings
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
Labels: PR target: master-only, cla: yes

#18760 fix(@angular/cli): improve logs in ng update
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/models/schematic-command.ts
  packages/angular_devkit/schematics_cli/bin/schematics.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18786 test: support Webpack 5 in platform server E2E test
  tests/legacy-cli/e2e/tests/build/platform-server.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18793 test: remove custom internal tslint rules
  etc/rules/README.md
  etc/rules/Rule.ts
  etc/rules/defocusRule.ts
  etc/rules/importGroupsRule.ts
  etc/rules/noGlobalTslintDisableRule.ts
  etc/rules/singleEofLineRule.ts
  etc/rules/tsconfig.json
  tslint.json
Labels: PR action: merge, PR target: master-only, cla: yes

#18794 refactor(@ngtools/webpack): add webpack diagnostic helpers
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/ngtools/webpack/src/webpack-diagnostics.ts
  packages/ngtools/webpack/src/webpack-version.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18802 refactor(@angular-devkit/build-angular): add spinners for localize and downlevelling
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/i18n-inlining.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18759 feat(@schematics/angular): add migration to add declaration maps to libraries
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-11/add-declaration-map-compiler-option.ts
  packages/schematics/angular/migrations/update-11/add-declaration-map-compiler-option_spec.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18779 feat(@angular-devkit/build-angular): improve build stats output format
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/browser/specs/scripts-array_spec.ts
  packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#18811 fix(@angular-devkit/build-angular): add node-sass deprecation warning
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18836 refactor(@angular/cli): remove outdated 1.x karma plugin error placeholder
  packages/angular/cli/plugins/karma.js
Labels: PR action: merge, PR target: master-only, cla: yes

#18831 Replace regex with correct project name valdiation
  packages/angular/cli/lib/config/schema.json
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/index_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18845 fix(@angular/cli): favor dirname when resolving @schematics/angular
  packages/angular/cli/models/schematic-command.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18848 docs: remove usage of blacklist from third-party-libraries documentation
  docs/design/third-party-libraries.md
Labels: PR action: merge, PR target: master & patch, cla: yes

#18849 refactor: remove usages of the term whitelist
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/dev-server/schema.json
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
  packages/angular_devkit/core/src/analytics/index.ts
  packages/schematics/update/update/index.ts
Labels: PR action: merge, PR target: master & patch, cla: yes, comp: devkit/build-optimizer, comp: schematics/update

#18851 fix(@schematics/angular): remove solution style throw an error
  packages/schematics/angular/migrations/update-10/remove-solution-style-tsconfig.ts
  packages/schematics/angular/migrations/update-10/remove-solution-style-tsconfig_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18863 docs: change beta to next tag in release process
  docs/process/release.md
Labels: PR action: merge, PR target: master-only, cla: yes

#18870 test(@angular-devkit/build-angular): test Ivy specific files in unused file tests
  packages/angular_devkit/build_angular/src/browser/specs/unused-files-warning_spec.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18875 refactor(@schematics/angular): remove unused json utils
  packages/schematics/angular/utility/json-utils.ts
  packages/schematics/angular/utility/json-utils_spec.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18887 Extract messages libs
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
  tests/legacy-cli/e2e/tests/i18n/extract-ivy-libraries.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18890 fix(@angular-devkit/architect-cli): remove minimist `_` from options
  packages/angular_devkit/architect_cli/bin/architect.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18788 feat(@angular-devkit/build-angular): auto configure hot module replacement (HMR)
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/webpack/hmr.js
Labels: PR action: merge, PR target: master-only, cla: yes

#18879 feat(@angular-devkit/build-angular): support package references in styles & scripts options
  packages/angular_devkit/build_angular/src/browser/specs/styles_spec.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18868 feat(@angular-devkit/core): add basic support for oneOf/anyOf to `addUndefinedDefaults` transformer
  packages/angular_devkit/core/src/json/schema/registry_spec.ts
  packages/angular_devkit/core/src/json/schema/transforms.ts
  packages/angular_devkit/core/src/json/schema/transforms_spec.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18884 fix(@angular-devkit/build-angular): webpack5 deprecation of module property in Dependency
  packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/common-js-usage-warn-plugin.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18906 fix(@angular-devkit/build-angular): maxModules were deprecated and renamed to modulesSpace
  packages/angular_devkit/build_angular/src/webpack/configs/stats.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18908 fix(@angular-devkit/build-angular): implement `relative` method in extractor FS
  packages/angular_devkit/build_angular/src/extract-i18n/ivy-extract-loader.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18894 refactor(@angular-devkit/build-angular): remove redundant tslint vers…
  packages/angular_devkit/build_angular/src/tslint/index.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18912 refactor(@schematics/schematics): reduce type usage and imports
  packages/schematics/schematics/blank/factory.ts
  packages/schematics/schematics/schematic/factory.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18913 fix(@angular-devkit/build-angular): fixed Module.issuer is deprecated in webpack 5 for commonjs warn plugin
  packages/angular_devkit/build_angular/src/webpack/plugins/common-js-usage-warn-plugin.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18911 fix(@angular-devkit/build-angular): fixed afterOptimizeChunkAssets is deprecated in webpack 5
  packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18922 fix(@angular-devkit/build-angular): handle undefined descriptionFileData
  packages/angular_devkit/build_angular/src/webpack/plugins/dedupe-module-resolve-plugin.ts
  tests/legacy-cli/e2e/tests/build/ts-paths.ts
Labels: PR target: master-only, cla: yes

#18921 [PATCH] fix(@angular-devkit/build-angular): handle undefined descriptionFileData
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/dedupe-module-resolve-plugin.ts
  tests/legacy-cli/e2e/tests/build/ts-paths.ts
Labels: PR action: merge, PR target: patch-only, cla: yes

#18925 fix(@angular-devkit/build-angular): fix webpack 5 deprecation warning for chunk.push
  packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18915 fix(@angular-devkit/build-angular): fixes deprecation warning for MianTemplate.hooks.assetPath in webpack 5
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/remove-hash-plugin.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18914 fix(@angular-devkit/build-angular): fixes optimizeChunkAssets is deprecated in webpack 5
  packages/angular_devkit/build_angular/src/webpack/plugins/optimize-css-webpack-plugin.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18930 docs: fix incorrect number of test suites
  README.md
  scripts/templates/readme.ejs
Labels: PR action: merge, PR target: master-only, cla: yes

#18935 refactor(@angular-devkit/build-angular): change errors and warnings messages
  packages/angular/cli/models/schematic-command.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/browser/specs/browser-support_spec.ts
  packages/angular_devkit/build_angular/src/browser/specs/bundle-budgets_spec.ts
  packages/angular_devkit/build_angular/src/browser/specs/common-js-warning_spec.ts
  packages/angular_devkit/build_angular/src/browser/specs/web-worker_spec.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/server/index.ts
  packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
  packages/ngtools/webpack/src/type_checker.ts
  tests/legacy-cli/e2e/tests/build/bundle-budgets.ts
  tests/legacy-cli/e2e/tests/build/rebuild-deps-type-check.ts
  tests/legacy-cli/e2e/tests/misc/circular-dependency.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18934 fix(@angular-devkit/build-angular): don't process stylesheets in extraction builder
  packages/angular_devkit/build_angular/src/extract-i18n/empty-export-default.js
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18931 feat(@schematics/angular): don't generate special `package.json` and `no-any` when using `--strict`
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/application/other-files/package.json.template
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/ng-new/schema.json
  packages/schematics/angular/workspace/files/tslint.json.template
  packages/schematics/angular/workspace/index_spec.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18943 ci: disable lint check in the update test
  tests/legacy-cli/e2e/tests/update/update-7.0.ts
Labels: PR target: master-only, cla: yes
