Repository angular/angular-cli, pull requests merged in 2020-02, with the labels that each got.

#16810 fix(@angular-devkit/build-angular): add crossorigin attribute to lazy…
  packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
  packages/angular_devkit/build_angular/test/browser/cross-origin_spec_large.ts
Labels: PR action: merge, PR target: LTS-only, PR target: master & patch, cla: yes

#16807 fix(@schematics/angular): resolve windows paths in tsconfig migration
  packages/schematics/angular/migrations/update-9/update-app-tsconfigs.ts
  packages/schematics/angular/migrations/update-9/update-app-tsconfigs_spec.ts
  packages/schematics/angular/migrations/update-9/update-workspace-config_spec.ts
  packages/schematics/angular/migrations/update-9/utils.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16827 build: update latest-versions for rc.14
  packages/schematics/angular/utility/latest-versions.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16817 fix(@angular-devkit/build-angular): use translation file in bundle hash calculations
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-hashes.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16823 refactor(@angular-devkit/build-angular): remove redundant ES2015 string polyfills
  packages/angular_devkit/build_angular/src/angular-cli-files/models/es5-polyfills.js
Labels: PR action: merge, PR target: master & patch, cla: yes

#16826 fix: remove alias for ng doc command
  packages/angular/cli/commands/doc.json
Labels: PR action: merge, PR target: LTS-only, cla: yes

#16829 fix(@angular-devkit/build-angular): provide supported browsers to babel
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/build-browser-features.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR action: merge, PR target: LTS-only, PR target: master & patch, cla: yes

#16830 [LTS] fix(@angular-devkit/build-angular): provide supported browsers to babel
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/build-browser-features.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR action: merge, PR target: LTS-only, cla: yes

#16834 ci: update pako version
  scripts/validate-licenses.ts
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#16833 revert: "build: update @angular/animations to version 9.0.0-rc.14"
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_ng_packagr/package.json
  packages/ngtools/webpack/package.json
  tests/legacy-cli/e2e/ng-snapshot/package.json
  yarn.lock
Labels: PR action: merge, PR target: patch-only, cla: yes

#16822 fix(@ngtools/webpack): don't elide imports for type references that …
  packages/ngtools/webpack/src/transformers/ast_helpers.ts
  packages/ngtools/webpack/src/transformers/elide_imports.ts
  packages/ngtools/webpack/src/transformers/elide_imports_spec.ts
  packages/ngtools/webpack/src/transformers/make_transform.ts
  packages/ngtools/webpack/src/transformers/remove_decorators_spec.ts
  packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16299 feat(@schematics/angular): add opt-in option for 'display: block;'
  packages/angular/cli/lib/config/schema.json
  packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.__style__.template
  packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
  packages/schematics/angular/component/index_spec.ts
  packages/schematics/angular/component/schema.json
Labels: PR action: merge, PR target: master-only, cla: yes

#16842 [8.3.x] Update browserslist & caniuse-lite
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR action: merge, PR target: LTS-only, cla: yes

#16846 fix(@angular/cli): change the url for doc search
  packages/angular/cli/commands/doc-impl.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16852 fix(@angular-devkit/build-angular): resolve webdriver-manager from protractor location
  packages/angular_devkit/build_angular/src/protractor/index.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16859 fix(@ngtools/webpack): only load test helpers on tests
  packages/ngtools/webpack/src/transformers/ast_helpers.ts
  packages/ngtools/webpack/src/transformers/ctor-parameters_spec.ts
  packages/ngtools/webpack/src/transformers/elide_imports_spec.ts
  packages/ngtools/webpack/src/transformers/export_lazy_module_map_spec.ts
  packages/ngtools/webpack/src/transformers/export_ngfactory_spec.ts
  packages/ngtools/webpack/src/transformers/import_factory_spec.ts
  packages/ngtools/webpack/src/transformers/multiple_transformers_spec.ts
  packages/ngtools/webpack/src/transformers/register_locale_data_spec.ts
  packages/ngtools/webpack/src/transformers/remove-ivy-jit-support-calls_spec.ts
  packages/ngtools/webpack/src/transformers/remove_decorators_spec.ts
  packages/ngtools/webpack/src/transformers/replace_bootstrap_spec.ts
  packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
  packages/ngtools/webpack/src/transformers/replace_server_bootstrap_spec.ts
  packages/ngtools/webpack/src/transformers/spec_helpers.ts
Labels: PR target: master & patch, cla: yes

#16861 fix(@ngtools/webpack): only load test helpers on tests
  packages/ngtools/webpack/src/transformers/ast_helpers.ts
  packages/ngtools/webpack/src/transformers/ctor-parameters_spec.ts
  packages/ngtools/webpack/src/transformers/elide_imports_spec.ts
  packages/ngtools/webpack/src/transformers/export_lazy_module_map_spec.ts
  packages/ngtools/webpack/src/transformers/export_ngfactory_spec.ts
  packages/ngtools/webpack/src/transformers/import_factory_spec.ts
  packages/ngtools/webpack/src/transformers/multiple_transformers_spec.ts
  packages/ngtools/webpack/src/transformers/register_locale_data_spec.ts
  packages/ngtools/webpack/src/transformers/remove-ivy-jit-support-calls_spec.ts
  packages/ngtools/webpack/src/transformers/remove_decorators_spec.ts
  packages/ngtools/webpack/src/transformers/replace_bootstrap_spec.ts
  packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
  packages/ngtools/webpack/src/transformers/replace_server_bootstrap_spec.ts
  packages/ngtools/webpack/src/transformers/spec_helpers.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#16856 fix(@angular/cli): fix the URL for doc search
  packages/angular/cli/commands/doc-impl.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16839 fix(@angular-devkit/core): Rename to a non-existing dir
  packages/angular_devkit/core/node/host.ts
  packages/angular_devkit/core/node/host_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16892 fix(@angular/cli): added clarity on angular cli version issues
  packages/angular/cli/commands/update-impl.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16878 fix(@angular-devkit/build-angular): wrong budgets
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/bundle-calculator.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16936 fix(@angular/cli): expand locale pattern in workspace schema
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/core/src/experimental/workspace/workspace-schema.json
Labels: PR action: merge, PR target: master & patch, cla: yes

#16926 fix(@angular/cli): typo in error message
  packages/angular/cli/bin/ng
Labels: PR action: merge, PR target: master & patch, cla: yes

#16925 fix(@angular-devkit/build-angular): only remove localize polyfill if in AOT mode
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16924 fix(@schematics/angular): migrate spec and styleext schematic options
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-9/schematic-options.ts
  packages/schematics/angular/migrations/update-9/schematic-options_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16850 build: update to 9.0.0 final
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_ng_packagr/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  tests/legacy-cli/e2e/assets/webpack/test-app-weird/package.json
  tests/legacy-cli/e2e/assets/webpack/test-app/package.json
  tests/legacy-cli/e2e/assets/webpack/test-server-app/package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#16853 Patch version of https://github.com/angular/angular-cli/pull/16850
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_ng_packagr/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  tests/legacy-cli/e2e/assets/webpack/test-app-weird/package.json
  tests/legacy-cli/e2e/assets/webpack/test-app/package.json
  tests/legacy-cli/e2e/assets/webpack/test-server-app/package.json
  yarn.lock
Labels: PR action: merge, PR target: patch-only, cla: yes

#16953 Add skipTests to @schematics/angular:component
  packages/angular/cli/lib/config/schema.json
Labels: PR action: merge, PR target: master & patch, cla: yes, comp: angular/cli

#16942 fix(@schematics/angular) remove file extension from zone flags comment
  packages/schematics/angular/application/files/src/polyfills.ts.template
Labels: PR action: merge, PR target: master & patch, cla: yes

#16939 fix(@schematics/angular): add include to type definitions in tsconfig
  packages/schematics/angular/migrations/update-9/update-app-tsconfigs.ts
  packages/schematics/angular/migrations/update-9/update-app-tsconfigs_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16938 fix(@angular-devkit/build-angular): provide explicit return type for extract-i18n builder
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16937 fix(@angular-devkit/build-angular): generate correct filenames when targeting ESNext
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/utils.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/action-cache.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
  packages/angular_devkit/build_angular/test/browser/differential_loading_spec_large.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16959 fix(@angular-devkit/build-angular): insert sourcemap source content when using fast path
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16734 Correctly prints the size of the chunk during the build statistic print
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16993 test(@schematics/angular): fix component schematic tests on Windows
  packages/schematics/angular/component/index_spec.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#16894 feat(@angular-devkit/build-angular): pass "grep" and "invertGrep"
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/protractor/index.ts
  packages/angular_devkit/build_angular/src/protractor/schema.json
  packages/angular_devkit/build_angular/test/protractor/works_spec_large.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#16973 fix(@angular/cli): print `ng update` errors stack to log file
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/lib/cli/index.ts
  packages/angular/cli/utilities/log-file.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16978 fix(@angular-devkit/build-angular): limit CPUs used by terser-webpack…
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16992 fix(@ngtools/webpack): add local dts file as dependencies
  packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16988 fix(@angular/cli): set inlineTemplate and inlineStyle for minimal projects
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/index_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16990 docs: update test case description
  packages/schematics/angular/migrations/update-9/update-workspace-config_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17003 fix(@schematics/angular): scroll issue on new app after adding Material
  packages/schematics/angular/application/other-files/app.component.html.template
Labels: PR action: merge, PR target: master & patch, cla: yes

#16967 refactor(@angular-devkit/build-angular): use localize babel plugins directly
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-es2015.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-es5.ts
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#16995 fix(@ngtools/webpack): elide imports for `implements` keywords
  packages/ngtools/webpack/src/transformers/elide_imports.ts
  packages/ngtools/webpack/src/transformers/elide_imports_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17043 build: update tslib to 1.11.0
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/src/transformers/spec_helpers.ts
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#17059 fix(@angular-devkit/build-angular): update core-js to 3.6.4
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR action: merge, PR target: patch-only, cla: yes

#17055 fix(@angular/cli): directly remove ansi color codes when no color support
  packages/angular/cli/lib/cli/index.ts
  packages/angular/cli/utilities/color.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17033 fix(@angular/cli): expanded locale pattern in workspace schema for lo…
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/server/schema.json
  packages/angular_devkit/core/src/experimental/workspace/workspace-schema.json
Labels: PR action: merge, PR target: master & patch, cla: yes

#17030 fix(@angular-devkit/build-angular): baseHref with protocol and localize option
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/index.ts
  packages/angular_devkit/build_angular/src/utils/url.ts
  packages/angular_devkit/build_angular/src/utils/url_spec.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-basehref.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#16816 multiple files: fix typos
  docs/documentation/stories/create-library.md
  docs/process/release.md
  packages/angular/cli/README.md
  packages/angular_devkit/core/src/experimental/jobs/architecture.md
Labels: PR action: merge, PR target: master & patch, cla: yes

#17045 fix(@angular-devkit/build-angular): fix autoprefixer comments support in scss
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
  packages/angular_devkit/build_angular/test/browser/styles_spec_large.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17077 fix(@ngtools/webpack): handle union type with a nullable argument
  packages/ngtools/webpack/src/transformers/ctor-parameters.ts
  packages/ngtools/webpack/src/transformers/ctor-parameters_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17075 fix(@angular/pwa): use relative paths in webmanifest
  packages/angular/pwa/pwa/files/root/manifest.webmanifest
Labels: PR action: merge, PR target: master & patch, cla: yes

#17071 fix(@angular-devkit/schematics-cli): provide resolvePaths to NodeWorkflow
  packages/angular_devkit/schematics_cli/bin/schematics.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17028 fix(@angular-devkit/build-angular): limit the amount of CPUs used by workers
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/utils/action-executor.ts
  packages/angular_devkit/build_angular/src/utils/index.ts
  packages/angular_devkit/build_angular/src/utils/workers.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17086 fix(@ngtools/webpack): always use VE for deprecated string route discovery
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17083 fix(@ngtools/webpack): don't elide decorated method parameter type reference
  packages/ngtools/webpack/src/transformers/elide_imports.ts
  packages/ngtools/webpack/src/transformers/elide_imports_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17040 fix(@schematics/angular): Allow empty string in the type option
  packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.spec.ts.template
  packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
  packages/schematics/angular/component/index.ts
  packages/schematics/angular/component/index_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17094 fix(@angular-devkit/build-angular): allow function in filename while …
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17050 build: exclude redundant cherry-picked commits when generating changelog
  scripts/changelog.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#17102 feat(@schematics/angular): set quote_type = single in .editorconfig
  packages/schematics/angular/workspace/files/__dot__editorconfig.template
Labels: PR action: merge, PR target: master-only, cla: yes
