Repository angular/angular-cli, pull requests merged in 2020-05, with the labels that each got.

#17610 build: update several packages
  integration/angular_cli/package.json
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
  packages/angular_devkit/build_angular/src/karma/code-coverage_spec.ts
  packages/schematics/angular/workspace/files/package.json.template
  tests/legacy-cli/e2e/utils/project.ts
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#17361 feat(@schematics/angular): evergreen new applications
  packages/angular_devkit/build_angular/src/utils/build-browser-features_spec.ts
  packages/schematics/angular/application/files/.browserslistrc.template
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/ng-new/index.ts
  packages/schematics/angular/ng-new/schema.json
  tests/legacy-cli/e2e/tests/basic/aot.ts
  tests/legacy-cli/e2e/tests/basic/build.ts
  tests/legacy-cli/e2e/tests/basic/scripts-array.ts
  tests/legacy-cli/e2e/tests/basic/styles-array.ts
  tests/legacy-cli/e2e/tests/build/css-urls.ts
  tests/legacy-cli/e2e/tests/build/deploy-url.ts
  tests/legacy-cli/e2e/tests/build/differential-cache.ts
  tests/legacy-cli/e2e/tests/build/differential-loading.ts
  tests/legacy-cli/e2e/tests/build/dynamic-import.ts
  tests/legacy-cli/e2e/tests/build/environment.ts
  tests/legacy-cli/e2e/tests/build/extract-licenses.ts
  tests/legacy-cli/e2e/tests/build/json.ts
  tests/legacy-cli/e2e/tests/build/multiple-configs.ts
  tests/legacy-cli/e2e/tests/build/no-sourcemap.ts
  tests/legacy-cli/e2e/tests/build/output-dir.ts
  tests/legacy-cli/e2e/tests/build/output-hashing.ts
  tests/legacy-cli/e2e/tests/build/polyfills.ts
  tests/legacy-cli/e2e/tests/build/prod-build.ts
  tests/legacy-cli/e2e/tests/build/profile.ts
  tests/legacy-cli/e2e/tests/build/script-target.ts
  tests/legacy-cli/e2e/tests/build/sourcemap.ts
  tests/legacy-cli/e2e/tests/build/styles/extract-css.ts
  tests/legacy-cli/e2e/tests/build/styles/imports.ts
  tests/legacy-cli/e2e/tests/build/styles/include-paths.ts
  tests/legacy-cli/e2e/tests/build/styles/less.ts
  tests/legacy-cli/e2e/tests/build/styles/node-sass.ts
  tests/legacy-cli/e2e/tests/build/styles/scss.ts
  tests/legacy-cli/e2e/tests/build/styles/stylus.ts
  tests/legacy-cli/e2e/tests/build/vendor-chunk.ts
  tests/legacy-cli/e2e/tests/build/worker.ts
  tests/legacy-cli/e2e/tests/i18n/build-locale.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl-xliff2.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-hashes.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-sourcelocale.ts
  tests/legacy-cli/e2e/tests/i18n/legacy.ts
  tests/legacy-cli/e2e/tests/misc/browsers.ts
  tests/legacy-cli/e2e/tests/misc/forwardref-es2015.ts
  tests/legacy-cli/e2e/tests/misc/lazy-module.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#17612 refactor(@angular-devkit/build-angular): remove unused rxjs path mapping
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#17615 fix(@angular/cli): allow configuration option in `ng deploy`
  packages/angular/cli/commands/deploy.json
Labels: PR action: merge, PR target: master & patch, cla: yes

#17607 fix(@angular-devkit/build-angular): update worker-plugin
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_ng_packagr/package.json
  packages/ngtools/webpack/package.json
  yarn.lock
Labels: PR action: merge, PR target: patch-only, cla: yes

#17609 ci: disable ngcc async
  package.json
Labels: PR action: merge, PR target: master-only, cla: yes

#17632 [PATCH] fix(@schematics/angular): don't add `@angular/language-service` in new Angular projects
  packages/schematics/angular/workspace/files/package.json.template
Labels: PR action: merge, PR target: patch-only, cla: yes

#17636 refactor(@ngtools/webpack): remove deprecated isSupported method
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#17631 fix(@schematics/angular): don't add `@angular/language-service` in new Angular projects
  integration/angular_cli/package.json
  packages/schematics/angular/workspace/files/package.json.template
Labels: PR action: merge, PR target: master-only, cla: yes

#17611 fix(@ngtools/webpack): only emit import default helper when needed
  packages/ngtools/webpack/src/transformers/replace_resources.ts
  packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17649 fix(@ngtools/webpack): don't emit unused file warning for`.ngtypecheck.ts`
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#17644 refactor(@angular-devkit/build-angular): support ES5 target with ES2015 APF
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#17643 refactor(@angular/cli): exclude .yarn directory
  .idea/angular-cli.iml
Labels: PR action: merge, PR target: master-only, cla: yes

#17641 ci: exclude private packages from consideration for license checking
  scripts/validate-licenses.ts
Labels: PR action: merge, PR target: master & patch, cla: yes, comp: etc/misc

#17637 feat(@schematics/angular): update compiler options target and module settings
  integration/angular_cli/e2e/tsconfig.json
  integration/angular_cli/tsconfig.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/bundle-calculator.ts
  packages/angular_devkit/build_angular/test/hello-world-app/e2e/tsconfig.e2e.json
  packages/angular_devkit/build_angular/test/hello-world-app/tsconfig.json
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/tsconfig.json
  packages/angular_devkit/build_webpack/test/angular-app/src/tsconfig.app.json
  packages/schematics/angular/e2e/files/tsconfig.json.template
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-10/update-module-and-target-compiler-options.ts
  packages/schematics/angular/migrations/update-10/update-module-and-target-compiler-options_spec.ts
  packages/schematics/angular/workspace/files/tsconfig.json.template
  tests/legacy-cli/e2e/assets/1.7-project/e2e/tsconfig.e2e.json
  tests/legacy-cli/e2e/assets/7.0-project/e2e/tsconfig.e2e.json
Labels: PR action: merge, PR target: master-only, cla: yes

#17635 refactor(@schematic/angular): remove deprecated options from app-shell and universal schematics
  packages/schematics/angular/app-shell/index.ts
  packages/schematics/angular/app-shell/index_spec.ts
  packages/schematics/angular/app-shell/schema.json
  packages/schematics/angular/universal/schema.json
Labels: PR action: merge, PR target: master-only, cla: yes

#17625 fix(@angular-devkit/build-angular): downlevel and optimize locale data
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl-xliff2.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#17661 refactor(@angular/cli): remove deprecated typescriptMismatch
  packages/angular/cli/commands/config-impl.ts
  packages/angular/cli/lib/config/schema.json
  packages/angular/cli/models/command-runner.ts
  packages/schematics/angular/migrations/update-10/update-angular-config.ts
  packages/schematics/angular/migrations/update-10/update-angular-config_spec.ts
  packages/schematics/angular/utility/config.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#17658 refactor(@angular/cli): remove deprecated get/set commands
  packages/angular/cli/BUILD.bazel
  packages/angular/cli/commands.json
  packages/angular/cli/commands/deprecated-impl.ts
  packages/angular/cli/commands/deprecated.json
  packages/angular/cli/models/command-runner.ts
  tests/legacy-cli/e2e/tests/commands/config/get-set-deprecation.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#17648 ci: add 0BSD as a valid license
  scripts/validate-licenses.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17664 test: update third-party decorators E2E to use latest package versions
  tests/legacy-cli/e2e/tests/misc/third-party-decorators.ts
Labels: PR target: master-only, cla: yes

#17675 ci: Use node v10.20 for node v10 e2e test
  .circleci/config.yml
Labels: PR target: master-only, cla: yes

#17671 revert: "ci: disable ngcc async"
  package.json
Labels: PR target: master-only, cla: yes

#17668 build: generate project using karma-coverage-istanbul-reporter version 3.0.2
  packages/schematics/angular/workspace/files/package.json.template
Labels: PR action: merge, PR target: master-only, cla: yes

#17692 fix(@ngtools/webpack): getCanonicalFileName should return FS compatible paths
  packages/ngtools/webpack/src/compiler_host.ts
  packages/ngtools/webpack/src/utils.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17715 build: use @bazel/bazelisk rather than @bazel/bazel
  WORKSPACE
  package.json
  yarn.lock
Labels: PR action: merge, PR target: master & patch, cla: yes, comp: etc/misc

#17699 docs: add primary-secondary pairs and update calendar link
  docs/process/release.md
Labels: PR action: merge, PR target: master-only, cla: yes

#17732 fix(@angular-devkit/build-angular): add link when displaying commonJS usage warnings
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/common-js-usage-warn-plugin.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#17749 fix(@angular-devkit/build-angular): downlevel and optimize locale data
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl-xliff2.ts
Labels: PR action: merge, PR target: patch-only, cla: yes

#17762 fix(@schematics/angular): add migration to ensure tslint deprecation rule
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-10/add-deprecation-rule-tslint.ts
  packages/schematics/angular/migrations/update-10/add-deprecation-rule-tslint_spec.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#17763 ci: schedule daily CI for branch 9.1.x
  .circleci/config.yml
Labels: PR action: merge, PR target: patch-only, cla: yes

#17761 fix(@schematics/angular): add tslib as a direct dependency for new libraries
  packages/schematics/angular/library/files/package.json.template
Labels: PR action: merge, PR target: patch-only, cla: yes

#17774 test: change dedupe-duplicate-modules test to work on windows
  tests/legacy-cli/e2e/tests/misc/debupe-duplicate-modules.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#17799 test: make CoreSchemaRegistry test green again
  packages/angular_devkit/core/src/json/schema/registry.ts
  packages/angular_devkit/core/src/json/schema/registry_spec.ts
Labels: PR action: merge, PR target: lts-only, cla: yes

#17800 test: make CoreSchemaRegistry test green again
  packages/angular_devkit/core/src/json/schema/registry.ts
  packages/angular_devkit/core/src/json/schema/registry_spec.ts
Labels: PR action: merge, PR target: lts-only, cla: yes

#17798 test: make CoreSchemaRegistry test green again
  packages/angular_devkit/core/src/json/schema/registry.ts
  packages/angular_devkit/core/src/json/schema/registry_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17793 fix(@schematics/angular): remove node typings from tsconfig.spec.json
  integration/angular_cli/tsconfig.spec.json
  packages/angular_devkit/build_angular/test/hello-world-app/src/tsconfig.spec.json
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/tsconfig.spec.json
  packages/schematics/angular/application/files/tsconfig.spec.json.template
  packages/schematics/angular/library/files/tsconfig.spec.json.template
Labels: PR action: merge, PR target: master & patch, cla: yes

#17802 refactor(@angular-devkit/build-angular): mention how to disable the w…
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/common-js-usage-warn-plugin.ts
  packages/angular_devkit/build_angular/src/browser/specs/common-js-warning_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes
