Repository angular/angular-cli, pull requests merged in 2020-04, with the labels that each got.

#17358 fix(@angular/cli): downgrade pacote to 9.5.12
  package.json
  packages/angular/cli/package.json
  packages/schematics/update/package.json
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#17359 fix(@angular/cli): downgrade pacote to 9.5.12
  package.json
  packages/angular/cli/package.json
  packages/schematics/update/package.json
  yarn.lock
Labels: PR action: merge, PR target: patch-only, cla: yes

#17383 ci: disable separate renovate PRs for devDependencies and dependencies
  renovate.json
Labels: PR action: merge, PR target: master-only, cla: yes

#17386 fix(@angular/pwa): add purpose any to manifest icons
  packages/angular/pwa/pwa/files/root/manifest.webmanifest
Labels: PR action: merge, PR target: master & patch, cla: yes

#17389 fix(@angular-devkiit/build-angular): avoid overwriting localize sourcemaps
  packages/angular_devkit/build_angular/src/browser/index.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17404 feat(@angular-devkit/build-angular): provide webpack support for resolving via Yarn PnP
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#17413 fix(@schematics/angular): invalid rgba color in app.component.html
  packages/schematics/angular/application/other-files/app.component.html.template
Labels: PR action: merge, PR target: master & patch, cla: yes

#17406 build: default to wombat proxy for publishing
  docs/process/release.md
  scripts/publish.ts
Labels: PR action: merge, PR target: master & patch, cla: yes, comp: etc/misc

#17306 Schedule daily CI for LTS branch 8.3.x
  .circleci/config.yml
Labels: PR action: merge, PR target: lts-only, cla: yes

#17424 build: version from git tag which consists two or more digits
  lib/packages.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#17431 fix(@angular-devkit/build-angular): retain css declarations order when using `extractCss` and `@import` rule
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/raw-css-loader.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/webpack.ts
  packages/angular_devkit/build_angular/test/browser/styles_spec_large.ts
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#17441 fix(@ngtools/webpack): give higher priority to ivy-specific entry-points
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17436 [patch] fix(@angular-devkit/build-angular): retain css declarations order whe…
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/raw-css-loader.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/webpack.ts
  packages/angular_devkit/build_angular/test/browser/styles_spec_large.ts
  yarn.lock
Labels: PR action: merge, PR target: patch-only, cla: yes

#17456 feat(@schematics/angular): update karma to 5.0.0
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-10/update-dependencies.ts
  packages/schematics/angular/workspace/files/package.json.template
Labels: PR action: merge, PR target: master-only, cla: yes

#17457 test: update ng-packagr tests tsconfig as per CLI default
  tests/angular_devkit/build_ng_packagr/ng-packaged-ve/tsconfig.json
  tests/angular_devkit/build_ng_packagr/ng-packaged/tsconfig.json
Labels: PR action: merge, PR target: master & patch, cla: yes

#17463 fix(@angular/cli): ensure Node.js message is shown on old Node.js versions
  packages/angular/cli/bin/ng
Labels: PR action: merge, PR target: master & patch, cla: yes

#17461 build: update rxjs to version 6.5.5
  package.json
  packages/angular_devkit/architect/package.json
  packages/angular_devkit/architect_cli/package.json
  packages/angular_devkit/benchmark/package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_ng_packagr/package.json
  packages/angular_devkit/build_webpack/package.json
  packages/angular_devkit/core/package.json
  packages/angular_devkit/schematics/package.json
  packages/angular_devkit/schematics_cli/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/update/package.json
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#17515 fix(@angular-devkit/core): workspace reader spread/rest operator usage with falsy values
  packages/angular_devkit/core/src/workspace/json/reader_spec.ts
  packages/angular_devkit/core/src/workspace/json/utilities.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17496 docs: add notes about various release foot-guns
  docs/process/release.md
Labels: PR action: merge, PR target: master & patch, cla: yes, type: docs

#17525 fix(@schematics/angular): generate new projects with Karma v5
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/schematics/angular/workspace/files/package.json.template
  yarn.lock
Labels: PR target: patch-only, cla: yes

#17507 refactor(@angular-devkit/schematics): remove deprecated FileSystemHost
  etc/api/angular_devkit/schematics/tools/index.d.ts
  packages/angular_devkit/schematics/tools/file-system-host.ts
  packages/angular_devkit/schematics/tools/index.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#17508 refactor(@schematics/angular): remove deprecated guard `spec` option
  packages/schematics/angular/guard/index.ts
  packages/schematics/angular/guard/schema.json
  packages/schematics/angular/migrations/migration-collection.json
Labels: PR action: merge, PR target: master-only, cla: yes

#17535 docs: update analytics command aio link
  packages/angular/cli/commands/analytics.json
Labels: PR action: merge, PR target: master & patch, cla: yes

#17536 build: update to codelyzer@6.0.0-next.1
  packages/schematics/angular/workspace/files/package.json.template
Labels: PR action: merge, PR target: master-only, cla: yes

#17533 ci: remove circle ci cache fallback
  .circleci/config.yml
Labels: PR action: merge, PR target: master & patch, cla: yes

#17540 docs: remove `universal-project` options reference from app-shell docs
  packages/schematics/angular/app-shell/app-shell-long.md
Labels: PR action: merge, PR target: master & patch, cla: yes

#17554 build: fix typescript 3.9 compilation
  packages/angular_devkit/core/src/utils/object.ts
  packages/ngtools/webpack/src/compiler_host.ts
  packages/ngtools/webpack/src/transformers/replace_resources.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#17574 fix(@angular-devkit/build-angular): the path to `source_file_utils` changed in v10.0.0
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#17575 fix(@angular-devkit/build-angular): disable inline svg optimizations
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/optimize-css-webpack-plugin.ts
Labels: PR action: merge, PR target: master & patch, cla: yes
