Repository angular/angular-cli, pull requests merged in 2020-08, with the labels that each got.

#18412 build: update @types/webpack-sources to version ^1.4.2
  package.json
  packages/angular_devkit/build_angular/plugins/webpack/analytics.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/optimize-css-webpack-plugin.ts
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#18429 build: update terser to version 5.0.0
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#18431 perf(@angular-devkit/build-angular): lazy load several optional webpack plugins
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/worker.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/named-chunks-plugin.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18432 refactor(@angular/devkit-build-angular): simplify Webpack split chunks configuration
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18439 refactor: minor cleanup to common webpack configuration
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/find-up.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18445 ci: increase CircleCI no output timeout for bazel tests
  .circleci/config.yml
Labels: PR action: merge, PR target: master & patch, cla: yes

#18444 refactor(@angular-devkit/build-angular): cleanup Webpack rule generation
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/karma/index.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18438 fix(@angular-devkit/build-angular): don't use parent modules while deduping
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/dedupe-module-resolve-plugin.ts
  tests/legacy-cli/e2e/tests/misc/dedupe-duplicate-modules.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18451 build: update Angular packages to match prelease versions
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_ng_packagr/package.json
  packages/ngtools/webpack/package.json
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#18449 fix(@angular-devkit/schematics): set correct parent id in actions lists
  packages/angular_devkit/schematics/src/tree/action.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18454 test: fix dedupe tslint tests on Windows
  tests/legacy-cli/e2e/tests/misc/dedupe-duplicate-modules.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18159 refactor(@angular-devkit/build-angular): improve budget warning messages
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/bundle-calculator.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/bundle-calculator_spec.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18452 refactor(@angular-devkit/build-angular): use library output for stylesheet child compilations
  packages/ngtools/webpack/src/resource_loader.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18463 fix(@angular-devkit/build-angular): generate service worker manifest …
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/browser/specs/service-worker_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18455 ci: fix markdown typo
  docs/process/release.md
Labels: PR action: merge, PR target: master & patch, cla: yes

#18467 Improve compiler options migration error reporting
  packages/schematics/angular/migrations/update-10/add-deprecation-rule-tslint.ts
  packages/schematics/angular/migrations/update-10/update-module-and-target-compiler-options.ts
  packages/schematics/angular/migrations/update-10/update-tslint.ts
  packages/schematics/angular/utility/dependencies.ts
  packages/schematics/angular/utility/json-file.ts
  packages/schematics/angular/web-worker/index.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18483 refactor(@angular-devkit/build-angular) use webpack warnings instead …
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/dedupe-module-resolve-plugin.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18488 Fix relative paths with bundleDependencies=false
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18479 fix(@ngtools/webpack): issue warning when using `strictMetadataEmit`
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18380 ci: use ramdisk for E2E jobs
  .circleci/config.yml
Labels: PR action: merge, PR target: master-only, cla: yes

#18481 refactor(@angular-devkit/build-optimizer): verify Program for type-checking passes
  etc/api/angular_devkit/build_optimizer/src/_golden-api.d.ts
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
  packages/angular_devkit/build_optimizer/src/helpers/transform-javascript.ts
  packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18495 refactor(@angular-devkit/build-angular): simplify budgets `allEquivalent` method
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/bundle-calculator.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18506 refactor(@angular/cli): update CLI package to be strict compliant
  packages/angular/cli/commands/config-impl.ts
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/commands/xi18n-impl.ts
  packages/angular/cli/lib/cli/index.ts
  packages/angular/cli/models/architect-command.ts
  packages/angular/cli/models/schematic-command.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18507 refactor(@angular-devkit/build-angular): cleanup server webpack configuration
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18513 build: update karma-jasmine to version ~4.0.0
  packages/schematics/angular/migrations/update-10/update-dependencies.ts
  packages/schematics/angular/workspace/files/package.json.template
Labels: PR action: merge, PR target: master-only, cla: yes

#18502 fix(@angular-devkit/architect): add name of the non-existing project
  packages/angular_devkit/architect/node/node-modules-architect-host.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18508 feat(@angular-devkit/build-angular): support multiple translation files per locale
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/utils/i18n-options.ts
  packages/angular_devkit/build_angular/src/utils/load-translations.ts
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
  packages/angular_devkit/core/src/experimental/workspace/workspace-schema.json
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-merging.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18522 test: improve reliability of E2E local npm registry on CI
  package.json
  tests/legacy-cli/verdaccio.yaml
  yarn.lock
Labels: PR target: master & patch, cla: yes

#18529 fix(@angular-devkit/build-angular): don't log blank warnings in console
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
Labels: PR target: master & patch, cla: yes

#16203 fix(@schematics/angular): don't create e2e script when createApplication is false
  packages/schematics/angular/e2e/index.ts
  packages/schematics/angular/e2e/index_spec.ts
  packages/schematics/angular/workspace/files/package.json.template
Labels: PR action: merge, PR target: master-only, cla: yes

#18528 fix(@angular-devkit/build-angular): don't warn on transitive CommonJS dependencies in AOT mode
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/common-js-usage-warn-plugin.ts
  packages/angular_devkit/build_angular/src/browser/specs/common-js-warning_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18549 perf(@angular-devkit/core): avoid RxJS performance penalty in sync fs calls
  packages/angular_devkit/core/src/virtual-fs/host/sync.ts
Labels: PR action: merge, PR target: master & patch, cla: yes, comp: devkit/core, severity4: memory/performance, type: bug/fix

#18535 refactor(@angular/cli): replace experimental workspace API with stable API
  packages/angular/cli/commands/config-impl.ts
  packages/angular/cli/utilities/config.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18553 fix(@angular-devkit/schematics-cli): use workflow to list schematics
  packages/angular_devkit/schematics_cli/bin/schematics.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18544 refactor: remove old excludes and paths from repo tsconfig
  tsconfig.json
Labels: PR action: merge, PR target: master-only, cla: yes

#18557 test: fix multiple configs e2e test
  tests/legacy-cli/e2e/tests/build/multiple-configs.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18559 feat(@schematics/angular): add `strictInputAccessModifiers` option when using strict mode
  packages/schematics/angular/workspace/files/tsconfig.json.template
Labels: PR action: merge, PR target: master-only, cla: yes

#18542 refactor(@angular-devkit/core): remove any types
  packages/angular_devkit/core/node/experimental/jobs/job-registry.ts
  packages/angular_devkit/core/src/experimental/jobs/api.ts
  packages/angular_devkit/core/src/json/schema/interface.ts
  packages/angular_devkit/core/src/json/schema/registry.ts
  packages/angular_devkit/core/src/json/schema/schema.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18565 refactor(@angular/pwa): minor cleanup to PWA schematic
  packages/angular/pwa/pwa/index.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18572 refactor(@schematics/update): remove direct rxjs dependency
  packages/schematics/update/BUILD.bazel
  packages/schematics/update/migrate/index_spec.ts
  packages/schematics/update/package.json
  packages/schematics/update/update/index.ts
  packages/schematics/update/update/index_spec.ts
  packages/schematics/update/update/npm.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18582 fix(@angular-devkit/core): strict typings for json, logger, and virtual-fs
  etc/api/angular_devkit/core/src/_golden-api.d.ts
  packages/angular_devkit/core/src/json/schema/registry.ts
  packages/angular_devkit/core/src/logger/logger.ts
  packages/angular_devkit/core/src/virtual-fs/host/buffer.ts
  packages/angular_devkit/core/src/virtual-fs/host/test.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18597 fix(@schematics/schematics): run install step with sample schematics
  packages/schematics/schematics/schematic/factory.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18607 fix(@angular-devkit/build-angular): handle base tag endOffset in inde…
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/augment-index-html.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/augment-index-html_spec.ts
  packages/angular_devkit/build_angular/src/browser/specs/service-worker_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18624 refactor(@schematics/angular): rename guard param of generated file
  packages/schematics/angular/guard/files/__name@dasherize__.guard.ts.template
Labels: PR action: merge, PR target: master-only, cla: yes

#18611 feat(@angular-devkit/architect): support async generator based builders
  etc/api/angular_devkit/architect/src/index.d.ts
  packages/angular_devkit/architect/src/api.ts
  packages/angular_devkit/architect/src/create-builder.ts
  packages/angular_devkit/architect/src/index_spec.ts
Labels: PR target: master-only, cla: yes

#18613 feat(@angular-devkit/build-angular): allow transformation of i18n extraction builder configuration
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18623 refactor(@angular-devkit/build-optimizer): refactor scrub file to use…
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
  packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts
  packages/angular_devkit/build_optimizer/src/transforms/scrub-file_spec.ts
Labels: PR target: master-only, cla: yes

#18632 build: update less-loader to version 7.0.0
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#18635 feat(@schematics/angular): add migration to replace deprecated library builder
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-11/replace-ng-packagr-builder.ts
  packages/schematics/angular/migrations/update-11/replace-ng-packagr-builder_spec.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18637 refactor(@angular-devkit/schematics): remove internal use of isAction helper
  packages/angular_devkit/schematics/src/sink/sink.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18634 build: update webpack-merge to version 5.1.2
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#18641 feat(@angular-devkit/build-angular): ask to use a new port if in use
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/check-port.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/tty.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18640 fix(@angular-devkit/build-angular): ensure ivy extraction file names match sourcemaps
  packages/angular_devkit/build_angular/src/extract-i18n/ivy-extract-loader.ts
  tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18639 build: bump to lastest sha of angular/dev-infra's lock-closed action
  .github/workflows/lock-closed.yml
Labels: PR action: merge, PR target: master & patch, cla: yes, comp: build & ci

#18661 refactor(@schematics/angular): change the order of node types in package.json template
  packages/schematics/angular/workspace/files/package.json.template
Labels: PR action: merge, PR target: master-only, cla: yes

#18647 docs: update `fileReplacements` description
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/karma/schema.json
  packages/angular_devkit/build_angular/src/server/schema.json
Labels: PR action: merge, PR target: master & patch, cla: yes

#18650 fix(@angular-devkit/build-angular): correct Windows paths in ivy i18n extract
  .circleci/config.yml
  packages/angular_devkit/build_angular/src/extract-i18n/ivy-extract-loader.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18657 fix(@angular-devkit/core): allow property remove with workspace API
  packages/angular_devkit/core/src/workspace/json/test/cases/ObjectRemove.json
  packages/angular_devkit/core/src/workspace/json/test/cases/ObjectRemoveMultiple.json
  packages/angular_devkit/core/src/workspace/json/utilities.ts
  packages/angular_devkit/core/src/workspace/json/writer_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes
