Repository angular/angular-cli, pull requests merged in 2020-10, with the labels that each got.

#18942 refactor(@angular-devkit/schematics-cli): remove unused rxjs dependency
  packages/angular_devkit/schematics_cli/BUILD.bazel
  packages/angular_devkit/schematics_cli/package.json
Labels: PR action: merge, PR target: master-only, cla: yes

#18950 refactor(@schematics/angular): display Stylus documentation url with HTTPS
  packages/schematics/angular/application/schema.json
Labels: PR action: merge, PR target: master-only, cla: yes

#18940 refactor(@angular/cli): discover/load workspace on startup
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/commands/version-impl.ts
  packages/angular/cli/lib/cli/index.ts
  packages/angular/cli/models/architect-command.ts
  packages/angular/cli/models/command-runner.ts
  packages/angular/cli/models/command.ts
  packages/angular/cli/models/interface.ts
  packages/angular/cli/models/schematic-command.ts
  packages/angular/cli/utilities/config.ts
  packages/angular/cli/utilities/project.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18957 fix(@schematics/angular) remove reference to IE10 in comment
  packages/schematics/angular/application/files/src/polyfills.ts.template
Labels: PR action: merge, PR target: master-only, cla: yes

#18958 refactor(@angular/cli): use new NodeWorkflow schematic features
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/models/schematic-command.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18967 test: use tslint directly to lint repository
  package.json
  scripts/README.md
  scripts/lint.ts
Labels: PR target: master-only, cla: yes

#18971 fix(@angular/cli): add blank line in migration commit message
  packages/angular/cli/commands/update-impl.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#18987 test(@angular/cli): disable Webpack 5 e2e tests
  tests/legacy-cli/e2e/tests/misc/webpack-5.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18982 fix(@angular/cli): collect analytics option usage from workspace config and prompts
  packages/angular/cli/commands/build-impl.ts
  packages/angular/cli/commands/deploy-impl.ts
  packages/angular/cli/commands/generate-impl.ts
  packages/angular/cli/commands/serve-impl.ts
  packages/angular/cli/models/architect-command.ts
  packages/angular/cli/models/command.ts
  packages/angular/cli/models/schematic-command.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18993 build: use @angular/dev-infra-private for bazel stamping
  .bazelrc
Labels: PR action: merge, PR target: master-only, cla: yes

#18995 fix(@angular-devkit/core): remove deprecated isObservable function
  etc/api/angular_devkit/core/src/_golden-api.d.ts
  packages/angular_devkit/core/src/utils/lang.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18994 refactor(@angular-devkit/build-angular): additional webpack 5 type improvements
  packages/angular_devkit/build_angular/src/webpack/plugins/common-js-usage-warn-plugin.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/optimize-css-webpack-plugin.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18959 build: configure dependabot updates
  .github/dependabot.yml
Labels: PR action: merge, PR target: master & patch, cla: yes, comp: build & ci

#18996 refactor(@angular-devkit/build-angular): remove unneeded 10.1 localize checks
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
  tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#18999 build: add required fields to dependabot configuration
  .github/dependabot.yml
Labels: PR target: master-only, cla: yes

#18998 build: delete @angular-devkit/build-ng-packagr
  CONTRIBUTING.md
  README.md
  packages/angular_devkit/build_ng_packagr/BUILD.bazel
  packages/angular_devkit/build_ng_packagr/README.md
  packages/angular_devkit/build_ng_packagr/builders.json
  packages/angular_devkit/build_ng_packagr/package.json
  packages/angular_devkit/build_ng_packagr/src/build/index.ts
  packages/angular_devkit/build_ng_packagr/src/build/index_spec.ts
  packages/angular_devkit/build_ng_packagr/src/build/schema.json
  packages/angular_devkit/build_ng_packagr/src/index.ts
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/.gitignore
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/angular.json
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/karma.conf.js
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/ng-package.json
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/package.json
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/src/lib/lib.component.spec.ts
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/src/lib/lib.component.ts
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/src/lib/lib.module.ts
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/src/lib/lib.service.spec.ts
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/src/lib/lib.service.ts
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/src/public-api.ts
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/src/test.ts
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/tsconfig.lib.json
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/tsconfig.lib.prod.json
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/tsconfig.spec.json
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/tsconfig.json
  packages/angular_devkit/build_ng_packagr/test/ng-packaged/tslint.json
Labels: PR action: merge, PR target: master-only, cla: yes

#18997 docs(@angular-devkit/build-ng-packagr): Add deprecation message
  packages/angular_devkit/build_ng_packagr/README.md
Labels: PR action: merge, PR target: patch-only, cla: yes

#19010 test(@angular-devkit/build-angular): re-enable ivy extract test on Windows
  tests/legacy-cli/e2e/tests/i18n/extract-ivy-libraries.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19011 refactor(@angular-devkit/build-angular): remove RxJs usage from `writeIndexHtml`
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/index-file/write-index-html.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19020 refactor(@angular-devkit/build-optimizer): remove old checks
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19021 fix(@angular-devkit/build-angular): use IE11 as oldest browser when downlevelling
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19041 Revert "test(@angular/cli): disable Webpack 5 e2e tests"
  tests/legacy-cli/e2e/tests/misc/webpack-5.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19015 feat(@angular-devkit/build-angular): support custom headers in dev-server
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/dev-server/schema.json
  packages/angular_devkit/build_angular/src/dev-server/works_spec.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19028 fix(@angular/cli): don't show deprecation messages for defaults when using `--defaults`
  packages/angular/cli/models/schematic-command.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19029 fix(@angular/cli): don't display prompts twice
  packages/angular/cli/models/schematic-command.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19073 build: only include `packages/angular_devkit/build_angular/src/typings.d.ts` during bazel builds
  tsconfig.json
Labels: PR action: merge, PR target: master-only, cla: yes

#19048 feat(@schematics/angular): add generation for resolvers
  packages/schematics/angular/collection.json
  packages/schematics/angular/resolver/files/__name@dasherize__.resolver.spec.ts.template
  packages/schematics/angular/resolver/files/__name@dasherize__.resolver.ts.template
  packages/schematics/angular/resolver/index.ts
  packages/schematics/angular/resolver/index_spec.ts
  packages/schematics/angular/resolver/schema.json
Labels: PR action: merge, PR target: master-only, cla: yes

#18944 Revert "ci: disable lint check in the update test"
  tests/legacy-cli/e2e/tests/update/update-7.0.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19085 refactor(@angular-devkit/build-angular): simplify global_defs usage f…
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19090 fix(@angular-devkit/build-angular): set HTML lang attribute when serving
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/dev-server/index_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19091 fix(@ngtools/webpack): improve bad component resource error message
  packages/ngtools/webpack/src/resource_loader.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19094 test(@angular/cli): cleanup CDK in add material E2E test
  tests/legacy-cli/e2e/tests/commands/add/add-material.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19093 fix(@angular-devkit/build-angular): ensure correct SRI values with differential loading
  packages/angular_devkit/build_angular/src/utils/action-cache.ts
  tests/legacy-cli/e2e/tests/build/differential-loading-sri.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19101 fix(@schematics/angular): allow inlineTemplate/inlineStyle with minimal application
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/ng-new/schema.json
Labels: PR action: merge, PR target: master & patch, cla: yes

#19119 fix(@angular-devkit/build-angular): add a base href to karma debug context
  packages/angular_devkit/build_angular/src/webpack/plugins/karma-debug.html
Labels: PR action: merge, PR target: lts-only, PR target: master & patch, cla: yes

#19121 test(@angular-devkit/build-angular): remove old e2e test
  tests/legacy-cli/e2e/tests/build/aot/aot-decorators.ts
  tests/legacy-cli/e2e/tests/build/vendor-chunk-symlink-node-module.ts
  tests/legacy-cli/e2e/tests/build/watch.ts
  tests/legacy-cli/e2e/tests/test/e2e-baseurl.ts
  tests/legacy-cli/e2e/tests/test/test-assets.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19120 refactor(@angular/cli): remove install-package under utils
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/utilities/install-package.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19127 docs(@angular/cli): fix formatting in docs command
  packages/angular/cli/commands/deploy-long.md
Labels: PR action: merge, PR target: master & patch, cla: yes

#19135 fix(@angular/cli): include deprecated option in JSON help
  packages/angular/cli/models/interface.ts
  packages/angular/cli/utilities/json-schema.ts
Labels: PR action: merge, PR target: lts-only, PR target: master & patch, cla: yes

#19136 ci: schedule nightly CI for 10.1.x branch
  .circleci/config.yml
Labels: PR action: merge, PR target: lts-only, cla: yes

#19140 ci: remove docs-preview branch filter
  .circleci/config.yml
Labels: PR action: merge, PR target: master & patch, cla: yes

#19142 refactor(@angular-devkit/core): deprecate unused isFile/isDirectory utilities
  packages/angular_devkit/core/node/fs.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19141 fix(@angular/cli): skip searching deprecated packages with ng add
  packages/angular/cli/commands/add-impl.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19143 refactor(@angular-devkit/schematics): minor cleanup to reduce utility imports
  packages/angular_devkit/schematics/src/tree/host-tree.ts
  packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19154 docs: update further help section in readme
  packages/schematics/angular/library/files/README.md.template
  packages/schematics/angular/workspace/files/README.md.template
Labels: PR action: merge, PR target: lts-only, PR target: master & patch, cla: yes

#19158 docs: remove `=true` from `--next`
  packages/angular/cli/commands/update-long.md
Labels: PR action: merge, PR target: lts-only, PR target: master & patch, cla: yes

#19161 fix(@angular/cli): use newer update command if global version is newer
  packages/angular/cli/lib/init.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19165 build: update `lock-closed` GitHub action to latest version
  .github/workflows/lock-closed.yml
Labels: PR action: merge, PR target: master-only, cla: yes

#19102 feat(@angular-devkit/build-angular): support following symlinked asset directories
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/utils/copy-assets.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  tests/legacy-cli/e2e/tests/build/assets.ts
  tests/legacy-cli/e2e/tests/misc/assets.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19166 ci: remove nightly CI run for 10.1.x branch
  .circleci/config.yml
Labels: PR target: lts-only, cla: yes

#19170 test(@angular/cli): use local registry in update-1.0-yarn test
  tests/legacy-cli/e2e/tests/update/update-1.0-yarn.ts
Labels: PR action: merge, PR target: patch-only, cla: yes

#19168 test(@angular/cli): use local registry in update-1.0-yarn test
  tests/legacy-cli/e2e/tests/update/update-1.0-yarn.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19172 fix(@schematics/angular): remove lint fix default value
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/component/schema.json
  packages/schematics/angular/directive/schema.json
  packages/schematics/angular/enum/schema.json
  packages/schematics/angular/guard/schema.json
  packages/schematics/angular/interceptor/schema.json
  packages/schematics/angular/interface/schema.json
  packages/schematics/angular/library/schema.json
  packages/schematics/angular/module/schema.json
  packages/schematics/angular/service/schema.json
Labels: PR target: master & patch, cla: yes

#19173 refactor(@angular-devkit/build-angular): remove legacy server bundle guess logic
  packages/angular_devkit/build_angular/src/app-shell/index.ts
Labels: PR target: master & patch, cla: yes

#19174 fix(@angular-devkit/build-angular): don't add publicHost pathname to sockPath in dev-server
  packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
Labels: PR target: master & patch, cla: yes

#19179 build: add husky ignored files to .gitignore
  .gitignore
Labels: PR action: merge, PR target: master & patch, cla: yes, comp: build & ci

#19180 docs: add `rm -rf node_modules/` to release docs
  docs/process/release.md
Labels: PR action: merge, PR target: master-only, cla: yes, type: docs

#19190 fix(@angular-devkit/build-angular): support emitting AVIF image files
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: PR target: master & patch, cla: yes

#19215 build: remove @types/jasminewd2 from repo devDependencies
  integration/angular_cli/e2e/tsconfig.json
  integration/angular_cli/package.json
  packages/angular_devkit/build_angular/test/hello-world-app/e2e/tsconfig.e2e.json
Labels: PR target: master-only, cla: yes

#19192 fix(@angular-devkit/build-angular): skip application emit during i18n extraction
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19218 docs(@angular-devkit/build-angular): remove `="true"` from prod flag …
  packages/angular/cli/commands/build-long.md
Labels: PR target: master & patch, cla: yes

#19224 build: revert @angular/dev-infra-private package to bb9763f15077a4cb279ba0e210d337e2fde4be0e
  package.json
  yarn.lock
Labels: PR action: merge, PR target: master & patch, cla: yes

#19225 refactor(@schematics/update): remove "all" logic which is no longer used
  packages/schematics/update/update/index.ts
  packages/schematics/update/update/index_spec.ts
  packages/schematics/update/update/schema.json
Labels: PR target: master-only, cla: yes

#19220 fix(@angular-devkit/build-angular): correctly index and remove `webpack-dev-server/client` in non main chunk
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19227 fix(@angular-devkit/build-angular): when optimizing don't wrap function arguments in parenthesis
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19221 fix(@angular-devkit/build-optimizer): set rxjs as having safe side effects
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19232 feat(@schematics/angular): add `enableI18nLegacyMessageIdFormat` defa…
  packages/schematics/angular/workspace/files/tsconfig.json.template
  packages/schematics/angular/workspace/index_spec.ts
Labels: PR action: merge, PR target: master-only, cla: yes, devkit/build-angular: i18n

#19217 fix(@schematics/update): update fail when using yarn 2.0 protocols
  packages/schematics/update/update/index.ts
  packages/schematics/update/update/index_spec.ts
Labels: PR action: merge, PR target: master & patch, cla: yes

#19243 fix(@schematics/update): update fail when using yarn 2.0 protocols
  packages/schematics/update/update/index.ts
  packages/schematics/update/update/index_spec.ts
Labels: PR target: patch-only, cla: yes

#19245 refactor(@angular-devkit/build-angular): remove host from index writer
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/fs.ts
  packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
  packages/angular_devkit/build_angular/src/utils/index-file/write-index-html.ts
Labels: PR target: master-only, cla: yes

#19244 fix(@ngtools/webpack): elide type-only imports when using emitDecoratorMetadata
  packages/ngtools/webpack/src/transformers/elide_imports.ts
  packages/ngtools/webpack/src/transformers/elide_imports_spec.ts
Labels: PR action: merge, PR target: lts-only, PR target: master & patch, cla: yes

#19237 fix(@angular-devkit/build-angular): use source locale with non-localized serving
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/dev-server/works_spec.ts
  packages/angular_devkit/build_angular/src/utils/i18n-options.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19254 refactor(@angular-devkit/core): clean up NodeJsAsyncHost and NodeJsSyncHost
  packages/angular_devkit/core/node/host.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#19258 fix(@angular-devkit/build-angular): re-enable webpack 5 license extraction support
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
  packages/angular_devkit/build_angular/src/webpack/configs/worker.ts
  packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
Labels: PR action: merge, PR target: master-only, cla: yes
