Repository angular/angular-cli, pull requests merged in 2021-09, with the labels that each got.

#21690 docs: release notes for the v12.2.4 release
  CHANGELOG.md
Labels: cla: yes, action: merge

#21691 Bump version to "v13.0.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, target: major, action: merge

#21695 build: update ng-packagr to version `13.0.0-next.0`
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/schematics/angular/utility/latest-versions/package.json
  yarn.lock
Labels: cla: yes, target: major, action: merge

#21718 fix(@angular-devkit/build-angular): improve Safari browserslist to esbuild target conversion
  packages/angular_devkit/build_angular/src/webpack/plugins/css-optimizer-plugin.ts
Labels: cla: yes, target: major, action: merge

#21719 fix(@angular-devkit/build-angular): improve Safari browserslist to esbuild target conversion
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: cla: yes, target: patch, action: merge

#21723 fix(@angular-devkit/build-angular): disable dev-server response compression
  packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
Labels: cla: yes, target: patch, action: merge

#21728 Bump version to "v12.2.5" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, target: patch, action: merge

#21729 docs: release notes for the v12.2.5 release
  CHANGELOG.md
Labels: cla: yes, target: major, action: merge

#21730 Bump version to "v13.0.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, target: major, action: merge

#21745 build: update dev-infra merge configuration
  .ng-dev/merge.ts
Labels: cla: yes, target: major, action: merge

#21739 fix(@angular-devkit/build-angular): add web-streams-polyfill to downlevel exclusion list
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: cla: yes, target: patch, action: merge

#21758 Bump version to "v12.2.6" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, target: patch, action: merge

#21759 docs: release notes for the v12.2.6 release
  CHANGELOG.md
Labels: cla: yes, action: merge

#21760 Fix release notes
  CHANGELOG.md
Labels: cla: yes, action: merge, comp: build & ci

#21761 Bump version to "v13.0.0-next.5" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, target: major, action: merge

#21781 fix(@angular-devkit/build-webpack): better handle concurrent dev-servers
  packages/angular_devkit/build_webpack/src/webpack-dev-server/index.ts
Labels: cla: yes, target: major, action: merge

#21783 docs: replace deprecated camel-case argument
  packages/angular/cli/commands/new.md
Labels: cla: yes, target: patch, action: merge

#21787 build: replace ng-dev MergeConfig wiith PullRequestConfig
  .ng-dev/config.ts
  .ng-dev/pull-request.ts
Labels: cla: yes, target: major, action: merge

#21763 fix(@angular-devkit/build-angular): support WASM-based esbuild optimizer fallback
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/esbuild-check.js
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/webpack/plugins/css-optimizer-plugin.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/esbuild-executor.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts
  tests/legacy-cli/e2e/tests/build/esbuild-unsupported.ts
  yarn.lock
Labels: cla: yes, target: major, action: merge

#21789 [12.2.x] fix(@angular-devkit/build-angular): support WASM-based esbuild optimizer fallback
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/esbuild-check.js
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/esbuild-executor.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts
  tests/legacy-cli/e2e/tests/build/esbuild-unsupported.ts
  yarn.lock
Labels: cla: yes, target: patch, action: merge

#21794 Bump version to "v13.0.0-next.6" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, target: major, action: merge

#21796 Bump version to "v12.2.7" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, target: patch, action: merge

#21797 docs: release notes for the v12.2.7 release
  CHANGELOG.md
Labels: cla: yes, target: major, action: merge

#21795 feat(@schematics/angular): create new projects with rxjs 7
  packages/schematics/angular/utility/latest-versions/package.json
Labels: cla: yes, target: major, action: merge

#21809 ci: ensure Windows CI installs Windows specific npm dependencies
  .circleci/config.yml
Labels: cla: yes, target: major, action: merge

#21804 fix(@angular-devkit/build-angular): use URLs for absolute import paths with ESM
  packages/angular_devkit/build_angular/src/utils/load-esm.ts
  packages/angular_devkit/build_angular/src/utils/service-worker.ts
Labels: cla: yes, target: major

#21792 feat(@angular-devkit/build-angular): support ESM proxy configuration files for the dev server
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/proxy-config_spec.ts
  packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
Labels: cla: yes, action: merge, target: minor

#21805 fix(@angular-devkit/build-angular): babel adjust enum plugin incorrectly transforming loose enums
  packages/angular_devkit/build_angular/src/babel/plugins/adjust-typescript-enums.ts
  packages/angular_devkit/build_angular/src/babel/plugins/adjust-typescript-enums_spec.ts
Labels: cla: yes, target: patch, action: merge

#21818 refactor(@angular-devkit/build-angular): support ESM `@angular/localize` usage
  packages/angular_devkit/build_angular/src/babel/presets/application.ts
  packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
  packages/angular_devkit/build_angular/src/builders/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/builders/extract-i18n/ivy-extract-loader.ts
  packages/angular_devkit/build_angular/src/utils/load-translations.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: cla: yes, target: major, action: merge

#21826 refactor(@angular-devkit/build-angular): pass SSL cert and key path to dev-server
  packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
Labels: cla: yes, target: major, action: merge

#21830 refactor(@angular-devkit/build-webpack): port 0 WEBPACK_DEV_SERVER_BASE_PORT workaround
  packages/angular_devkit/build_webpack/src/webpack-dev-server/index.ts
Labels: cla: yes, target: major

#21815 fix(@angular/cli): remove unused cli project options.
  packages/angular/cli/lib/config/workspace-schema.json
Labels: cla: yes, target: major, action: merge

#21835 fix(@angular-devkit/build-angular): update IE unsupported and deprecation messages
  packages/angular_devkit/build_angular/src/builders/browser/index.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/browser-support_spec.ts
Labels: cla: yes, target: major, action: merge

#21825 perf(@angular-devkit/build-angular): change webpack hashing function to `xxhash64`
  packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/source-map_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/web-worker_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/output-hashing_spec.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  tests/legacy-cli/e2e/tests/basic/build.ts
  tests/legacy-cli/e2e/tests/build/output-hashing.ts
  tests/legacy-cli/e2e/tests/build/prod-build.ts
  tests/legacy-cli/e2e/tests/update/update-9.ts
Labels: cla: yes, target: major, action: merge

#21842 fix(@angular-devkit/build-angular): ESM-interop loaded plugin creators of `@angular/localize/tools` not respected
  packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: cla: yes, target: major, action: merge

#21848 test: remove last string-form loadChildren usage
  tests/legacy-cli/e2e/assets/webpack/test-app/app/feature/lazy-feature.module.ts
Labels: cla: yes, target: major

#21847 Bump version to "v13.0.0-next.7" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, target: major, action: merge
