Repository angular/angular-cli, pull requests merged in 2021-05, with the labels that each got.

#20670 fix(@schematics/angular): add "type" option in enum schematic
  packages/schematics/angular/enum/files/__name@dasherize____type__.ts.template
  packages/schematics/angular/enum/index.ts
  packages/schematics/angular/enum/index_spec.ts
  packages/schematics/angular/enum/schema.json
Labels: action: merge, cla: yes, target: rc

#20681 refactor(@angular-devkit/build-angular): remove redundant any casting
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: action: merge, cla: yes, target: rc

#20678 fix(@angular/cli): don't display options multiple times in schematics…
  packages/angular/cli/models/command.ts
  packages/angular/cli/models/schematic-command.ts
  tests/legacy-cli/e2e/tests/generate/help-output-no-duplicates.ts
Labels: action: merge, cla: yes, target: rc

#20683 Angular Webpack plugin small performance enhancements
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: action: merge, cla: yes, target: rc

#20691 test: remove `/tests/` from paths that prettier should ignore
  .prettierignore
Labels: action: merge, cla: yes, target: rc

#20686 fix(@schematics/angular): only run `emitDecoratorMetadata` removal migration in safe workspaces
  packages/schematics/angular/migrations/update-12/remove-emit-decorator-metadata.ts
  packages/schematics/angular/migrations/update-12/remove-emit-decorator-metadata_spec.ts
Labels: action: merge, cla: yes, target: rc

#20696 fix(@angular-devkit/build-angular): disable CSS declaration sorting optimizations
  packages/angular_devkit/build_angular/src/webpack/plugins/optimize-css-webpack-plugin.ts
Labels: action: merge, cla: yes, target: patch

#20700 docs: fix typo in `showCircularDependencies` deprecation message
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/server/schema.json
Labels: action: merge, cla: yes, target: rc

#20695 fix(@angular-devkit/build-angular): disable CSS declaration sorting optimizations
  packages/angular_devkit/build_angular/src/webpack/plugins/optimize-css-webpack-plugin.ts
Labels: action: merge, cla: yes, target: rc

#20699 fix(@angular/cli): change package installation to async
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/utilities/install-package.ts
Labels: action: merge, cla: yes, target: rc

#20684 build: use platform from shared dev-infra package for remote execution
  .bazelrc
  .bazelversion
  WORKSPACE
  package.json
  renovate.json
  tools/BUILD.bazel
  yarn.lock
Labels: action: merge, cla: yes, target: minor

#20717 build: update non-major dependencies
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_optimizer/package.json
  packages/angular_devkit/build_webpack/package.json
  packages/ngtools/webpack/package.json
  yarn.lock
Labels: action: merge, cla: yes, target: rc

#20716 fix(@angular-devkit/build-angular): update cssnano/postcss to fix optimization defects
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: action: merge, cla: yes, target: patch

#20727 Unset config
  packages/angular/cli/commands/config-impl.ts
  tests/legacy-cli/e2e/tests/commands/config/config-set.ts
Labels: action: merge, cla: yes, target: rc

#20729 fix(@angular/cli): disallow additional properties in builders sections
  packages/angular/cli/lib/config/workspace-schema.json
Labels: action: merge, cla: yes, target: rc

#20732 build: update dependency resolve-url-loader to v4
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: action: merge, cla: yes, target: rc

#20748 docs(@angular/cli): Add Cypress schematic to e2e command
  packages/angular/cli/commands/e2e-impl.ts
Labels: action: merge, cla: yes, target: patch

#20740 perf(@angular-devkit/build-angular): execute dart-sass in a worker
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/src/sass/sass-service.ts
  packages/angular_devkit/build_angular/src/sass/worker.ts
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
  yarn.lock
Labels: action: merge, cla: yes, target: patch

#20759 build: update prettier to match version in master branch
  package.json
  yarn.lock
Labels: action: merge, cla: yes, target: patch

#20758 test: fix formatting in `src/webpack/configs/styles.ts`
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: action: merge, cla: yes, target: patch

#20766 perf(@angular-devkit/build-angular): reduce JSON stats
  packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
Labels: action: merge, cla: yes, target: patch

#20767 fix(@angular-devkit/build-angular): add experimental web-assembly
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: action: merge, cla: yes, target: patch

#20775 build: update Angular dependencies to stable v12.0
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  tests/legacy-cli/e2e/assets/webpack/test-app/package.json
  yarn.lock
Labels: action: merge, cla: yes, target: patch

#20774 fix(@schematics/angular): remove --prod option from README template
  packages/schematics/angular/workspace/files/README.md.template
Labels: action: merge, cla: yes, target: patch

#20749 fix(@angular-devkit/build-angular): fix error with inline styles when running extract-i18n
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
Labels: action: merge, cla: yes, target: patch

#20776 docs(@schematics/angular): clarify that users need to install ng e2e …
  packages/schematics/angular/workspace/files/README.md.template
Labels: action: merge, cla: yes, target: patch

#20789 fix(@angular/cli): cannot locate bin for temporary package
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/utilities/install-package.ts
Labels: action: merge, cla: yes, target: patch

#20787 fix(@angular-devkit/build-angular): non injected styles should not count as initial
  packages/angular_devkit/build_angular/src/webpack/utils/async-chunks.ts
  packages/angular_devkit/build_angular/src/webpack/utils/async-chunks_spec.ts
  tests/legacy-cli/e2e/tests/basic/styles-array.ts
Labels: action: merge, cla: yes, target: patch

#20798 fix(@angular/cli): clean node modules directory prior to updating
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/src/commands/update/schematic/index.ts
  packages/angular/cli/utilities/install-package.ts
Labels: action: merge, cla: yes, target: patch

#20771 perf(@angular-devkit/build-angular): render Sass using a pool of workers
  packages/angular_devkit/build_angular/src/sass/sass-service.ts
Labels: action: merge, cla: yes, target: patch

#20818 fix(@angular/cli): improve `--prod` deprecation warning
  packages/angular/cli/models/architect-command.ts
Labels: action: merge, cla: yes, target: patch

#20813 fix(@angular-devkit/build-angular): revert open to 8.0.2
  package.json
  packages/angular/cli/package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: action: merge, cla: yes, target: patch

#20824 build: update terser-webpack-plugin to version 5
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  yarn.lock
Labels: action: merge, cla: yes, target: patch

#20810 Fix for webpack 5 + babel "failed to resolve" error
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: action: merge, cla: yes, target: patch

#20830 ci: disable `eslint-plugin-import` from auto updates
  renovate.json
Labels: cla: yes, target: minor

#20831 build: update babel packages
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: action: merge, cla: yes, target: patch

#20829 docs(@angular-devkit/build-angular): add more info link to `proxyConfig`
  packages/angular_devkit/build_angular/src/dev-server/schema.json
Labels: action: merge, cla: yes, target: patch

#20836 perf(@angular-devkit/build-angular): clean no-longer used assets during builds
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: action: merge, cla: yes, target: patch

#20842 Data path must NOT have additional properties(skipTests)
  packages/schematics/angular/application/index.ts
Labels: action: merge, cla: yes, target: patch

#20825 docs(@angular-devkit/schematics): properly escape code in Templating
  packages/angular_devkit/schematics/README.md
Labels: action: merge, cla: yes, target: patch

#20826 build: set up releasing using ng-dev
  .ng-dev/config.ts
  .ng-dev/release.ts
  scripts/build.ts
Labels: action: merge, cla: yes, target: patch

#20850 fix(@angular-devkit/build-angular): compile schema in synchronously
  packages/angular_devkit/core/src/json/schema/registry.ts
Labels: action: merge, cla: yes, target: patch

#20849 fix(@schematics/angular): add migration to remove `skipTests` from `@schematics/angular:module`
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-12/schematic-options.ts
  packages/schematics/angular/migrations/update-12/schematic-options_spec.ts
Labels: action: merge, cla: yes, target: patch

#20854 perf(@ngtools/webpack): reduce non-watch mode TypeScript diagnostic analysis overhead
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: action: merge, cla: yes, target: patch

#20858 ci: update e2e-cli to use node 12.20
  .circleci/config.yml
Labels: action: merge, cla: yes, comp: build & ci, target: patch

#20889 perf(@angular-devkit/build-angular): update PostCSS to 8.3
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: action: merge, cla: yes, target: patch

#20876 fix(@angular-devkit/build-angular): ensure Sass worker implementation supports Node.js 12.14
  packages/angular_devkit/build_angular/src/sass/sass-service.ts
  packages/angular_devkit/build_angular/src/sass/worker.ts
Labels: action: merge, cla: yes, target: patch

#20861 fix(@angular-devkit/build-angular): don't add `.hot-update.js` script tags
  packages/angular_devkit/build_angular/src/webpack/plugins/index-html-webpack-plugin.ts
Labels: action: merge, cla: yes, target: patch

#20886 perf(@angular-devkit/build-angular): disable CSS optimization parallelism for components styles
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: action: merge, cla: yes, target: patch

#20885 fix(@ngtools/webpack): re-emit component stylesheet assets
  packages/angular_devkit/build_angular/src/webpack/plugins/postcss-cli-resources.ts
  packages/ngtools/webpack/src/resource_loader.ts
Labels: action: merge, cla: yes, target: patch

#20881 feat(@angular/cli): show Node.js version support status in version command
  packages/angular/cli/commands/version-impl.ts
  tests/legacy-cli/e2e/tests/misc/version.ts
Labels: action: merge, cla: yes, target: minor

#20897 fix(@angular-devkit/build-angular): correctly generate ServiceWorker config on Windows
  packages/angular_devkit/build_angular/src/utils/service-worker.ts
  tests/legacy-cli/e2e/tests/commands/add/add-pwa.ts
Labels: action: merge, cla: yes, comp: devkit/build-angular, devkit/build-angular: browser, severity5: regression, target: patch, type: bug/fix

#20902 test: fix local mapping path of @ angular-devkit/schematics-cli
  packages/circular-deps-test.conf.js
Labels: action: merge, cla: yes, target: patch

#20913 perf(@angular-devkit/build-angular): load postcss-preset-env configuration once
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: action: merge, cla: yes, target: patch

#20925 test: use correct snapshot versions in add-pwa E2E test
  tests/legacy-cli/e2e/ng-snapshot/package.json
  tests/legacy-cli/e2e/tests/commands/add/add-pwa.ts
Labels: action: merge, cla: yes, target: minor

#20920 fix(@angular-devkit/build-angular): ensure latest inline stylesheet data is used during rebuilds
  packages/angular_devkit/build_angular/src/browser/tests/options/inline-style-language_spec.ts
  packages/ngtools/webpack/src/ivy/host.ts
  packages/ngtools/webpack/src/resource_loader.ts
Labels: action: merge, cla: yes, target: patch

#20936 fix(@angular/cli): ng update on windows to allow path
  packages/angular/cli/utilities/install-package.ts
Labels: action: merge, cla: yes, target: patch

#20931 fix(@angular-devkit/build-angular): allow i18n extraction on application that uses web-workers
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
Labels: action: merge, cla: yes, target: patch

#20939 fix(@angular-devkit/build-angular): hide stacktraces from dart-sass errors
  packages/angular_devkit/build_angular/src/sass/worker.ts
Labels: action: merge, cla: yes, target: patch

#20938 fix(@angular-devkit/build-angular): resolve absolute outputPath properly
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: action: merge, cla: yes, target: patch

#20956 test: use correct snapshot versions in add-pwa E2E test with yarn
  tests/legacy-cli/e2e/tests/commands/add/add-pwa.ts
Labels: cla: yes, target: minor

#20952 fix(@angular-devkit/build-angular): show `--disable-host-check` warning only when not using `disableHostCheck`
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: action: merge, cla: yes, target: patch

#20953 feat(@angular-devkit/build-angular): deprecate protractor builder
  packages/angular_devkit/build_angular/README.md
  packages/angular_devkit/build_angular/src/protractor/index.ts
Labels: action: merge, cla: yes, target: minor

#20948 fix(@angular-devkit/build-angular): do not resolve web-workers in server builds
  packages/angular_devkit/build_angular/src/server/base_spec.ts
  packages/angular_devkit/build_angular/src/webpack/configs/server.ts
Labels: action: merge, cla: yes, target: patch

#20958 docs: fold post-release version bump with the release commit
  docs/process/release.md
Labels: action: merge, cla: yes, target: patch

#20959 fix(@angular/cli): update supported range of node versions to be less restrictive
  lib/packages.ts
Labels: action: merge, cla: yes, target: patch

#20960 fix(@angular-devkit/build-angular): provided earlier build feedback in console
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: action: merge, cla: yes, target: patch

#20971 fix(@angular-devkit/build-angular): correctly ignore inline styles during i18n extraction
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/extract-i18n/works_spec.ts
Labels: action: merge, cla: yes, target: patch

#20972 [12.1.x]fix(@angular-devkit/build-angular): correctly ignore inline styles during i18n extraction
  packages/angular_devkit/build_angular/src/extract-i18n/empty-export-default.js
  packages/angular_devkit/build_angular/src/extract-i18n/empty-loader.ts
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/extract-i18n/works_spec.ts
Labels: action: merge, cla: yes, target: minor

#20980 fix(@schematics/angular): make version 12 workspace config migration idempotent
  packages/schematics/angular/migrations/update-12/update-angular-config.ts
  packages/schematics/angular/migrations/update-12/update-angular-config_spec.ts
Labels: action: merge, cla: yes, target: patch

#20981 build: update Webpack to version 5.38.1
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/browser/specs/differential_loading_spec.ts
  packages/angular_devkit/build_angular/src/browser/specs/scripts-array_spec.ts
  packages/angular_devkit/build_angular/test/hello-world-app/angular.json
  packages/angular_devkit/build_optimizer/package.json
  packages/angular_devkit/build_webpack/package.json
  packages/ngtools/webpack/package.json
  yarn.lock
Labels: action: merge, cla: yes, target: minor

#20984 fix(@ngtools/webpack): normalize paths when adding file dependencies
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: action: merge, cla: yes, target: patch

#20974 fix(@ngtools/webpack): remove redundant inline style cache
  packages/ngtools/webpack/src/resource_loader.ts
Labels: action: merge, cla: yes, target: patch
