Repository angular/angular-cli, pull requests merged in 2021-12, with the labels that each got.

#22268 fix(@angular-devkit/build-angular): display cleaner errors
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: cla: yes, action: merge, target: minor

#22271 Bump version to "v13.0.4" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, target: patch, action: merge

#22272 docs: release notes for the v13.0.4 release
  CHANGELOG.md
Labels: cla: yes, action: merge, target: minor

#22273 Bump version to "v13.1.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes, action: merge, target: minor

#22265 fix(@ngtools/webpack): handle promise rejection during Angular program analyzes
  packages/ngtools/webpack/src/ivy/loader.ts
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: cla: yes, target: patch, action: merge

#22278 fix(@angular-devkit/build-angular): display cleaner errors
  packages/angular_devkit/build_angular/src/webpack/configs/typescript.ts
Labels: cla: yes, target: patch, action: merge

#22281 build: update `@ampproject/remapping` to `1.0.2`
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: cla: yes, target: patch, action: merge

#22286 Bump version to "v12.2.14" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: lts

#22279 docs: update CPU profiling section
  packages/angular/cli/README.md
Labels: cla: yes, target: patch, action: merge

#22291 fix(@angular-devkit/build-angular): fallback to use language ID to set the `dir` attribute
  packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html.ts
  packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html_spec.ts
Labels: cla: yes, action: merge, target: minor

#22292 refactor(@angular-devkit/build-angular): remove `NG_BUILD_PROFILING` and `DEVKIT_PROFILING` logic
  lib/bootstrap-local.js
  packages/angular_devkit/build_angular/src/utils/environment-options.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  tests/legacy-cli/e2e/tests/build/profile.ts
Labels: cla: yes, action: merge, target: minor

#22294 fix(@angular-devkit/build-angular): Sass compilation in StackBlitz webcontainers
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: cla: yes, target: patch, action: merge

#22297 refactor(@ngtools/webpack): use webpack API to delete assets in compilation
  packages/ngtools/webpack/src/resource_loader.ts
Labels: cla: yes, action: merge, target: minor

#22314 Bump version to "v12.2.14" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: lts

#22315 docs: release notes for the v12.2.14 release
  CHANGELOG.md
Labels: action: merge, target: minor

#22305 fix(@angular-devkit/build-angular): prefer ES2015 entrypoints when application targets ES2019 or lower
  packages/angular_devkit/build_angular/src/builders/browser/specs/lazy-module_spec.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
Labels: cla: yes, action: merge, target: minor

#22306 fix(@angular-devkit/build-angular): prefer ES2015 entrypoints when application targets ES2019 or lower
  packages/angular_devkit/build_angular/src/builders/browser/specs/lazy-module_spec.ts
  packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/configs/server.ts
  packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
Labels: cla: yes, target: patch, action: merge

#22312 refactor(@angular-devkit/build-angular): remove usage of deprecated url methods
  packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
Labels: action: merge, target: minor

#22326 Bump version to "v13.1.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#22328 Bump version to "v13.1.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#22329 docs: release notes for the v13.1.0 release
  CHANGELOG.md
Labels: action: merge

#22330 Bump version to "v13.2.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge

#22337 fix(@schematics/angular): updated Angular new project version to v13.2.0-next.0
  packages/schematics/angular/utility/latest-versions.ts
Labels: action: merge, target: minor

#22334 fix(@schematics/angular): updated Angular new project version to v13.1.0
  packages/schematics/angular/utility/latest-versions.ts
Labels: target: patch, action: merge

#22308 build: reproduce original package structure using bazel
  .bazelrc
  BUILD.bazel
  WORKSPACE
  packages/angular/cli/BUILD.bazel
  packages/angular/pwa/BUILD.bazel
  packages/angular_devkit/architect/BUILD.bazel
  packages/angular_devkit/architect_cli/BUILD.bazel
  packages/angular_devkit/benchmark/BUILD.bazel
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_optimizer/BUILD.bazel
  packages/angular_devkit/build_webpack/BUILD.bazel
  packages/angular_devkit/core/BUILD.bazel
  packages/angular_devkit/schematics/BUILD.bazel
  packages/angular_devkit/schematics_cli/BUILD.bazel
  packages/ngtools/webpack/BUILD.bazel
  packages/schematics/angular/BUILD.bazel
  packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
  tools/defaults.bzl
Labels: cla: yes, target: patch, action: merge

#22348 Bump version to "v13.1.1" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#22349 docs: release notes for the v13.1.1 release
  CHANGELOG.md
Labels: action: merge, target: minor

#22353 refactor(@angular-devkit/core): update missing workspace file error to explicitly call out `angular.json`
  packages/angular_devkit/core/src/workspace/core.ts
Labels: comp: devkit/core, target: patch, action: merge

#22345 fix(@angular-devkit/build-angular): add `tailwindcss` support for version 3
  packages/angular_devkit/build_angular/package.json
  tests/legacy-cli/e2e/tests/build/styles/tailwind-v2.ts
  tests/legacy-cli/e2e/tests/build/styles/tailwind-v3.ts
Labels: target: patch, action: merge

#22341 test: remove `disableTypeScriptVersionCheck` from tests setup
  tests/legacy-cli/e2e/setup/500-create-project.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-es2015.ts
Labels: target: patch, action: merge

#22367 docs: add `latest-versions.ts` bump to minor/major version release instructions
  docs/process/release.md
Labels: target: patch, action: merge

#22372 Bump version to "v11.2.16" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: lts

#22350 build: add parallel script to build using bazel
  package.json
  scripts/build-bazel.ts
Labels: target: patch, action: merge

#22373 Bump version to "v11.2.16" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: lts

#22381 Bump version to "v11.2.16" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: lts

#22376 fix(@angular-devkit/build-angular): only extract CSS styles when are specified in `styles` option
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: target: patch, action: merge

#22378 fix(@angular-devkit/build-angular): display FS cache information when `verbose` option is used
  packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
Labels: target: patch, action: merge

#22377 perf(@ngtools/webpack): reduce redundant module rebuilds when cache is restored
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: target: patch, action: merge

#22382 Bump version to "v13.1.2" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#22383 docs: release notes for the v13.1.2 release
  CHANGELOG.md
Labels: action: merge, target: minor

#22384 Bump version to "v13.2.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: minor

#22385 docs: release notes for the v11.2.16 release
  CHANGELOG.md
Labels: action: merge, target: minor

#22387 docs: release notes for the v10.2.4 release
  CHANGELOG.md
Labels: action: merge, target: minor

#22392 fix(@angular/cli): exclude deprecated packages with removal migration…
  packages/schematics/update/update/index.ts
Labels: action: merge, target: lts

#22399 docs: release notes for the v11.2.17 release
  CHANGELOG.md
Labels: action: merge, target: minor

#22394 fix(@angular/cli): remove extra space in `Unable to find compatible package` during `ng add`
  packages/angular/cli/commands/add-impl.ts
Labels: target: patch, action: merge

#22379 fix(@angular-devkit/build-angular): ability to perform DCE but retain symbol names
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts
Labels: target: patch, action: merge
