Repository angular/angular-cli, pull requests merged in 2021-01, with the labels that each got.

#19673 test(@angular-devkit/build-angular): add browser builder polyfills option tests
  packages/angular_devkit/build_angular/src/browser/tests/options/polyfills_spec.ts
Labels: action: merge, cla: yes, target: minor

#19674 test(@angular-devkit/build-angular): add browser builder tsConfig option tests
  packages/angular_devkit/build_angular/src/browser/tests/options/tsconfig_spec.ts
Labels: action: merge, cla: yes, target: minor

#19669 test(@angular-devkit/build-angular): add browser builder assets option tests
  packages/angular_devkit/build_angular/src/browser/tests/options/assets_spec.ts
Labels: cla: yes, preserve commits, target: minor

#19709 fix(@angular-devkit/build-angular): don't downlevel web-animations-js
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: action: merge, cla: yes, preserve commits, target: patch

#19719 test(@angular-devkit/build-angular): add browser builder statsJson option tests
  packages/angular_devkit/build_angular/src/browser/tests/options/stats-json_spec.ts
Labels: action: merge, cla: yes, preserve commits, target: minor

#19720 test(@angular-devkit/build-angular): add browser builder styles option tests
  packages/angular_devkit/build_angular/src/browser/tests/options/styles_spec.ts
Labels: action: merge, cla: yes, preserve commits, target: minor

#19713 fix(@angular-devkit/build-angular): correctly resolve symlinked global styles entrypoints
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
  tests/legacy-cli/e2e/tests/build/styles/symlinked-global.ts
Labels: action: merge, cla: yes, preserve commits, target: patch

#19714 fix(@schematics/angular): correctly handle PropertyAssignments with StringLiteral keys
  packages/schematics/angular/utility/ast-utils.ts
  packages/schematics/angular/utility/ast-utils_spec.ts
Labels: action: merge, cla: yes, preserve commits, target: patch

#19715 refactor(@schematics/angular): remove unused TS AST utils
  packages/schematics/angular/utility/ast-utils.ts
Labels: action: merge, cla: yes, preserve commits, target: minor

#19731 test(@angular-devkit/build-angular): fix symlink tests on windows
  tests/legacy-cli/e2e/tests/build/styles/symlinked-global.ts
Labels: action: merge, cla: yes, preserve commits, target: patch

#19736 Revert "docs: add default value for karma watch option"
  packages/angular_devkit/build_angular/src/karma/schema.json
Labels: action: merge, cla: yes, preserve commits, target: patch

#19737 build: update revert pattern in changelog generator
  scripts/changelog.ts
Labels: action: merge, cla: yes, preserve commits, target: patch

#19750 refactor(@angular-devkit/build-angular): use script target in custom babel loader
  packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
  packages/angular_devkit/build_angular/src/utils/build-options.ts
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: action: merge, cla: yes, preserve commits, target: minor

#19738 docs: update Ivy NGCC link
  packages/angular_devkit/build_angular/src/server/index.ts
Labels: action: merge, cla: yes, preserve commits, target: patch

#19760 test(@angular-devkit/build-angular): change `extractLicenses` unit test to use build harness
  packages/angular_devkit/build_angular/src/browser/specs/license-extraction_spec.ts
  packages/angular_devkit/build_angular/src/browser/tests/options/extract-licenses_spec.ts
Labels: action: merge, cla: yes, preserve commits, target: minor

#19766 ci: change merge strategy to rebase instead of squash
  .ng-dev/merge.ts
Labels: action: merge, cla: yes, comp: build & ci, preserve commits, target: patch

#19764 feat(@angular-devkit/build-angular): update IE11 Object/Array polyfills
  packages/angular_devkit/build_angular/src/webpack/es5-polyfills.js
Labels: action: merge, cla: yes, target: minor

#19767 test(@angular-devkit/build-angular): add browser builder scripts longhand option tests
  packages/angular_devkit/build_angular/src/browser/tests/options/scripts_spec.ts
Labels: action: merge, cla: yes, target: minor

#19761 fix(@angular-devkit/build-angular): generate consistent filenames
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/browser/specs/differential_loading_spec.ts
  packages/angular_devkit/build_angular/src/browser/specs/scripts-array_spec.ts
  packages/angular_devkit/build_angular/src/utils/build-options.ts
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
  packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  tests/legacy-cli/e2e/tests/build/differential-loading-watch.ts
Labels: action: merge, cla: yes, target: minor

#19791 build: update next branch to reflect new release-train `v11.2.0-next.0`
  package.json
Labels: action: merge, cla: yes, target: minor

#19792 refactor(@schematics/angular): use includes instead of RegExp
  packages/schematics/angular/component/index.ts
Labels: action: merge, cla: yes, target: minor

#19790 fix(@ngtools/webpack): use `getDiagnosticsForFile` instead of `getDiagnostics`
  package.json
  packages/ngtools/webpack/package.json
  packages/ngtools/webpack/src/ivy/plugin.ts
  yarn.lock
Labels: action: merge, cla: yes, target: rc

#19803 docs: change documentation text
  packages/angular/cli/README.md
Labels: action: merge, cla: yes, target: patch

#19802 refactor(@angular-devkit/build-angular): move karma plugin in own folder
  packages/angular_devkit/build_angular/plugins/karma.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma-context.html
  packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma-debug.html
  packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma-webpack-failure-cb.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma.ts
Labels: action: merge, cla: yes, target: minor

#19801 fix(@angular-devkit/build-angular): resolve i18n outFile with normalized format
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
Labels: action: merge, cla: yes, target: patch

#19818 refactor(@angular-devkit/build-angular): remove virtualfs host usage from browser/dev-server
  packages/angular_devkit/build_angular/src/app-shell/index.ts
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/utils/normalize-asset-patterns.ts
  packages/angular_devkit/build_angular/src/utils/normalize-builder-schema.ts
  packages/angular_devkit/build_angular/src/utils/normalize-file-replacements.ts
  packages/angular_devkit/build_angular/src/utils/service-worker.ts
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
Labels: action: merge, cla: yes, target: minor

#19821 fix(@angular/cli): add @angular-devkit/architect to ng-update packageGroup
  packages/angular/cli/package.json
Labels: action: merge, cla: yes, target: rc

#19832 fix(@angular/cli): avoid analytics cli object check if not present
  packages/angular/cli/models/analytics.ts
Labels: action: merge, cla: yes, target: rc

#19841 fix(@ngtools/webpack): perform import eliding before TypeScript transforms
  packages/ngtools/webpack/src/ivy/transformation.ts
  packages/ngtools/webpack/src/transformers/elide_imports.ts
  packages/ngtools/webpack/src/transformers/elide_imports_spec.ts
  packages/ngtools/webpack/src/transformers/spec_helpers.ts
Labels: action: merge, cla: yes, target: patch

#19847 fix(@angular-devkit/build-angular): resolve postcss from build-angular package
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
  yarn.lock
Labels: action: merge, cla: yes, target: patch

#19848 fix(@angular-devkit/build-angular): inlining fonts behind proxy
  package.json
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
  yarn.lock
Labels: action: merge, cla: yes, target: patch

#19862 refactor(@angular-devkit/core): deprecate flatten schema method
  packages/angular_devkit/core/src/json/schema/interface.ts
  packages/angular_devkit/core/src/json/schema/registry.ts
Labels: action: merge, cla: yes, target: minor

#19838 fix(@schematics/update): update line end normalization for CA file read from .npmrc
  packages/angular/cli/utilities/package-metadata.ts
  packages/schematics/update/update/npm.ts
Labels: action: merge, cla: yes, target: patch

#19871 feat(@angular-devkit/build-angular): support targeting ES2017 with Zone.js
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/babel/presets/application.ts
  packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
  packages/angular_devkit/build_angular/src/browser/tests/behavior/typescript-target_spec.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/configs/typescript.ts
  yarn.lock
Labels: action: merge, cla: yes, target: minor

#19883 refactor(@ngtools/webpack): replace deprecated TypeScript methods
  packages/ngtools/webpack/src/ivy/transformation.ts
Labels: action: merge, cla: yes, target: minor

#19880 feat(@angular/cli): provide additional status messaging for ng add
  packages/angular/cli/BUILD.bazel
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/package.json
  packages/angular/cli/utilities/install-package.ts
  packages/angular/cli/utilities/spinner.ts
Labels: action: merge, cla: yes, target: minor

#19878 fix(@angular-devkit/schematics): Fix merge that causes an overwrite
  packages/angular_devkit/schematics/src/tree/host-tree.ts
  packages/angular_devkit/schematics/src/tree/host-tree_spec.ts
  tests/legacy-cli/e2e/tests/generate/component/component-duplicate.ts
Labels: action: merge, cla: yes, target: patch

#19876 fix(@angular-devkit/build-angular): styles that are not injected do count for initial bundle size
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/bundle-budget.ts
  packages/angular_devkit/build_angular/src/webpack/utils/async-chunks.ts
Labels: action: merge, cla: yes, target: patch

#19874 docs: fix tests with Bazel link
  README.md
  scripts/templates/readme.ejs
Labels: action: merge, cla: yes, target: patch

#19889 build: update bazel to 4.0.0
  .bazelrc
  .bazelversion
  .gitignore
  WORKSPACE
Labels: action: merge, cla: yes, comp: build & ci, target: patch

#19868 Fix bundle budgets with any script and differential loading
  packages/angular_devkit/build_angular/src/utils/bundle-calculator.ts
  packages/angular_devkit/build_angular/src/utils/bundle-calculator_spec.ts
Labels: action: merge, cla: yes, target: patch

#19894 refactor(@angular/cli): fix super minor typo
  packages/angular/cli/models/schematic-command.ts
Labels: action: merge, cla: yes, target: patch
