Repository angular/angular-cli, pull requests merged in 2021-03, with the labels that each got.

#20168 fix(@angular-devkit/build-angular): remove left-over `experimentalRollupPass` option
  packages/angular_devkit/build_angular/src/browser/schema.json
Labels: cla: yes, target: major

#20075 refactor(@angular/cli): remove dependency on universal-analytics
  package.json
  packages/angular/cli/BUILD.bazel
  packages/angular/cli/lib/cli/index.ts
  packages/angular/cli/models/analytics-collector.ts
  packages/angular/cli/models/analytics.ts
  packages/angular/cli/models/command-runner.ts
  packages/angular/cli/models/version.ts
  packages/angular/cli/package.json
  yarn.lock
Labels: action: merge, cla: yes, target: major

#20174 test(@angular/cli): minimize project changes during E2E project CI setup
  tests/legacy-cli/e2e/tests/generate/application/application-basic.ts
  tests/legacy-cli/e2e/tests/generate/library/library-basic.ts
  tests/legacy-cli/e2e/utils/project.ts
Labels: action: merge, cla: yes, target: major

#20171 refactor(@angular-devkit/build-angular): only inline component stylesheet sourcemaps
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: action: merge, cla: yes, target: major

#20173 test(@angular-devkit/build-angular): improve reliability of app-shell server-worker test
  packages/angular_devkit/build_angular/src/app-shell/app-shell_spec.ts
Labels: action: merge, cla: yes, target: patch

#20172 refactor(@angular-devkit/build-angular): use custom babel loader for i18n dev-server support
  packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: action: merge, cla: yes, target: patch

#20184 build: remove unused development dependencies
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  yarn.lock
Labels: action: merge, cla: yes, target: major

#20185 refactor(@angular-devkit/core): deprecate unused utility functions
  packages/angular_devkit/core/src/utils/array.ts
  packages/angular_devkit/core/src/utils/object.ts
Labels: cla: yes, target: major

#20205 Webpack styles configuration refactor and cleanup
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: action: merge, cla: yes, target: major

#20213 fix(@angular-devkit/build-angular): only remove nomodule and defer attributes empty values
  packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
Labels: action: merge, cla: yes, target: patch

#20195 fix(@angular/cli): add ng-packagr builder schema in IDE schema
  packages/angular/cli/lib/config/schema.json
Labels: action: merge, cla: yes, target: patch

#20220 fix(@schematics/angular): add `additionalProperties` to all schemas
  packages/schematics/angular/app-shell/schema.json
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/class/schema.json
  packages/schematics/angular/component/schema.json
  packages/schematics/angular/directive/schema.json
  packages/schematics/angular/e2e/schema.json
  packages/schematics/angular/enum/schema.json
  packages/schematics/angular/guard/schema.json
  packages/schematics/angular/interceptor/schema.json
  packages/schematics/angular/interface/schema.json
  packages/schematics/angular/library/schema.json
  packages/schematics/angular/migrations/update-9/ivy-libraries_spec.ts
  packages/schematics/angular/migrations/update-9/remove-tsickle_spec.ts
  packages/schematics/angular/module/index.ts
  packages/schematics/angular/module/schema.json
  packages/schematics/angular/ng-new/schema.json
  packages/schematics/angular/pipe/schema.json
  packages/schematics/angular/resolver/schema.json
  packages/schematics/angular/service-worker/schema.json
  packages/schematics/angular/service/schema.json
  packages/schematics/angular/universal/schema.json
  packages/schematics/angular/web-worker/schema.json
  packages/schematics/angular/workspace/schema.json
Labels: action: merge, cla: yes, target: major

#20226 test(@ngtools/webpack): delete disabled test-app-weird and server-app
  tests/legacy-cli/e2e/assets/webpack/test-app-weird/aotplugin.config.json
  tests/legacy-cli/e2e/assets/webpack/test-app-weird/not/so/source/app/app.component.html
  tests/legacy-cli/e2e/assets/webpack/test-app-weird/not/so/source/app/app.component.scss
  tests/legacy-cli/e2e/assets/webpack/test-app-weird/not/so/source/app/app.component.ts
  tests/legacy-cli/e2e/assets/webpack/test-app-weird/not/so/source/app/app.module.ts
  tests/legacy-cli/e2e/assets/webpack/test-app-weird/not/so/source/app/feature/feature.module.ts
  tests/legacy-cli/e2e/assets/webpack/test-app-weird/not/so/source/app/feature/lazy-feature.module.ts
  tests/legacy-cli/e2e/assets/webpack/test-app-weird/not/so/source/app/lazy.module.ts
  tests/legacy-cli/e2e/assets/webpack/test-app-weird/not/so/source/app/main.jit.ts
  tests/legacy-cli/e2e/assets/webpack/test-app-weird/not/so/source/index.html
  tests/legacy-cli/e2e/assets/webpack/test-app-weird/not/so/source/tsconfig.json
  tests/legacy-cli/e2e/assets/webpack/test-app-weird/package.json
  tests/legacy-cli/e2e/assets/webpack/test-app-weird/webpack.config.js
  tests/legacy-cli/e2e/assets/webpack/test-app-weird/webpack.flags.json
  tests/legacy-cli/e2e/assets/webpack/test-server-app/app/app.component.html
  tests/legacy-cli/e2e/assets/webpack/test-server-app/app/app.component.scss
  tests/legacy-cli/e2e/assets/webpack/test-server-app/app/app.component.ts
  tests/legacy-cli/e2e/assets/webpack/test-server-app/app/app.module.ts
  tests/legacy-cli/e2e/assets/webpack/test-server-app/app/feature/feature.module.ts
  tests/legacy-cli/e2e/assets/webpack/test-server-app/app/feature/lazy-feature.module.ts
  tests/legacy-cli/e2e/assets/webpack/test-server-app/app/injectable.ts
  tests/legacy-cli/e2e/assets/webpack/test-server-app/app/lazy.module.ts
  tests/legacy-cli/e2e/assets/webpack/test-server-app/app/main.commonjs.ts
  tests/legacy-cli/e2e/assets/webpack/test-server-app/app/main.ts
  tests/legacy-cli/e2e/assets/webpack/test-server-app/index.html
  tests/legacy-cli/e2e/assets/webpack/test-server-app/index.js
  tests/legacy-cli/e2e/assets/webpack/test-server-app/package.json
  tests/legacy-cli/e2e/assets/webpack/test-server-app/tsconfig.json
  tests/legacy-cli/e2e/assets/webpack/test-server-app/webpack.config.js
  tests/legacy-cli/e2e/tests/packages/webpack/server-app.ts
  tests/legacy-cli/e2e/tests/packages/webpack/weird-app.ts
Labels: action: merge, cla: yes, target: patch

#20228 fix(@angular/cli): avoid exceptions for expected errors in architect commands
  packages/angular/cli/commands/deploy-impl.ts
  packages/angular/cli/models/architect-command.ts
  packages/angular/cli/models/command.ts
Labels: action: merge, cla: yes, target: major

#20234 feat(@angular/cli): confirm ng add action before installation
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/commands/add.json
  packages/angular/cli/utilities/prompt.ts
  tests/legacy-cli/e2e/tests/build/material.ts
  tests/legacy-cli/e2e/tests/commands/add/add-material.ts
  tests/legacy-cli/e2e/tests/commands/add/add-pwa-yarn.ts
  tests/legacy-cli/e2e/tests/commands/add/add-pwa.ts
  tests/legacy-cli/e2e/tests/commands/add/add-version.ts
  tests/legacy-cli/e2e/tests/commands/add/add.ts
  tests/legacy-cli/e2e/tests/commands/add/dir.ts
  tests/legacy-cli/e2e/tests/commands/add/file.ts
  tests/legacy-cli/e2e/tests/commands/add/peer.ts
  tests/legacy-cli/e2e/tests/commands/add/registry-option.ts
  tests/legacy-cli/e2e/tests/commands/add/version-specifier.ts
  tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts
Labels: action: merge, cla: yes, target: major

#20236 perf(@ngtools/webpack): avoid adding transitive dependencies to Webpack's dependency graph
  packages/ngtools/webpack/src/ivy/host.ts
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: action: merge, cla: yes, target: major

#20241 fix(@schematics/angular): remove references to the prod flag
  integration/angular_cli/src/app/app.component.html
  integration/angular_cli/src/environments/environment.ts
  packages/schematics/angular/application/files/src/environments/environment.ts.template
  packages/schematics/angular/application/other-files/app.component.html.template
Labels: action: merge, cla: yes, target: major

#20237 perf(@ngtools/webpack): avoid full compiler lazy route analysis on JIT rebuilds
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: cla: yes, target: patch

#20247 [11.2.x] perf(@ngtools/webpack): avoid adding transitive dependencies to Webpack's dependency graph
  packages/ngtools/webpack/src/ivy/host.ts
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: action: merge, cla: yes, target: patch

#20245 build: update Angular CLI repo to use ES2019
  tsconfig.json
Labels: action: merge, cla: yes, target: major

#20249 fix(@angular/cli): remove `project` from required properties in ng-packagr schema
  packages/angular/cli/lib/config/schema.json
Labels: action: merge, cla: yes, target: patch

#20221 build: automate @angular/cli schema.json generation
  packages/angular/cli/BUILD.bazel
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/lib/config/schema.json
  packages/angular/cli/lib/config/workspace-schema.json
  packages/angular/cli/utilities/install-package.ts
  packages/angular/cli/utilities/package-manager.ts
  scripts/build-schema.ts
  scripts/build.ts
  tools/BUILD.bazel
  tools/ng_cli_schema_generator.bzl
  tools/ng_cli_schema_generator.js
Labels: action: merge, cla: yes, target: major

#20242 fix(@angular-devkit/build-angular): display correct filename for bundles that are ES2016+
  packages/angular_devkit/build_angular/src/utils/bundle-calculator.ts
  packages/angular_devkit/build_angular/src/utils/bundle-calculator_spec.ts
Labels: action: merge, cla: yes, target: patch

#20252 fix(@angular-devkit/build-angular): don't load an input sourcemap from file when using Babel
  packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
Labels: action: merge, cla: yes, target: patch

#20262 perf(@angular-devkit/build-angular): skip FESM2015 from `async` transformation
  packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
Labels: action: merge, cla: yes, target: patch

#20250 perf(@ngtools/webpack): use precalculated dependencies in unused file check
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: action: merge, cla: yes, target: major

#20251 [11.2.x] perf(@ngtools/webpack): use precalculated dependencies in unused file check
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: action: merge, cla: yes, target: patch

#20267 perf(@angular-devkit/build-angular): remove Webpack Stats.toJson usage in analytics plugin
  packages/angular_devkit/build_angular/src/webpack/plugins/analytics.ts
Labels: action: merge, cla: yes, target: patch

#20264 perf(@angular-devkit/build-angular): remove Webpack Stats.toJson usage in karma plugin
  packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma.ts
Labels: action: merge, cla: yes, target: patch

#20274 fix(@schematics/angular): fix youtube icon margin
  packages/schematics/angular/application/other-files/app.component.html.template
Labels: action: merge, cla: yes, target: patch

#20272 refactor(@angular-devkit/build-angular): clean up linker detection code
  packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
Labels: action: merge, cla: yes, target: major

#20273 perf(@angular-devkit/build-angular): enforce Babel not to load sourcemaps from file
  packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
Labels: action: merge, cla: yes, target: patch

#20275 fix(@schematics/angular): only show legacy browsers deprecation warning when option is used
  packages/schematics/angular/ng-new/index.ts
Labels: cla: yes, target: major

#20282 fix(@schematics/angular): remove Native value from viewEncapsulation option
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/component/schema.json
  packages/schematics/angular/ng-new/schema.json
Labels: action: merge, cla: yes, target: patch

#20211 refactor(@ngtools/webpack): reduce complexity of resource loader processing
  packages/ngtools/webpack/src/resource_loader.ts
Labels: action: merge, cla: yes, target: major

#20292 fix(@angular-devkit/build-angular): support writing large Webpack stat output
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/babel-bazel.d.ts
  packages/angular_devkit/build_angular/src/typings.d.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  tsconfig.json
  yarn.lock
Labels: action: merge, cla: yes, target: major

#20295 fix(@ngtools/webpack): remove Webpack 5 deprecation warning in resource loader
  packages/ngtools/webpack/src/resource_loader.ts
Labels: action: merge, cla: yes, target: major

#20296 test(@angular-devkit/build-angular): avoid crashing during test failure in utility function
  packages/angular_devkit/build_angular/src/test-utils.ts
Labels: action: merge, cla: yes, target: patch

#20301 test(@angular/cli): add `ng add` e2e tests to yarn subset
  .circleci/config.yml
  tests/legacy-cli/e2e/tests/commands/add/add-pwa-yarn.ts
Labels: action: merge, cla: yes, target: major

#20294 feat(@angular-devkit/build-angular): expose legacy-migrate message format
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/extract-i18n/schema.json
Labels: action: merge, cla: yes, target: major

#20304 [11.2.x] test(@angular/cli): add `ng add` e2e tests to yarn subset
  .circleci/config.yml
  tests/legacy-cli/e2e/tests/commands/add/add-pwa-yarn.ts
Labels: action: merge, cla: yes, target: patch

#20305 [11.2.x] fix(@angular-devkit/build-angular): support writing large Webpack stat outputs
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/babel-bazel.d.ts
  packages/angular_devkit/build_angular/src/typings.d.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  tsconfig.json
  yarn.lock
Labels: action: merge, cla: yes, target: patch

#20307 test(@angular/cli): fully test update process in update from v8 E2E
  tests/legacy-cli/e2e/tests/update/update-8.ts
Labels: cla: yes, target: major

#20314 fix(@schematics/angular): use title for svg on home page
  packages/schematics/angular/application/other-files/app.component.html.template
Labels: action: merge, cla: yes, target: patch

#20306 doc: update `yarn` command to freeze lockfile.
  docs/process/release.md
Labels: action: merge, cla: yes, target: major

#20318 feat(@angular-devkit/build-angular): integrate JIT mode linker
  packages/angular_devkit/build_angular/src/babel/presets/application.ts
  packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  tests/legacy-cli/e2e/tests/generate/library/library-consumption-linker.ts
Labels: action: merge, cla: yes, target: major

#20321 ci: fix component-path-case E2E test on Windows CI
  tests/legacy-cli/e2e/tests/generate/component/component-path-case.ts
Labels: action: merge, cla: yes, target: patch

#20311 build: update changelog to include perf commits
  scripts/templates/changelog-commit.ejs
  scripts/templates/changelog-feat.ejs
  scripts/templates/changelog.ejs
Labels: action: merge, cla: yes, target: patch

#20323 build: sort changelog by commit message scope
  scripts/templates/changelog.ejs
Labels: action: merge, cla: yes, target: patch

#20339 perf(@ngtools/webpack): reduce resource processing during JIT initial lazy route analysis
  packages/ngtools/webpack/src/ivy/host.ts
  packages/ngtools/webpack/src/ivy/plugin.ts
  packages/ngtools/webpack/src/resource_loader.ts
Labels: action: merge, cla: yes, target: patch

#20332 fix(@schematics/angular): remove leftover workspace tslint config
  packages/schematics/angular/workspace/files/tslint.json.template
  packages/schematics/angular/workspace/index.ts
  packages/schematics/angular/workspace/index_spec.ts
  tests/legacy-cli/e2e/tests/commands/new/new-minimal.ts
Labels: action: merge, cla: yes, target: major

#20350 fix(@angular-devkit/build-angular): ensure output directory is present before writing stats JSON
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: action: merge, cla: yes, target: patch

#20233 feat(@schematics/angular): add production by default optional migration
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-12/production-default-config.ts
  packages/schematics/angular/migrations/update-12/production-default-config_spec.ts
  packages/schematics/angular/utility/workspace-models.ts
Labels: action: merge, cla: yes, target: major

#20353 build: determine release version from package.json instead of git tag
  docs/process/release.md
  lib/packages.ts
  package.json
  packages/schematics/angular/utility/latest-versions.ts
  scripts/packages.ts
  scripts/publish.ts
Labels: action: merge, cla: yes, target: patch

#20366 feat(@schematics/angular): update new workspaces to use Karma 6.3
  packages/schematics/angular/workspace/files/package.json.template
Labels: action: merge, cla: yes, target: major

#20368 build: determine version to publish from package.json
  docs/process/release.md
  lib/packages.ts
  package.json
  packages/schematics/angular/utility/latest-versions.ts
  scripts/packages.ts
  scripts/publish.ts
Labels: cla: yes, target: patch

#20369 build: bump version to v12.0.0-next.7
  package.json
  packages/schematics/angular/utility/latest-versions.ts
Labels: action: merge, cla: yes, target: major

#20370 build: bump version to v11.2.7
  package.json
  packages/schematics/angular/utility/latest-versions.ts
Labels: action: merge, cla: yes, target: patch

#20348 perf(@ngtools/webpack): only check affected files for Angular semantic diagnostics
  packages/angular_devkit/build_angular/src/browser/tests/behavior/rebuild-errors_spec.ts
  packages/angular_devkit/build_angular/test/hello-world-app/tsconfig.json
  packages/ngtools/webpack/src/ivy/cache.ts
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: action: merge, cla: yes, target: major

#20361 fix(@angular-devkit/build-angular): validate scripts and styles bundleName
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/karma/schema.json
Labels: action: merge, cla: yes, target: patch

#20396 build: removed unused benchmark utility script
  scripts/benchmark.ts
Labels: action: merge, cla: yes, target: major

#20397 fix(@angular-devkit/build-angular): remove deprecated View Engine support for i18n extraction
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/extract-i18n/schema.json
  tests/legacy-cli/e2e/tests/i18n/build-locale.ts
  tests/legacy-cli/e2e/tests/i18n/extract-default.ts
  tests/legacy-cli/e2e/tests/i18n/extract-errors.ts
  tests/legacy-cli/e2e/tests/i18n/extract-ivy-libraries.ts
  tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts
  tests/legacy-cli/e2e/tests/i18n/extract-locale.ts
  tests/legacy-cli/e2e/tests/i18n/extract-outfile.ts
  tests/legacy-cli/e2e/tests/i18n/extract-xmb.ts
  tests/legacy-cli/e2e/tests/i18n/ve-localize-es2015.ts
Labels: action: merge, cla: yes, target: major

#20401 build: update to critters 0.0.10
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
  yarn.lock
Labels: action: merge, cla: yes, target: major

#20403 refactor(@angular/cli): remove `Ivy Workspace` from `ng version`
  packages/angular/cli/commands/version-impl.ts
  tests/legacy-cli/e2e/tests/misc/version.ts
Labels: action: merge, cla: yes, target: major

#20404 test(@angular-devkit/build-angular): clean up tests from ViewEngine code
  packages/angular_devkit/build_angular/src/browser/specs/aot_spec.ts
  packages/angular_devkit/build_angular/src/browser/specs/errors_spec.ts
  packages/angular_devkit/build_angular/src/browser/specs/i18n_spec.ts
  packages/angular_devkit/build_angular/src/browser/specs/lazy-module_spec.ts
  packages/angular_devkit/build_angular/src/browser/specs/no-entry-module_spec.ts
  packages/angular_devkit/build_angular/src/browser/specs/rebuild_spec.ts
  packages/angular_devkit/build_angular/src/browser/specs/svg_spec.ts
  packages/angular_devkit/build_angular/src/browser/specs/unused-files-warning_spec.ts
  packages/angular_devkit/build_angular/src/extract-i18n/works_spec.ts
  packages/angular_devkit/build_angular/src/ng-packagr/works_spec.ts
  packages/angular_devkit/build_angular/src/server/base_spec.ts
  packages/angular_devkit/build_angular/src/test-utils.ts
  scripts/test.ts
  tests/legacy-cli/e2e/setup/500-create-project.ts
  tests/legacy-cli/e2e/tests/basic/aot.ts
  tests/legacy-cli/e2e/tests/basic/ivy-opt-out.ts
  tests/legacy-cli/e2e/tests/basic/ivy.ts
  tests/legacy-cli/e2e/tests/basic/ngcc-es2015-only.ts
  tests/legacy-cli/e2e/tests/build/platform-server.ts
  tests/legacy-cli/e2e/tests/build/prod-build.ts
  tests/legacy-cli/e2e/tests/generate/library/library-consumption-linker.ts
  tests/legacy-cli/e2e/tests/i18n/extract-ivy-libraries.ts
  tests/legacy-cli/e2e/tests/i18n/legacy.ts
  tests/legacy-cli/e2e/tests/misc/browsers.ts
  tests/legacy-cli/e2e/tests/packages/webpack/test-app.ts
  tests/legacy-cli/e2e_runner.ts
Labels: action: merge, cla: yes, target: major

#20421 test(@ngtools/webpack): update webpack test-app E2E to use ivy plugin
  tests/legacy-cli/e2e/assets/webpack/test-app/package.json
  tests/legacy-cli/e2e/assets/webpack/test-app/webpack.config.js
Labels: action: merge, cla: yes, target: major

#20420 fix(@ngtools/webpack): use correct Webpack asset stage in resource loader
  packages/ngtools/webpack/src/resource_loader.ts
Labels: action: merge, cla: yes, target: major

#20417 test(@angular/cli): remove E2E tests which are not used
  tests/legacy-cli/e2e/tests/build/module-id.ts
  tests/legacy-cli/e2e/tests/build/service-worker.ts
  tests/legacy-cli/e2e/tests/commands/new/check-yarn.ts
  tests/legacy-cli/e2e/tests/commands/new/existing-directory.ts
  tests/legacy-cli/e2e/tests/commands/new/new-minimal.ts
  tests/legacy-cli/e2e/tests/commands/new/new-routing.ts
  tests/legacy-cli/e2e/tests/commands/new/new-skip-commit.ts
  tests/legacy-cli/e2e/tests/commands/new/new-skip-tests.ts
  tests/legacy-cli/e2e/tests/commands/new/new-style.ts
  tests/legacy-cli/e2e/tests/misc/different-file-format.ts
  tests/legacy-cli/e2e_runner.ts
Labels: action: merge, cla: yes, target: major
