Repository angular/angular-cli, pull requests merged in 2021-02, with the labels that each got.

#19915 fix(@angular/cli): remove unnecessary promise around "open"
  packages/angular/cli/commands/doc-impl.ts
Labels: action: merge, cla: yes, target: patch

#19716 ci: update to build_bazel_rules_nodejs version 3
  WORKSPACE
  etc/api/BUILD.bazel
  package.json
  packages/angular_devkit/schematics/tools/export-ref_spec.ts
  tools/BUILD.bazel
  tsconfig.json
  yarn.lock
Labels: action: merge, cla: yes, target: minor

#19916 refactor(@ngtools/webpack): use readConfiguration existingOptions ins…
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: action: merge, cla: yes, target: minor

#19922 fix(@ngtools/webpack): improve resource loader caching
  packages/ngtools/webpack/src/resource_loader.ts
Labels: action: merge, cla: yes, target: patch

#19899 fix(@ngtools/webpack): recover from component stylesheet errors
  packages/angular_devkit/build_angular/src/browser/tests/behavior/rebuild-errors_spec.ts
  packages/ngtools/webpack/src/resource_loader.ts
Labels: action: merge, cla: yes, target: patch

#19927 fix(@angular-devkit/build-angular): error with status code when response code is not 200
  packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
Labels: action: merge, cla: yes, target: patch

#19932 docs: replace broken link
  packages/schematics/angular/ng-new/schema.json
Labels: action: merge, cla: yes, target: patch

#19933 build: update puppeteer to version 6
  integration/angular_cli/package.json
  package.json
  tests/legacy-cli/e2e/utils/project.ts
  yarn.lock
Labels: action: merge, cla: yes, target: minor

#19935 feat(@angular-devkit/build-angular): detect and use tailwindcss in projects
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
  tests/legacy-cli/e2e/tests/build/styles/tailwind.ts
Labels: action: merge, cla: yes, target: minor

#19946 ci: remove `validate-do-not-submit` check
  .circleci/config.yml
  scripts/validate-do-not-submit.ts
  scripts/validate.ts
Labels: action: merge, cla: yes, target: patch

#19940 fix(@angular/cli): resolve migration collections from containing package
  packages/angular/cli/commands/update-impl.ts
Labels: action: merge, cla: yes, target: patch

#19953 fix(@ngtools/webpack): don't use `skipTemplateCodegen` to determine if compilation is JIT mode
  packages/angular_devkit/build_angular/src/webpack/configs/typescript.ts
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: action: merge, cla: yes, target: patch

#19882 refactor(@angular-devkit/build-angular): remove file-loader dependency
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  yarn.lock
Labels: action: merge, cla: yes, target: major

#19965 ci: use npm 6.x on Node.js 10 CI jobs
  .circleci/config.yml
Labels: cla: yes, target: patch

#19956 ci: remove integration job
  .circleci/config.yml
Labels: action: merge, cla: yes, target: patch

#19966 test(@angular-devkit/build-angular): add async downlevel source map unit test
  packages/angular_devkit/build_angular/src/browser/tests/behavior/typescript-target_spec.ts
Labels: action: merge, cla: yes, target: rc

#19929 fix(@angular-devkit/build-angular): remove `0.0.0` version from supported Angular semver versions error message
  packages/angular_devkit/build_angular/src/utils/version.ts
Labels: action: merge, cla: yes, target: patch

#19967 test(@angular/cli): allow invalid deps E2E to pass on release commits
  tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts
Labels: action: merge, cla: yes, target: rc

#19968 fix(@angular-devkit/build-angular): increase resilience of babel cache identifier
  packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: action: merge, cla: yes, target: rc

#19970 fix(@angular/cli): temporarily limit npm to version 6
  lib/packages.ts
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/commands/new-impl.ts
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/utilities/package-manager.ts
  tests/legacy-cli/e2e/tests/misc/npm-7.ts
Labels: cla: yes, target: patch

#19971 [11.1.x] fix(@angular/cli): temporarily limit npm to version 6
  lib/packages.ts
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/commands/new-impl.ts
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/utilities/package-manager.ts
  tests/legacy-cli/e2e/tests/misc/npm-7.ts
Labels: cla: yes, target: patch

#19973 ci: remove Node.js 10 E2E job
  .circleci/config.yml
Labels: action: merge, cla: yes, target: major

#19972 test(@angular/cli): skip npm version limit E2E on Windows
  tests/legacy-cli/e2e/tests/misc/npm-7.ts
Labels: action: merge, cla: yes, target: patch

#19984 ci: remove unused integration job from required robot checks
  .github/angular-robot.yml
Labels: action: merge, cla: yes, target: patch

#19981 fix(@angular/cli): only show incompatible NPM error when NPM is used as package manager
  packages/angular/cli/commands/add-impl.ts
  packages/angular/cli/commands/new-impl.ts
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/utilities/package-manager.ts
Labels: action: merge, cla: yes, target: patch

#19983 build: set minimum Node.js version to 12.13
  .circleci/config.yml
  lib/packages.ts
  package.json
  packages/angular/cli/bin/ng
  packages/angular_devkit/benchmark/package.json
Labels: action: merge, cla: yes, target: major

#19994 fix(@angular-devkit/build-angular): fixed ignoring of karma plugins config
  packages/angular_devkit/build_angular/src/karma/code-coverage_spec.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma.ts
Labels: action: merge, cla: yes, target: patch

#19995 fix(@angular-devkit/build-angular): the root Tailwind configuration f…
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: action: merge, cla: yes, target: rc

#19991 docs: update ESLint migration link
  packages/angular/cli/commands/lint-long.md
  packages/angular_devkit/build_angular/src/tslint/index.ts
Labels: action: merge, cla: yes, target: patch, type: docs

#20000 fix(@angular-devkit/build-angular): ensure i18n extraction sourcemaps are fully configured
  packages/angular_devkit/build_angular/src/extract-i18n/index.ts
Labels: action: merge, cla: yes, target: patch

#20003 fix(@angular/cli): update NPM 7 guidance
  packages/angular/cli/commands/new-impl.ts
  packages/angular/cli/models/schematic-command.ts
  packages/angular/cli/utilities/package-manager.ts
  tests/legacy-cli/e2e/tests/misc/npm-7.ts
Labels: action: merge, cla: yes, target: patch

#20002 ci: only validate PR commit messages
  scripts/validate.ts
Labels: action: merge, cla: yes, target: lts

#20001 ci: fix component-child-dir E2E test on Windows CI
  tests/legacy-cli/e2e/tests/generate/component/component-child-dir.ts
Labels: action: merge, cla: yes, target: patch

#19980 feat(@angular-devkit/build-angular): add `postcss-preset-env` with stage 3 features
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
  tests/legacy-cli/e2e/tests/build/styles/preset-env.ts
  yarn.lock
Labels: action: merge, cla: yes, target: major

#20011 ci: only validate PR commit messages and remove do not submit check
  .circleci/config.yml
Labels: cla: yes, target: lts

#20017 refactor(@angular-devkit/build-angular): remove use of Webpack RuleSetLoader type
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
  packages/angular_devkit/build_angular/src/webpack/configs/typescript.ts
Labels: action: merge, cla: yes, target: major

#20019 [10.2.x] ci: provide names for nightly E2E jobs
  .circleci/config.yml
Labels: cla: yes, target: lts

#20029 feat(@schematics/angular): strict mode by default
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/ng-new/schema.json
  packages/schematics/angular/workspace/schema.json
  tests/legacy-cli/e2e/tests/build/strict-mode.ts
Labels: cla: yes, target: major

#20016 refactor(@angular-devkit/build-angular): remove usage of Webpack Stats.ToJsonOutput type
  packages/angular_devkit/build_angular/src/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/bundle-calculator.ts
  packages/angular_devkit/build_angular/src/utils/bundle-calculator_spec.ts
  packages/angular_devkit/build_angular/src/webpack/utils/async-chunks.ts
  packages/angular_devkit/build_angular/src/webpack/utils/async-chunks_spec.ts
  packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
Labels: action: merge, cla: yes, target: major

#20033 fix(@angular/cli): improve error logging when resolving update migrations
  packages/angular/cli/commands/update-impl.ts
Labels: action: merge, cla: yes, target: patch

#20027 Update several dependencies
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  yarn.lock
Labels: cla: yes, target: major

#20040 build: changer angular packages local version to `0.0.0`
  packages/angular_devkit/build_angular/src/utils/version.ts
Labels: action: merge, cla: yes, target: patch

#20046 build: update critters to version 0.0.7
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: action: merge, cla: yes, target: patch

#20047 Switch angular.io from HTTP to HTTPS
  packages/angular/cli/models/analytics.ts
Labels: action: merge, cla: yes, target: patch

#20049 feat(@angular-devkit/build-optimizer): support Webpack 5
  etc/api/angular_devkit/build_optimizer/src/_golden-api.d.ts
  packages/angular_devkit/build_optimizer/package.json
  packages/angular_devkit/build_optimizer/src/build-optimizer/webpack-loader.ts
  packages/angular_devkit/build_optimizer/src/build-optimizer/webpack-plugin.ts
Labels: action: merge, cla: yes, target: major

#20051 fix(@angular/cli): ensure odd number Node.js version message is a warning
  packages/angular/cli/bin/ng
Labels: action: merge, cla: yes, target: major

#20066 fix(@angular/cli): support update migration packages with no entry points
  packages/angular/cli/commands/update-impl.ts
Labels: action: merge, cla: yes, target: patch

#20082 docs: replace Minko with Joey as secondary caretaker
  docs/process/release.md
Labels: action: merge, cla: yes, target: major

#20065 refactor(@angular-devkit/build-optimizer): improve transitional Webpack 5 compatibility
  etc/api/angular_devkit/build_optimizer/src/_golden-api.d.ts
  packages/angular_devkit/build_optimizer/package.json
  packages/angular_devkit/build_optimizer/src/build-optimizer/webpack-plugin.ts
  packages/angular_devkit/build_optimizer/src/webpack.d.ts
Labels: action: merge, cla: yes, target: major

#20077 build: exclude workspace json test files from core package
  scripts/build.ts
Labels: action: merge, cla: yes, target: patch

#20078 fix(@ngtools/webpack): normalize paths when pruning AOT rebuild requests
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: action: merge, cla: yes, target: patch

#20026 feat(@schematics/angular): add migration to remove emitDecoratorMetadata
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-12/remove-emit-decorator-metadata.ts
  packages/schematics/angular/migrations/update-12/remove-emit-decorator-metadata_spec.ts
Labels: action: merge, cla: yes, target: major

#19869 feat(@schematics/angular): augment `universal` schematics to import `platform-server` shims
  packages/schematics/angular/universal/files/src/__main@stripTsExtension__.ts.template
  packages/schematics/angular/universal/index_spec.ts
Labels: action: merge, cla: yes, comp: schematics/angular, target: major, type: bug/fix

#20097 fix(@angular-devkit/build-angular): force less version 3.5 math behaviour
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: action: merge, cla: yes, target: patch

#20099 test(@angular-devkit/build-angular): add browser builder namedChunks option tests
  packages/angular_devkit/build_angular/src/browser/specs/lazy-module_spec.ts
  packages/angular_devkit/build_angular/src/browser/tests/options/named-chunks_spec.ts
Labels: action: merge, cla: yes, target: major

#20109 feat(@schematics/angular): update new project dependencies versions
  packages/schematics/angular/workspace/files/package.json.template
Labels: cla: yes, target: major

#20110 fix(@angular-devkit/build-angular): disable declaration and declarationMap
  packages/angular_devkit/build_angular/src/webpack/configs/typescript.ts
Labels: action: merge, cla: yes, target: patch

#20117 test(@angular-devkit/build-angular): avoid loading dev typings in unit test
  packages/angular_devkit/build_angular/src/browser/tests/options/tsconfig_spec.ts
Labels: action: merge, cla: yes, target: patch

#20116 refactor(@ngtools/webpack): initialize paths plugin in resolve options hook
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: action: merge, cla: yes, target: major

#20098 docs: fix build-system-overview graph
  docs/design/build-system-overview.dot
Labels: action: merge, cla: yes, target: patch

#20127 build: update to rules_nodejs@3.2.1
  WORKSPACE
  package.json
  yarn.lock
Labels: action: merge, cla: yes, comp: build & ci, target: major

#20124 fix(@angular-devkit/build-angular): only show index and service worker status once
  packages/angular_devkit/build_angular/src/browser/index.ts
Labels: action: merge, cla: yes, target: patch

#20132 fix(@angular/cli): remove npm 7 incompatibility notification
  lib/packages.ts
  packages/angular/cli/utilities/package-manager.ts
  tests/legacy-cli/e2e/tests/misc/npm-7.ts
Labels: action: merge, cla: yes, target: major

#20133 [11.2.x] fix(@angular/cli): remove npm 7 incompatibility notification
  lib/packages.ts
  packages/angular/cli/utilities/package-manager.ts
  tests/legacy-cli/e2e/tests/misc/npm-7.ts
Labels: action: merge, cla: yes, target: patch

#20134 [9.1.x] fix(@angular/cli): remove npm 7 incompatibility notification
  lib/packages.ts
  packages/angular/cli/commands/new-impl.ts
  packages/angular/cli/models/schematic-command.ts
  packages/angular/cli/utilities/package-manager.ts
  tests/legacy-cli/e2e/tests/misc/npm-7.ts
Labels: action: merge, cla: yes, target: lts

#20135 [10.2.x] fix(@angular/cli): remove npm 7 incompatibility notification
  lib/packages.ts
  packages/angular/cli/commands/new-impl.ts
  packages/angular/cli/models/schematic-command.ts
  packages/angular/cli/utilities/package-manager.ts
  tests/legacy-cli/e2e/tests/misc/npm-7.ts
Labels: action: merge, cla: yes, target: lts

#20137 test: install latest packages from local registry
  tests/legacy-cli/e2e/tests/misc/npm-7.ts
Labels: cla: yes, target: lts

#20138 test: install latest packages from local registry
  tests/legacy-cli/e2e/tests/misc/npm-7.ts
Labels: cla: yes, target: lts

#20139 fix(@schematics/angular): update ng new links
  packages/schematics/angular/application/other-files/app.component.html.template
Labels: action: merge, cla: yes, target: patch

#20144 build: update to rules_nodejs@3.2.1
  WORKSPACE
  package.json
  yarn.lock
Labels: action: merge, cla: yes, comp: build & ci, target: patch

#20136 docs: use specific `git add` command to avoid adding unnecessary files
  docs/process/release.md
Labels: action: merge, cla: yes, target: major, type: docs

#20146 refactor(@angular/cli): remove v1 postinstall update check
  packages/angular/cli/bin/postinstall/ng-update-message.js
  packages/angular/cli/bin/postinstall/script.js
Labels: action: merge, cla: yes, target: major

#20148 test(@angular/cli): reuse chrome/chromedriver in E2E tests
  tests/legacy-cli/e2e/tests/basic/e2e.ts
  tests/legacy-cli/e2e/tests/commands/add/add-pwa-yarn.ts
  tests/legacy-cli/e2e/tests/generate/library/library-consumption-linker.ts
  tests/legacy-cli/e2e/tests/misc/webpack-5.ts
  tests/legacy-cli/e2e/tests/update/update-8.ts
  tests/legacy-cli/e2e/utils/assets.ts
  tests/legacy-cli/e2e/utils/packages.ts
  tests/legacy-cli/e2e/utils/project.ts
Labels: action: merge, cla: yes, target: patch

#20145 build: bump typescript to 4.1.5 due to security issue
  package.json
  packages/angular_devkit/build_optimizer/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/schematics/schematic/files/package.json
  yarn.lock
Labels: action: merge, cla: yes, target: patch

#20143 ci: use CircleCI matrix support for E2E jobs
  .circleci/config.yml
  .circleci/env.sh
Labels: action: merge, cla: yes, target: major

#20155 [11.2.x] test(@angular/cli): reuse chrome/chromedriver in E2E tests
  tests/legacy-cli/e2e/tests/basic/e2e.ts
  tests/legacy-cli/e2e/tests/commands/add/add-pwa-yarn.ts
  tests/legacy-cli/e2e/tests/generate/library/library-consumption-linker.ts
  tests/legacy-cli/e2e/tests/misc/webpack-5.ts
  tests/legacy-cli/e2e/tests/update/update-8.ts
  tests/legacy-cli/e2e/utils/assets.ts
  tests/legacy-cli/e2e/utils/packages.ts
  tests/legacy-cli/e2e/utils/project.ts
Labels: cla: yes, target: patch

#20142 test(@angular/cli): centralize E2E test registry configuration
  tests/legacy-cli/e2e/setup/010-local-publish.ts
  tests/legacy-cli/e2e/setup/100-global-cli.ts
  tests/legacy-cli/e2e/setup/500-create-project.ts
  tests/legacy-cli/e2e/tests/commands/add/registry-option.ts
  tests/legacy-cli/e2e/tests/misc/ask-analytics-install.ts
  tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts
  tests/legacy-cli/e2e/tests/misc/npm-7.ts
  tests/legacy-cli/e2e/tests/misc/webpack-5.ts
  tests/legacy-cli/e2e/tests/schematics_cli/basic.ts
  tests/legacy-cli/e2e/tests/schematics_cli/blank-test.ts
  tests/legacy-cli/e2e/tests/schematics_cli/schematic-test.ts
  tests/legacy-cli/e2e/utils/assets.ts
  tests/legacy-cli/e2e/utils/project.ts
  tests/legacy-cli/e2e_runner.ts
Labels: action: merge, cla: yes, target: patch

#20157 [10.2.x] test(@angular/cli): reuse chrome/chromedriver in E2E tests
  tests/legacy-cli/e2e/tests/basic/e2e.ts
  tests/legacy-cli/e2e/tests/commands/add/add-pwa-yarn.ts
  tests/legacy-cli/e2e/utils/project.ts
Labels: cla: yes, target: lts

#20096 feat(@angular-devkit/build-angular): enable inlineCritical by default
  packages/angular/cli/lib/config/schema.json
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/utils/normalize-optimization.ts
Labels: action: merge, cla: yes, target: major

#20159 fix(@angular-devkit/build-angular): inline critical font-face rules when using critical css inlining
  packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
Labels: action: merge, cla: yes, target: patch

#20158 [9.1.x] test(@angular/cli): reuse chrome/chromedriver in E2E tests
  .circleci/config.yml
  tests/legacy-cli/e2e/tests/basic/e2e.ts
  tests/legacy-cli/e2e/tests/commands/add/add-pwa-yarn.ts
  tests/legacy-cli/e2e/utils/project.ts
Labels: cla: yes, target: lts
