Repository angular/angular-cli, pull requests merged in 2022-06, with the labels that each got.

#23237 docs: update major release instructions to mention `latest-versions.ts` bump
  docs/process/release.md
Labels: action: merge, target: minor

#23270 Bump version to "v14.0.0" with changelog.
  CHANGELOG.md
  package.json
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/angular/utility/latest-versions/package.json
Labels: target: major, action: merge

#23268 test(@angular/cli): force using `NPM_CONFIG_legacy_peer_deps` for `ng add` NPM 7 test
  tests/legacy-cli/e2e/tests/misc/npm-7.ts
Labels: action: merge, target: minor

#23253 fix(@schematics/angular): remove strict setting under application project
  packages/schematics/angular/application/index.ts
Labels: target: patch, action: merge

#23262 test: keep npm servers alive while in debug state
  tests/legacy-cli/e2e_runner.ts
Labels: action: merge, target: minor

#23271 docs: release notes for the v14.0.0 release
  CHANGELOG.md
Labels: action: merge, target: minor

#23286 refactor(@angular-devkit/build-angular): remove unneeded TypeScript transforms with esbuild
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
Labels: target: patch, action: merge

#23281 fix(@angular/cli): correct scope cache command
  packages/angular/cli/src/commands/cache/clean/cli.ts
  packages/angular/cli/src/commands/cache/cli.ts
  packages/angular/cli/src/commands/cache/info/cli.ts
  packages/angular/cli/src/commands/cache/settings/cli.ts
Labels: target: patch, action: merge

#23283 fix(@angular/cli): add text to help output to indicate that additional commands are available when ran in different context
  packages/angular/cli/src/command-builder/command-runner.ts
Labels: target: patch, action: merge

#23265 fix(@angular/cli): avoid creating unnecessary global configuration
  packages/angular/cli/src/command-builder/command-module.ts
  packages/angular/cli/src/command-builder/command-runner.ts
  packages/angular/cli/src/command-builder/schematics-command-module.ts
  packages/angular/cli/src/commands/config/cli.ts
  packages/angular/cli/src/utilities/config.ts
  packages/angular/cli/src/utilities/package-manager.ts
Labels: target: patch, action: merge

#23277 build: update angular
  .github/workflows/dev-infra.yml
  .github/workflows/feature-requests.yml
  .github/workflows/lock-closed.yml
  package.json
  packages/ngtools/webpack/package.json
  yarn.lock
Labels: target: patch, action: merge

#23296 fix(@angular/cli): improve resilience of logging during process exit
  packages/angular/cli/lib/cli/index.ts
  tests/legacy-cli/e2e/tests/misc/completion-script.ts
Labels: target: patch, action: merge

#23245 run e2e tests in isolated child processes
  tests/legacy-cli/BUILD.bazel
  tests/legacy-cli/e2e/initialize/300-log-environment.ts
  tests/legacy-cli/e2e/initialize/500-create-project.ts
  tests/legacy-cli/e2e/initialize/BUILD.bazel
  tests/legacy-cli/e2e/setup/002-npm-sandbox.ts
  tests/legacy-cli/e2e/setup/100-global-cli.ts
  tests/legacy-cli/e2e/tests/basic/e2e.ts
  tests/legacy-cli/e2e/tests/packages/webpack/test-app.ts
  tests/legacy-cli/e2e/utils/env.ts
  tests/legacy-cli/e2e/utils/process.ts
  tests/legacy-cli/e2e/utils/project.ts
  tests/legacy-cli/e2e/utils/run_test_process.js
  tests/legacy-cli/e2e/utils/test_process.ts
  tests/legacy-cli/e2e_runner.ts
Labels: action: merge, target: minor

#23309 ci: disable outdated Angular robot merge and triage behavior
  .github/angular-robot.yml
Labels: action: merge, target: minor

#23312 test: wait for killAllProcesses() to complete before proceeding
  tests/legacy-cli/e2e/tests/misc/fallback.ts
Labels: target: minor

#23307 fix(@angular/pwa): add peer dependency on Angular CLI
  packages/angular/pwa/package.json
Labels: target: patch, action: merge

#23306 test(@angular/cli): move `completion` command test in own directory
  tests/legacy-cli/e2e/tests/commands/completion/completion-prompt.ts
  tests/legacy-cli/e2e/tests/commands/completion/completion-script.ts
  tests/legacy-cli/e2e/tests/commands/completion/completion.ts
Labels: target: patch, action: merge

#23302 fix(@angular/cli): provide actionable error when project cannot be determined
  packages/angular/cli/src/command-builder/architect-command-module.ts
  tests/legacy-cli/e2e/tests/commands/project-cannot-be-determined-by-cwd.ts
Labels: target: patch, action: merge

#23314 fix(@angular-devkit/build-angular): update Angular peer dependencies to 14.0 stable
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  yarn.lock
Labels: target: patch, action: merge

#23318 fix(@angular-devkit/build-angular): log modified and removed files when using the `verbose` option
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/verbose_spec.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/watch-files-logs-plugin.ts
Labels: target: patch, action: merge

#23321 fix(@angular/cli): correctly print package manager name when an install is needed
  packages/angular/cli/src/command-builder/architect-base-command-module.ts
  tests/legacy-cli/e2e/tests/commands/builder-not-found.ts
Labels: target: patch, action: merge

#23323 Bump version to "v14.0.1" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#23324 docs: release notes for the v14.0.1 release
  CHANGELOG.md
Labels: action: merge

#23325 Bump version to "v14.1.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, target: minor

#23299 test: reduce use of npmrc for test npm configuration
  tests/legacy-cli/e2e/setup/002-npm-sandbox.ts
  tests/legacy-cli/e2e/tests/commands/add/registry-option.ts
  tests/legacy-cli/e2e/utils/packages.ts
Labels: action: merge, target: minor

#23340 refactor(@angular/cli): assert catch clause variable type before usage
  packages/angular/cli/lib/cli/index.ts
  packages/angular/cli/src/analytics/analytics.ts
  packages/angular/cli/src/command-builder/architect-base-command-module.ts
  packages/angular/cli/src/command-builder/command-runner.ts
  packages/angular/cli/src/command-builder/schematics-command-module.ts
  packages/angular/cli/src/command-builder/utilities/schematic-engine-host.ts
  packages/angular/cli/src/commands/add/cli.ts
  packages/angular/cli/src/commands/completion/cli.ts
  packages/angular/cli/src/commands/update/cli.ts
  packages/angular/cli/src/commands/update/schematic/index.ts
  packages/angular/cli/src/utilities/completion.ts
  packages/angular/cli/src/utilities/error.ts
Labels: action: merge, target: minor

#23336 test: split module resolutions E2E in multiple tests
  tests/legacy-cli/e2e/tests/misc/module-resolution.ts
  tests/legacy-cli/e2e/tests/misc/module-resolution/module-resolution-core-mapping.ts
  tests/legacy-cli/e2e/tests/misc/module-resolution/module-resolution-firebase.ts
Labels: target: patch, action: merge

#23345 test: reduce disk-cache E2E tests duration
  tests/legacy-cli/e2e/tests/build/disk-cache-purge.ts
  tests/legacy-cli/e2e/tests/build/disk-cache.ts
Labels: target: patch, action: merge

#23332 ci: increase parallelism for Linux E2E
  .circleci/config.yml
Labels: target: patch, action: merge

#23371 fix(@schematics/angular): remove vscode testing configurations for `minimal` workspaces
  packages/schematics/angular/workspace/files/__dot__vscode/launch.json.template
  packages/schematics/angular/workspace/files/__dot__vscode/tasks.json.template
  packages/schematics/angular/workspace/index_spec.ts
Labels: target: patch, action: merge

#23380 Bump version to "v14.0.2" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#23381 docs: release notes for the v14.0.2 release
  CHANGELOG.md
Labels: action: merge, target: minor

#23382 Bump version to "v14.1.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: minor

#23375 fix(@angular/cli): disable version check when running `ng completion` commands
  packages/angular/cli/lib/init.ts
Labels: target: patch, action: merge

#23386 build: mark external only bazel rules
  packages/angular/cli/BUILD.bazel
  packages/angular_devkit/architect/BUILD.bazel
  packages/angular_devkit/core/BUILD.bazel
  packages/angular_devkit/schematics/BUILD.bazel
Labels: target: patch, action: merge

#23394 build: mark external only bazel rules
  packages/angular/cli/BUILD.bazel
  packages/angular_devkit/architect/BUILD.bazel
  packages/angular_devkit/core/BUILD.bazel
  packages/angular_devkit/schematics/BUILD.bazel
Labels: action: merge, target: lts

#23393 build: update `ng-dev` setup to work with new ESM version
  .ng-dev/caretaker.mts
  .ng-dev/commit-message.mts
  .ng-dev/commit-message.ts
  .ng-dev/config.mts
  .ng-dev/config.ts
  .ng-dev/format.mts
  .ng-dev/github.mts
  .ng-dev/pull-request.mts
  .ng-dev/release.mts
  .ng-dev/tsconfig.json
  package.json
  scripts/templates.ts
  scripts/templates/contributing.ejs
  yarn.lock
Labels: action: merge, target: minor

#23395 build: update `ng-dev` setup to work with new ESM version
  .ng-dev/caretaker.mts
  .ng-dev/commit-message.mts
  .ng-dev/commit-message.ts
  .ng-dev/config.mts
  .ng-dev/config.ts
  .ng-dev/format.mts
  .ng-dev/github.mts
  .ng-dev/pull-request.mts
  .ng-dev/release.mts
  .ng-dev/tsconfig.json
  package.json
  scripts/templates.ts
  scripts/templates/contributing.ejs
  yarn.lock
Labels: target: patch, action: merge

#23401 fix(@angular-devkit/build-angular): fix incorrect glob cwd in karma when using `--include` option
  packages/angular_devkit/build_angular/src/builders/karma/index.ts
  tests/legacy-cli/e2e/tests/test/test-include-glob.ts
Labels: target: patch, action: merge

#23399 build: ensure ng-dev command works on windows
  package.json
Labels: target: patch, action: merge

#23422 build: avoid use of ts-node wrapper script as it breaks child process forking
  package.json
  yarn.lock
Labels: action: merge, target: minor

#23421 fix(@angular-devkit/build-angular): ignore supported browsers during i18n extraction
  packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
  packages/angular_devkit/build_angular/src/builders/extract-i18n/index.ts
Labels: target: patch, action: merge

#23424 build: avoid use of ts-node wrapper script as it breaks child process forking
  package.json
  yarn.lock
Labels: target: patch, action: merge

#23425 Bump version to "v14.0.3" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#23426 docs: release notes for the v14.0.3 release
  CHANGELOG.md
Labels: action: merge, target: minor

#23427 Bump version to "v14.1.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: minor

#23326 test: do not depend on a global npm binary
  package.json
  tests/legacy-cli/e2e/setup/010-local-publish.ts
  tests/legacy-cli/e2e/setup/100-global-cli.ts
  tests/legacy-cli/e2e/utils/BUILD.bazel
  tests/legacy-cli/e2e/utils/process.ts
  tests/legacy-cli/e2e_runner.ts
  yarn.lock
Labels: action: merge, target: minor

#23404 fix(@angular/cli): prevent schema validation error
  packages/angular/cli/lib/config/workspace-schema.json
  packages/angular/cli/src/commands/config/cli.ts
  packages/angular/cli/src/utilities/config.ts
  tests/legacy-cli/e2e/tests/commands/config/config-global-validation.ts
  tests/legacy-cli/e2e/tests/commands/config/config-set.ts
Labels: target: patch, action: merge

#23435 ci: attempt to fix renovate configuration schedules
  renovate.json
Labels: action: merge, target: minor

#23438 fix(@angular-devkit/build-angular): exit dev-server when CTRL+C is pressed
  packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
Labels: target: patch, action: merge, 2022Q3 Fixit

#23440 fix(@angular/cli): correctly handle `--collection` option in `ng new`
  packages/angular/cli/src/commands/new/cli.ts
  tests/legacy-cli/e2e/tests/commands/ng-new-collection.ts
Labels: target: patch, action: merge, 2022Q3 Fixit

#23455 refactor: clean up old ansi-colors castings
  packages/angular/cli/src/utilities/color.ts
  packages/angular_devkit/architect_cli/bin/architect.ts
  packages/angular_devkit/benchmark/src/main.ts
  packages/angular_devkit/build_angular/src/utils/color.ts
  packages/angular_devkit/schematics_cli/bin/schematics.ts
  tests/legacy-cli/e2e/utils/process.ts
Labels: action: merge, target: minor

#23446 fix(@ngtools/webpack): show a compilation error on invalid TypeScript version
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: target: patch, action: merge, 2022Q3 Fixit

#23457 fix(@angular-devkit/build-angular): exit localized build when CTRL+C is pressed
  packages/angular_devkit/build_angular/src/utils/i18n-options.ts
Labels: target: patch, action: merge, 2022Q3 Fixit

#23458 fix(@ngtools/webpack): restore process title after NGCC is executed
  packages/ngtools/webpack/src/ngcc_processor.ts
Labels: target: patch, action: merge, 2022Q3 Fixit

#23454 fix(@angular-devkit/build-angular): set base-href in service worker manifest when using i18n and app-shell
  goldens/public-api/angular_devkit/build_angular/index.md
  packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
  packages/angular_devkit/build_angular/src/builders/browser/index.ts
  packages/angular_devkit/build_angular/src/builders/server/index.ts
  packages/angular_devkit/build_angular/src/testing/test-utils.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-app-shell-service-worker.ts
Labels: target: patch, action: merge, 2022Q3 Fixit

#23459 fix(@angular-devkit/architect): complete builders on the next event loop iteration
  packages/angular_devkit/architect/src/create-builder.ts
  packages/angular_devkit/architect/src/index_spec.ts
Labels: target: patch, action: merge, 2022Q3 Fixit

#23464 Bump version to "v14.0.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#23466 Bump version to "v14.1.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#23472 fix(@angular-devkit/build-angular): disable glob mounting for patterns that start with a forward slash
  packages/angular_devkit/build_angular/src/builders/karma/find-tests.ts
  packages/angular_devkit/build_angular/src/builders/karma/tests/options/code-coverage-exclude_spec.ts
  packages/angular_devkit/build_angular/src/builders/karma/tests/options/include_spec.ts
  packages/angular_devkit/build_angular/src/utils/copy-assets.ts
  packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
Labels: target: patch, action: merge, 2022Q3 Fixit

#23478 build: add bazel config that disabled sharding and flaky re-runs
  .bazelrc
Labels: target: patch, action: merge

#23479 build: account for rename of `angular/code-of-conduct` default branch
  CONTRIBUTING.md
  scripts/templates/contributing.ejs
Labels: target: patch, action: merge
