Repository angular/angular-cli, pull requests merged in 2022-10, with the labels that each got.

#24000 refactor(@angular-devkit/schematics): Delete 'rename' rule
  packages/angular_devkit/schematics/src/rules/rename.ts
  packages/angular_devkit/schematics/src/rules/rename_spec.ts
  packages/angular_devkit/schematics/src/rules/template.ts
Labels: target: major, action: merge

#24002 feat(@angular/cli): drop support for Node.js versions older than 14.20
  .circleci/dynamic_config.yml
  .nvmrc
  WORKSPACE
  constants.bzl
  docs/DEVELOPER.md
  lib/packages.ts
  package.json
  packages/angular/cli/BUILD.bazel
  packages/angular/cli/bin/ng.js
  packages/angular/cli/package.json
  packages/angular/cli/src/analytics/analytics.ts
  packages/angular/cli/src/commands/config/cli.ts
  tools/test/expected_package.json
  yarn.lock
Labels: feature, action: merge, flag: breaking change

#24008 feat(@schematics/angular): remove `ngOnInit` from component template
  packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
  packages/schematics/angular/component/index_spec.ts
Labels: feature, action: merge

#24011 feat(@angular-devkit/build-angular): add initial incremental code rebuilding to esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/esbuild.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
Labels: feature, target: major, action: merge

#24016 fix(@angular-devkit/schematics): throw more relevant error when Rule returns invalid null value
  packages/angular_devkit/schematics/src/rules/call.ts
  packages/angular_devkit/schematics/src/rules/call_spec.ts
Labels: target: patch, action: merge

#24020 Bump version to "v14.2.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24021 docs: release notes for the v14.2.5 release
  CHANGELOG.md
Labels: action: merge, comp: docs

#24022 Bump version to "v15.0.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24006 refactor(@angular/cli): remove leftover schematics path handling
  packages/angular/cli/src/command-builder/schematics-command-module.ts
Labels: action: merge, target: minor

#24028 fix(@angular/cli): skip downloading temp CLI when running `ng update` without package names
  packages/angular/cli/src/commands/update/cli.ts
  packages/angular/cli/src/utilities/package-metadata.ts
Labels: target: patch, action: merge

#23983 fix(@angular-devkit/core): project extension warning message should identify concerned project
  packages/angular_devkit/core/src/workspace/json/reader.ts
Labels: target: patch, action: merge

#24029 refactor(@angular-devkit/build-angular): use high resolution time for esbuild builder completion time
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
Labels: target: major, action: merge

#24035 refactor(@angular-devkit/schematics): remove `UpdateBuffer` and rename `UpdateBuffer2` to `UpdateBuffer`
  packages/angular_devkit/schematics/src/tree/recorder_spec.ts
  packages/angular_devkit/schematics/src/utility/environment-options.ts
  packages/angular_devkit/schematics/src/utility/linked-list.ts
  packages/angular_devkit/schematics/src/utility/update-buffer.ts
  packages/angular_devkit/schematics/src/utility/update-buffer_spec.ts
Labels: target: major, action: merge, flag: breaking change

#24034 feat(@schematics/angular): mark `projectRoot` as non hidden option in application schematic
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/schema.json
Labels: feature, action: merge, target: minor

#24037 refactor: move experimental `jobs` API from `@angular-devkit/core` to `@angular-devkit/architect`
  goldens/public-api/angular_devkit/architect/index.md
  goldens/public-api/angular_devkit/core/index.md
  goldens/public-api/angular_devkit/core/node/index.md
  packages/angular_devkit/architect/node/BUILD.bazel
  packages/angular_devkit/architect/node/index.ts
  packages/angular_devkit/architect/node/jobs/job-registry.ts
  packages/angular_devkit/architect/node/jobs/job-registry_spec.ts
  packages/angular_devkit/architect/src/api.ts
  packages/angular_devkit/architect/src/architect.ts
  packages/angular_devkit/architect/src/create-builder.ts
  packages/angular_devkit/architect/src/index.ts
  packages/angular_devkit/architect/src/internal.ts
  packages/angular_devkit/architect/src/jobs/README.md
  packages/angular_devkit/architect/src/jobs/api.ts
  packages/angular_devkit/architect/src/jobs/architecture.md
  packages/angular_devkit/architect/src/jobs/create-job-handler.ts
  packages/angular_devkit/architect/src/jobs/dispatcher.ts
  packages/angular_devkit/architect/src/jobs/dispatcher_spec.ts
  packages/angular_devkit/architect/src/jobs/exception.ts
  packages/angular_devkit/architect/src/jobs/fallback-registry.ts
  packages/angular_devkit/architect/src/jobs/index.ts
  packages/angular_devkit/architect/src/jobs/simple-registry.ts
  packages/angular_devkit/architect/src/jobs/simple-registry_spec.ts
  packages/angular_devkit/architect/src/jobs/simple-scheduler.ts
  packages/angular_devkit/architect/src/jobs/simple-scheduler_spec.ts
  packages/angular_devkit/architect/src/jobs/strategy.ts
  packages/angular_devkit/architect/src/jobs/strategy_spec.ts
  packages/angular_devkit/architect/src/jobs/types.ts
  packages/angular_devkit/architect/src/schedule-by-name.ts
  packages/angular_devkit/core/BUILD.bazel
  packages/angular_devkit/core/node/BUILD.bazel
  packages/angular_devkit/core/node/experimental/index.ts
  packages/angular_devkit/core/node/experimental/jobs/index.ts
  packages/angular_devkit/core/node/index.ts
  packages/angular_devkit/core/src/experimental.ts
  packages/angular_devkit/core/src/index.ts
  packages/angular_devkit/core/src/utils/index.ts
  tests/angular_devkit/architect/node/jobs/BUILD.bazel
  tests/angular_devkit/architect/node/jobs/add.ts
  tests/angular_devkit/core/node/jobs/add.ts
Labels: target: major, action: merge

#24026 feat(@angular/cli): add support for Node.js version 18
  .circleci/dynamic_config.yml
  constants.bzl
  docs/DEVELOPER.md
  lib/packages.ts
  package.json
  packages/angular/cli/bin/ng.js
  packages/angular/cli/src/commands/version/cli.ts
  tools/test/expected_package.json
Labels: feature, action: merge, flag: breaking change

#24036 fix(@angular/cli): handle missing `which` binary in path
  packages/angular/cli/src/utilities/completion.ts
Labels: target: patch, action: merge

#24019 refactor(@angular/cli) Address issues and enable strictNullChecks.
  goldens/public-api/angular_devkit/core/index.md
  packages/angular_devkit/core/src/logger/logger.ts
  packages/angular_devkit/core/src/utils/partially-ordered-set.ts
  packages/angular_devkit/core/src/utils/strings.ts
  packages/angular_devkit/core/src/utils/template.ts
  packages/angular_devkit/core/src/virtual-fs/host/memory.ts
  packages/angular_devkit/schematics/src/sink/sink.ts
  packages/angular_devkit/schematics/src/tree/scoped.ts
  packages/schematics/angular/utility/ast-utils.ts
Labels: action: merge, target: minor

#24042 fix(@angular-devkit/build-angular): isolate zone.js usage when rendering server bundles
  packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
  packages/angular_devkit/build_angular/src/builders/app-shell/render-worker.ts
Labels: target: major, action: merge

#24044 Revert "refactor(@angular-devkit/schematics): remove `UpdateBuffer` and rename `UpdateBuffer2` to `UpdateBuffer`"
  packages/angular_devkit/schematics/src/tree/recorder_spec.ts
  packages/angular_devkit/schematics/src/utility/environment-options.ts
  packages/angular_devkit/schematics/src/utility/linked-list.ts
  packages/angular_devkit/schematics/src/utility/update-buffer.ts
  packages/angular_devkit/schematics/src/utility/update-buffer_spec.ts
Labels: target: major, action: merge

#24046 refactor(@ngtools/webpack): use new name of Angular compiler incremental compilation property
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: action: review, target: major, action: merge

#23949 fix(@angular-devkit/build-angular): show warning when using TypeScript target older then ES2022 in esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
Labels: target: major, action: merge

#24048 fix(@angular-devkit/build-angular): correctly resolve Scss partial files in node packages
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
  tests/legacy-cli/e2e/tests/build/styles/scss-partial-resolution.ts
Labels: target: major, action: merge

#24051 fix(@angular-devkit/build-angular): use relative sourcemap source paths for Sass in esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
Labels: target: major, action: merge

#24052 perf(@angular-devkit/build-angular): minimize Angular diagnostics incremental analysis in esbuild-based builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/profiling.ts
Labels: target: major, action: merge

#24059 test(@schematics/angular): test names typos
  packages/schematics/angular/universal/index_spec.ts
Labels: target: major, action: merge

#24054 test: remove `node16-broken` from app-shell unit test
  packages/angular_devkit/build_angular/BUILD.bazel
Labels: target: major, action: merge

#24055 docs: remove page view section from analytics doc
  docs/design/analytics.md
  packages/angular/cli/src/analytics/analytics-parameters.ts
  scripts/validate-user-analytics.ts
Labels: target: major, action: merge, comp: docs

#24060 fix(@angular-devkit/build-angular): ignore specs in node_modules when finding specs
  packages/angular_devkit/build_angular/src/builders/karma/find-tests-plugin.ts
Labels: target: major, action: merge

#24065 Bump version to "v15.0.0-next.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24068 Bump version to "v14.2.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24069 docs: release notes for the v14.2.6 release
  CHANGELOG.md
Labels: action: merge

#24070 build: update labels to match standardized labels
  .ng-dev/pull-request.mts
Labels: target: patch, action: merge, comp: build & ci

#24072 build: update to the latest version of the feature triage action
  .github/workflows/feature-requests.yml
Labels: action: merge, comp: build & ci

#24073 build: update comp labels to be area instead
  .github/angular-robot.yml
  .github/dependabot.yml
Labels: target: patch, action: merge, comp: build & ci

#24074 build: update commit message based labels action
  .github/workflows/dev-infra.yml
Labels: target: patch, action: merge, area: build & ci

#24067 perf(@angular-devkit/build-angular): use Uint8Arrays for incremental caching with esbuild-based builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
Labels: target: rc, action: merge

#24076 fix(@angular-devkit/build-angular): only import karma when running karma builder
  goldens/public-api/angular_devkit/build_angular/index.md
  packages/angular_devkit/build_angular/src/builders/karma/index.ts
Labels: target: rc, action: merge

#24083 build: remove labels from pull-requests config
  .ng-dev/pull-request.mts
Labels: action: merge, target: minor

#24085 fix(@angular-devkit/core): update logger `forEach` `promiseCtor` type
  goldens/public-api/angular_devkit/core/index.md
  packages/angular_devkit/core/src/logger/logger.ts
Labels: target: rc, action: merge

#24089 fix(@angular-devkit/build-angular): add `@angular/platform-server` as an optional peer dependency
  packages/angular_devkit/build_angular/package.json
Labels: target: rc, action: merge

#24090 fix(@angular/cli): do not collect analytics when running in non TTY mode
  packages/angular/cli/src/analytics/analytics.ts
  tests/legacy-cli/e2e/tests/commands/analytics/analytics-enable-disable.ts
  tests/legacy-cli/e2e/tests/commands/analytics/analytics-info.ts
  tests/legacy-cli/e2e/tests/commands/analytics/ask-analytics-command.ts
Labels: target: rc, action: merge

#24077 fix(@angular-devkit/build-angular): resolve transitive dependencies in Sass when using Yarn PNP
  packages/angular_devkit/build_angular/src/sass/sass-service.ts
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: action: review, target: rc, action: merge

#24091 Bump version to "v15.0.0-next.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24092 docs: release notes for the v15.0.0-next.6 release
  CHANGELOG.md
Labels: action: merge

#24107 docs: release notes for the v15.0.0-rc.0 release
  CHANGELOG.md
Labels: area: docs, target: major, action: merge

#24110 build: update angular
  .github/workflows/dev-infra.yml
  .github/workflows/feature-requests.yml
  .github/workflows/lock-closed.yml
  package.json
  packages/ngtools/webpack/package.json
  tests/legacy-cli/e2e/ng-snapshot/package.json
  yarn.lock
Labels: target: rc, action: merge

#24111 build: update all non-major dependencies
  package.json
  packages/angular/cli/package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members_spec.ts
  packages/angular_devkit/build_angular/src/babel/plugins/adjust-typescript-enums_spec.ts
  yarn.lock
Labels: target: rc, action: merge, action: caretaker note

#24088 fix(@schematics/angular): add `@angular/localize` as type when localize package is installed
  packages/angular_devkit/build_angular/test/hello-world-app/src/tsconfig.app.json
  packages/angular_devkit/build_angular/test/hello-world-app/src/tsconfig.server.json
  packages/angular_devkit/build_angular/test/hello-world-app/src/tsconfig.spec.json
  packages/schematics/angular/universal/files/root/tsconfig.server.json.template
  packages/schematics/angular/universal/index_spec.ts
Labels: target: rc, action: merge

#24118 docs(@angular/cli): update add long description to analytics command
  packages/angular/cli/src/commands/analytics/cli.ts
  packages/angular/cli/src/commands/analytics/long-description.md
  packages/angular/cli/src/commands/config/long-description.md
  tests/legacy-cli/e2e/tests/commands/help/help-json.ts
Labels: area: docs, target: rc, action: merge

#24119 docs: replace browserslist with AIO link
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/typescript.ts
Labels: area: docs, target: rc, action: merge

#24134 fix(@angular/cli): disable version check during auto completion
  packages/angular/cli/lib/init.ts
Labels: target: patch, action: merge

#24132 feat(@schematics/angular): add sideEffects:false to library package.json
  packages/schematics/angular/library/files/package.json.template
  packages/schematics/angular/library/index_spec.ts
Labels: action: merge, target: minor, detected: feature

#24135 perf(@angular-devkit/build-angular): avoid template diagnostics for declaration files in esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
Labels: target: rc, action: merge

#24137 fix(@angular/cli): allow ng add to find prerelease versions when CLI is prerelease
  packages/angular/cli/src/commands/add/cli.ts
Labels: target: rc, action: merge

#24136 refactor: Make Logger.forEach compatible with both rxjs 6 and 7.
  packages/angular_devkit/core/src/logger/logger.ts
Labels: target: rc, action: merge

#24144 fix(@angular-devkit/build-angular): issue dev-server support warning when using esbuild builder
  packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
Labels: target: patch, action: merge

#24141 fix(@schematics/angular): remove TypeScript target from universal schematic
  packages/schematics/angular/universal/files/root/tsconfig.server.json.template
  packages/schematics/angular/universal/index_spec.ts
Labels: target: rc, action: merge

#24138 fix(@angular-devkit/build-angular): ignore cache path when watching with esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
Labels: target: rc, action: merge

#24147 Bump version to "v14.2.7" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#24148 docs: release notes for the v14.2.7 release
  CHANGELOG.md
Labels: area: docs, action: merge, target: minor

#24149 Bump version to "v15.0.0-rc.1" with changelog.
  CHANGELOG.md
  package.json
Labels: target: rc, action: merge

#24150 docs: release notes for the v15.0.0-rc.1 release
  CHANGELOG.md
Labels: action: merge, target: minor

#24152 fix(@angular/cli): exclude `@angular/localize@<10.0.0` from ng add pa…
  packages/angular/cli/src/commands/add/cli.ts
Labels: target: rc, action: merge, merge: squash commits

#24154 fix(@angular-devkit/build-angular): correct escaping of target warning text in esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
Labels: target: rc, action: merge

#24159 fix(@angular-devkit/build-angular): wait during file watching to improve multi-save rebuilds for esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/watcher.ts
Labels: target: rc, action: merge

#24158 perf(@angular-devkit/build-angular): use Sass worker pool for Sass support in esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
  packages/angular_devkit/build_angular/src/sass/sass-service.ts
  packages/angular_devkit/build_angular/src/sass/worker.ts
Labels: target: rc, action: merge
