Repository angular/angular-cli, pull requests merged in 2022-09, with the labels that each got.

#23839 build: adjust BUILD file external comment markers
  BUILD.bazel
  packages/angular_devkit/core/BUILD.bazel
  packages/angular_devkit/schematics/tools/BUILD.bazel
  packages/angular_devkit/schematics_cli/BUILD.bazel
Labels: target: patch, action: merge

#23841 fix(@angular/cli): favor non deprecated packages during update
  packages/angular/cli/src/commands/update/schematic/index.ts
  packages/angular/cli/src/utilities/package-metadata.ts
Labels: target: patch, action: merge

#23852 fix(@angular-devkit/build-angular): watch index file when running build in watch mode
  packages/angular_devkit/build_angular/src/builders/browser/index.ts
  packages/angular_devkit/build_angular/src/builders/browser/tests/behavior/index_watch_spec.ts
Labels: target: patch, action: merge

#23850 fix(@schematics/angular): mark project as required option
  packages/schematics/angular/class/schema.json
  packages/schematics/angular/component/schema.json
  packages/schematics/angular/directive/schema.json
  packages/schematics/angular/enum/schema.json
  packages/schematics/angular/guard/schema.json
  packages/schematics/angular/interceptor/schema.json
  packages/schematics/angular/interface/schema.json
  packages/schematics/angular/module/schema.json
  packages/schematics/angular/pipe/schema.json
  packages/schematics/angular/resolver/schema.json
  packages/schematics/angular/service/schema.json
  packages/schematics/angular/utility/generate-from-files.ts
Labels: action: merge, target: minor

#23849 fix(@angular-devkit/build-angular): handle service-worker serving with localize in dev-server
  packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/serve_service-worker_spec.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/service-worker-plugin.ts
Labels: target: patch, action: merge

#23855 build: update web-driver and puppeteer
  package.json
  yarn.lock
Labels: action: merge, target: minor

#23856 refactor(@angular-devkit/build-angular): remove Ivy checks
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/typescript.ts
  packages/ngtools/webpack/src/ivy/plugin.ts
Labels: action: merge, target: minor

#23858 fix(@angular-devkit/build-angular): change service worker errors to compilation errors
  packages/angular_devkit/build_angular/src/webpack/plugins/service-worker-plugin.ts
Labels: target: patch, action: merge

#23863 refactor(@schematics/angular): consolidate `addDeclarationToNgModule` logic
  packages/schematics/angular/component/index.ts
  packages/schematics/angular/directive/index.ts
  packages/schematics/angular/module/index.ts
  packages/schematics/angular/pipe/index.ts
  packages/schematics/angular/utility/add-declaration-to-ng-module.ts
Labels: action: merge, target: minor

#23869 build: update `webpack-dev-server` to `4.11.0`
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge

#23870 test: delete firebase resolution tests
  tests/legacy-cli/e2e/tests/misc/module-resolution/module-resolution-firebase.ts
Labels: target: patch, action: merge

#23872 Bump version to "v14.2.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#23873 docs: release notes for the v14.2.2 release
  CHANGELOG.md
Labels: action: merge, comp: docs

#23877 refactor(@angular-devkit/build-angular): remove `postcss-preset-env`
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
  tests/legacy-cli/e2e/tests/build/styles/preset-env.ts
  yarn.lock
Labels: target: major, action: merge

#23874 fix(@angular-devkit/build-angular): correctly display error messages that contain "at"
  packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
Labels: target: patch, action: merge

#23822 refactor(@angular-devkit/build-angular): remove old `bundleDependencies` logic
  goldens/public-api/angular_devkit/build_angular/index.md
  packages/angular_devkit/build_angular/src/builders/server/index.ts
  packages/angular_devkit/build_angular/src/builders/server/schema.json
Labels: target: major, action: merge, flag: breaking change

#23880 perf(@ngtools/webpack): avoid bootstrap conversion AST traversal where possible
  packages/ngtools/webpack/src/ivy/transformation.ts
Labels: target: patch, action: merge

#23888 build: update Bazel to 5.3 and rules_pkg to 0.7.1
  .bazelversion
  WORKSPACE
Labels: target: patch, action: merge

#23887 test: don't run git clean on test failure
  tests/legacy-cli/e2e_runner.ts
Labels: target: patch, action: merge

#23889 refactor: remove unused file
  packages/angular_devkit/build_angular/test/build-browser-features/.browserslistrc
Labels: target: patch, action: merge

#23902 test: suppress npm update warnings
  tests/legacy-cli/e2e/setup/002-npm-sandbox.ts
  tests/legacy-cli/e2e/tests/misc/npm-7.ts
  tests/legacy-cli/e2e/utils/process.ts
Labels: action: merge, target: minor

#23904 build: remove unneeded BUILD file licenses rule comments
  packages/angular/cli/BUILD.bazel
  packages/angular/create/BUILD.bazel
  packages/angular/pwa/BUILD.bazel
  packages/angular_devkit/architect/BUILD.bazel
  packages/angular_devkit/architect/node/BUILD.bazel
  packages/angular_devkit/architect/testing/BUILD.bazel
  packages/angular_devkit/architect_cli/BUILD.bazel
  packages/angular_devkit/benchmark/BUILD.bazel
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_webpack/BUILD.bazel
  packages/angular_devkit/core/BUILD.bazel
  packages/angular_devkit/core/node/BUILD.bazel
  packages/angular_devkit/core/node/testing/BUILD.bazel
  packages/ngtools/webpack/BUILD.bazel
  packages/schematics/angular/BUILD.bazel
  tests/angular_devkit/core/node/jobs/BUILD.bazel
  tests/angular_devkit/schematics/tools/file-system-engine-host/BUILD.bazel
Labels: target: patch, action: merge

#23910 ci: remove manually specifying GITHUB_TOKEN in scorecard action
  .github/workflows/scorecard.yml
Labels: action: merge, target: minor

#23908 test: re-enable Angular material tests
  tests/legacy-cli/e2e/tests/build/material.ts
  tests/legacy-cli/e2e/tests/commands/add/add-material.ts
  tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts
Labels: target: major, action: merge

#23900 fix(@angular-devkit/build-angular): watch symbolic links
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  tests/legacy-cli/e2e/tests/build/rebuild-symlink.ts
Labels: target: patch, action: merge

#23714 test: unit test multiple node versions in separate jobs
  .circleci/dynamic_config.yml
  packages/angular/cli/BUILD.bazel
  packages/angular/pwa/BUILD.bazel
  packages/angular_devkit/architect/BUILD.bazel
  packages/angular_devkit/benchmark/BUILD.bazel
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_webpack/BUILD.bazel
  packages/angular_devkit/core/BUILD.bazel
  packages/angular_devkit/core/node/BUILD.bazel
  packages/angular_devkit/schematics/BUILD.bazel
  packages/angular_devkit/schematics/tools/BUILD.bazel
  packages/angular_devkit/schematics_cli/BUILD.bazel
  packages/ngtools/webpack/BUILD.bazel
  packages/schematics/angular/BUILD.bazel
  tools/toolchain_info.bzl
Labels: target: patch, action: merge

#23909 build: update saucelabs connect version
  package.json
  yarn.lock
Labels: target: major, action: merge, comp: build & ci

#23912 test(@angular-devkit/build-angular): rewrite app-shell unit test into e2e
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/src/builders/app-shell/app-shell_spec.ts
  tests/legacy-cli/e2e/tests/build/app-shell/app-shell-with-schematic.ts
  tests/legacy-cli/e2e/tests/build/app-shell/app-shell-with-service-worker.ts
Labels: target: patch, action: merge

#23916 ci: adjust workflow permissions for OpenSSF Scorecard results publishing
  .github/workflows/scorecard.yml
Labels: action: merge, target: minor

#23911 build: update saucelabs connect version
  package.json
  yarn.lock
Labels: target: patch, action: merge

#23917 Bump version to "v14.2.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#23919 docs: release notes for the v14.2.3 release
  CHANGELOG.md
Labels: action: merge, comp: docs

#23920 Bump version to "v15.0.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#23924 feat(@angular-devkit/build-angular): add esbuild-based builder initial support for fileReplacements
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/experimental-warnings.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/schema.json
Labels: action: merge, target: minor

#23922 refactor(@angular-devkit/build-angular): simplify configuration of `inlineStyleFileExtension`
  packages/angular_devkit/build_angular/src/webpack/plugins/typescript.ts
Labels: action: merge, target: minor

#23914 feat(@schematics/angular): enable error on unknown properties and elements in tests
  packages/angular_devkit/build_angular/test/hello-world-app/src/test.ts
  packages/angular_devkit/build_angular/test/hello-world-lib/projects/lib/src/test.ts
  packages/schematics/angular/application/files/src/test.ts.template
  packages/schematics/angular/library/files/src/test.ts.template
Labels: target: major, action: merge

#23899 refactor(@angular-devkit/build-angular): remove deprecated ES5 support
  packages/angular_devkit/build_angular/src/babel/presets/application.ts
  packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
  packages/angular_devkit/build_angular/src/builders/browser/index.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/allow-js_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/browser-support_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/optimization-level_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/resolve-json-module_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/styles_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/tests/behavior/browser-support_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/tests/behavior/typescript-target_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/tsconfig_spec.ts
  packages/angular_devkit/build_angular/src/builders/server/index.ts
  packages/angular_devkit/build_angular/src/utils/i18n-inlining.ts
  packages/angular_devkit/build_angular/src/utils/normalize-builder-schema.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
  packages/angular_devkit/build_angular/src/utils/supported-browsers.ts
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/typescript.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-es5.ts
  tests/legacy-cli/e2e/tests/misc/es2015-nometa.ts
  tests/legacy-cli/e2e/tests/misc/forwardref-es2015.ts
Labels: target: major, action: merge, flag: breaking change

#23836 refactor(@angular-devkit/build-angular): remove support for Stylus
  docs/design/build-system-overview.dot
  docs/design/build-system.md
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/schema.json
  packages/angular_devkit/build_angular/src/builders/browser/schema.json
  packages/angular_devkit/build_angular/src/builders/browser/specs/styles_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/bundle-budgets_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/inline-style-language_spec.ts
  packages/angular_devkit/build_angular/src/builders/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/builders/karma/schema.json
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/css-optimizer-plugin.ts
  tests/legacy-cli/e2e/tests/build/styles/include-paths.ts
  tests/legacy-cli/e2e/tests/build/styles/stylus.ts
Labels: target: major, action: merge, flag: breaking change

#23921 docs: clarify that version bumps must happen separately from the release PR
  docs/process/release.md
Labels: target: major, action: merge, comp: docs

#23926 test: enable git core.longpaths option
  .circleci/dynamic_config.yml
  tests/legacy-cli/e2e/utils/project.ts
Labels: target: patch, action: merge

#23903 test: catch and log all errors include test setup
  tests/legacy-cli/e2e_runner.ts
Labels: target: patch, action: merge

#23933 refactor(@angular/cli): remove use of global require resolve
  packages/angular/cli/lib/init.ts
  packages/angular/cli/src/command-builder/utilities/schematic-engine-host.ts
  packages/angular/cli/src/commands/add/cli.ts
  packages/angular/cli/src/commands/update/cli.ts
Labels: target: major, action: merge

#23929 build: use shared circleci dev-infra for common circleci code
  .circleci/dynamic_config.yml
  tools/rebase-pr.js
Labels: target: patch, action: merge

#23821 fix(@angular-devkit/core): throw error when project has missing root property
  packages/angular_devkit/core/src/workspace/json/reader.ts
  packages/angular_devkit/core/src/workspace/json/reader_spec.ts
Labels: target: major, action: merge, flag: breaking change

#23940 Bump version to "v15.0.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#23943 refactor: use `addWarning` and `addError` helpers to push Webpack diagnostics
  packages/angular_devkit/build_angular/src/utils/webpack-diagnostics.ts
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/transfer-size-plugin.ts
  packages/ngtools/webpack/src/ivy/plugin.ts
  packages/ngtools/webpack/src/resource_loader.ts
Labels: action: merge, target: minor

#23946 build: update dev-infra orb for recent rebase command fixes
  .circleci/dynamic_config.yml
Labels: target: patch, action: merge

#23718 fix(@angular/cli): add builders and schematic names as page titles in collected analytics
  packages/angular/cli/src/command-builder/architect-base-command-module.ts
  packages/angular/cli/src/command-builder/command-module.ts
  packages/angular/cli/src/command-builder/schematics-command-module.ts
Labels: target: patch, action: merge

#23951 feat(@angular-devkit/build-angular): add `ng-server-context` when using app-shell builder
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/src/builders/app-shell/app-shell_spec.ts
  packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
Labels: target: major, action: merge

#23947 feat(@angular-devkit/build-angular): remove `bundleDependencies` from server builder
  goldens/public-api/angular_devkit/build_angular/index.md
  packages/angular_devkit/build_angular/src/builders/server/schema.json
  packages/angular_devkit/build_angular/src/utils/build-options.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-15/update-workspace-config.ts
  packages/schematics/angular/migrations/update-15/update-workspace-config_spec.ts
  tests/legacy-cli/e2e/tests/build/platform-server.ts
  tests/legacy-cli/e2e/tests/misc/universal-bundle-dependencies.ts
Labels: feature, target: major, action: merge, flag: breaking change

#23939 refactor(@angular-devkit/build-angular): simplify how specs are found and loaded
  packages/angular_devkit/build_angular/src/builders/karma/find-tests-plugin.ts
  packages/angular_devkit/build_angular/src/builders/karma/index.ts
  packages/angular_devkit/build_angular/src/builders/karma/schema.json
  packages/angular_devkit/build_angular/src/builders/karma/tests/options/include_spec.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/single-test-transform.ts
  packages/angular_devkit/build_angular/test/hello-world-app/src/test.ts
  packages/angular_devkit/build_angular/test/hello-world-lib/projects/lib/src/test.ts
  packages/schematics/angular/application/files/src/test.ts.template
  packages/schematics/angular/library/files/src/test.ts.template
Labels: target: major, action: merge

#23953 build: setup remote execution through shared command
  .circleci/dynamic_config.yml
  .circleci/gcp_token
Labels: target: patch, action: merge

#23753 test: run e2e tests on pre-compiled packages
  .circleci/dynamic_config.yml
  docs/DEVELOPER.md
  lib/BUILD.bazel
  package.json
  tests/legacy-cli/e2e/setup/010-local-publish.ts
  tests/legacy-cli/e2e/tests/update/update.ts
  tests/legacy-cli/e2e/utils/BUILD.bazel
  tests/legacy-cli/e2e/utils/packages.ts
  tests/legacy-cli/e2e/utils/project.ts
  tests/legacy-cli/e2e/utils/tar.ts
  tests/legacy-cli/e2e_runner.ts
  yarn.lock
Labels: target: patch, action: merge

#23962 CI build-bazel-e2e fix
  .circleci/dynamic_config.yml
Labels: target: patch, action: merge

#23931 feat(@schematics/angular): remove environment files in new applications
  packages/angular_devkit/build_angular/src/builders/app-shell/app-shell_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/rebuild_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/unused-files-warning_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/vendor-source-map_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/web-worker_spec.ts
  packages/angular_devkit/build_angular/test/hello-world-app/angular.json
  packages/angular_devkit/build_angular/test/hello-world-app/src/environments/environment.prod.ts
  packages/angular_devkit/build_angular/test/hello-world-app/src/environments/environment.ts
  packages/angular_devkit/build_angular/test/hello-world-app/src/main.server.ts
  packages/angular_devkit/build_angular/test/hello-world-app/src/main.ts
  packages/angular_devkit/build_webpack/test/angular-app/src/environments/environment.prod.ts
  packages/angular_devkit/build_webpack/test/angular-app/src/environments/environment.ts
  packages/angular_devkit/build_webpack/test/angular-app/src/main.ts
  packages/schematics/angular/application/files/src/environments/environment.prod.ts.template
  packages/schematics/angular/application/files/src/environments/environment.ts.template
  packages/schematics/angular/application/files/src/main.ts.template
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/service-worker/index.ts
  packages/schematics/angular/service-worker/index_spec.ts
  packages/schematics/angular/universal/files/src/__main@stripTsExtension__.ts.template
  packages/schematics/angular/universal/index_spec.ts
  packages/schematics/angular/utility/ast-utils.ts
  tests/legacy-cli/e2e/tests/basic/environment.ts
  tests/legacy-cli/e2e/tests/basic/rebuild.ts
  tests/legacy-cli/e2e/tests/build/rebuild-replacements.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-app-shell.ts
  tests/legacy-cli/e2e/tests/i18n/setup.ts
  tests/legacy-cli/e2e/tests/misc/third-party-decorators.ts
  tests/legacy-cli/e2e/tests/test/test-environment.ts
Labels: feature, target: major, action: merge

#23968 Bump version to "v14.2.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#23970 docs: release notes for the v14.2.4 release
  CHANGELOG.md
Labels: action: merge, comp: docs

#23966 fix(@angular-devkit/build-angular): fix crash when Sass error occurs
  packages/angular_devkit/build_angular/src/sass/worker.ts
Labels: action: review, target: major

#23974 Bump version to "v15.0.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#23967 fix(@angular-devkit/build-angular): support Yarn PNP resolution in modern SASS API
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: target: major, action: merge

#23982 fix(@schematics/angular): remove empty lines in main.ts
  packages/schematics/angular/application/files/src/main.ts.template
Labels: target: major, action: merge

#23981 docs(@angular/cli): update platform support information in auto-completion
  packages/angular/cli/src/commands/completion/long-description.md
Labels: target: patch, action: merge, comp: docs

#23971 fix(@angular-devkit/build-angular): handle conditional exports in `scripts` and `styles` option
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/scripts-array_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/scripts_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/styles_spec.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/styles-webpack-plugin.ts
  packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
Labels: target: major, action: merge

#23979 fix(@angular-devkit/build-angular): allow both script and module sourceTypes to be localized
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: target: major, action: merge
