Repository angular/angular-cli, pull requests merged in 2022-08, with the labels that each got.

#23638 test(@angular-devkit/build-angular): re-write live-reload tests to use new test harness.
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/serve-live-reload-proxies_spec.ts
Labels: target: patch, action: merge

#23642 fix(@angular-devkit/build-angular): correctly respond to preflight requests
  packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
  tests/legacy-cli/e2e/tests/commands/serve/preflight-request.ts
Labels: target: patch, action: merge

#23626 build: remove dependency on font-awesome
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/src/builders/browser/specs/styles_spec.ts
  scripts/validate-licenses.ts
  yarn.lock
Labels: action: merge, target: minor

#22420 test: run tests on multiple node versions
  .bazelrc
  WORKSPACE
  packages/angular/cli/BUILD.bazel
  packages/angular/pwa/BUILD.bazel
  packages/angular_devkit/architect/BUILD.bazel
  packages/angular_devkit/benchmark/BUILD.bazel
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_webpack/BUILD.bazel
  packages/angular_devkit/core/BUILD.bazel
  packages/angular_devkit/core/node/BUILD.bazel
  packages/angular_devkit/schematics/BUILD.bazel
  packages/angular_devkit/schematics/tools/BUILD.bazel
  packages/angular_devkit/schematics_cli/BUILD.bazel
  packages/ngtools/webpack/BUILD.bazel
  packages/schematics/angular/BUILD.bazel
  tools/toolchain_info.bzl
Labels: target: patch, action: merge

#23676 build: update all non-major dependencies
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/webpack/plugins/esbuild-executor.ts
  yarn.lock
Labels: action: merge, target: minor

#23683 Bump version to "v14.1.1" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#23684 docs: release notes for the v14.1.1 release
  CHANGELOG.md
Labels: action: merge, target: minor

#23685 Bump version to "v14.2.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, target: minor

#23691 fix(@angular-devkit/build-angular): correctly handle data URIs with escaped quotes in stylesheets
  packages/angular_devkit/build_angular/src/builders/browser/specs/styles_spec.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/postcss-cli-resources.ts
Labels: target: patch, action: merge

#23687 test: use common mockHome method
  tests/legacy-cli/e2e/tests/commands/completion/completion-prompt.ts
  tests/legacy-cli/e2e/tests/commands/completion/completion.ts
  tests/legacy-cli/e2e/tests/misc/ask-analytics-command.ts
  tests/legacy-cli/e2e/utils/utils.ts
Labels: target: patch, action: merge

#23679 feat(@angular-devkit/build-angular): add ability to serve service worker when using dev-server
  packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/serve_service-worker_spec.ts
  packages/angular_devkit/build_angular/src/utils/service-worker.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/service-worker-plugin.ts
Labels: action: merge, target: minor

#23681 build: remove dependency on font-awesome
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/src/builders/browser/specs/styles_spec.ts
  scripts/validate-licenses.ts
  yarn.lock
Labels: target: patch, action: merge

#23690 build: update all non-major dependencies
  package.json
  packages/angular_devkit/architect_cli/bin/architect.ts
  packages/angular_devkit/architect_cli/package.json
  packages/angular_devkit/benchmark/package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/schematics_cli/package.json
  yarn.lock
Labels: action: merge, target: minor

#23697 feat(@angular-devkit/build-angular): switch to Sass modern API in esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
Labels: action: merge, target: minor

#23671 fix(@ngtools/webpack): elide type only named imports when using `emitDecoratorMetadata`
  packages/ngtools/webpack/src/transformers/elide_imports.ts
  packages/ngtools/webpack/src/transformers/elide_imports_spec.ts
Labels: target: patch, action: merge

#23706 fix(@angular-devkit/build-angular): process stylesheet resources from url tokens with esbuild browser builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/css-resource-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
Labels: action: merge, target: minor

#23710 [14.1.x]fix(@angular-devkit/build-angular): process stylesheet resources from url tokens with esbuild browser builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/css-resource-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
Labels: target: patch, action: merge

#23709 build: disable UT testing multiple node versions
  tools/toolchain_info.bzl
Labels: target: patch, action: merge

#23694 test: improve test error message logs
  tests/legacy-cli/e2e/utils/process.ts
  tests/legacy-cli/e2e/utils/test_process.ts
Labels: target: patch, action: merge

#23719 fix(@angular-devkit/build-angular): avoid collect stats from chunks with no files
  packages/angular_devkit/build_angular/src/webpack/plugins/analytics.ts
Labels: target: patch, action: merge

#23720 Bump version to "v14.1.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#23721 docs: release notes for the v14.1.2 release
  CHANGELOG.md
Labels: action: merge

#23722 fix(@angular-devkit/build-angular): use valid CSS comment for sourcemaps with Sass in esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
Labels: action: merge, target: minor

#23725 refactor(@angular-devkit/build-angular): remove workaround for handle options requests
  packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
Labels: action: merge, target: minor

#23727 Bump version to "v14.2.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#23711 test: add missing yargs config
  tests/legacy-cli/e2e_runner.ts
Labels: target: patch, action: merge

#23712 test: ensure test assets are writable when copied for use in e2e tests
  tests/legacy-cli/e2e/utils/assets.ts
Labels: target: patch, action: merge

#23728 fix(@angular-devkit/core): update workspace extension warning to use correct phrasing
  packages/angular_devkit/core/src/workspace/json/reader.ts
Labels: target: patch, action: merge

#23730 refactor(@angular-devkit/core): remove deprecated rxjs `empty` function usage
  packages/angular_devkit/core/src/logger/logger.ts
Labels: target: patch, action: merge

#23731 ci: re add `test-browsers` step
  .circleci/dynamic_config.yml
Labels: target: patch, action: merge

#23732 refactor(@angular-devkit/schematics): reduce RxJS usage in callRule/callSource functions
  packages/angular_devkit/schematics/src/engine/schematic.ts
  packages/angular_devkit/schematics/src/rules/call.ts
Labels: action: merge, target: minor

#23740 refactor: remove unused local variables
  packages/angular/cli/src/command-builder/command-runner.ts
  packages/angular/cli/src/utilities/color.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/utils/color.ts
  packages/angular_devkit/build_angular/src/utils/purge-cache.ts
  packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
  packages/angular_devkit/core/node/testing/index.ts
  packages/angular_devkit/schematics/src/engine/interface.ts
  packages/schematics/angular/module/index.ts
  scripts/json-help.ts
  tests/legacy-cli/e2e/utils/packages.ts
Labels: action: merge, target: minor

#23733 docs: typo in cache command long description
  packages/angular/cli/src/commands/cache/long-description.md
Labels: target: patch, action: merge

#23739 ci: update `ChromeDriver` to `104.0.5112.79`
  package.json
Labels: action: merge, target: minor

#23747 build: update `@types/semver` to `^7.3.12`
  package.json
  packages/angular/cli/src/commands/update/cli.ts
  yarn.lock
Labels: action: merge, target: minor

#23757 Bump version to "v14.1.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#23758 docs: release notes for the v14.1.3 release
  CHANGELOG.md
Labels: action: merge

#23759 Bump version to "v14.2.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#23761 Bump version to "v14.2.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: target: rc, action: merge

#23774 fix(@angular-devkit/build-angular): correctly handle parenthesis in url
  packages/angular_devkit/build_angular/src/builders/browser/specs/styles_spec.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/postcss-cli-resources.ts
Labels: target: patch, action: merge

#23770 build: prevent busting bazel analysis cache between build and test
  .bazelrc
Labels: target: patch, action: merge

#23779 refactor(@angular/cli): update analytics prompt copy
  packages/angular/cli/lib/config/workspace-schema.json
  packages/angular/cli/src/analytics/analytics.ts
  tests/legacy-cli/e2e/tests/misc/ask-analytics-command.ts
Labels: target: patch, action: merge

#23778 refactor(@angular-devkit/build-angular): process esbuild builder global stylesheets and code at the same time
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
Labels: target: rc, action: merge

#23782 Minor performance improvements for esbuild-based builder Sass support
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
Labels: target: rc, action: merge

#23790 fix(@angular-devkit/build-angular): correct esbuild builder global stylesheet sourcemap URL
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
Labels: target: rc, action: merge

#23794 build: update ng-dev version
  package.json
  yarn.lock
Labels: action: merge, comp: build & ci, target: minor

#23795 build: update ng-dev version
  package.json
  yarn.lock
Labels: target: rc, action: merge

#23796 Bump version to "v14.2.0" with changelog.
  CHANGELOG.md
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
Labels: action: merge

#23797 docs: release notes for the v14.2.0 release
  CHANGELOG.md
Labels: action: merge, target: minor, comp: docs

#23811 fix(@schematics/angular): update ng-packagr version to `^14.2.0`
  packages/schematics/angular/utility/latest-versions/package.json
Labels: target: patch, action: merge

#23812 Bump version to "v14.2.1" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#23813 docs: release notes for the v14.2.1 release
  CHANGELOG.md
Labels: action: merge, target: minor, comp: docs

#23767 test: watch full stdout when waiting for match
  tests/legacy-cli/e2e/tests/build/bundle-budgets.ts
  tests/legacy-cli/e2e/utils/process.ts
  tests/legacy-cli/e2e/utils/utils.ts
Labels: target: patch, action: merge

#23741 test: remove reliance on built tarballs in E2E tests
  tests/legacy-cli/e2e/tests/misc/cli-exit-interop.ts
  tests/legacy-cli/e2e/tests/packages/webpack/test-app.ts
  tests/legacy-cli/e2e/tests/update/update-multiple-versions.ts
  tests/legacy-cli/e2e/tests/update/update.ts
  tests/legacy-cli/e2e/utils/assets.ts
  tests/legacy-cli/e2e/utils/project.ts
Labels: target: patch, action: merge

#23784 test: ensure saucelabs tests are not excluded in CI
  .circleci/dynamic_config.yml
  tests/legacy-cli/e2e/tests/misc/browsers.ts
  tests/legacy-cli/e2e/utils/process.ts
Labels: target: patch, action: merge

#23788 build: upload build artifacts from PR builds to CircleCI for usage
  .circleci/dynamic_config.yml
Labels: target: patch, action: merge

#23793 refactor(@angular-devkit/build-angular): reorganize esbuild builder setup steps
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
Labels: action: merge, target: minor

#23808 fix(@angular-devkit/build-angular): allow esbuild-based builder to use SVG Angular templates
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
Labels: target: patch, action: merge

#23818 Revert "test: enable rbe on all unit tests"
  packages/angular_devkit/build_angular/BUILD.bazel
Labels: target: patch, action: merge

#23823 refactor(@angular/cli): remove deprecated path handler
  packages/angular/cli/src/command-builder/schematics-command-module.ts
Labels: target: major, action: merge, flag: breaking change

#23820 refactor(@schematics/angular): remove deprecated appDir option
  packages/schematics/angular/app-shell/schema.json
  packages/schematics/angular/universal/schema.json
Labels: target: major, action: merge, flag: breaking change

#23787 fix(@angular-devkit/build-angular): issue warning when using deprecated tilde imports
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: target: patch, action: merge

#23828 build: adjust BUILD file external comment markers
  packages/angular/cli/BUILD.bazel
  packages/angular/pwa/BUILD.bazel
  packages/angular_devkit/architect/BUILD.bazel
  packages/angular_devkit/architect/node/BUILD.bazel
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/core/BUILD.bazel
  packages/angular_devkit/core/node/BUILD.bazel
  packages/angular_devkit/core/node/testing/BUILD.bazel
  packages/angular_devkit/schematics/BUILD.bazel
  packages/angular_devkit/schematics/tasks/BUILD.bazel
  packages/angular_devkit/schematics/tasks/node/BUILD.bazel
  packages/angular_devkit/schematics/tools/BUILD.bazel
  packages/angular_devkit/schematics_cli/BUILD.bazel
  packages/schematics/angular/BUILD.bazel
  tools/ng_cli_schema_generator.bzl
  tools/ts_json_schema.bzl
Labels: target: patch, action: merge

#23827 perf(@angular-devkit/build-angular): use esbuild-based builder to directly downlevel `for await...of`
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
Labels: action: merge, target: minor

#23835 fix(@angular-devkit/build-angular): handling of `@media` queries inside css layers
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge

#21997 build: use issue forms for issue creation
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/2-feature-request.md
  .github/ISSUE_TEMPLATE/2-feature-request.yml
  .github/ISSUE_TEMPLATE/3-docs-bug.md
  .github/ISSUE_TEMPLATE/4-security-issue-disclosure.md
  .github/ISSUE_TEMPLATE/5-support-request.md
  .github/ISSUE_TEMPLATE/6-angular-framework.md
  .github/ISSUE_TEMPLATE/7-angular-material.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: target: patch, action: merge

#23686 test: remove ci specific logic
  tests/legacy-cli/e2e_runner.ts
Labels: target: patch, action: merge
