Repository angular/angular-cli, pull requests merged in 2022-12, with the labels that each got.

#24353 fix(@angular-devkit/build-angular): prevent optimization adding unsupported ECMASCript features
  packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts
Labels: target: patch, action: merge

#24359 fix(@schematics/angular): add missing semicolon in functional guard/resolver/interceptor
  packages/schematics/angular/guard/type-files/__name@dasherize__.guard.ts.template
  packages/schematics/angular/interceptor/functional-files/__name@dasherize@if-flat__/__name@dasherize__.interceptor.ts.template
  packages/schematics/angular/resolver/functional-files/__name@dasherize__.resolver.ts.template
Labels: action: merge, target: minor

#24358 fix(@schematics/angular): add missing import for functional interceptor spec
  packages/schematics/angular/interceptor/functional-files/__name@dasherize@if-flat__/__name@dasherize__.interceptor.spec.ts.template
Labels: action: merge, target: minor

#24357 fix(@angular-devkit/build-angular): downlevel class properties when targeting Safari <=v15
  packages/angular_devkit/build_angular/src/babel/presets/application.ts
  packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
  tests/legacy-cli/e2e/tests/misc/safari-15-class-properties.ts
Labels: area: devkit/build-angular, target: patch, action: merge

#24367 refactor(@angular-devkit/build-angular): convert `transformedContent` into a function
  packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html.ts
  packages/angular_devkit/build_angular/src/utils/index-file/html-rewriting-stream.ts
  packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
Labels: target: patch, action: merge

#24380 fix(@angular-devkit/build-angular): default preserve symlinks to Node.js value for esbuild
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
Labels: target: patch, action: merge

#24382 fix(@angular-devkit/build-angular): explicitly send options to JS transformer workers
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer.ts
Labels: action: merge, target: minor

#24390 Bump version to "v15.0.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24391 docs: release notes for the v15.0.3 release
  CHANGELOG.md
Labels: area: docs, action: merge

#24400 Bump version to "v15.1.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24397 feat(@angular-devkit/schematics): add `runSchematic` and `runExternalSchematic` methods
  goldens/public-api/angular_devkit/schematics/testing/index.md
  packages/angular/cli/src/commands/update/schematic/index_spec.ts
  packages/angular/pwa/pwa/index_spec.ts
  packages/angular_devkit/build_angular/src/builders/karma/index.ts
  packages/angular_devkit/schematics/testing/schematic-test-runner.ts
  packages/angular_devkit/schematics_cli/blank/schematic-files/src/__name@dasherize__/index_spec.ts
  packages/angular_devkit/schematics_cli/schematic/files/src/my-full-schematic/index_spec.ts
  packages/angular_devkit/schematics_cli/schematic/files/src/my-other-schematic/index_spec.ts
  packages/angular_devkit/schematics_cli/schematic/files/src/my-schematic/index_spec.ts
  packages/schematics/angular/app-shell/index_spec.ts
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/class/index_spec.ts
  packages/schematics/angular/component/index_spec.ts
  packages/schematics/angular/directive/index_spec.ts
  packages/schematics/angular/e2e/index_spec.ts
  packages/schematics/angular/enum/index_spec.ts
  packages/schematics/angular/guard/index_spec.ts
  packages/schematics/angular/interceptor/index_spec.ts
  packages/schematics/angular/interface/index_spec.ts
  packages/schematics/angular/library/index_spec.ts
  packages/schematics/angular/migrations/update-15/remove-browserslist-config_spec.ts
  packages/schematics/angular/migrations/update-15/remove-platform-server-exports_spec.ts
  packages/schematics/angular/migrations/update-15/update-karma-main-file_spec.ts
  packages/schematics/angular/migrations/update-15/update-typescript-target_spec.ts
  packages/schematics/angular/migrations/update-15/update-workspace-config_spec.ts
  packages/schematics/angular/module/index_spec.ts
  packages/schematics/angular/ng-new/index_spec.ts
  packages/schematics/angular/pipe/index_spec.ts
  packages/schematics/angular/resolver/index_spec.ts
  packages/schematics/angular/service-worker/index_spec.ts
  packages/schematics/angular/service/index_spec.ts
  packages/schematics/angular/universal/index_spec.ts
  packages/schematics/angular/web-worker/index_spec.ts
  packages/schematics/angular/workspace/index_spec.ts
Labels: action: merge, target: minor, detected: feature, detected: deprecation

#24395 fix(@angular-devkit/build-angular): include sources in generated Sass source maps
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: target: patch, action: merge

#24404 fix(@angular-devkit/build-angular): update locale setting snippet to use `globalThis`.
  packages/angular_devkit/build_angular/src/utils/i18n-inlining.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: target: patch, action: merge

#24418 fix(@angular-devkit/build-angular): display actionable error when a style does not exist in Karma builder
  packages/angular_devkit/build_angular/src/builders/karma/tests/options/styles_spec.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/styles-webpack-plugin.ts
Labels: target: patch, action: merge

#24409 feat(@schematics/angular): add environments generation schematic
  packages/schematics/angular/collection.json
  packages/schematics/angular/environments/index.ts
  packages/schematics/angular/environments/index_spec.ts
  packages/schematics/angular/environments/schema.json
Labels: action: merge, target: minor, detected: feature

#24420 feat(@angular-devkit/build-angular): support inline component Sass styles with esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/experimental-warnings.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
Labels: action: merge, target: minor, detected: feature

#24421 fix(@angular-devkit/build-angular): only set ngDevMode when script optimizations are enabled
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
Labels: target: patch, action: merge

#24427 fix(@angular-devkit/build-angular): transform async generator class methods for Zone.js support
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer-worker.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer.ts
Labels: action: merge, target: minor

#24436 fix(@angular-devkit/build-angular): update `css-loader` to `6.7.3`
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge

#24437 Bump version to "v15.0.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24438 docs: release notes for the v15.0.4 release
  CHANGELOG.md
Labels: area: docs, action: merge

#24439 Bump version to "v15.1.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge
