Repository angular/angular-cli, pull requests merged in 2022-11, with the labels that each got.

#24164 fix(@angular-devkit/build-angular): provide workaround for V8 object spread performance defect
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
Labels: target: rc, action: merge

#24167 fix(@schematics/angular): guard schematics should include all guards (CanMatch)
  packages/schematics/angular/guard/files/__name@dasherize__.guard.ts.template
  packages/schematics/angular/guard/index.ts
  packages/schematics/angular/guard/index_spec.ts
  packages/schematics/angular/guard/schema.json
Labels: target: patch, action: merge

#24171 Bump version to "v14.2.8" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#24172 docs: release notes for the v14.2.8 release
  CHANGELOG.md
Labels: area: docs, target: major, action: merge

#24173 Bump version to "v15.0.0-rc.2" with changelog.
  CHANGELOG.md
  package.json
Labels: target: rc, action: merge

#24174 docs: release notes for the v15.0.0-rc.2 release
  CHANGELOG.md
Labels: area: docs, action: merge, target: minor

#24180 build: update github/codeql-action action to v2.1.30
  .github/workflows/scorecard.yml
Labels: target: rc, action: merge

#24184 refactor(@angular-devkit/core): remove unneeded import statements from Node.js file host
  goldens/public-api/angular_devkit/core/node/index.md
  packages/angular_devkit/core/node/host.ts
Labels: action: merge, target: minor

#24181 fix(@angular-devkit/build-angular): account for package.json exports with Sass in esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
Labels: target: rc, action: merge

#24169 build: update dependency npm-package-arg to v10
  package.json
  packages/angular/cli/package.json
  packages/angular/cli/src/commands/add/cli.ts
  packages/angular/cli/src/commands/update/cli.ts
  yarn.lock
Labels: action: merge, target: minor

#24185 fix(@angular-devkit/build-angular): rebase Sass url() values when using esbuild-based builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
  packages/angular_devkit/build_angular/src/sass/rebasing-importer.ts
  packages/angular_devkit/build_angular/src/sass/sass-service.ts
  packages/angular_devkit/build_angular/src/sass/worker.ts
Labels: target: rc, action: merge

#24192 fix(@angular-devkit/build-angular): isolate zone.js usage when rendering server bundles
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
  packages/angular_devkit/build_angular/src/builders/app-shell/render-worker.ts
Labels: target: patch, action: merge

#24191 fix(@angular-devkit/build-angular): only add `@angular/platform-server/init` when package is installed.
  packages/angular_devkit/build_angular/src/builders/server/index.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
Labels: target: rc, action: merge

#24194 fix(@angular-devkit/build-angular): update sourcemaps when rebasing Sass url() functions in esbuild builder
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/sass/rebasing-importer.ts
  packages/angular_devkit/build_angular/src/sass/sass-service.ts
  packages/angular_devkit/build_angular/src/sass/worker.ts
Labels: target: rc, action: merge

#24196 fix(@angular-devkit/architect): default to failure if no builder result is provided
  packages/angular_devkit/architect/src/create-builder.ts
Labels: target: patch, action: merge

#24201 fix(@angular-devkit/build-angular): avoid attempted resolve of external CSS URLs with esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/css-resource-plugin.ts
Labels: target: rc, action: merge

#24202 build: remove unused dependency `minimatch` from `@angular-devkit/build-angular`
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
Labels: target: rc, action: merge

#24205 Bump version to "v14.2.9" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24206 docs: release notes for the v14.2.9 release
  CHANGELOG.md
Labels: area: docs, action: merge

#24207 Bump version to "v15.0.0-rc.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24208 docs: release notes for the v15.0.0-rc.3 release
  CHANGELOG.md
Labels: action: merge

#24215 fix(@angular-devkit/build-angular): update browerslist package
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: rc, action: merge

#24209 fix(@angular/cli): respect registry in RC when running update through yarn
  packages/angular/cli/src/utilities/package-metadata.ts
  tests/legacy-cli/e2e/tests/update/update-secure-registry.ts
Labels: target: patch, action: merge

#24224 test(@angular/cli): remove version 12 update tests
  tests/legacy-cli/e2e/assets/12.0-project/.browserslistrc
  tests/legacy-cli/e2e/assets/12.0-project/.editorconfig
  tests/legacy-cli/e2e/assets/12.0-project/.gitignore
  tests/legacy-cli/e2e/assets/12.0-project/README.md
  tests/legacy-cli/e2e/assets/12.0-project/angular.json
  tests/legacy-cli/e2e/assets/12.0-project/e2e/protractor.conf.js
  tests/legacy-cli/e2e/assets/12.0-project/e2e/src/app.e2e-spec.ts
  tests/legacy-cli/e2e/assets/12.0-project/e2e/src/app.po.ts
  tests/legacy-cli/e2e/assets/12.0-project/e2e/tsconfig.json
  tests/legacy-cli/e2e/assets/12.0-project/karma.conf.js
  tests/legacy-cli/e2e/assets/12.0-project/package.json
  tests/legacy-cli/e2e/assets/12.0-project/src/app/app-routing.module.ts
  tests/legacy-cli/e2e/assets/12.0-project/src/app/app.component.css
  tests/legacy-cli/e2e/assets/12.0-project/src/app/app.component.html
  tests/legacy-cli/e2e/assets/12.0-project/src/app/app.component.spec.ts
  tests/legacy-cli/e2e/assets/12.0-project/src/app/app.component.ts
  tests/legacy-cli/e2e/assets/12.0-project/src/app/app.module.ts
  tests/legacy-cli/e2e/assets/12.0-project/src/assets/.gitkeep
  tests/legacy-cli/e2e/assets/12.0-project/src/environments/environment.prod.ts
  tests/legacy-cli/e2e/assets/12.0-project/src/environments/environment.ts
  tests/legacy-cli/e2e/assets/12.0-project/src/favicon.ico
  tests/legacy-cli/e2e/assets/12.0-project/src/index.html
  tests/legacy-cli/e2e/assets/12.0-project/src/main.ts
  tests/legacy-cli/e2e/assets/12.0-project/src/polyfills.ts
  tests/legacy-cli/e2e/assets/12.0-project/src/styles.css
  tests/legacy-cli/e2e/assets/12.0-project/src/test.ts
  tests/legacy-cli/e2e/assets/12.0-project/tsconfig.app.json
  tests/legacy-cli/e2e/assets/12.0-project/tsconfig.json
  tests/legacy-cli/e2e/assets/12.0-project/tsconfig.spec.json
  tests/legacy-cli/e2e/assets/13.0-project/package.json
  tests/legacy-cli/e2e/tests/update/update-multiple-versions.ts
  tests/legacy-cli/e2e/tests/update/update.ts
Labels: target: rc, action: merge

#24218 fix(@angular-devkit/build-angular): show file replacement in TS missing file error in esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
Labels: target: rc, action: merge

#24227 Bump version to "v15.0.0-rc.4" with changelog.
  CHANGELOG.md
  package.json
Labels: target: rc, action: merge

#24228 docs: release notes for the v15.0.0-rc.4 release
  CHANGELOG.md
Labels: area: docs, action: merge, target: minor

#24223 perf(@angular-devkit/build-angular): add vendor chunking to server builder
  goldens/public-api/angular_devkit/build_angular/index.md
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/schema.json
  packages/angular_devkit/build_angular/src/builders/browser/schema.json
  packages/angular_devkit/build_angular/src/builders/server/schema.json
  packages/schematics/angular/migrations/update-15/update-workspace-config.ts
  packages/schematics/angular/migrations/update-15/update-workspace-config_spec.ts
  packages/schematics/angular/universal/index.ts
Labels: target: rc, action: merge

#24226 refactor(@angular-devkit/build-angular): move esbuild angular compiler host creation to separate function
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular-host.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
Labels: action: merge, target: minor

#24236 refactor: temporaily disable sending analytics
  packages/angular/cli/src/analytics/analytics-collector.ts
Labels: target: rc, action: merge

#24237 Bump version to "v15.0.0-rc.5" with changelog.
  CHANGELOG.md
  package.json
Labels: target: rc, action: merge

#24238 docs: release notes for the v15.0.0-rc.5 release
  CHANGELOG.md
Labels: action: merge, target: minor

#24248 refactor: update framework dependencies to v15
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/angular/utility/latest-versions/package.json
Labels: target: rc, action: merge

#24249 Bump version to "v15.0.0" with changelog.
  CHANGELOG.md
  package.json
  tests/legacy-cli/e2e/tests/update/update-multiple-versions.ts
Labels: target: rc, action: merge

#24251 docs: release notes for the v15.0.0 release
  CHANGELOG.md
Labels: area: docs, action: merge

#24242 fix(@angular-devkit/build-angular): update `loader-utils` to `3.2.1`
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: action: merge, target: lts

#24234 fix(@angular/cli): use global version of the CLI when running `ng new`
  packages/angular/cli/lib/init.ts
Labels: target: patch, action: merge

#24267 Bump version to "v14.2.10" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: lts

#24268 docs: release notes for the v14.2.10 release
  CHANGELOG.md
Labels: area: docs, action: merge, target: minor

#24272 Bump version to "v13.3.10" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: lts

#24273 docs: release notes for the v13.3.10 release
  CHANGELOG.md
Labels: area: docs, action: merge, target: minor

#24252 docs: updates release documentation to include `latest-versions/package.json` and clarify what can be done in the release PR
  docs/process/release.md
Labels: area: docs, action: merge, target: minor

#24258 ci: create daily_run_workflow for 14.2.x branch
  .circleci/dynamic_config.yml
Labels: action: merge, target: lts

#24260 ci: disable nightly ci for version 12
  .circleci/config.yml
Labels: action: merge, target: lts, merge: caretaker note

#24250 refactor(@angular-devkit/build-angular): preprocess Sass resolve cache entries in esbuild Sass plugin
  packages/angular_devkit/build_angular/src/sass/rebasing-importer.ts
  packages/angular_devkit/build_angular/src/sass/worker.ts
Labels: action: merge, target: minor

#24265 fix(@schematics/angular): show warning when a TS Config is not found during migrations
  packages/schematics/angular/migrations/update-15/update-typescript-target.ts
Labels: target: patch, action: merge

#24269 ci: fix update test to work when `@angular/cli` and `@angular/core` majors diverge
  tests/legacy-cli/e2e/tests/update/update-multiple-versions.ts
Labels: target: patch, action: merge

#24270 ci: fix update test to work when `@angular/cli` and `@angular/core` majors diverge
  tests/legacy-cli/e2e/tests/update/update-multiple-versions.ts
Labels: action: merge, target: minor

#24281 build: enable the assistant-to-the-branch-manager github action
  .github/workflows/assistant-to-the-branch-manager.yml
Labels: target: patch, action: merge, area: build & ci

#24278 build: remove `regenerator-runtime` from dependencies
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
Labels: target: patch, action: merge

#24280 build: enable the ng-dev auth service
  .ng-dev/github.mts
Labels: target: patch, action: merge, area: build & ci

#24266 perf(@angular-devkit/build-angular): use worker pool for JavaScript transforms in esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer-worker.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer.ts
Labels: action: merge, target: minor

#24279 fix(@angular-devkit/build-angular): improve package deep import Sass index resolution in esbuild plugin
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
Labels: target: patch, action: merge

#24284 ci: update browser-tools
  .circleci/dynamic_config.yml
Labels: target: patch, action: merge

#24298 refactor(@angular-devkit/build-angular): encapsulate Angular compilation within esbuild compiler plugin
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular-compilation.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
Labels: action: merge, target: minor

#24285 fix(@angular-devkit/build-angular): use url function lexer to rebase Sass URLs
  packages/angular_devkit/build_angular/src/sass/rebasing-importer.ts
Labels: action: merge, target: minor

#24308 fix(@angular-devkit/build-angular): hide loader paths in webpack warnings
  packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
Labels: target: patch, action: merge

#24309 [15.0.x] fix(@angular-devkit/build-angular): use url function lexer to rebase Sass URLs
  packages/angular_devkit/build_angular/src/sass/rebasing-importer.ts
Labels: target: patch, action: merge

#24310 [15.0.x] fix(@angular-devkit/build-angular): hide loader paths in webpack warnings
  packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
Labels: target: patch, action: merge

#24311 Bump version to "v15.0.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24312 docs: release notes for the v15.0.1 release
  CHANGELOG.md
Labels: area: docs, action: merge

#24313 Bump version to "v15.1.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge

#24321 fix(@angular-devkit/build-angular): correctly set Sass quietDeps and verbose options
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: target: patch, action: merge

#24332 fix(@schematics/angular): remove EnvironmentInjector import in functional guard spec
  packages/schematics/angular/guard/type-files/__name@dasherize__.guard.spec.ts.template
Labels: action: merge, target: minor

#24331 fix(@schematics/angular): use proper variable in resolver functional spec
  packages/schematics/angular/resolver/functional-files/__name@dasherize__.resolver.spec.ts.template
Labels: action: merge, target: minor

#24333 fix(@schematics/angular): use proper variable in functional guard spec
  packages/schematics/angular/guard/type-files/__name@dasherize__.guard.spec.ts.template
Labels: action: merge, target: minor

#24330 build: update all non-major dependencies
  WORKSPACE
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#24343 Revert "docs: remove `@latest` reference from `npm init` command"
  packages/angular/create/README.md
Labels: target: patch, action: merge

#24348 Bump version to "v15.0.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24349 docs: release notes for the v15.0.2 release
  CHANGELOG.md
Labels: area: docs, action: merge

#24350 Bump version to "v15.1.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge
