Repository angular/angular-cli, pull requests merged in 2022-02, with the labels that each got.

#22629 fix(@angular-devkit/build-angular): add `whatwg-url` to downlevel exclusion list
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: target: patch, action: merge

#22628 docs(@angular-devkit/build-angular): add missing period in `include` description
  packages/angular_devkit/build_angular/src/builders/karma/schema.json
Labels: target: patch, action: merge

#22624 test: remove hardcoded app-shell test
  tests/legacy-cli/e2e/tests/build/build-app-shell.ts
Labels: target: patch, action: merge

#22623 Patch version of #22612
  packages/angular_devkit/build_angular/src/utils/build-options.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
  packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
Labels: target: patch, action: merge

#22612 fix(@angular-devkit/build-angular): ensure to use content hash as filenames hashing mechanism
  packages/angular_devkit/build_angular/src/utils/build-options.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
  packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
Labels: target: major, action: merge

#22631 build: stop publishing `@angular-devkit/build-optimizer` to NPM
  README.md
  packages/angular_devkit/build_optimizer/package.json
Labels: target: patch, action: merge

#22626 fix(@angular-devkit/core): correctly resolve schema references defaults
  packages/angular_devkit/core/src/json/schema/registry.ts
  packages/angular_devkit/core/src/json/schema/transforms.ts
  packages/angular_devkit/core/src/json/schema/transforms_spec.ts
Labels: target: patch, action: merge

#22625 docs(@angular/cli): update `@angular/cli` package readme
  docs/DEVELOPER.md
  packages/angular/cli/README.md
Labels: target: patch, action: merge

#22639 Bump version to "v13.2.2" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge, comp: build & ci

#22640 docs: release notes for the v13.2.2 release
  CHANGELOG.md
Labels: target: major, action: merge, comp: build & ci

#22641 Bump version to "v14.0.0-next.0" with changelog.
  CHANGELOG.md
Labels: target: major, action: merge, comp: build & ci

#22645 build: setup OpenSSF Scorecard
  .github/workflows/scorecard.yml
Labels: target: patch, action: merge, comp: build & ci

#22646 refactor(@angular-devkit/build-angular): remove workaround for fidelity and performance of babel sourcemaps
  packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
Labels: target: major, action: merge

#22633 fix(@ngtools/webpack): support locating PNPM lock file during NGCC processing
  packages/ngtools/webpack/src/ngcc_processor.ts
Labels: target: patch, action: merge

#22663 ci: group all scorecard action dependencies
  renovate.json
Labels: target: patch, action: merge

#22666 build: fix bazel build on windows
  WORKSPACE
Labels: target: patch, action: merge

#22670 fix(@angular-devkit/build-angular): block Karma from starting until build is complete
  packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma.ts
Labels: target: patch, action: merge

#22678 Bump version to "v13.2.3" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#22679 docs: release notes for the v13.2.3 release
  CHANGELOG.md
Labels: target: major, action: merge

#22680 Bump version to "v14.0.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: target: major, action: merge

#22695 build: add permissions to current github action workflows
  .github/workflows/dev-infra.yml
  .github/workflows/feature-requests.yml
  .github/workflows/lock-closed.yml
  .github/workflows/scorecard.yml
Labels: target: patch, action: merge

#22719 build: revert to @babel/core version 7.17.2
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: major, action: merge

#22729 docs: release notes for the v13.2.4 release
  CHANGELOG.md
Labels: action: merge

#22730 Bump version to "v14.0.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#22731 test: update E2E production application size expectations
  tests/legacy-cli/e2e/tests/build/prod-build.ts
Labels: target: major, action: merge

#22722 build: update bazel to 5.0.0
  .bazelversion
Labels: target: minor

#22735 build: remove multiple unused development dependencies
  package.json
  yarn.lock
Labels: target: minor

#22746 build: update snapshot e2e setup to reflect builds repository rename
  tests/legacy-cli/e2e/ng-snapshot/package.json
Labels: action: merge, target: minor

#22745 fix(@angular-devkit/build-angular): update `terser` to `5.11.0`
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge

#22740 fix(@angular-devkit/build-angular): don't rename blocks which have a name
  packages/angular_devkit/build_angular/src/webpack/plugins/named-chunks-plugin.ts
Labels: target: patch, action: merge

#22721 ci: use renovate Github Action tag version pinning
  .github/workflows/dev-infra.yml
  .github/workflows/scorecard.yml
Labels: action: merge, target: minor

#22747 [13.2.x] build: update snapshot e2e setup to reflect builds repository rename
  tests/legacy-cli/e2e/ng-snapshot/package.json
Labels: target: patch, action: merge

#22759 Bump version to "v13.2.5" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#22761 docs: release notes for the v13.2.5 release
  CHANGELOG.md
Labels: target: major, action: merge

#22762 Bump version to "v14.0.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: target: major, action: merge

#22756 docs(@angular-devkit/core): typo in string.ts docs
  packages/angular_devkit/core/src/utils/strings.ts
Labels: target: patch, action: merge

#22767 refactor(@angular-devkit/build-angular): replace most custom path `resolve` usages with Node.js builtins
  packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
  packages/angular_devkit/build_angular/src/builders/browser/index.ts
  packages/angular_devkit/build_angular/src/utils/normalize-builder-schema.ts
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
Labels: target: major, action: merge

#22775 refactor(@angular/cli): remove unused `INITIAL_COMMIT_MESSAGE` text file
  packages/angular/cli/BUILD.bazel
  packages/angular/cli/utilities/INITIAL_COMMIT_MESSAGE.txt
Labels: action: merge, target: minor

#22774 refactor(@angular-devkit/build-angular): remove unneeded JsonObject type casting
  goldens/public-api/angular_devkit/build_angular/src/index.md
  packages/angular_devkit/build_angular/src/builders/browser/index.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
  packages/angular_devkit/build_angular/src/builders/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/builders/protractor/index.ts
  packages/angular_devkit/build_angular/src/builders/server/index.ts
Labels: target: major, action: merge
