Repository angular/angular-cli, pull requests merged in 2022-03, with the labels that each got.

#22790 ci: remove Node.js v12 E2E job
  .circleci/config.yml
Labels: target: major, action: merge

#22791 test: update E2E production application size expectations
  tests/legacy-cli/e2e/tests/build/prod-build.ts
Labels: target: patch, action: merge

#22793 Bump version to "v14.0.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: target: major, action: merge

#22792 build: update `@types/yargs-parser` to `21.0.0`
  package.json
  packages/angular_devkit/architect_cli/bin/architect.ts
  packages/angular_devkit/schematics_cli/bin/schematics.ts
  yarn.lock
Labels: target: major, action: merge

#22800 fix(@angular-devkit/build-angular): ignore css only chunks during naming
  packages/angular_devkit/build_angular/src/webpack/plugins/named-chunks-plugin.ts
Labels: target: patch, action: merge

#22802 refactor(@angular-devkit/build-angular): move dev-server specs into a seperate directory
  packages/angular_devkit/build_angular/src/builders/dev-server/specs/hmr_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/specs/index_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/specs/live-reload_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/specs/ssl_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/specs/works_spec.ts
Labels: target: patch, action: merge

#22806 build: update `@types/node` to `^14.15.0`
  packages/angular_devkit/schematics_cli/blank/project-files/package.json
  packages/angular_devkit/schematics_cli/schematic/files/package.json
  packages/schematics/angular/migrations/update-14/angular-packages-version-prefix_spec.ts
  packages/schematics/angular/utility/latest-versions/package.json
Labels: target: major, action: merge

#22816 build: fix order of JSON help generation
  scripts/json-help.ts
  scripts/snapshots.ts
Labels: target: major, action: merge

#22817 refactor(@angular/cli): always use posix separator in `longDescriptionRelativePath`
  packages/angular/cli/src/command-builder/command-module.ts
Labels: action: merge, target: minor

#22819 Bump version to "v14.0.0-next.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#22820 Bump version to "v13.2.6" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#22821 docs: release notes for the v13.2.6 release
  CHANGELOG.md
Labels: action: merge

#22823 refactor(@angular/cli): replace `longDescription` line endings with `\n`
  packages/angular/cli/src/command-builder/command-module.ts
Labels: target: major, action: merge

#22828 fix(@angular/cli): add long description to `ng update`
  packages/angular/cli/src/commands/update/cli.ts
Labels: target: major, action: merge

#22824 fix(@angular/cli): remove JSON serialized description from help output
  packages/angular/cli/src/command-builder/utilities/json-help.ts
Labels: target: major, action: merge

#22830 docs: replace `app` with `application`
  packages/angular_devkit/build_angular/src/builders/app-shell/schema.json
  packages/angular_devkit/build_angular/src/builders/dev-server/schema.json
  packages/schematics/angular/app-shell/index.ts
  packages/schematics/angular/app-shell/schema.json
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/collection.json
  packages/schematics/angular/e2e/e2e-long.md
  packages/schematics/angular/e2e/schema.json
  packages/schematics/angular/service-worker/index.ts
  packages/schematics/angular/service-worker/index_spec.ts
  packages/schematics/angular/universal/schema.json
  packages/schematics/angular/utility/ng-ast-utils.ts
  packages/schematics/angular/workspace/files/README.md.template
  tests/angular_devkit/core/json/schema/serializers/schema_benchmark.json
Labels: target: patch, action: merge

#22814 fix(@angular/cli): don't prompt for analytics when running `ng analytics`
  packages/angular/cli/src/command-builder/command-module.ts
Labels: target: major, action: merge

#22832 docs(@angular/cli): improve several ng update option descriptions
  packages/angular/cli/src/commands/update/cli.ts
Labels: target: major, action: merge

#22835 fix(@angular/cli): sort commands in help output
  packages/angular/cli/src/command-builder/command-runner.ts
Labels: target: major, action: merge

#22810 fix(@angular/cli): favor project in cwd when running architect commands
  packages/angular/cli/src/command-builder/architect-command-module.ts
  tests/legacy-cli/e2e/tests/commands/builder-project-by-cwd.ts
Labels: target: major, action: merge

#22841 build: update webpack to 5.70.0
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_optimizer/package.json
  packages/angular_devkit/build_webpack/package.json
  packages/ngtools/webpack/package.json
  yarn.lock
Labels: action: merge, target: minor

#22844 refactor(@angular-devkit/build-angular): remove deprecated `NG_BUILD_CACHE` environment variable
  packages/angular_devkit/build_angular/src/utils/environment-options.ts
  packages/angular_devkit/build_angular/src/utils/normalize-cache.ts
Labels: target: major, action: merge, flag: breaking change

#22770 fix(@schematics/angular): remove `@types/node` from new projects
  packages/schematics/angular/e2e/index.ts
  packages/schematics/angular/universal/index.ts
  packages/schematics/angular/workspace/files/package.json.template
Labels: target: patch, action: merge

#22848 refactor(@angular/cli): remove `hasAnalyticsConfig` analytics logic
  packages/angular/cli/bin/postinstall/analytics-prompt.js
  packages/angular/cli/src/analytics/analytics.ts
Labels: target: major, action: merge

#22853 refactor: bump CLI version to `13.3.0-rc.0`
  package.json
Labels: target: minor

#22854 Bump version to "v13.3.0" with changelog.
  CHANGELOG.md
  package.json
  packages/schematics/angular/utility/latest-versions.ts
Labels: action: merge, target: minor

#22855 docs: release notes for the v13.3.0 release
  CHANGELOG.md
Labels: target: major, action: merge

#22856 Bump version to "v14.0.0-next.6" with changelog.
  CHANGELOG.md
  package.json
Labels: target: major, action: merge

#22858 Couple of small `ng generate` help fixes
  packages/angular/cli/src/commands/generate/cli.ts
Labels: target: major, action: merge

#22859 fix(@angular/cli): print entire config when no positional args are provided to `ng config`
  packages/angular/cli/src/commands/config/cli.ts
  tests/legacy-cli/e2e/tests/commands/config/config-get.ts
  tests/legacy-cli/e2e/tests/commands/help/help-json.ts
Labels: target: major, action: merge

#22862 fix(@schematics/angular): Consolidated setup with a single `beforeEach()`
  packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.spec.ts.template
Labels: target: major, action: merge

#22864 refactor: replace deprecated String.prototype.substr()
  lib/bootstrap-local.js
  lib/packages.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
  packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/postcss-cli-resources.ts
  packages/angular_devkit/core/src/json/parser.ts
  packages/angular_devkit/core/src/utils/strings.ts
  packages/angular_devkit/core/src/virtual-fs/path.ts
  packages/angular_devkit/core/src/workspace/json/utilities.ts
  packages/angular_devkit/schematics/src/rules/move.ts
  packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts
  packages/angular_devkit/schematics_cli/bin/schematics.ts
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/library/index.ts
  packages/schematics/angular/ng-new/index.ts
  scripts/build.ts
Labels: action: merge, target: minor

#22879 fix(@ngtools/webpack): update peer dependency to reflect TS 4.6 support
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
Labels: target: major, action: merge

#22880 fix(@angular-devkit/build-angular): remove unneeded JIT reflect metadata polyfill
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/angular_devkit/build_webpack/test/angular-app/src/polyfills.ts
  tests/legacy-cli/e2e/assets/webpack/test-app/app/main.ts
  tests/legacy-cli/e2e/assets/webpack/test-app/package.json
  tests/legacy-cli/e2e/tests/build/polyfills.ts
  tests/legacy-cli/e2e/tests/misc/minimal-config.ts
Labels: target: major, action: merge, flag: breaking change

#22133 fix(@angular-devkit/core): add Angular CLI major version as analytics dimension
  docs/design/analytics.md
  goldens/public-api/angular_devkit/core/src/index.md
  packages/angular/cli/src/analytics/analytics-collector.ts
  packages/angular_devkit/build_angular/src/webpack/configs/analytics.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/analytics.ts
  packages/angular_devkit/core/src/analytics/index.ts
Labels: hotlist: devRel, target: patch, action: merge

#22883 refactor(@angular-devkit/build-angular): remove types for `@discoveryjs/json-ext`
  packages/angular_devkit/build_angular/src/typings.d.ts
Labels: target: patch, action: merge

#22882 refactor(@angular/cli): clean up package-metadata retrieval logic
  package.json
  packages/angular/cli/BUILD.bazel
  packages/angular/cli/src/commands/add/cli.ts
  packages/angular/cli/src/commands/update/schematic/index.ts
  packages/angular/cli/src/typings-bazel.d.ts
  packages/angular/cli/src/typings.ts
  packages/angular/cli/src/utilities/install-package.ts
  packages/angular/cli/src/utilities/package-json.ts
  packages/angular/cli/src/utilities/package-metadata.ts
  packages/angular/cli/src/utilities/package-tree.ts
  yarn.lock
Labels: target: major, action: merge

#22900 fix(@angular-devkit/build-angular): allow Workers in Stackblitz
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: target: patch, action: merge

#22915 fix(@angular-devkit/build-angular): don't override asset info when updating assets
  packages/angular_devkit/build_angular/src/webpack/plugins/css-optimizer-plugin.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/transfer-size-plugin.ts
Labels: target: patch, action: merge

#22910 refactor(@angular-devkit/core): deprecate unused exception classes
  goldens/public-api/angular_devkit/core/index.md
  packages/angular_devkit/core/src/exception.ts
  packages/angular_devkit/core/src/exception/index.ts
  packages/angular_devkit/core/src/experimental/jobs/create-job-handler.ts
  packages/angular_devkit/core/src/experimental/jobs/exception.ts
  packages/angular_devkit/core/src/index.ts
  packages/angular_devkit/core/src/json/schema/registry.ts
Labels: target: major, action: merge, flag: deprecation

#22916 refactor(@angular/cli): improved code quality
  lib/bootstrap-local.js
  packages/angular/cli/src/commands/analytics/cli.ts
  packages/angular/cli/src/commands/analytics/info/cli.ts
  packages/angular/cli/src/commands/analytics/settings/cli.ts
  packages/angular/cli/src/commands/doc/cli.ts
  packages/angular/cli/src/commands/e2e/cli.ts
Labels: target: major, action: merge

#22917 fix(@angular-devkit/build-angular): add `node_modules` prefix to excludes RegExp
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: target: patch, action: merge

#22918 fix(@angular/cli): display package manager during `ng update`
  packages/angular/cli/src/commands/update/cli.ts
Labels: target: major, action: merge

#22920 Bump version to "v13.3.1" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#22921 docs: release notes for the v13.3.1 release
  CHANGELOG.md
Labels: action: merge

#22922 Bump version to "v14.0.0-next.7" with changelog.
  CHANGELOG.md
  package.json
Labels: target: major, action: merge

#22929 refactor(@angular-devkit/build-angular): replace most custom path normalize usage with Node.js builtins
  packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
  packages/angular_devkit/build_angular/src/builders/browser/index.ts
  packages/angular_devkit/build_angular/src/builders/karma/index.ts
  packages/angular_devkit/build_angular/src/utils/normalize-asset-patterns.ts
  packages/angular_devkit/build_angular/src/utils/normalize-builder-schema.ts
  packages/angular_devkit/build_angular/src/utils/normalize-file-replacements.ts
  packages/angular_devkit/build_angular/src/utils/service-worker.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/typescript.ts
Labels: target: major, action: merge

#22930 Bump version to "v12.2.17" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: lts

#22931 docs: release notes for the v12.2.17 release
  CHANGELOG.md
Labels: target: major, action: merge
