Repository angular/angular-cli, pull requests merged in 2022-01, with the labels that each got.

#22451 fix(@angular-devkit/build-angular): enable `:where` CSS pseudo-class
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge

#22447 Don't set TAILWIND_MODE=watch
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: action: merge, target: minor

#22446 fix(@schematics/angular): set `skipTests` flag for resolvers when using ng new --skip-tests
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/index_spec.ts
Labels: target: patch, action: merge

#22425 build: perform package.json substitutions in bazel build
  .bazelrc
  .prettierignore
  BUILD.bazel
  WORKSPACE
  packages/angular/cli/BUILD.bazel
  packages/angular/pwa/BUILD.bazel
  packages/angular_devkit/architect/BUILD.bazel
  packages/angular_devkit/architect_cli/BUILD.bazel
  packages/angular_devkit/benchmark/BUILD.bazel
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_optimizer/BUILD.bazel
  packages/angular_devkit/build_webpack/BUILD.bazel
  packages/angular_devkit/core/BUILD.bazel
  packages/angular_devkit/schematics/BUILD.bazel
  packages/angular_devkit/schematics_cli/BUILD.bazel
  packages/ngtools/webpack/BUILD.bazel
  packages/schematics/angular/BUILD.bazel
  scripts/build-bazel.ts
  tools/BUILD.bazel
  tools/defaults.bzl
  tools/link_package_json_to_tarballs.bzl
  tools/package_json_release_filter.jq
  tools/test/BUILD.bazel
  tools/test/expected_package.json
  tools/test/project_package.json
  tools/test/root_package.json
Labels: target: patch, action: merge, comp: build & ci

#22459 docs: remove old information from debugging section
  docs/design/analytics.md
Labels: target: patch, action: merge

#22466 fix(@angular-devkit/build-angular): enable `:where` CSS pseudo-class
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge

#22457 fix(@angular-devkit/build-angular): correctly resolve `core-js/proposals/reflect-metadata`
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: target: patch, action: merge

#22456 fix(@angular-devkit/build-angular): use `contenthash` instead of `chunkhash` for chunks
  packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
Labels: target: patch, action: merge

#22209 feat(@angular-devkit/build-angular): expose i18nDuplicateTranslation …
  goldens/public-api/angular_devkit/build_angular/src/index.md
  packages/angular_devkit/build_angular/src/builders/browser/schema.json
  packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
  packages/angular_devkit/build_angular/src/builders/server/schema.json
  packages/angular_devkit/build_angular/src/utils/build-options.ts
  packages/angular_devkit/build_angular/src/utils/i18n-options.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-merging.ts
Labels: action: merge, target: minor

#22473 fix(@angular-devkit/build-angular): automatically purge stale build cache entries
  packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
  packages/angular_devkit/build_angular/src/builders/browser/index.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
  packages/angular_devkit/build_angular/src/builders/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/builders/karma/index.ts
  packages/angular_devkit/build_angular/src/builders/ng-packagr/index.ts
  packages/angular_devkit/build_angular/src/builders/server/index.ts
  packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
  packages/angular_devkit/build_angular/src/utils/normalize-cache.ts
  packages/angular_devkit/build_angular/src/utils/package-version.ts
  packages/angular_devkit/build_angular/src/utils/purge-cache.ts
  packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
  tests/legacy-cli/e2e/tests/build/disk-cache-purge.ts
Labels: target: patch, action: merge

#22484 fix(@angular-devkit/build-angular): updated webpack-dev-server to latest minor version
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: action: merge, target: lts

#22483 fix(@angular-devkit/build-angular): updated webpack-dev-server to latest minor version
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: action: merge, target: lts

#22469 docs: add README to `@schematics/update`
  packages/schematics/update/BUILD.bazel
  packages/schematics/update/README.md
Labels: action: merge, target: lts

#22468 docs: clarify that patch/next releases do not require framework to release in advance
  docs/process/release.md
Labels: action: merge, target: minor

#22454 fix(@angular-devkit/build-angular): websocket client only injected if required
  packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
Labels: target: patch, action: merge

#22417 refactor(@schematics/angular): changed casings and small reorganizing
  packages/schematics/angular/workspace/files/__dot__gitignore.template
Labels: target: patch, action: merge

#22403 fix(@angular-devkit/build-angular): localized bundle generation fails in watch mode
  packages/angular_devkit/build_angular/src/builders/browser/index.ts
  packages/angular_devkit/build_angular/src/builders/browser/tests/behavior/localize_watch_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/tests/behavior/rebuild-errors_spec.ts
  packages/angular_devkit/build_angular/src/utils/i18n-inlining.ts
  packages/angular_devkit/build_angular/src/utils/i18n-options.ts
Labels: target: patch, action: merge

#22461 fix(@angular-devkit/build-angular): ensure `$localize` calls are replaced in watch mode
  packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build_localize_replaced_watch_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/setup.ts
Labels: action: merge, target: minor

#22488 build: update shelljs dependencies to "^0.8.5"
  package.json
  yarn.lock
Labels: action: merge, comp: build & ci, target: minor

#22489 Bump version to "v13.2.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: minor

#22492 Bump version to "v13.1.3" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#22493 docs: release notes for the v13.1.3 release
  CHANGELOG.md
Labels: action: merge, target: minor

#22494 Bump version to "v12.2.15" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: lts

#22496 docs: release notes for the v12.2.15 release
  CHANGELOG.md
Labels: target: minor

#22497 docs: release notes for the v11.2.18 release
  CHANGELOG.md
Labels: target: minor

#22402 fix(@angular-devkit/build-angular): disable parsing `new URL` syntax
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Labels: target: patch, action: merge

#22498 ci: remove Node v10
  .circleci/config.yml
Labels: action: merge, target: lts

#22500 build: update dependency postcss-preset-env to v7
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge

#22501 fix(@angular-devkit/build-angular): support ESNext as target for JavaScript optimizations
  packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts
Labels: target: patch, action: merge

#22509 refactor(@angular-devkit/build-angular): exit early when there are no component style budgets
  packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts
Labels: target: patch, action: merge

#22499 build: bump `.nvmrc` version
  .nvmrc
Labels: target: patch, action: merge

#22522 build: bump Angular peer deps to 13.2.0-next
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
Labels: action: merge, target: minor

#22524 fix(@angular-devkit/build-angular): load translations fresh start
  packages/angular_devkit/build_angular/src/utils/i18n-options.ts
Labels: action: merge, target: minor

#22527 Bump version to "v13.1.4" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge, comp: build & ci

#22528 docs: release notes for the v13.1.4 release
  CHANGELOG.md
Labels: action: merge

#22529 Bump version to "v13.2.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: target: rc, action: merge, comp: build & ci

#22561 build: bump Angular dependency to `rc`
  packages/schematics/angular/utility/latest-versions.ts
Labels: target: rc, action: merge

#22560 docs: bump FW peer deps at the same time as FW dependencies
  docs/process/release.md
Labels: target: minor

#22562 Bump version to "v13.2.0-rc.1" with changelog.
  CHANGELOG.md
  package.json
Labels: target: rc, action: merge

#22563 docs: release notes for the v13.2.0-rc.1 release
  CHANGELOG.md
Labels: action: merge

#22558 build: add RC releases to framework peer deps
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
Labels: target: rc, action: merge

#22564 docs: fix character code in expression example
  packages/angular_devkit/schematics/README.md
Labels: target: patch, action: merge, squash commits

#22580 Bump version to "v13.2.0" with changelog.
  CHANGELOG.md
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
Labels: target: rc, action: merge

#22581 docs: release notes for the v13.2.0 release
  CHANGELOG.md
Labels: target: major, action: merge

#22577 refactor(@angular-devkit/build-angular): clean find tests logic
  packages/angular_devkit/build_angular/src/builders/karma/find-tests.ts
  packages/angular_devkit/build_angular/src/builders/karma/index.ts
  packages/angular_devkit/build_angular/src/utils/is-directory.ts
Labels: action: merge, target: minor

#22574 refactor: remove build-optimizer from repo
  .monorepo.json
  CONTRIBUTING.md
  README.md
  bin/build-optimizer
  constants.bzl
  package.json
  packages/angular_devkit/build_angular/src/builders/browser/schema.json
  packages/angular_devkit/build_optimizer/BUILD.bazel
  packages/angular_devkit/build_optimizer/README.md
  packages/angular_devkit/build_optimizer/package.json
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
  packages/angular_devkit/build_optimizer/src/build-optimizer/cli.ts
  packages/angular_devkit/build_optimizer/src/build-optimizer/rollup-plugin.ts
  packages/angular_devkit/build_optimizer/src/build-optimizer/webpack-loader.ts
  packages/angular_devkit/build_optimizer/src/build-optimizer/webpack-plugin.ts
  packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts
  packages/angular_devkit/build_optimizer/src/helpers/transform-javascript.ts
  packages/angular_devkit/build_optimizer/src/index.ts
  packages/angular_devkit/build_optimizer/src/transforms/prefix-classes.ts
  packages/angular_devkit/build_optimizer/src/transforms/prefix-classes_spec.ts
  packages/angular_devkit/build_optimizer/src/transforms/prefix-functions.ts
  packages/angular_devkit/build_optimizer/src/transforms/prefix-functions_spec.ts
  packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts
  packages/angular_devkit/build_optimizer/src/transforms/scrub-file_spec.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums_spec.ts
  packages/angular_devkit/build_optimizer/webpack-loader/package.json
  packages/circular-deps-test.conf.js
  tsconfig.json
Labels: target: major, action: merge

#22573 refactor(@ngtools/webpack) remove deprecated ivy namespace
  goldens/public-api/ngtools/webpack/src/index.md
  packages/ngtools/webpack/src/index.ts
Labels: target: major, action: merge, flag: breaking change

#22572 refactor(@angular/cli): remove deprecated `--all` option from `ng update`
  docs/specifications/update.md
  packages/angular/cli/commands/update-impl.ts
  packages/angular/cli/commands/update.json
  packages/angular/cli/src/commands/update/schematic/index.ts
Labels: target: major, action: merge, flag: breaking change

#22363 fix(@angular-devkit/build-angular): fail build when importing CSS files as an ECMA modules
  packages/angular_devkit/build_angular/src/builders/browser/tests/behavior/styles_unsupported_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/allowed-common-js-dependencies_spec.ts
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: target: major, action: merge, flag: breaking change

#22586 build: remove extra period in build script
  scripts/build-bazel.ts
Labels: target: patch, action: merge

#22597 build: update `@angular/` packages to version 14 prerelease
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  yarn.lock
Labels: target: major, action: merge

#22585 feat(@schematics/angular): update new and existing projects compilation target to `ES2020`
  packages/angular_devkit/build_angular/src/builders/browser/specs/allow-js_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/lazy-module_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/resolve-json-module_spec.ts
  packages/angular_devkit/build_angular/test/hello-world-app/tsconfig.json
  packages/angular_devkit/build_angular/test/hello-world-lib/tsconfig.json
  packages/angular_devkit/build_webpack/test/angular-app/tsconfig.json
  packages/angular_devkit/build_webpack/test/basic-app/tsconfig.json
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-14/update-tsconfig-target.ts
  packages/schematics/angular/migrations/update-14/update-tsconfig-target_spec.ts
  packages/schematics/angular/workspace/files/tsconfig.json.template
  tests/legacy-cli/e2e/tests/build/prod-build.ts
  tests/legacy-cli/e2e/tests/i18n/ivy-localize-es2015.ts
Labels: target: major, action: merge

#22584 refactor(@angular/cli): remove deprecated `--prod` flag
  packages/angular/cli/commands/definitions.json
  packages/angular/cli/models/architect-command.ts
  tests/legacy-cli/e2e/assets/9.0-project/README.md
  tests/legacy-cli/e2e/tests/build/lazy-load-syntax.ts
  tests/legacy-cli/e2e/tests/build/material.ts
  tests/legacy-cli/e2e/tests/build/rebuild-replacements.ts
  tests/legacy-cli/e2e/tests/misc/third-party-decorators.ts
  tests/legacy-cli/e2e/tests/test/test-environment.ts
  tests/legacy-cli/e2e/tests/update/update-9.ts
Labels: target: major, action: merge, flag: breaking change

#22583 refactor(@angular-devkit/schematics): remove deprecated `analytics` property
  goldens/public-api/angular_devkit/schematics/src/index.md
  goldens/public-api/angular_devkit/schematics/testing/index.md
  goldens/public-api/angular_devkit/schematics/tools/index.md
  packages/angular_devkit/schematics/src/engine/interface.ts
Labels: target: major, action: merge, flag: breaking change

#22605 docs: add note about switching FW dependencies off of `-rc.0` and `-next.0` before the production release
  docs/process/release.md
Labels: target: major, action: merge

#22610 fix(@angular-devkit/build-angular): invalid browsers version ranges
  packages/angular_devkit/build_angular/src/webpack/plugins/css-optimizer-plugin.ts
Labels: target: patch, action: merge

#22611 fix(@angular-devkit/build-angular): invalid browsers version ranges
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Labels: action: merge, target: lts

#22615 Bump version to "v12.2.16" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: lts, comp: build & ci

#22616 Bump version to "v13.2.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#22617 docs: release notes for the v13.2.1 release
  CHANGELOG.md
Labels: action: merge

#22613 feat(@angular-devkit/build-angular): validate file extensions for `scripts` and `styles` options
  goldens/public-api/angular_devkit/build_angular/src/index.md
  packages/angular_devkit/build_angular/src/builders/browser/schema.json
  packages/angular_devkit/build_angular/src/builders/karma/schema.json
  packages/angular_devkit/build_angular/src/index.ts
  packages/angular_devkit/build_angular/src/utils/build-options.ts
  packages/angular_devkit/build_angular/src/utils/package-chunk-sort.ts
  packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
  packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
Labels: target: major, action: merge, flag: breaking change

#22599 refactor(@angular-devkit/build-angular): remove deprecated `showCircularDependencies` browser and server builder option
  goldens/public-api/angular_devkit/build_angular/src/index.md
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/builders/browser/schema.json
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/show-circular-dependencies_spec.ts
  packages/angular_devkit/build_angular/src/builders/server/schema.json
  packages/angular_devkit/build_angular/src/utils/build-options.ts
  packages/angular_devkit/build_angular/src/webpack/configs/common.ts
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-14/remove-show-circular-dependencies-option.ts
  packages/schematics/angular/migrations/update-14/remove-show-circular-dependencies-option_spec.ts
  tests/legacy-cli/e2e/tests/misc/circular-dependency.ts
Labels: target: major, action: merge, flag: breaking change

#22582 refactor(@angular-devkit/core): remove deprecated fs, object and array APIs
  goldens/public-api/angular_devkit/core/node/index.md
  goldens/public-api/angular_devkit/core/src/index.md
  packages/angular_devkit/core/node/fs.ts
  packages/angular_devkit/core/node/index.ts
  packages/angular_devkit/core/src/utils/array.ts
  packages/angular_devkit/core/src/utils/index.ts
  packages/angular_devkit/core/src/utils/object.ts
Labels: target: major, action: merge, flag: breaking change

#22604 build: add an action for handling feature requests
  .github/workflows/feature-requests.yml
Labels: target: patch, action: merge, comp: build & ci

#22614 perf(@angular-devkit/build-angular): update `license-webpack-plugin` to `4.0.1`
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge
