Repository angular/angular-cli, pull requests merged in 2023-08, with the labels that each got.

#25614 ci: temporarily use direct GHA checkout and setup node actions in test job
  .github/workflows/ci.yml
Labels: action: merge, area: build & ci, target: minor

#25603 ci: transfer PR package artifact storage to GHA
  .circleci/dynamic_config.yml
  .github/workflows/ci.yml
Labels: action: merge, area: build & ci, target: minor

#25618 Bump version to "v16.1.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#25619 docs: release notes for the v16.1.7 release
  CHANGELOG.md
Labels: area: docs, action: merge

#25620 Bump version to "v16.2.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#25555 fix(@angular-devkit/build-angular): prevent race condition in setting up sass worker pool
  packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/sass-language.ts
Labels: target: rc, action: merge

#25612 docs: omit repetitions
  packages/angular_devkit/build_angular/src/tools/babel/webpack-loader.ts
Labels: area: docs, action: merge, target: minor

#25611 docs: fix typo in api.ts
  packages/angular_devkit/architect/src/api.ts
Labels: area: docs, action: merge, target: minor

#25630 build: update critters
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: rc, action: merge, area: build & ci

#25632 Bump version to "v16.2.0-rc.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#25633 docs: release notes for the v16.2.0-rc.1 release
  CHANGELOG.md
Labels: area: docs, action: merge

#25631 build: update critters
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge, area: build & ci

#25635 build: update critters
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge, area: build & ci

#25636 Bump version to "v16.1.8" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#25638 docs: release notes for the v16.1.8 release
  CHANGELOG.md
Labels: area: docs, action: merge

#25644 refactor(@angular-devkit/build-angular): reduce source map resolution…
  packages/angular_devkit/build_angular/src/tools/sass/rebasing-importer.ts
Labels: area: devkit/build-angular, target: major, action: merge

#25654 refactor: remove `-next` from peer dependency versions for 16.2.0 release
  packages/angular/pwa/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/angular/utility/latest-versions/package.json
Labels: target: rc, action: merge

#25655 Bump version to "v16.2.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#25656 docs: release notes for the v16.2.0 release
  CHANGELOG.md
Labels: area: docs, action: merge

#25659 fix(@angular-devkit/build-angular): display warning when using `resourcesOutputPath` with esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/builder-status-warnings.ts
Labels: target: patch, action: merge

#25661 refactor(@schematics/angular): remove deprecated appId option
  packages/schematics/angular/app-shell/schema.json
  packages/schematics/angular/universal/schema.json
Labels: target: major, action: merge, detected: breaking change

#25663 build: update all non-major dependencies
  package.json
  packages/angular/cli/package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
  yarn.lock
Labels: target: major, action: merge, area: build & ci

#25640 refactor(@angular-devkit/build-angular): move TypeScript diagnostic conversion into compilation base
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/angular-compilation.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
Labels: target: major, action: merge

#25617 ci: partially move E2E tests to GHA
  .circleci/dynamic_config.yml
  .github/workflows/ci.yml
Labels: target: major, action: merge, area: build & ci

#25665 fix(@angular-devkit/build-angular): display warning when using `resourcesOutputPath` with esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/builder-status-warnings.ts
Labels: target: patch, action: merge

#25667 test: cleanup E2E test regular expressions
  tests/legacy-cli/e2e/tests/commands/builder-not-found.ts
  tests/legacy-cli/e2e/tests/generate/module/module-import.ts
Labels: target: major, action: merge

#25666 fix(@angular-devkit/build-angular): encode Sass package resolve directories in importer URLs
  packages/angular_devkit/build_angular/src/tools/sass/rebasing-importer.ts
  tests/legacy-cli/e2e/tests/build/styles/scss-partial-resolution.ts
Labels: target: patch, action: merge

#25674 fix(@angular-devkit/build-angular): encode Sass package resolve directories in importer URLs
  packages/angular_devkit/build_angular/src/tools/sass/rebasing-importer.ts
  tests/legacy-cli/e2e/tests/build/styles/scss-partial-resolution.ts
Labels: target: patch, action: merge

#25653 fix(@angular-devkit/build-angular): update vite to be able to serve app-shell and SSG pages
  packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
  packages/angular_devkit/build_angular/src/utils/server-rendering/esm-in-memory-file-loader.ts
  packages/angular_devkit/build_angular/src/utils/server-rendering/prerender.ts
Labels: target: major, action: merge

#25508 docs: update the http tag with https
  CONTRIBUTING.md
  scripts/templates/contributing.ejs
Labels: area: docs, target: patch, action: merge

#25673 refactor(@angular-devkit/build-angular): remove unneeded esbuild external packages workaround
  packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/external-packages-plugin.ts
Labels: target: major, action: merge

#25675 fix(@angular-devkit/build-angular): remove support for Node.js v16
  .circleci/dynamic_config.yml
  .github/workflows/ci.yml
  .nvmrc
  WORKSPACE
  constants.bzl
  docs/DEVELOPER.md
  package.json
  packages/angular/cli/bin/ng.js
  packages/angular/cli/lib/cli/index.ts
  packages/angular_devkit/build_angular/BUILD.bazel
  tools/toolchain_info.bzl
  yarn.lock
Labels: target: major, action: merge, detected: breaking change

#25681 fix(@angular-devkit/build-angular): update vite to be able to serve app-shell and SSG pages [cherry-pick]
  packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
  packages/angular_devkit/build_angular/src/utils/server-rendering/esm-in-memory-file-loader.ts
  packages/angular_devkit/build_angular/src/utils/server-rendering/prerender.ts
Labels: target: patch, action: merge

#25672 feat(@angular-devkit/build-angular): initial i18n extraction support for application builder
  packages/angular_devkit/build_angular/src/builders/extract-i18n/application-extraction.ts
  packages/angular_devkit/build_angular/src/builders/extract-i18n/builder.ts
  tests/legacy-cli/e2e.bzl
  tests/legacy-cli/e2e/tests/i18n/extract-ivy-disk-cache.ts
  tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts
Labels: target: major, action: merge, detected: feature

#25682 fix(@angular-devkit/build-angular): handle HMR updates of global CSS when using Vite
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
Labels: target: patch, action: merge

#25713 build: update Angular version to v17 prerelease
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  yarn.lock
Labels: target: major, action: merge, area: build & ci

#25707 fix(@angular-devkit/build-angular): use correct type for `extraEntryPoints`
  packages/angular_devkit/build_angular/src/utils/package-chunk-sort.ts
Labels: target: patch, action: merge

#25723 test(@angular/cli): update `ng update` tests to start from v14
  tests/legacy-cli/e2e/assets/13.0-project/e2e/protractor.conf.js
  tests/legacy-cli/e2e/assets/13.0-project/e2e/src/app.e2e-spec.ts
  tests/legacy-cli/e2e/assets/13.0-project/e2e/src/app.po.ts
  tests/legacy-cli/e2e/assets/13.0-project/e2e/tsconfig.json
  tests/legacy-cli/e2e/assets/13.0-project/package.json
  tests/legacy-cli/e2e/assets/14.0-project/.browserslistrc
  tests/legacy-cli/e2e/assets/14.0-project/.editorconfig
  tests/legacy-cli/e2e/assets/14.0-project/.gitignore
  tests/legacy-cli/e2e/assets/14.0-project/README.md
  tests/legacy-cli/e2e/assets/14.0-project/angular.json
  tests/legacy-cli/e2e/assets/14.0-project/karma.conf.js
  tests/legacy-cli/e2e/assets/14.0-project/package.json
  tests/legacy-cli/e2e/assets/14.0-project/src/app/app-routing.module.ts
  tests/legacy-cli/e2e/assets/14.0-project/src/app/app.component.css
  tests/legacy-cli/e2e/assets/14.0-project/src/app/app.component.html
  tests/legacy-cli/e2e/assets/14.0-project/src/app/app.component.spec.ts
  tests/legacy-cli/e2e/assets/14.0-project/src/app/app.component.ts
  tests/legacy-cli/e2e/assets/14.0-project/src/app/app.module.ts
  tests/legacy-cli/e2e/assets/14.0-project/src/assets/.gitkeep
  tests/legacy-cli/e2e/assets/14.0-project/src/environments/environment.prod.ts
  tests/legacy-cli/e2e/assets/14.0-project/src/environments/environment.ts
  tests/legacy-cli/e2e/assets/14.0-project/src/favicon.ico
  tests/legacy-cli/e2e/assets/14.0-project/src/index.html
  tests/legacy-cli/e2e/assets/14.0-project/src/main.ts
  tests/legacy-cli/e2e/assets/14.0-project/src/polyfills.ts
  tests/legacy-cli/e2e/assets/14.0-project/src/styles.css
  tests/legacy-cli/e2e/assets/14.0-project/src/test.ts
  tests/legacy-cli/e2e/assets/14.0-project/tsconfig.app.json
  tests/legacy-cli/e2e/assets/14.0-project/tsconfig.json
  tests/legacy-cli/e2e/assets/14.0-project/tsconfig.spec.json
  tests/legacy-cli/e2e/tests/misc/cli-exit-interop.ts
  tests/legacy-cli/e2e/tests/update/update-multiple-versions.ts
  tests/legacy-cli/e2e/tests/update/update.ts
Labels: action: merge, target: minor

#25733 build: use bazel ts_library rule to build @angular/ssr
  WORKSPACE
  package.json
  packages/angular/ssr/BUILD.bazel
  tools/postinstall/patches/@angular+bazel+16.0.0-next.6.patch
  tools/postinstall/patches/@angular+bazel+17.0.0-next.1.patch
  yarn.lock
Labels: target: major, action: merge, area: build & ci

#25732 refactor(@angular-devkit/core): use picomatch for PatternMatchingHost glob support
  packages/angular_devkit/core/BUILD.bazel
  packages/angular_devkit/core/package.json
  packages/angular_devkit/core/src/virtual-fs/host/pattern.ts
Labels: target: patch, action: merge

#25730 refactor(@angular/ssr): remove express engine
  packages/angular/ssr/public_api.ts
  packages/angular/ssr/schematics/ng-add/files/server.ts.template
  packages/angular/ssr/schematics/ng-add/index_spec.ts
  packages/angular/ssr/src/express-engine.ts
  packages/angular_devkit/build_angular/src/builders/ssr-dev-server/specs/proxy_spec.ts
  packages/angular_devkit/build_angular/src/builders/ssr-dev-server/specs/ssl_spec.ts
  packages/angular_devkit/build_angular/src/builders/ssr-dev-server/specs/works_spec.ts
Labels: action: merge, target: minor

#25740 build: update dependency jasmine to v5
  package.json
  tools/postinstall/patches/@bazel+jasmine+5.8.1.patch
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#25743 refactor: remove polynomial regular expression
  packages/angular/ssr/src/common-engine.ts
  packages/angular/ssr/src/inline-css-processor.ts
  packages/angular_devkit/build_angular/src/builders/prerender/render-worker.ts
  packages/angular_devkit/build_angular/src/builders/prerender/works_spec.ts
  packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
Labels: action: merge, target: minor

#25741 refactor(@angular-devkit/build-angular): remove disabling certificate validation when inlining fonts
  packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
Labels: target: patch, action: merge

#25745 Bump version to "v16.2.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#25746 docs: release notes for the v16.2.1 release
  CHANGELOG.md
Labels: area: docs, action: merge

#25747 build: update peer Angular peer deps
  packages/angular/pwa/package.json
  packages/angular/ssr/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
Labels: action: merge, area: build & ci, target: minor

#25749 Bump version to "v17.0.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge

#25750 build: update peer deps check to support stable versions when cutting a major prerelease
  scripts/release-checks/dependency-ranges/peer-deps-check.mts
Labels: target: patch, action: merge, area: build & ci

#25559 refactor(@angular-devkit/build-angular): normalize i18n options for application builder
  packages/angular_devkit/build_angular/src/builders/application/options.ts
Labels: target: major, action: merge

#25754 docs: updated the http tag with https
  .github/SAVED_REPLIES.md
Labels: area: docs, target: patch, action: merge
