Repository angular/angular-cli, pull requests merged in 2023-07, with the labels that each got.

#25481 fix(@angular-devkit/build-angular): normalize paths in loader cache with esbuild
  packages/angular_devkit/build_angular/src/tools/esbuild/global-scripts.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/load-result-cache.ts
Labels: target: patch, action: merge

#25495 refactor(@angular-devkit/build-angular): remove `resourcesOutputPath` option from application builder.
  packages/angular_devkit/build_angular/src/builders/application/options.ts
  packages/angular_devkit/build_angular/src/builders/application/schema.json
  packages/angular_devkit/build_angular/src/builders/application/tests/options/output-hashing_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/builder-status-warnings.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/bundle-options.ts
Labels: action: merge, target: minor

#25501 test: convert e2e_runner `ignore` to array
  tests/legacy-cli/e2e_runner.ts
Labels: target: patch, action: merge

#25500 build: update `@babel/generator` to `7.22.8`
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge, area: build & ci

#25502 Bump version to "v16.1.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#25504 docs: release notes for the v16.1.4 release
  CHANGELOG.md
Labels: area: docs, action: merge

#25505 Bump version to "v16.2.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#25489 feat(@angular-devkit/build-angular): add pre-rendering (SSG) and App-shell support generation to application builder
  WORKSPACE
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/builders/app-shell/render-worker.ts
  packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
  packages/angular_devkit/build_angular/src/builders/application/options.ts
  packages/angular_devkit/build_angular/src/builders/application/schema.json
  packages/angular_devkit/build_angular/src/builders/application/tests/options/app-shell_spec.ts
  packages/angular_devkit/build_angular/src/builders/application/tests/options/server_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/builder-status-warnings.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/schema.json
  packages/angular_devkit/build_angular/src/builders/jest/index.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/index-html-generator.ts
  packages/angular_devkit/build_angular/src/utils/ssg/esm-in-memory-file-loader.ts
  packages/angular_devkit/build_angular/src/utils/ssg/render-worker.ts
  packages/angular_devkit/build_angular/src/utils/ssg/render.ts
  packages/angular_devkit/build_angular/test/hello-world-app/src/main.server.ts
  yarn.lock
Labels: action: merge, target: minor, detected: feature

#25506 fix(@angular/cli): throw an error when executed in a google3-context
  packages/angular/cli/bin/ng.js
Labels: target: patch, action: merge

#25503 build: update prettier to v3.0.0
  .prettierrc
  package.json
  packages/angular_devkit/build_angular/src/tools/babel/plugins/adjust-static-class-members_spec.ts
  packages/angular_devkit/build_angular/src/tools/babel/plugins/adjust-typescript-enums_spec.ts
  packages/angular_devkit/build_angular/src/tools/babel/plugins/elide-angular-metadata_spec.ts
  packages/angular_devkit/build_angular/src/tools/babel/plugins/pure-toplevel-functions_spec.ts
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#25484 docs: updated the b tag to the strong tag in the changelog docs
  CHANGELOG.md
Labels: area: docs, action: merge, target: minor

#25519 perf(@angular-devkit/build-angular): only load browserslist in babel preset if needed
  packages/angular_devkit/build_angular/src/tools/babel/presets/application.ts
Labels: action: merge, target: minor

#25499 feat(@angular-devkit/build-angular): add `ssr` option in application builder
  packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
  packages/angular_devkit/build_angular/src/builders/application/options.ts
  packages/angular_devkit/build_angular/src/builders/application/schema.json
  packages/angular_devkit/build_angular/src/builders/application/tests/options/server_spec.ts
  packages/angular_devkit/build_angular/src/builders/application/tests/options/ssr_spec.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
  packages/angular_devkit/build_angular/src/utils/ssg/render-worker.ts
  tests/legacy-cli/e2e_runner.ts
Labels: action: merge, target: minor, detected: feature

#25520 refactor(@angular-devkit/build-angular): ensure TS resolution cache with file replacements
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/angular-host.ts
Labels: action: merge, target: minor

#25531 fix(@angular/cli): add `zone.js` to `ng version` output
  packages/angular/cli/src/commands/version/cli.ts
Labels: target: patch, action: merge

#25528 Revert "ci: disable update of `quicktype-core`"
  renovate.json
Labels: action: merge, target: minor

#25530 fix(@angular-devkit/build-angular): ensure that server dependencies are loaded also in ssr entrypoint
  packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
Labels: action: merge, target: minor

#25539 Bump version to "v16.2.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#25537 refactor(@angular-devkit/build-angular): configure AOT compiler to skip NgModule scope metadata emit in esbuild
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/angular-aot-metadata_spec.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/angular-compilation.ts
Labels: action: merge, target: minor

#25538 fix(@angular-devkit/build-angular): correctly wrap CommonJS exported enums when optimizing
  packages/angular_devkit/build_angular/src/tools/babel/plugins/adjust-typescript-enums.ts
  packages/angular_devkit/build_angular/src/tools/babel/plugins/adjust-typescript-enums_spec.ts
Labels: action: merge, target: minor

#25540 [16.1.x] fix(@angular-devkit/build-angular): correctly wrap CommonJS exported enums when optimizing
  packages/angular_devkit/build_angular/src/tools/babel/plugins/adjust-typescript-enums.ts
  packages/angular_devkit/build_angular/src/tools/babel/plugins/adjust-typescript-enums_spec.ts
Labels: target: patch, action: merge

#25511 fix(@angular-devkit/build-angular): Set chunk names explicitly
  packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
  tests/legacy-cli/e2e/tests/basic/rebuild.ts
Labels: action: merge, target: minor

#25534 perf(@angular-devkit/build-angular): inject Sass import/use directive importer information when resolving
  packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/sass-language.ts
  packages/angular_devkit/build_angular/src/tools/sass/lexer.ts
  packages/angular_devkit/build_angular/src/tools/sass/rebasing-importer.ts
  packages/angular_devkit/build_angular/src/tools/sass/sass-service.ts
Labels: action: merge, target: minor

#25548 perf(@angular-devkit/build-angular): use in-memory Sass module resolution cache
  packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/sass-language.ts
Labels: action: merge, target: minor

#25564 Bump version to "v16.1.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#25565 docs: release notes for the v16.1.5 release
  CHANGELOG.md
Labels: area: docs, action: merge

#25567 Bump version to "v16.2.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#25577 fix(@angular-devkit/build-angular): correctly load dev server assets with vite 4.4.0+
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
  tests/legacy-cli/e2e/tests/basic/serve.ts
Labels: action: merge, target: minor

#25584 fix(@angular-devkit/build-angular): error during critical CSS inlining for external stylesheets
  packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
  packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css_spec.ts
Labels: area: devkit/build-angular, target: patch, action: merge

#25585 Bump version to "v16.1.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#25586 docs: release notes for the v16.1.6 release
  CHANGELOG.md
Labels: action: merge

#25587 Bump version to "v16.2.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#25589 Bump version to "v16.2.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#25597 ci: migrate lint validation to GHA
  .circleci/dynamic_config.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
Labels: action: merge, area: build & ci, target: minor

#25594 fix(@angular-devkit/build-angular): hot update filename suffix with `.mjs`
  packages/angular_devkit/build_angular/src/tools/webpack/plugins/index-html-webpack-plugin.ts
Labels: target: patch, action: merge

#25598 Migrate more things
  .circleci/dynamic_config.yml
  .github/workflows/ci.yml
Labels: action: merge, area: build & ci, target: minor

#25552 docs: updated the changelog doc with the obsolete tag
  CHANGELOG.md
Labels: area: docs, action: merge, target: minor
