Repository angular/angular-cli, pull requests merged in 2023-01, with the labels that each got.

#24450 refactor(@ngtools/webpack): remove TypeScript 4.7 compatibility code
  packages/ngtools/webpack/src/transformers/replace_resources.ts
Labels: target: patch, action: merge

#24460 feat(@angular-devkit/build-angular): implement stats-json option for esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/experimental-warnings.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
Labels: action: merge, target: minor, detected: feature

#24449 test: removed empty methods
  packages/angular_devkit/build_angular/test/hello-world-lib/projects/lib/src/lib/lib.component.ts
Labels: target: patch, action: merge

#24463 fix(@angular-devkit/build-angular): format esbuild error messages to include more information
  packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts
Labels: target: patch, action: merge

#24475 fix(@angular-devkit/build-angular): ensure Sass load paths are resolved from workspace root
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
Labels: action: merge, target: minor

#24483 build: use bazel to perform release builds
  .circleci/dynamic_config.yml
  .ng-dev/release.mts
  package.json
  packages/angular/cli/BUILD.bazel
  packages/angular/create/BUILD.bazel
  packages/angular/pwa/BUILD.bazel
  packages/angular_devkit/architect/BUILD.bazel
  packages/angular_devkit/architect/node/BUILD.bazel
  packages/angular_devkit/architect_cli/BUILD.bazel
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_webpack/BUILD.bazel
  packages/angular_devkit/core/BUILD.bazel
  packages/angular_devkit/schematics/BUILD.bazel
  packages/angular_devkit/schematics_cli/BUILD.bazel
  packages/ngtools/webpack/BUILD.bazel
  packages/schematics/angular/BUILD.bazel
  scripts/build-packages-dist.mts
  tsconfig-build.json
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#24493 Bump version to "v15.0.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24494 docs: release notes for the v15.0.5 release
  CHANGELOG.md
Labels: area: docs, action: merge

#24495 Bump version to "v15.1.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24503 build: re-enable material e2e tests
  tests/legacy-cli/e2e/tests/build/material.ts
  tests/legacy-cli/e2e/tests/commands/add/add-material.ts
  tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts
Labels: target: rc, action: merge, area: build & ci

#24474 refactor(@angular-devkit/build-angular): remove duplicate namespaces in esbuild manifest paths
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
Labels: target: rc, action: merge

#24473 feat(@angular-devkit/build-angular): implement node module license extraction for esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/experimental-warnings.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/license-extractor.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
Labels: action: merge, target: minor, detected: feature

#24505 fix(@angular-devkit/build-angular): provide an option to `exclude` specs in Karma builder
  goldens/public-api/angular_devkit/build_angular/index.md
  packages/angular_devkit/build_angular/src/builders/karma/find-tests-plugin.ts
  packages/angular_devkit/build_angular/src/builders/karma/index.ts
  packages/angular_devkit/build_angular/src/builders/karma/schema.json
  packages/angular_devkit/build_angular/src/builders/karma/tests/options/exclude_spec.ts
Labels: target: patch, action: merge

#24499 fix(@angular-devkit/build-angular): use relative css resource paths in esbuild JSON stats
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/css-resource-plugin.ts
Labels: target: rc, action: merge

#24515 build: update angular packages for 15.1.0 release
  package.json
  packages/angular/pwa/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/angular/utility/latest-versions/package.json
  yarn.lock
Labels: target: rc, action: merge, area: build & ci

#24519 Bump version to "v15.1.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24520 docs: release notes for the v15.1.0 release
  CHANGELOG.md
Labels: area: docs, action: merge

#24508 docs(@angular/cli): add ng new long description
  packages/angular/cli/src/commands/new/cli.ts
  packages/angular/cli/src/commands/new/long-description.md
Labels: area: docs, target: patch, action: merge

#24531 fix(@angular-devkit/build-angular): update `esbuild` to `0.16.17`
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge

#24530 build: update `eslint-plugin-import` to `2.27.4`
  package.json
  packages/angular_devkit/build_angular/src/builders/extract-i18n/index.ts
  packages/angular_devkit/build_angular/src/utils/build-options.ts
  scripts/create.ts
  yarn.lock
Labels: target: patch, action: merge, area: build & ci

#24533 refactor: change `JSONFile` to private instead of internal
  packages/schematics/angular/utility/json-file.ts
Labels: target: patch, action: merge

#24534 Bump version to "v15.1.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24536 Bump version to "v15.2.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge

#24538 build: cleanup unneeded and/or default tsconfig options
  .eslintignore
  .ng-dev/tsconfig.json
  scripts/json-help.ts
  tsconfig.json
Labels: action: merge, area: build & ci, target: minor

#24539 refactor(@angular-devkit/build-angular): remove direct import of i18n worker code
  packages/angular_devkit/build_angular/src/utils/action-executor.ts
  packages/angular_devkit/build_angular/src/utils/bundle-inline-options.ts
  packages/angular_devkit/build_angular/src/utils/i18n-inlining.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Labels: target: patch, action: merge

#24516 fix(@angular/cli): remove `--to` option from being required when using `--from` in `ng update`
  packages/angular/cli/src/commands/update/cli.ts
Labels: target: patch, action: merge

#24522 feat(@angular-devkit/build-angular): support CommonJS dependency checking in esbuild
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/commonjs-checker.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/esbuild.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/experimental-warnings.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
Labels: action: merge, target: minor, detected: feature

#24545 build: update dev-infra packages
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#24546 build: update dev-infra packages [patch]
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: target: patch, action: merge, area: build & ci

#24542 fix(@angular/cli): register schematic aliases when providing collection name in `ng generate`
  packages/angular/cli/src/commands/generate/cli.ts
  tests/legacy-cli/e2e/tests/generate/schematic-aliases.ts
Labels: target: patch, action: merge

#24548 Revert "test: use `NPM_CONFIG_legacy_peer_deps` when testing prerelease versions of Angular material."
  tests/legacy-cli/e2e/tests/build/material.ts
  tests/legacy-cli/e2e/tests/commands/add/add-material.ts
  tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts
Labels: action: merge, target: minor

#24549 fix(@angular-devkit/build-angular): prevent hanging initial build during exception with esbuild
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
Labels: target: patch, action: merge

#24558 build: update dependency minimatch to v6
  package.json
  scripts/build.ts
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#24527 refactor: only collect Node version if it's a standard version string
  packages/angular/cli/src/analytics/analytics-collector.ts
Labels: target: patch, action: merge

#24561 refactor(@angular-devkit/build-angular): use esbuild 0.17 incremental API in esbuild builder
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/esbuild.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
  yarn.lock
Labels: action: merge, target: minor

#24564 fix(@schematics/angular): replace existing `BrowserModule.withServerTransition` calls when running universal schematic
  packages/schematics/angular/universal/index.ts
  packages/schematics/angular/universal/index_spec.ts
Labels: target: patch, action: merge

#24567 Bump version to "v15.1.2" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#24570 docs: release notes for the v15.1.2 release
  CHANGELOG.md
Labels: area: docs, action: merge

#24571 Bump version to "v15.2.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: minor

#24568 Re-enable analytics
  packages/angular/cli/src/analytics/analytics-collector.ts
Labels: target: patch, action: merge

#24575 fix(@angular/cli): handle extended schematics when retrieving aliases
  packages/angular/cli/src/commands/generate/cli.ts
Labels: target: patch, action: merge

#24569 fix(@angular-devkit/build-angular): avoid undefined module path for Sass imports in esbuild
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
Labels: target: patch, action: merge

#24565 feat(@angular/cli): log number of files update during `ng update`
  packages/angular/cli/src/commands/update/cli.ts
Labels: action: merge, target: minor, detected: feature

#24543 fix(@angular-devkit/core): handle number like strings in workspace writer
  packages/angular_devkit/core/src/workspace/json/test/cases/AddProject3.json
  packages/angular_devkit/core/src/workspace/json/writer.ts
  packages/angular_devkit/core/src/workspace/json/writer_spec.ts
Labels: target: patch, action: merge

#24583 build: update `@types/yargs` to `^17.0.20`
  package.json
  packages/angular/cli/src/commands/generate/cli.ts
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#24559 build: update `quicktype-core` to `20.0.15`
  package.json
  packages/angular/cli/lib/config/workspace-schema.json
  renovate.json
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#24305 feat(@angular-devkit/schematics-cli): auto detect package manager
  packages/angular_devkit/schematics_cli/bin/schematics.ts
Labels: action: merge, target: minor, merge: squash commits, detected: feature

#24607 build: update bazel aspect lib to 1.23.3
  WORKSPACE
Labels: target: patch, action: merge, area: build & ci

#24608 Bump version to "v15.1.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24609 docs: release notes for the v15.1.3 release
  CHANGELOG.md
Labels: area: docs, action: merge

#24610 Bump version to "v15.2.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24614 fix(@angular-devkit/build-angular): print server builder errors and warnings
  packages/angular_devkit/build_angular/src/builders/server/index.ts
  packages/angular_devkit/build_angular/src/builders/server/tests/behavior/build-errors_spec.ts
  packages/angular_devkit/build_angular/src/builders/server/tests/behavior/web-workers_spec.ts
Labels: target: patch, action: merge

#24620 fix(@angular-devkit/build-angular): load JavaScript bundles as modules in karma
  packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma-context.html
  packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma-debug.html
Labels: target: patch, action: merge
