Repository angular/angular-cli, pull requests merged in 2023-02, with the labels that each got.

#24638 Bump version to "v15.1.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24641 docs: release notes for the v15.1.4 release
  CHANGELOG.md
Labels: area: docs, action: merge

#24642 Bump version to "v15.2.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24640 fix(@angular-devkit/build-angular): fix support of Safari TP versions
  packages/angular_devkit/build_angular/src/utils/esbuild-targets.ts
Labels: target: patch, action: merge

#24649 fix(@angular/cli): only set `DebugView` when `NG_DEBUG` is passed
  packages/angular/cli/src/analytics/analytics-collector.ts
Labels: target: patch, action: merge

#24338 run e2e tests under bazel
  .bazelrc
  .circleci/dynamic_config.yml
  .circleci/env.sh
  .circleci/win-ram-disk.ps1
  BUILD.bazel
  WORKSPACE
  docs/DEVELOPER.md
  packages/angular/cli/src/utilities/version.ts
  packages/angular_devkit/build_angular/src/builders/karma/index.ts
  tests/legacy-cli/BUILD.bazel
  tests/legacy-cli/e2e.bzl
  tests/legacy-cli/e2e/assets/13.0-project/karma.conf.js
  tests/legacy-cli/e2e/assets/BUILD.bazel
  tests/legacy-cli/e2e/initialize/500-create-project.ts
  tests/legacy-cli/e2e/initialize/BUILD.bazel
  tests/legacy-cli/e2e/ng-snapshot/BUILD.bazel
  tests/legacy-cli/e2e/setup/001-create-tmp-dir.ts
  tests/legacy-cli/e2e/setup/002-npm-sandbox.ts
  tests/legacy-cli/e2e/tests/BUILD.bazel
  tests/legacy-cli/e2e/tests/basic/test.ts
  tests/legacy-cli/e2e/tests/build/esbuild-unsupported.ts
  tests/legacy-cli/e2e/tests/generate/confg/type-karma.ts
  tests/legacy-cli/e2e/utils/BUILD.bazel
  tests/legacy-cli/e2e/utils/bazel.ts
  tests/legacy-cli/e2e/utils/process.ts
  tests/legacy-cli/e2e/utils/project.ts
  tests/legacy-cli/e2e/utils/utils.ts
  tests/legacy-cli/e2e_runner.ts
  tools/defaults.bzl
Labels: action: merge, target: minor, merge: squash commits

#24635 feat(@angular-devkit/build-angular): support JIT compilation with esbuild
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/jit-compilation.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/jit-plugin-callbacks.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/jit-resource-transformer.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/uri.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer-worker.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
Labels: action: merge, target: minor, detected: feature

#24655 fix(@angular-devkit/build-angular): load polyfills and runtime as scripts instead of modules
  packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma-context.html
  packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma-debug.html
  tests/legacy-cli/e2e/tests/test/test-jasmine-clock.ts
Labels: target: patch, action: merge

#24666 fix(@schematics/angular): remove bootstrapping wrapping in universal schematic
  packages/schematics/angular/universal/index.ts
  packages/schematics/angular/universal/index_spec.ts
Labels: target: patch, action: merge

#24665 fix(@angular-devkit/build-angular): do not fail compilation when spec pattern does not match
  packages/angular_devkit/build_angular/src/builders/karma/find-tests-plugin.ts
  packages/angular_devkit/build_angular/src/builders/karma/tests/options/include_spec.ts
Labels: target: patch, action: merge

#24662 fix(@angular/cli): error if Angular compiler is used in a schematic
  packages/angular/cli/src/command-builder/utilities/schematic-engine-host.ts
Labels: area: angular/cli, target: patch, action: merge

#24658 fix(@angular-devkit/build-angular): build optimizer support for spec-compliant downlevel class properties
  packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members.ts
  packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members_spec.ts
Labels: target: patch, action: merge

#24677 ci: enable HTTP caching for Bazel on Windows
  .circleci/bazel.common.rc
  .circleci/bazel.linux.rc
  .circleci/bazel.windows.rc
  .circleci/dynamic_config.yml
Labels: action: merge, area: build & ci, target: minor

#24679 Bump version to "v15.1.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24680 docs: release notes for the v15.1.5 release
  CHANGELOG.md
Labels: area: docs, action: merge

#24681 Bump version to "v15.2.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24698 fix(@angular-devkit/build-angular): update the ECMA output warning message to be more actionable
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/typescript.ts
Labels: target: patch, action: merge

#24692 fix(@angular-devkit/build-angular): use babel default export helper in build optimizer
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members.ts
  packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members_spec.ts
  packages/angular_devkit/build_angular/src/typings.d.ts
  yarn.lock
Labels: target: patch, action: merge

#24687 fix(@angular/cli): convert `before` option in `.npmrc` to Date
  packages/angular/cli/src/utilities/package-metadata.ts
  tests/legacy-cli/e2e/tests/commands/add/npm-config.ts
Labels: target: patch, action: merge

#24684 fix(@angular-devkit/build-angular): correctly copy `safety-worker.js` contents
  packages/angular_devkit/build_angular/src/utils/service-worker.ts
Labels: target: patch, action: merge

#24699 fix(@angular-devkit/build-angular): avoid CommonJS warning for zone.js in esbuild
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/commonjs-checker.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/allowed-common-js-dependencies_spec.ts
  yarn.lock
Labels: action: merge, target: minor

#24715 perf(@angular-devkit/build-angular): reduce rebuilt times when using the `scripts` option
  packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts
Labels: target: patch, action: merge

#24708 test(@angular-devkit/build-angular): port additional unit tests to esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/extract-licenses_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/inline-critical_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/main_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/styles_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/subresource-integrity_spec.ts
Labels: action: merge, target: minor

#24713 Couple of GA fixes
  packages/angular/cli/src/analytics/analytics-collector.ts
Labels: target: patch, action: merge

#24714 build: update parse5-html-rewriting-stream to version 7
  package.json
  packages/angular/cli/src/command-builder/utilities/schematic-engine-host.ts
  packages/angular/pwa/BUILD.bazel
  packages/angular/pwa/package.json
  packages/angular/pwa/pwa/index.ts
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/utils/index-file/html-rewriting-stream.ts
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#24719 build: remove no longer used scripts
  package.json
  scripts/build-bazel.ts
  scripts/build.ts
  scripts/packages.ts
  scripts/publish.ts
  scripts/snapshots.ts
Labels: action: merge, area: build & ci, target: minor

#24722 Bump version to "v15.1.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24723 docs: release notes for the v15.1.6 release
  CHANGELOG.md
Labels: area: docs, action: merge

#24724 Revert "build: remove no longer used scripts"
  package.json
  scripts/build-bazel.ts
  scripts/build.ts
  scripts/packages.ts
  scripts/publish.ts
  scripts/snapshots.ts
Labels: action: merge, target: minor

#24725 Bump version to "v15.2.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24727 Configure next branch to receive major changes for v16.0.0-next.0
  package.json
Labels: action: merge

#24432 feat(@schematics/angular): remove deprecated CanLoad option for guards
  packages/schematics/angular/guard/implements-files/__name@dasherize__.guard.ts.template
  packages/schematics/angular/guard/index.ts
  packages/schematics/angular/guard/index_spec.ts
  packages/schematics/angular/guard/schema.json
  packages/schematics/angular/guard/type-files/__name@dasherize__.guard.ts.template
  packages/schematics/angular/utility/ast-utils_spec.ts
  tests/legacy-cli/e2e/tests/generate/guard/guard-implements.ts
  tests/legacy-cli/e2e/tests/generate/guard/guard-multiple-implements.ts
Labels: target: major, action: merge, detected: feature, detected: breaking change

#24718 feat(@angular-devkit/core): update SchemaRegistry `compile` to return `Promise`
  goldens/public-api/angular_devkit/core/index.md
  packages/angular/cli/src/command-builder/utilities/json-schema.ts
  packages/angular/cli/src/utilities/config.ts
  packages/angular_devkit/architect/src/architect.ts
  packages/angular_devkit/architect/src/jobs/simple-scheduler.ts
  packages/angular_devkit/build_angular/src/testing/builder-harness.ts
  packages/angular_devkit/core/src/json/schema/interface.ts
  packages/angular_devkit/core/src/json/schema/prompt_spec.ts
  packages/angular_devkit/core/src/json/schema/registry.ts
  packages/angular_devkit/core/src/json/schema/registry_spec.ts
  packages/angular_devkit/core/src/json/schema/transforms_spec.ts
  packages/angular_devkit/schematics/src/formats/format-validator.ts
  packages/angular_devkit/schematics/src/formats/html-selector_spec.ts
  packages/angular_devkit/schematics/src/formats/path_spec.ts
  packages/angular_devkit/schematics/tools/schema-option-transform.ts
Labels: target: major, action: merge, detected: feature, detected: breaking change

#24211 refactor(@angular-devkit/schematics): remove `UpdateBuffer` and rename `UpdateBuffer2` to `UpdateBuffer`
  packages/angular_devkit/schematics/src/tree/recorder_spec.ts
  packages/angular_devkit/schematics/src/utility/environment-options.ts
  packages/angular_devkit/schematics/src/utility/linked-list.ts
  packages/angular_devkit/schematics/src/utility/update-buffer.ts
  packages/angular_devkit/schematics/src/utility/update-buffer_spec.ts
Labels: target: major, action: merge, detected: breaking change

#24720 refactor(@ngtools/webpack): remove NGCC integration
  packages/ngtools/webpack/src/ivy/host.ts
  packages/ngtools/webpack/src/ivy/plugin.ts
  packages/ngtools/webpack/src/ngcc_processor.ts
Labels: target: major, action: merge, detected: breaking change

#24728 refactor(@angular/cli): remove Node.js v14 support
  .circleci/dynamic_config.yml
  .nvmrc
  WORKSPACE
  constants.bzl
  lib/packages.ts
  package.json
  packages/angular/cli/lib/cli/index.ts
  packages/angular/cli/src/commands/version/cli.ts
  tools/test/expected_package.json
  tools/toolchain_info.bzl
Labels: target: major, action: merge, detected: breaking change

#24721 build: update use bazel to build schemas for development
  scripts/build-schema.ts
  tsconfig.json
Labels: action: merge, area: build & ci, target: minor

#24733 build: remove no longer used scripts
  package.json
  packages/angular/cli/lib/init.ts
  scripts/build-bazel.ts
  scripts/build.ts
  scripts/json-help.ts
  scripts/packages.ts
  scripts/publish.ts
  scripts/snapshots.ts
Labels: action: merge, area: build & ci, target: minor

#24735 build: update output target to ES2020
  WORKSPACE
  tools/defaults.bzl
  tsconfig.json
Labels: target: major, action: merge, area: build & ci

#24737 fix(@angular-devkit/build-angular): allow empty scripts to be optimized
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/scripts_spec.ts
  packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts
Labels: target: patch, action: merge

#24585 feat(@schematics/angular): generate functional resolvers and guards by default
  packages/schematics/angular/guard/index_spec.ts
  packages/schematics/angular/guard/schema.json
  packages/schematics/angular/resolver/index_spec.ts
  packages/schematics/angular/resolver/schema.json
  tests/legacy-cli/e2e/tests/generate/guard/guard-basic.ts
  tests/legacy-cli/e2e/tests/generate/guard/guard-implements.ts
  tests/legacy-cli/e2e/tests/generate/guard/guard-multiple-implements.ts
Labels: target: major, action: merge, detected: feature, detected: breaking change

#24740 ci: reduce quicktype-core updates
  renovate.json
Labels: target: patch, action: merge, area: build & ci

#24745 ci: fix renovate monthly schedule
  renovate.json
Labels: target: patch, action: merge, area: build & ci

#24747 build: update to latest remote build execution setup
  .circleci/dynamic_config.yml
Labels: target: patch, action: merge, area: build & ci

#24746 test(@angular-devkit/build-angular): additional unit tests for esbuild builder
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/behavior/typescript-path-mapping_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/base-href_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/cross-origin_spec.ts
Labels: target: major, action: merge

#24753 refactor(@angular-devkit/core): remove deprecated exceptions
  goldens/public-api/angular_devkit/core/index.md
  packages/angular_devkit/core/src/exception.ts
Labels: target: major, action: merge, detected: breaking change

#24757 build: update angular dependencies to version 15.2.x
  packages/angular/pwa/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/angular/utility/latest-versions/package.json
Labels: target: rc, action: merge, area: build & ci

#24760 Bump version to "v15.2.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#24761 docs: release notes for the v15.2.0 release
  CHANGELOG.md
Labels: area: docs, action: merge

#24762 Bump version to "v16.0.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge

#24768 ci: correctly store E2E test results and artifacts
  .circleci/dynamic_config.yml
Labels: target: patch, action: merge, area: build & ci

#24777 build: refactor circular-deps-test.conf to use package.js file
  packages/circular-deps-test.conf.js
Labels: action: review, target: patch, action: merge, area: build & ci

#24772 build: add pre-release checks for dependency on framework
  .ng-dev/release.mts
  scripts/release-checks/dependency-ranges/index.mts
  scripts/release-checks/dependency-ranges/latest-versions-check.mts
  scripts/release-checks/dependency-ranges/peer-deps-check.mts
  scripts/release-checks/tsconfig.json
Labels: target: patch, action: merge, area: build & ci

#24776 fix(@angular-devkit/build-angular): improve parsing of error messages
  packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
Labels: target: patch, action: merge

#24754 refactor(@angular-devkit/build-angular): remove deprecated `outputPaths` and `outputPath` Builder output
  goldens/public-api/angular_devkit/build_angular/index.md
  packages/angular_devkit/build_angular/src/builders/browser/index.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/allow-js_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/base-href_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/build-optimizer_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/cross-origin_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/deploy-url_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/specs/index_spec.ts
  packages/angular_devkit/build_angular/src/builders/server/index.ts
Labels: target: major, action: merge, detected: breaking change
