Repository angular/angular-cli, pull requests merged in 2023-12, with the labels that each got.

#26515 feat(@schematics/angular): add optional migration to use application builder
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-17/use-application-builder.ts
  packages/schematics/angular/ssr/index.ts
  packages/schematics/angular/utility/workspace-models.ts
  packages/schematics/angular/utility/workspace.ts
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/.gitignore
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/README.md
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/angular.json
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/package.json
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/server.ts
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/src/app/app-routing.module.ts
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/src/app/app.component.css
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/src/app/app.component.html
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/src/app/app.component.spec.ts
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/src/app/app.component.ts
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/src/app/app.module.server.ts
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/src/app/app.module.ts
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/src/assets/.gitkeep
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/src/favicon.ico
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/src/index.html
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/src/main.server.ts
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/src/main.ts
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/src/styles.css
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/tsconfig.app.json
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/tsconfig.json
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/tsconfig.server.json
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/tsconfig.spec.json
  tests/legacy-cli/e2e/tests/update/update-application-builder.ts
Labels: action: merge, target: minor, detected: feature

#26521 test: update base project for E2E tests to version 15
  tests/legacy-cli/e2e/assets/14.0-project/.browserslistrc
  tests/legacy-cli/e2e/assets/14.0-project/karma.conf.js
  tests/legacy-cli/e2e/assets/14.0-project/package.json
  tests/legacy-cli/e2e/assets/14.0-project/src/environments/environment.prod.ts
  tests/legacy-cli/e2e/assets/14.0-project/src/environments/environment.ts
  tests/legacy-cli/e2e/assets/14.0-project/src/polyfills.ts
  tests/legacy-cli/e2e/assets/14.0-project/src/test.ts
  tests/legacy-cli/e2e/assets/15.0-project/.editorconfig
  tests/legacy-cli/e2e/assets/15.0-project/.gitignore
  tests/legacy-cli/e2e/assets/15.0-project/README.md
  tests/legacy-cli/e2e/assets/15.0-project/angular.json
  tests/legacy-cli/e2e/assets/15.0-project/package.json
  tests/legacy-cli/e2e/assets/15.0-project/src/app/app-routing.module.ts
  tests/legacy-cli/e2e/assets/15.0-project/src/app/app.component.css
  tests/legacy-cli/e2e/assets/15.0-project/src/app/app.component.html
  tests/legacy-cli/e2e/assets/15.0-project/src/app/app.component.spec.ts
  tests/legacy-cli/e2e/assets/15.0-project/src/app/app.component.ts
  tests/legacy-cli/e2e/assets/15.0-project/src/app/app.module.ts
  tests/legacy-cli/e2e/assets/15.0-project/src/assets/.gitkeep
  tests/legacy-cli/e2e/assets/15.0-project/src/favicon.ico
  tests/legacy-cli/e2e/assets/15.0-project/src/index.html
  tests/legacy-cli/e2e/assets/15.0-project/src/main.ts
  tests/legacy-cli/e2e/assets/15.0-project/src/styles.css
  tests/legacy-cli/e2e/assets/15.0-project/tsconfig.app.json
  tests/legacy-cli/e2e/assets/15.0-project/tsconfig.json
  tests/legacy-cli/e2e/assets/15.0-project/tsconfig.spec.json
  tests/legacy-cli/e2e/tests/update/update-multiple-versions.ts
  tests/legacy-cli/e2e/tests/update/update.ts
Labels: target: patch, action: merge

#26540 fix(@angular-devkit/build-angular): correctly align error/warning messages when spinner is active
  packages/angular_devkit/build_angular/src/utils/spinner.ts
Labels: target: patch, action: merge

#26552 refactor(@angular-devkit/build-angular): add watch builder teardown to application builder
  packages/angular_devkit/build_angular/src/builders/application/index.ts
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-component_styles_spec.ts
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-errors_spec.ts
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-global_styles_spec.ts
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-web-workers_spec.ts
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/typescript-rebuild-lazy_spec.ts
  packages/angular_devkit/build_angular/src/builders/application/tests/options/inline-style-language_spec.ts
Labels: action: merge, target: minor

#26554 test(@angular-devkit/build-angular): enable dev-server watch tests for vite
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/watch_spec.ts
Labels: action: merge, target: minor

#26546 fix(@schematics/angular): enable TypeScript `skipLibCheck` in new workspace
  packages/schematics/angular/workspace/files/tsconfig.json.template
Labels: target: patch, action: merge

#26557 perf(@angular-devkit/build-angular): only enable advanced optimizations with script optimizations
  packages/angular_devkit/build_angular/src/builders/application/options.ts
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/angular-aot-metadata_spec.ts
  tests/legacy-cli/e2e/tests/build/prerender/error-with-sourcemaps.ts
Labels: target: patch, action: merge

#26481 test: try to reduce flakes by added a timeout because e2e tests
  tests/legacy-cli/e2e/tests/basic/e2e.ts
  tests/legacy-cli/e2e/tests/build/lazy-load-syntax.ts
  tests/legacy-cli/e2e/tests/build/library/lib-consumption-full-aot.ts
  tests/legacy-cli/e2e/tests/build/library/lib-consumption-full-jit.ts
  tests/legacy-cli/e2e/tests/build/library/lib-consumption-partial-aot.ts
  tests/legacy-cli/e2e/tests/build/library/lib-consumption-partial-jit.ts
  tests/legacy-cli/e2e/tests/build/rebuild-types.ts
Labels: action: merge, target: minor

#26543 test(@angular-devkit/build-angular): enable vite service worker unit tests
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/serve_service-worker_spec.ts
Labels: target: patch, action: merge

#26566 fix(@angular-devkit/build-angular): normalize locale tags with `Intl` API when resolving in application builder
  packages/angular_devkit/build_angular/src/tools/esbuild/i18n-locale-plugin.ts
Labels: target: patch, action: merge

#26576 test: update browser compatibility test versions for v17
  tests/legacy-cli/e2e/assets/protractor-saucelabs.conf.js
Labels: target: patch, action: merge

#26580 test: disable new failing default typescript eslint rules to allow upgrading
  .eslintrc.json
Labels: action: merge, target: minor

#26578 test: correct misconfigured saucelabs platform/OS combination
  tests/legacy-cli/e2e/assets/protractor-saucelabs.conf.js
Labels: target: patch, action: merge

#26558 refactor(@angular-devkit/build-webpack): align builders source directory structure with build-angular
  packages/angular_devkit/build_webpack/BUILD.bazel
  packages/angular_devkit/build_webpack/builders.json
  packages/angular_devkit/build_webpack/package.json
  packages/angular_devkit/build_webpack/src/builders/webpack-dev-server/index.ts
  packages/angular_devkit/build_webpack/src/builders/webpack-dev-server/index_spec.ts
  packages/angular_devkit/build_webpack/src/builders/webpack-dev-server/schema.json
  packages/angular_devkit/build_webpack/src/builders/webpack/index.ts
  packages/angular_devkit/build_webpack/src/builders/webpack/index_spec.ts
  packages/angular_devkit/build_webpack/src/builders/webpack/schema.json
  packages/angular_devkit/build_webpack/src/index.ts
Labels: action: merge, target: minor

#26586 fix(@angular-devkit/build-angular): watch symlink when using `preserveSymlinks` option
  packages/angular_devkit/build_angular/src/builders/application/build-action.ts
  packages/angular_devkit/build_angular/src/builders/application/index.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/watcher.ts
Labels: target: patch, action: merge

#26582 build: change ng-dev config files to mjs with type jsdoc
  .ng-dev/caretaker.mjs
  .ng-dev/commit-message.mjs
  .ng-dev/config.mjs
  .ng-dev/format.mjs
  .ng-dev/github.mjs
  .ng-dev/pull-request.mjs
  .ng-dev/release.mjs
  .ng-dev/tsconfig.json
Labels: action: merge, area: build & ci, target: minor

#26588 refactor: update rxjs imports
  packages/angular_devkit/build_angular/src/builders/ssr-dev-server/index.ts
Labels: target: patch, action: merge

#26591 build: update dependency vite to v4.5.1
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge, area: build & ci

#26597 build: update dependency vite to v4.5.1
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: action: review, target: lts, area: build & ci

#26589 build: lock file maintenance
  packages/angular_devkit/build_angular/src/utils/server-rendering/esm-in-memory-loader/register-hooks.ts
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#26599 Bump version to "v17.0.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#26600 docs: release notes for the v17.0.6 release
  CHANGELOG.md
Labels: area: docs, action: merge

#26601 Bump version to "v17.1.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#26611 feat(@angular-devkit/build-angular): add support for `--no-browsers` in karma builder
  goldens/public-api/angular_devkit/build_angular/index.md
  packages/angular_devkit/build_angular/src/builders/karma/index.ts
  packages/angular_devkit/build_angular/src/builders/karma/schema.json
Labels: action: merge, target: minor, detected: feature

#26614 fix(@angular-devkit/build-angular): ensure port 0 uses random port with Vite development server
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/port_spec.ts
  packages/angular_devkit/build_angular/src/utils/check-port.ts
Labels: target: patch, action: merge

#26612 fix(@angular-devkit/build-angular): ensure browser-esbuild is used in dev server with browser builder and forceEsbuild
  packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/force-esbuild_spec.ts
Labels: target: patch, action: merge

#26619 fix(@angular-devkit/build-angular): `baseHref` with trailing slash causes server not to be accessible without trailing slash
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build-base-href_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
Labels: target: patch, action: merge

#26463 perf(@angular-devkit/build-angular): reduce TypeScript JSDoc parsing in application builder
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/angular-host.ts
Labels: action: merge, target: minor

#26623 fix(@angular-devkit/build-angular): inlining of fonts results in jagged fonts for Windows users
  packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
Labels: target: patch, action: merge

#26621 feat(@angular-devkit/build-angular): inline Google and Adobe fonts located in stylesheets
  packages/angular_devkit/build_angular/src/builders/application/tests/options/optimization-fonts-inline_spec.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/component-stylesheets.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/compiler-plugin-options.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/global-styles.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/bundle-options.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/css-inline-fonts-plugin.ts
  packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
Labels: action: merge, target: minor, detected: feature

#26625 refactor(@angular-devkit/build-angular): remove deployUrl from browser-esbuild builder-status-warnings
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/builder-status-warnings.ts
Labels: target: patch, action: merge

#26579 refactor(@angular-devkit/build-angular): convert watching to use watchpack package
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/builders/application/build-action.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/watcher.ts
  yarn.lock
Labels: action: merge, target: minor

#26630 fix(@angular-devkit/build-angular): handle updates of an `npm link` library from another workspace when `preserveSymlinks` is `true`
  packages/angular_devkit/build_angular/src/builders/application/build-action.ts
Labels: target: patch, action: merge

#26629 fix(@angular-devkit/build-angular): the request url "..." is outside of Vite serving allow list for all assets
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
Labels: action: merge, target: minor

#26636 fix(@angular-devkit/build-angular): cache loading of component resources in JIT mode
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-component_styles_spec.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/jit-plugin-callbacks.ts
Labels: action: merge, target: minor

#26646 [17.0.x] fix(@angular-devkit/build-angular): cache loading of component resources in JIT mode
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-component_styles_spec.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/jit-plugin-callbacks.ts
Labels: target: patch, action: merge

#26643 fix(@angular-devkit/build-angular): allow vite to serve JavaScript and TypeScript assets
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build-assets_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
Labels: target: patch, action: merge

#26650 fix(@angular-devkit/build-angular): update ESM loader to work with Node.js 18.19.0
  packages/angular_devkit/build_angular/src/utils/server-rendering/esm-in-memory-loader/node-18-utils.ts
Labels: target: patch, action: merge

#26640 fix(@angular-devkit/build-angular): file is missing from the TypeScript compilation with JIT
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/typescript-rebuild-touch-file_spec.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/source-file-cache.ts
Labels: target: patch, action: merge

#26656 Fix MAIN CI
  tests/legacy-cli/e2e/tests/basic/serve.ts
Labels: action: merge, target: minor

#26661 docs: release notes for the v17.0.7 release
  CHANGELOG.md
Labels: action: merge

#26662 Bump version to "v17.1.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#26651 refactor(@angular-devkit/build-angular): unify proxy config loading i…
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
  packages/angular_devkit/build_angular/src/builders/ssr-dev-server/index.ts
  packages/angular_devkit/build_angular/src/utils/index.ts
  packages/angular_devkit/build_angular/src/utils/load-proxy-config.ts
Labels: action: merge, target: minor

#26664 fix(@angular-devkit/build-angular): ensure empty optimized Sass stylesheets stay empty
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/component-stylesheets_spec.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/angular-host.ts
Labels: target: patch, action: merge

#26658 fix(@angular-devkit/build-angular): construct SSR request URL using server resolvedUrls
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
  tests/legacy-cli/e2e.bzl
  tests/legacy-cli/e2e/tests/commands/serve/ssr-http-requests-assets.ts
Labels: target: patch, action: merge

#26670 refactor: update test runner to use proxess.exit instead of treekill
  tests/legacy-cli/e2e/utils/test_process.ts
Labels: action: merge, target: minor

#26667 refactor(@angular-devkit/build-angular): add index HTML transformer to application programmatic usage
  goldens/public-api/angular_devkit/build_angular/index.md
  packages/angular_devkit/build_angular/src/builders/application/index.ts
  packages/angular_devkit/build_angular/src/builders/application/options.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/index-html-generator.ts
Labels: action: merge, target: minor

#26675 feat(@angular-devkit/build-angular): allow customization of output locations
  goldens/public-api/angular_devkit/build_angular/index.md
  packages/angular_devkit/build_angular/src/builders/application/build-action.ts
  packages/angular_devkit/build_angular/src/builders/application/index.ts
  packages/angular_devkit/build_angular/src/builders/application/options.ts
  packages/angular_devkit/build_angular/src/builders/application/schema.json
  packages/angular_devkit/build_angular/src/builders/application/tests/options/output-path_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
Labels: action: merge, target: minor, detected: feature

#26684 refactor(@angular/cli): remove no longer relevant regexps from `ng version` checks
  packages/angular/cli/src/commands/version/cli.ts
Labels: target: patch, action: merge

#26685 fix(@angular/cli): re-add `-d` alias for `--dry-run`
  packages/angular/cli/src/command-builder/schematics-command-module.ts
Labels: target: patch, action: merge

#26687 feat(@angular-devkit/build-angular): allowing control of index HTML initial preload generation
  packages/angular_devkit/build_angular/src/builders/application/options.ts
  packages/angular_devkit/build_angular/src/builders/application/schema.json
  packages/angular_devkit/build_angular/src/builders/application/tests/options/index_spec.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/index-html-generator.ts
Labels: action: merge, target: minor, detected: feature

#26688 refactor(@angular-devkit/schematics-cli): remove usage of devkit core tags helper
  packages/angular_devkit/schematics_cli/bin/schematics.ts
Labels: action: merge, target: minor

#26689 refactor(@angular/pwa): use stream pipeline operator with HTML rewriter
  packages/angular/pwa/pwa/index.ts
Labels: action: merge, target: minor

#26701 refactor(@angular-devkit/build-angular): reduce promise creation during estimated transfer size calculation
  packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
Labels: action: merge, target: minor

#26713 fix(@angular-devkit/build-angular): ensure external dependencies are used by Web Worker bundling
  packages/angular_devkit/build_angular/src/builders/application/tests/options/external-dependencies_spec.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
Labels: target: patch, action: merge

#26714 refactor(@angular-devkit/build-angular): remove no longer needed `realpathSync`
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
Labels: action: merge, target: minor

#26720 test: always use package manager force option in version add command E2E
  tests/legacy-cli/e2e/tests/commands/add/version-specifier.ts
Labels: action: merge, target: lts

#26711 feat(@angular-devkit/build-angular): emit external sourcemaps for component styles
  packages/angular_devkit/build_angular/src/builders/application/tests/options/sourcemap_spec.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/component-stylesheets.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/jit-plugin-callbacks.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/compiler-plugin-options.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/bundle-options.ts
Labels: action: merge, target: minor, detected: feature

#26725 fix(@angular/cli): `ng e2e` and `ng lint` prompt requires to hit Enter twice to proceed on Windows
  packages/angular/cli/src/command-builder/architect-base-command-module.ts
  packages/angular/cli/src/commands/add/cli.ts
Labels: target: patch, action: merge

#26726 refactor(@angular/cli): use `process.versions.pnp` to determine if PNP is used in `warnOnMissingNodeModules`
  packages/angular/cli/src/command-builder/architect-base-command-module.ts
Labels: action: merge, target: minor

#26694 fix(@schematics/angular): add missing property "buildTarget" to interface "ServeBuilderOptions"
  packages/schematics/angular/utility/workspace-models.ts
Labels: target: patch, action: merge

#26728 Bump version to "v16.2.11" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#26729 docs: release notes for the v16.2.11 release
  CHANGELOG.md
Labels: area: docs, action: merge

#26731 Bump version to "v17.0.8" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#26733 docs: changelog cherry pick for 17.0.8 release
  CHANGELOG.md
Labels: area: docs, action: merge, target: minor

#26734 Bump version to "v17.1.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#26735 fix(@angular-devkit/build-angular): filter explicit external dependencies for Vite prebundling
  packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
Labels: action: merge, target: minor

#26741 fix(@angular-devkit/build-angular): emit error when using prerender and app-shell builders with application builder
  packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
  packages/angular_devkit/build_angular/src/builders/prerender/index.ts
Labels: action: merge, target: minor

#26736 docs: remove Universal from caretaking doc
  docs/process/release.md
Labels: area: docs, target: patch, action: merge

#26739 fix(@schematics/angular): do not trigger NPM install when using `---skip-install` and `--ssr`
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/ssr/index.ts
Labels: action: merge, target: minor

#26749 refactor(@schematics/angular): fix typo in "expression" variable name inside "addSymbolToNgModuleMetadata" function
  packages/schematics/angular/utility/ast-utils.ts
Labels: action: merge, target: minor

#26753 Revert "build: update dependency webpack-dev-middleware to v7"
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: action: merge, target: minor

#26751 refactor: remove unused code from CSS Lexer
  packages/angular_devkit/build_angular/src/tools/sass/lexer.ts
Labels: action: merge, target: minor

#26756 fix(@angular-devkit/build-angular): typo in preloadInitial option description
  packages/angular_devkit/build_angular/src/builders/application/schema.json
Labels: action: merge, target: minor
