Repository angular/angular-cli, pull requests merged in 2024-06, with the labels that each got.

#27763 fix(@angular/build): watch all related files during a Sass error
  packages/angular/build/src/tools/esbuild/stylesheets/sass-language.ts
Labels: target: patch, action: merge

#27772 ci: use Github action-based dependency license checking
  .github/dependency-review-config.yml
  .github/workflows/pr.yml
  package.json
  scripts/validate-licenses.mts
  scripts/validate.mts
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27767 fix(@angular/cli): add `schema.json` options to parsed command, also when a version is passed to `ng add <package>@<version>`
  packages/angular/cli/src/commands/add/cli.ts
Labels: target: patch, action: merge

#27779 feat(@angular/build): add `--inspect` option to the dev-server
  goldens/public-api/angular/build/index.api.md
  goldens/public-api/angular_devkit/build_angular/index.api.md
  packages/angular/build/src/builders/dev-server/options.ts
  packages/angular/build/src/builders/dev-server/schema.json
  packages/angular/build/src/builders/dev-server/vite-server.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/options.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/schema.json
Labels: action: merge, target: minor, detected: feature

#27752 perf(@angular/build): use direct transpilation with isolated modules
  packages/angular/build/src/builders/application/tests/behavior/typescript-isolated-modules_spec.ts
  packages/angular/build/src/tools/esbuild/angular/compilation/aot-compilation.ts
  packages/angular/build/src/tools/esbuild/angular/compilation/parallel-worker.ts
  packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
Labels: action: merge, target: minor

#27714 docs: update tsconfig template link aio->adev
  packages/schematics/angular/application/files/common-files/tsconfig.app.json.template
  packages/schematics/angular/application/files/common-files/tsconfig.spec.json.template
  packages/schematics/angular/e2e/files/tsconfig.json.template
  packages/schematics/angular/library/files/tsconfig.lib.json.template
  packages/schematics/angular/library/files/tsconfig.lib.prod.json.template
  packages/schematics/angular/library/files/tsconfig.spec.json.template
  packages/schematics/angular/server/files/root/tsconfig.server.json.template
  packages/schematics/angular/web-worker/files/worker-tsconfig/tsconfig.worker.json.template
  packages/schematics/angular/workspace/files/tsconfig.json.template
Labels: area: docs, target: patch, action: merge

#27778 refactor(@schematics/angular): remove unnecessary whitespace in spec …
  packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.spec.ts.template
Labels: target: patch, action: merge

#27788 docs: release notes for the v18.0.3 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27789 Bump version to "v18.1.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27798 fix(@angular/build): issue warning when auto adding `@angular/localize/init`
  packages/angular/build/src/tools/esbuild/application-code-bundle.ts
  tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts
Labels: target: patch, action: merge

#27800 fix(@angular/build): generate module preloads next to script elements in index HTML
  packages/angular/build/src/utils/index-file/augment-index-html.ts
  packages/angular/build/src/utils/index-file/augment-index-html_spec.ts
Labels: target: patch, action: merge

#27809 fix(@angular/build): allow additional module preloads up to limit
  packages/angular/build/src/tools/esbuild/index-html-generator.ts
Labels: action: merge, target: minor

#27807 fix(@angular/build): Initiate PostCSS only once
  packages/angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts
Labels: target: patch, action: merge

#27811 ci: only download saucelabs connect utility when running tests
  package.json
  scripts/saucelabs/start-tunnel.sh
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27817 build: remove `--silent` from `yarn` command
  scripts/build-schema.mts
Labels: action: merge, area: build & ci, target: minor

#27818 refactor: replace custom promise-based setTimeout with native Node.js setTimeout
  packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/code-coverage_spec.ts
  packages/angular_devkit/build_angular/src/builders/karma/tests/options/code-coverage-exclude_spec.ts
  packages/angular_devkit/build_angular/src/builders/karma/tests/options/code-coverage_spec.ts
Labels: target: patch, action: merge

#27813 refactor(@angular/cli): use Node.js builtin ANSI escape removal helper
  packages/angular/cli/lib/cli/index.ts
  packages/angular/cli/src/utilities/color.ts
Labels: action: merge, target: minor

#27820 ci: disable `yarn` auto update
  renovate.json
Labels: action: merge, area: build & ci, target: minor

#27823 build: disable package install scripts by default
  .yarnrc.yml
  package.json
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27824 docs: update e2e test commands
  docs/DEVELOPER.md
Labels: area: docs, action: merge, target: minor

#27829 build: update E2E setup to use NPM 10 to publish packages
  .github/dependency-review-config.yml
  package.json
  tests/legacy-cli/e2e/setup/010-local-publish.ts
  tests/legacy-cli/e2e/utils/registry.ts
  yarn.lock
Labels: area: build & ci, target: minor

#27830 ci: clean up PR and CI workflow
  .github/workflows/ci.yml
  .github/workflows/pr.yml
Labels: action: merge, area: build & ci, target: minor

#27831 ci: disable running pnpm and yarn subsets on Node.js 20 and 18
  .github/workflows/ci.yml
Labels: action: merge, area: build & ci, target: minor

#27834 test: re-enable WTR test
  tests/legacy-cli/e2e/tests/web-test-runner/basic.ts
Labels: target: patch, action: merge

#27838 fix(@angular/build): do not reference sourcemaps in web workers and global stylesheet bundles when hidden setting is enabled
  packages/angular/build/src/builders/application/tests/options/sourcemap_spec.ts
  packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
  packages/angular/build/src/tools/esbuild/compiler-plugin-options.ts
  packages/angular/build/src/tools/esbuild/global-styles.ts
Labels: target: patch, action: merge

#27840 build: update copy-webpack-plugin to 12.0.2
  packages/angular_devkit/build_angular/package.json
  renovate.json
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27843 Bump version to "v18.0.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27844 docs: release notes for the v18.0.4 release
  CHANGELOG.md
Labels: action: merge

#27846 Bump version to "v18.1.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27848 fix(@angular/build): automatically resolve `.mjs` files when using Vite
  packages/angular/build/src/builders/dev-server/vite-server.ts
  packages/angular/build/src/tools/esbuild/application-code-bundle.ts
  packages/angular/build/src/tools/esbuild/global-scripts.ts
Labels: target: patch, action: merge

#27855 test: Update NPM to Latest Version
  tests/legacy-cli/e2e/setup/100-global-cli.ts
  tests/legacy-cli/e2e/tests/commands/add/npm-env-vars.ts
  tests/legacy-cli/e2e/tests/commands/add/secure-registry.ts
  tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts
Labels: action: merge, target: minor

#27859 ci: begin checking licenses of upstream dependencies to ensure they are approved
  .github/workflows/pr.yml
Labels: action: merge, area: build & ci, target: minor

#27851 fix(@angular/cli): update schematics to use RouterModule when --routing flag is present
  packages/schematics/angular/application/files/module-files/src/app/app.component.spec.ts.template
  tests/legacy-cli/e2e/assets/15.0-project/src/app/app.component.spec.ts
  tests/legacy-cli/e2e/assets/18-ssr-project-webpack/src/app/app.component.spec.ts
Labels: target: patch, action: merge

#27857 fix(@angular-devkit/build-angular): use istanbul-lib-instrument directly for karma code coverage
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/tools/babel/plugins/add-code-coverage.ts
  packages/angular_devkit/build_angular/src/tools/babel/plugins/types.d.ts
  packages/angular_devkit/build_angular/src/tools/babel/presets/application.ts
  yarn.lock
Labels: action: merge, target: minor

#27832 refactor(@angular/cli): improve console status logging for add command
  package.json
  packages/angular/cli/BUILD.bazel
  packages/angular/cli/package.json
  packages/angular/cli/src/commands/add/cli.ts
  packages/angular/cli/src/utilities/package-manager.ts
  tests/legacy-cli/e2e/tests/commands/add/peer.ts
  yarn.lock
Labels: action: merge, target: minor

#27867 refactor(@angular/cli): remove direct use of ansi-colors package
  packages/angular/cli/BUILD.bazel
  packages/angular/cli/lib/cli/index.ts
  packages/angular/cli/package.json
  packages/angular/cli/src/commands/update/cli.ts
  packages/angular/cli/src/utilities/color.ts
  yarn.lock
Labels: action: merge, target: minor

#27875 fix(@angular/build): add CSP nonce to script with src tags
  packages/angular/build/src/utils/index-file/nonce.ts
  packages/angular/build/src/utils/index-file/nonce_spec.ts
Labels: target: patch, action: merge

#27877 fix(@angular-devkit/build-angular): use istanbul-lib-instrument directly for karma code coverage
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/tools/babel/plugins/add-code-coverage.ts
  packages/angular_devkit/build_angular/src/tools/babel/plugins/types.d.ts
  packages/angular_devkit/build_angular/src/tools/babel/presets/application.ts
  yarn.lock
Labels: target: patch, action: merge

#27876 fix(@angular/build): use Node.js available parallelism for default worker count
  packages/angular/build/src/utils/environment-options.ts
  packages/angular_devkit/build_angular/src/utils/environment-options.ts
Labels: target: patch, action: merge

#27885 test: update create-angular test to install packages
  tests/legacy-cli/e2e/tests/misc/create-angular.ts
Labels: action: merge, target: minor

#27887 Bump version to "v18.0.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27888 docs: release notes for the v18.0.5 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27890 Bump version to "v18.1.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27891 refactor(@angular/build): include Angular compiler plugin in private API
  packages/angular/build/src/private.ts
Labels: target: patch, action: merge

#27898 refactor(@angular/cli): allow tty and color helpers to use a stream
  packages/angular/cli/src/utilities/color.ts
  packages/angular/cli/src/utilities/tty.ts
Labels: action: merge, target: minor

#27897 refactor(@angular/build): move generic Angular tools into separate source directory
  packages/angular/build/src/private.ts
  packages/angular/build/src/tools/angular/angular-host.ts
  packages/angular/build/src/tools/angular/compilation/angular-compilation.ts
  packages/angular/build/src/tools/angular/compilation/aot-compilation.ts
  packages/angular/build/src/tools/angular/compilation/factory.ts
  packages/angular/build/src/tools/angular/compilation/index.ts
  packages/angular/build/src/tools/angular/compilation/jit-compilation.ts
  packages/angular/build/src/tools/angular/compilation/noop-compilation.ts
  packages/angular/build/src/tools/angular/compilation/parallel-compilation.ts
  packages/angular/build/src/tools/angular/compilation/parallel-worker.ts
  packages/angular/build/src/tools/angular/transformers/jit-bootstrap-transformer.ts
  packages/angular/build/src/tools/angular/transformers/jit-resource-transformer.ts
  packages/angular/build/src/tools/angular/transformers/web-worker-transformer.ts
  packages/angular/build/src/tools/angular/uri.ts
  packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
  packages/angular/build/src/tools/esbuild/angular/jit-plugin-callbacks.ts
Labels: action: merge, target: minor

#27899 refactor(@angular/build): support directly merging bundler results
  packages/angular/build/src/tools/esbuild/bundler-context.ts
Labels: action: merge, target: minor

#27900 fix(@angular/build): show JavaScript cache store initialization warning
  packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
Labels: target: patch, action: merge

#27908 build: enabled isolated modules TypeScript option
  .yarn/patches/@bazel-concatjs-npm-5.8.1-1bf81df846.patch
  modules/testing/builder/src/file-watching.ts
  modules/testing/builder/src/index.ts
  packages/angular/build/src/builders/application/index.ts
  packages/angular/build/src/builders/dev-server/index.ts
  packages/angular/build/src/builders/dev-server/internal.ts
  packages/angular/build/src/index.ts
  packages/angular/build/src/private.ts
  packages/angular/build/src/utils/bundle-calculator.ts
  packages/angular/ssr/public_api.ts
  packages/angular_devkit/architect/src/index.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
  packages/angular_devkit/build_angular/src/builders/karma/index.ts
  packages/angular_devkit/build_angular/src/builders/ng-packagr/index.ts
  packages/angular_devkit/build_angular/src/builders/protractor/index.ts
  packages/angular_devkit/build_angular/src/builders/server/index.ts
  packages/angular_devkit/build_angular/src/index.ts
  packages/angular_devkit/build_angular/src/tools/webpack/plugins/index.ts
  packages/angular_devkit/build_webpack/src/index.ts
  packages/angular_devkit/core/src/virtual-fs/host/alias.ts
  packages/angular_devkit/core/src/virtual-fs/host/memory.ts
  packages/angular_devkit/core/src/virtual-fs/host/pattern.ts
  packages/angular_devkit/core/src/virtual-fs/host/record.ts
  packages/angular_devkit/core/src/virtual-fs/host/sync.ts
  packages/angular_devkit/core/src/virtual-fs/host/test.ts
  packages/angular_devkit/core/src/workspace/index.ts
  packages/angular_devkit/schematics/src/index.ts
  packages/ngtools/webpack/src/index.ts
  packages/ngtools/webpack/src/ivy/index.ts
  packages/schematics/angular/utility/index.ts
  packages/schematics/angular/utility/standalone/index.ts
  tsconfig.json
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27901 test: add proper assertions to several E2E tests
  tests/legacy-cli/e2e/tests/basic/aot.ts
  tests/legacy-cli/e2e/tests/basic/build.ts
  tests/legacy-cli/e2e/tests/basic/command-scope.ts
  tests/legacy-cli/e2e/tests/basic/e2e.ts
  tests/legacy-cli/e2e/tests/basic/run.ts
Labels: action: merge, target: minor

#27910 fix(@angular/build): address rxjs undefined issues during SSR prebundling
  packages/angular/build/src/builders/dev-server/vite-server.ts
Labels: action: merge, target: minor

#27914 build: remove tsetse rule exclusions
  packages/angular/cli/src/commands/config/cli.ts
  packages/angular/cli/src/commands/update/cli.ts
  packages/angular/cli/src/utilities/package-tree.ts
  packages/angular/cli/src/utilities/project.ts
  tsconfig.json
Labels: action: merge, area: build & ci, target: minor

#27915 refactor(@angular-devkit/core): additional JSON parse type casting
  packages/angular_devkit/core/src/json/schema/registry.ts
  packages/angular_devkit/core/src/utils/object.ts
Labels: action: merge, target: minor

#27913 refactor(@angular/cli): use non-experimental decorators for internal memoize
  packages/angular/cli/src/utilities/memoize.ts
  tsconfig.json
Labels: action: merge, target: minor

#27924 build: update all non-major dependencies
  WORKSPACE
  package.json
  packages/angular/build/package.json
  packages/angular/build/src/utils/index-file/inline-critical-css_spec.ts
  packages/angular/cli/package.json
  packages/angular/ssr/package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/core/package.json
  packages/angular_devkit/schematics/package.json
  packages/schematics/angular/package.json
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27925 build: remove `@types/browserslist`
  package.json
  packages/angular/build/BUILD.bazel
  packages/angular_devkit/build_angular/BUILD.bazel
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27926 refactor: minor code cleanup to improve code health
  packages/angular/build/src/tools/babel/plugins/adjust-static-class-members.ts
  packages/angular_devkit/build_angular/src/tools/babel/presets/application.ts
  packages/angular_devkit/build_angular/src/utils/run-module-as-observable-fork.ts
  packages/angular_devkit/schematics/tools/file-system-engine-host.ts
  scripts/devkit-admin.mts
Labels: action: merge, target: minor

#27931 build: use TypeScript 5.5 for new projects and tests
  package.json
  packages/angular_devkit/schematics_cli/blank/project-files/package.json
  packages/angular_devkit/schematics_cli/schematic/files/package.json
  packages/schematics/angular/utility/latest-versions/package.json
  tests/legacy-cli/e2e/assets/18-ssr-project-webpack/package.json
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27928 refactor(@angular-devkit/schematics): avoid double file access reading JSON files
  packages/angular_devkit/schematics/tools/file-system-utility.ts
Labels: action: merge, target: minor

#27929 refactor(@angular-devkit/schematics): use modern language features in test engine host
  packages/angular_devkit/schematics/tools/node-modules-test-engine-host.ts
Labels: action: merge, target: minor

#27938 Bump version to "v18.0.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27939 docs: release notes for the v18.0.6 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27940 Bump version to "v18.1.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27944 refactor(@angular/build): improve BuildOutputFile property access
  goldens/public-api/angular/build/index.api.md
  packages/angular/build/src/builders/application/execute-post-bundle.ts
  packages/angular/build/src/tools/esbuild/bundler-context.ts
  packages/angular/build/src/tools/esbuild/bundler-execution-result.ts
  packages/angular/build/src/tools/esbuild/i18n-inliner.ts
  packages/angular/build/src/tools/esbuild/utils.ts
Labels: target: rc, action: merge

#27946 fix(@angular/build): normalize paths during module resolution in Vite
  packages/angular/build/src/tools/vite/angular-memory-plugin.ts
Labels: target: rc, action: merge

#27947 fix(@angular/build): correctly name entry points to match budgets
  packages/angular/build/src/builders/application/tests/options/bundle-budgets_spec.ts
  packages/angular/build/src/tools/esbuild/budget-stats.ts
  packages/angular/build/src/tools/esbuild/utils.ts
Labels: target: patch, action: merge

#27950 refactor(@angular/build): use build output files directly in stats and budgets
  packages/angular/build/src/builders/application/execute-build.ts
  packages/angular/build/src/tools/esbuild/budget-stats.ts
  packages/angular/build/src/tools/esbuild/utils.ts
Labels: target: rc, action: merge

#27895 fix(@angular/cli): make `ng update` to keep newline at the end of package.json
  packages/angular/cli/src/commands/update/schematic/index.ts
  packages/angular/cli/src/commands/update/schematic/index_spec.ts
Labels: target: patch, action: merge

#27952 refactor: fix pipe type
  packages/angular_devkit/schematics/src/rules/template.ts
Labels: action: merge, target: minor

#27953 refactor(@angular/build): add experimental chunk optimizer for production application builds
  package.json
  packages/angular/build/BUILD.bazel
  packages/angular/build/package.json
  packages/angular/build/src/builders/application/chunk-optimizer.ts
  packages/angular/build/src/builders/application/execute-build.ts
  packages/angular/build/src/utils/environment-options.ts
  tests/legacy-cli/e2e/tests/build/chunk-optimizer.ts
  tests/legacy-cli/e2e/tests/build/material.ts
  yarn.lock
Labels: target: rc, action: merge

#27958 fix(@angular/build): redirect to path with trailing slash for asset directories
  packages/angular/build/src/builders/dev-server/tests/behavior/build-assets_spec.ts
  packages/angular/build/src/tools/vite/angular-memory-plugin.ts
Labels: target: patch, action: merge

#27961 refactor(@angular/build): move Vite middlewares into separate files
  packages/angular/build/src/builders/dev-server/vite-server.ts
  packages/angular/build/src/tools/vite/angular-memory-plugin.ts
  packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts
  packages/angular/build/src/tools/vite/middlewares/html-fallback-middleware.ts
  packages/angular/build/src/tools/vite/middlewares/index-html-middleware.ts
  packages/angular/build/src/tools/vite/middlewares/index.ts
  packages/angular/build/src/tools/vite/middlewares/ssr-middleware.ts
  packages/angular/build/src/tools/vite/utils.ts
Labels: target: rc, action: merge
