Repository angular/angular-cli, pull requests merged in 2024-02, with the labels that each got.

#27019 fix(@angular-devkit/build-angular): allow `./` baseHref when using vite based server
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
Labels: target: patch, action: merge

#27010 refactor(@angular-devkit/build-angular): allow internal externalPackages option to exclude packages
  packages/angular_devkit/build_angular/src/builders/application/options.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/external-packages-plugin.ts
Labels: action: merge, target: minor

#27024 test: update webpack tests filenames and size checks to pass with latest webpack
  tests/legacy-cli/e2e/tests/packages/webpack/test-app.ts
Labels: target: patch, action: merge

#27026 build: update all non-major dependencies
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/builders/browser/index.ts
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/named-chunks_spec.ts
  packages/angular_devkit/build_angular/src/builders/server/index.ts
  packages/angular_devkit/build_angular/src/tools/webpack/utils/stats.ts
  packages/angular_devkit/build_webpack/package.json
  packages/angular_devkit/build_webpack/src/builders/webpack-dev-server/index.ts
  packages/angular_devkit/build_webpack/src/builders/webpack/index.ts
  packages/ngtools/webpack/package.json
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27018 feat(@angular-devkit/build-angular): provide option to allow automatically cleaning the terminal screen during rebuilds
  goldens/public-api/angular_devkit/build_angular/index.md
  packages/angular_devkit/build_angular/src/builders/application/build-action.ts
  packages/angular_devkit/build_angular/src/builders/application/index.ts
  packages/angular_devkit/build_angular/src/builders/application/options.ts
  packages/angular_devkit/build_angular/src/builders/application/schema.json
Labels: action: merge, target: minor, detected: feature

#27035 fix(@angular-devkit/build-angular): avoid preloading server chunks
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/index-preload-hints_spec.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/index-html-generator.ts
Labels: action: merge, target: minor

#27021 feat(@angular-devkit/build-angular): allow control of Vite-based development server prebundling
  goldens/public-api/angular_devkit/build_angular/index.md
  packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/options.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/schema.json
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/execute-fetch.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/prebundle_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
Labels: action: merge, target: minor, detected: feature

#27049 fix(@angular-devkit/build-angular): ensure correct `.html` served with Vite dev-server
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build-assets_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
  packages/angular_devkit/build_angular/src/tools/vite/angular-memory-plugin.ts
Labels: action: merge, target: minor

#27047 feat(@angular-devkit/build-angular): add define build option to application builder
  goldens/public-api/angular_devkit/build_angular/index.md
  packages/angular_devkit/build_angular/src/builders/application/options.ts
  packages/angular_devkit/build_angular/src/builders/application/schema.json
  packages/angular_devkit/build_angular/src/builders/application/tests/options/define_spec.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
Labels: action: merge, target: minor, detected: feature

#27056 Bump version to "v17.1.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27057 docs: release notes for the v17.1.3 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27058 Bump version to "v17.2.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27065 fix(@angular-devkit/schematics): add `bun` to known package managers
  packages/angular_devkit/schematics/tasks/package-manager/executor.ts
Labels: target: rc, action: merge

#27062 fix(@angular/cli): prevent BOM errors in `package.json` during `ng update`
  packages/angular/cli/src/commands/update/schematic/index.ts
Labels: target: patch, action: merge

#27069 fix(@angular-devkit/build-angular): bypass Vite prebundling for absolute URL imports
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
Labels: target: patch, action: merge

#27084 refactor(@schematics/angular): correct several comment typos
  packages/schematics/angular/private/standalone.ts
  packages/schematics/angular/utility/standalone/code_block.ts
Labels: action: merge, target: minor

#27085 fix(@angular-devkit/build-angular): downgrade copy-webpack-plugin to workaround Node.js support issue
  packages/angular_devkit/build_angular/package.json
  renovate.json
  yarn.lock
Labels: action: merge, target: minor

#27098 fix(@angular-devkit/build-angular): support string as plugin option in custom postcss plugin config
  packages/angular_devkit/build_angular/src/utils/postcss-configuration.ts
Labels: target: rc, action: merge

#27099 build: update Angular peer deps packages to 17.2.0
  packages/angular/pwa/package.json
  packages/angular/ssr/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/angular/utility/latest-versions/package.json
Labels: target: rc, action: merge, area: build & ci

#27103 Bump version to "v17.2.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27104 docs: release notes for the v17.2.0 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27083 refactor(@angular-devkit/schematics-cli): rename schematic template files with a template extension
  packages/angular_devkit/schematics_cli/blank/factory.ts
  packages/angular_devkit/schematics_cli/blank/project-files/.gitignore.template
  packages/angular_devkit/schematics_cli/blank/project-files/.npmignore.template
  packages/angular_devkit/schematics_cli/blank/schematic-files/src/__name@dasherize__/index.ts.template
  packages/angular_devkit/schematics_cli/blank/schematic-files/src/__name@dasherize__/index_spec.ts.template
  packages/angular_devkit/schematics_cli/schematic/factory.ts
  packages/angular_devkit/schematics_cli/schematic/files/.gitignore.template
  packages/angular_devkit/schematics_cli/schematic/files/.npmignore.template
Labels: action: merge, target: minor

#27125 fix(@angular-devkit/build-angular): allow `mts` and `cts` file replac…
  packages/angular_devkit/build_angular/src/builders/application/schema.json
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/schema.json
  packages/angular_devkit/build_angular/src/builders/browser/schema.json
  packages/angular_devkit/build_angular/src/builders/server/schema.json
Labels: target: patch, action: merge

#27139 build: update `dart-sass` to v1.71.1
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/tools/sass/sass-service.ts
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27140 fix(@angular-devkit/build-angular): provide Vite client code source map when loading
  packages/angular_devkit/build_angular/src/tools/vite/angular-memory-plugin.ts
Labels: target: patch, action: merge

#27150 test: generalize webpack direct E2E chunk size testing
  tests/legacy-cli/e2e/tests/packages/webpack/test-app.ts
Labels: target: patch, action: merge

#27153 Bump version to "v17.2.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27154 docs: release notes for the v17.2.1 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27155 fix(@angular-devkit/build-angular): ensure all related stylesheets are rebuilt when an import changes
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-global_styles_spec.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/load-result-cache.ts
Labels: target: patch, action: merge

#27159 build: update webpack to v5.90.3
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/named-chunks_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/stats-json_spec.ts
  packages/angular_devkit/build_webpack/package.json
  packages/ngtools/webpack/package.json
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27178 test: update Safari 15 private property E2E for babel changes
  tests/legacy-cli/e2e/tests/misc/safari-15-class-properties.ts
Labels: target: patch, action: merge

#27179 Bump version to "v17.2.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27180 docs: release notes for the v17.2.2 release
  CHANGELOG.md
Labels: area: docs, action: merge
