Repository angular/angular-cli, pull requests merged in 2024-08, with the labels that each got.

#28161 fix(@angular/build): allow explicitly disabling TypeScript incremental mode
  packages/angular/build/src/builders/application/tests/behavior/typescript-incremental_spec.ts
  packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
Labels: target: patch, action: merge

#28168 test: update @typescript-eslint/eslint-plugin to v8.0.1
  .eslintrc.json
  package.json
  packages/angular_devkit/core/src/json/schema/interface.ts
  packages/ngtools/webpack/src/transformers/find_image_domains.ts
  scripts/validate-user-analytics.mts
  yarn.lock
Labels: action: merge, target: minor

#28167 build: update yarn to v4.4.0
  .yarn/releases/yarn-4.3.1.cjs
  .yarn/releases/yarn-4.4.0.cjs
  .yarnrc.yml
  WORKSPACE
  package.json
Labels: action: merge, area: build & ci, target: minor

#28173 fix(@angular/build): lazy load Node.js inspector for dev server
  packages/angular/build/src/builders/dev-server/vite-server.ts
Labels: target: patch, action: merge

#28174 Bump version to "v18.1.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#28175 docs: release notes for the v18.1.4 release
  CHANGELOG.md
Labels: area: docs, action: merge

#28176 Bump version to "v18.2.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#28139 feat(@angular/ssr): introduce new hybrid rendering API
  .yarn/patches/@angular-build-tooling-https-06f4984cdf.patch
  WORKSPACE
  goldens/circular-deps/packages.json
  package.json
  packages/angular/ssr/BUILD.bazel
  packages/angular/ssr/package.json
  packages/angular/ssr/public_api.ts
  packages/angular/ssr/src/app-engine.ts
  packages/angular/ssr/src/app.ts
  packages/angular/ssr/src/common-engine/common-engine.ts
  packages/angular/ssr/src/common-engine/inline-css-processor.ts
  packages/angular/ssr/src/common-engine/peformance-profiler.ts
  packages/angular/ssr/src/console.ts
  packages/angular/ssr/src/hooks.ts
  packages/angular/ssr/src/i18n.ts
  packages/angular/ssr/src/manifest.ts
  packages/angular/ssr/src/render.ts
  packages/angular/ssr/src/request.ts
  packages/angular/ssr/src/response.ts
  packages/angular/ssr/src/tokens.ts
  packages/angular/ssr/src/utils.ts
  packages/angular/ssr/test/BUILD.bazel
  packages/angular/ssr/test/app-engine_spec.ts
  packages/angular/ssr/test/app_spec.ts
  packages/angular/ssr/test/hooks_spec.ts
  packages/angular/ssr/test/i18n_spec.ts
  packages/angular/ssr/test/request_spec.ts
  packages/angular/ssr/test/response_spec.ts
  packages/angular/ssr/test/testing-utils.ts
  tsconfig.json
  yarn.lock
Labels: action: merge, target: minor, detected: feature, area: @angular/ssr

#28184 build: remove local patch for `@angular/build-tooling`
  .yarn/patches/@angular-build-tooling-https-06f4984cdf.patch
  package.json
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#28193 refactor(@angular-devkit/build-angular): reduce custom code in browser-esbuild implementation
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/assets_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/delete-output-path_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/deploy-url_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/main_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
  packages/angular_devkit/build_angular/src/builders/extract-i18n/application-extraction.ts
Labels: target: rc, action: merge

#28186 feat(@angular-devkit/schematics-cli): add package manager option to blank schematic
  packages/angular_devkit/schematics_cli/bin/schematics.ts
  packages/angular_devkit/schematics_cli/blank/factory.ts
  packages/angular_devkit/schematics_cli/blank/schema.json
  packages/angular_devkit/schematics_cli/schematic/factory.ts
  packages/angular_devkit/schematics_cli/schematic/schema.json
  tests/legacy-cli/e2e/tests/schematics_cli/basic.ts
  tests/legacy-cli/e2e/tests/schematics_cli/blank-test.ts
  tests/legacy-cli/e2e/tests/schematics_cli/schematic-test.ts
Labels: action: merge, target: minor, detected: feature

#28183 feat(@angular/ssr): dynamic route resolution using Angular router
  goldens/circular-deps/packages.json
  packages/angular/ssr/BUILD.bazel
  packages/angular/ssr/package.json
  packages/angular/ssr/src/app-engine.ts
  packages/angular/ssr/src/app.ts
  packages/angular/ssr/src/assets.ts
  packages/angular/ssr/src/manifest.ts
  packages/angular/ssr/src/render.ts
  packages/angular/ssr/src/routes/ng-routes.ts
  packages/angular/ssr/src/routes/route-tree.ts
  packages/angular/ssr/src/routes/router.ts
  packages/angular/ssr/src/utils/ng.ts
  packages/angular/ssr/src/utils/url.ts
  packages/angular/ssr/test/BUILD.bazel
  packages/angular/ssr/test/app-engine_spec.ts
  packages/angular/ssr/test/app_spec.ts
  packages/angular/ssr/test/assets_spec.ts
  packages/angular/ssr/test/routes/route-tree_spec.ts
  packages/angular/ssr/test/routes/router_spec.ts
  packages/angular/ssr/test/testing-utils.ts
  packages/angular/ssr/test/utils/url_spec.ts
  yarn.lock
Labels: action: merge, target: minor, detected: feature, area: @angular/ssr

#28198 refactor(@angular/build): remove route extractor and use version from `@angular/ssr`
  packages/angular/build/BUILD.bazel
  packages/angular/build/package.json
  packages/angular/build/src/tools/esbuild/application-code-bundle.ts
  packages/angular/build/src/utils/routes-extractor/BUILD.bazel
  packages/angular/build/src/utils/routes-extractor/extractor.ts
  packages/angular/build/src/utils/server-rendering/main-bundle-exports.ts
  packages/angular/build/src/utils/server-rendering/routes-extractor-worker.ts
  packages/angular/ssr/public_api.ts
  packages/angular/ssr/src/routes/ng-routes.ts
  packages/angular/ssr/src/routes/router.ts
  packages/angular/ssr/src/utils/ng.ts
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/builders/prerender/routes-extractor-worker.ts
  packages/angular_devkit/build_angular/src/builders/server/index.ts
  packages/angular_devkit/build_angular/src/builders/server/platform-server-exports-loader.ts
  packages/angular_devkit/build_angular/src/tools/webpack/configs/common.ts
  packages/angular_devkit/build_angular/src/tools/webpack/utils/helpers.ts
  tests/legacy-cli/e2e/tests/build/prerender/discover-routes-ngmodule.ts
  tests/legacy-cli/e2e/tests/build/prerender/discover-routes-standalone.ts
  yarn.lock
Labels: action: merge, target: minor

#28200 build: add missing `pkg_deps` for `@angular/create`
  packages/angular/create/BUILD.bazel
Labels: target: patch, action: merge, area: build & ci

#28202 build: remove Bazel typings workaround
  package.json
  packages/angular/cli/BUILD.bazel
  packages/angular/cli/src/typings-bazel.d.ts
  packages/angular_devkit/build_angular/src/babel-bazel.d.ts
  tsconfig.json
  yarn.lock
Labels: target: rc, action: merge, area: build & ci

#28204 build: remove unnecessary excludes from tsconfig.json
  tsconfig.json
Labels: target: rc, action: merge, area: build & ci

#28203 build: update Angular versions to 18.2 stable
  package.json
  packages/angular/build/package.json
  packages/angular/pwa/package.json
  packages/angular/ssr/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions/package.json
  yarn.lock
Labels: target: rc, action: merge, area: build & ci

#28205 Configure next branch to receive major changes for v19.0.0-next.0
  package.json
Labels: action: merge

#28207 Bump version to "v18.2.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#28208 docs: release notes for the v18.2.0 release
  CHANGELOG.md
Labels: area: docs, action: merge

#28206 build: update Angular versions to 19.0.0-next.0
  package.json
  packages/angular/build/package.json
  packages/angular/pwa/package.json
  packages/angular/ssr/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions/package.json
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/.gitignore
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/README.md
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/angular.json
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/package.json
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/server.ts
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/src/app/app-routing.module.ts
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/src/app/app.component.css
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/src/app/app.component.html
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/src/app/app.component.spec.ts
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/src/app/app.component.ts
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/src/app/app.module.server.ts
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/src/app/app.module.ts
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/src/assets/.gitkeep
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/src/favicon.ico
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/src/index.html
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/src/main.server.ts
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/src/main.ts
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/src/styles.css
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/tsconfig.app.json
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/tsconfig.json
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/tsconfig.server.json
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/tsconfig.spec.json
  tests/legacy-cli/e2e/tests/update/update-application-builder.ts
  tests/legacy-cli/e2e/tests/update/update.ts
  yarn.lock
Labels: target: major, action: merge, area: build & ci

#28211 Bump version to "v19.0.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge

#28215 fix(@angular/build): improve error message when an unhandled exception occurs during prerendering
  packages/angular/build/src/utils/server-rendering/prerender.ts
  packages/angular_devkit/build_angular/src/builders/server/tests/behavior/build-errors_spec.ts
Labels: target: patch, action: merge

#28100 BUILD: Changes to local repo's build system(path to npm_package_archive.tgz files)
  tools/link_package_json_to_tarballs.bzl
Labels: action: merge, area: build & ci, target: minor

#28234 build: downgrade sass version
  package.json
  packages/angular/build/package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge, area: build & ci

#28239 Revert "build: change to local repo's build system(path to npm_package_archive.tgz files)"
  tools/link_package_json_to_tarballs.bzl
Labels: action: merge, target: minor

#28237 fix(@angular/build): support reading on-disk files during i18n extraction
  packages/angular/build/src/builders/extract-i18n/application-extraction.ts
  packages/angular_devkit/build_angular/src/builders/extract-i18n/application-extraction.ts
Labels: target: patch, action: merge

#28238 fix(@angular-devkit/build-angular): remove outdated browser-esbuild option warning
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/builder-status-warnings.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
Labels: target: patch, action: merge

#28241 refactor(@angular/build): template style elements should always be CSS
  packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
Labels: target: major, action: merge

#28243 fix(@schematics/angular): remove `declaration` and `sourceMap` from default tsconfig
  packages/schematics/angular/workspace/files/tsconfig.json.template
Labels: target: major, action: merge

#28250 Bump version to "v18.2.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#28251 docs: release notes for the v18.2.1 release
  CHANGELOG.md
Labels: area: docs, action: merge

#28247 refactor(@angular-devkit/core): remove deprecated `fileBuffer` function in favor of `stringToFileBuffer`
  goldens/public-api/angular_devkit/core/index.api.md
  packages/angular_devkit/core/src/virtual-fs/host/buffer.ts
Labels: target: major, action: merge, detected: breaking change

#28254 build: mark server tests as flaky
  packages/angular_devkit/build_angular/BUILD.bazel
Labels: target: patch, action: merge, area: build & ci

#28253 refactor(@angular/ssr): remove duplicate `resetAngularServerApp` method
  packages/angular/ssr/src/app.ts
Labels: target: major, action: merge, area: @angular/ssr

#28245 refactor(@angular/build): remove automatic addition of `@angular/localize/init` polyfill and related warnings
  packages/angular/build/src/tools/esbuild/application-code-bundle.ts
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-workspace-config/migration.ts
  packages/schematics/angular/migrations/update-workspace-config/migration_spec.ts
Labels: target: major, action: merge, detected: breaking change

#28252 feat(@angular/ssr): improve handling of aborted requests in `AngularServerApp`
  goldens/circular-deps/packages.json
  packages/angular/ssr/private_export.ts
  packages/angular/ssr/src/app.ts
  packages/angular/ssr/src/render.ts
  packages/angular/ssr/test/app_spec.ts
Labels: target: major, action: merge, detected: feature, area: @angular/ssr

#28246 refactor(@angular-devkit/build-angular): remove deprecated `browserTarget`
  goldens/public-api/angular_devkit/build_angular/index.api.md
  modules/testing/builder/projects/hello-world-app/angular.json
  packages/angular/build/src/builders/dev-server/tests/behavior/build-inline-critical-css_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/options.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/schema.json
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build-inline-critical-css_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/serve-live-reload-proxies_spec.ts
  packages/angular_devkit/build_angular/src/builders/extract-i18n/options.ts
  packages/angular_devkit/build_angular/src/builders/extract-i18n/schema.json
  packages/schematics/angular/migrations/update-workspace-config/migration.ts
  packages/schematics/angular/utility/workspace-models.ts
  tests/legacy-cli/e2e/tests/i18n/setup.ts
Labels: target: major, action: merge, detected: breaking change

#28255 refactor(@schematics/angular): increase new application anyComponentSyle budget thresholds
  packages/schematics/angular/application/index.ts
Labels: target: major, action: merge

#28260 refactor(@angular/ssr): reorganize platform providers initialization in `AngularServerApp`
  packages/angular/ssr/src/app.ts
Labels: target: major, action: merge, area: @angular/ssr

#28263 build: update dependency zone.js to ~0.15.0 and angular
  .github/workflows/assistant-to-the-branch-manager.yml
  .github/workflows/ci.yml
  .github/workflows/dev-infra.yml
  .github/workflows/feature-requests.yml
  .github/workflows/pr.yml
  package.json
  packages/angular/ssr/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions/package.json
  tests/legacy-cli/e2e/assets/19-ssr-project-webpack/package.json
  tests/legacy-cli/e2e/ng-snapshot/package.json
  yarn.lock
Labels: target: major, action: merge, area: build & ci

#28264 Bump version to "v19.0.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#28265 build: clean up redundant `exclude` field from `tsconfig-build.json`
  tsconfig-build.json
Labels: target: patch, action: merge, area: build & ci

#28266 build: update material packages to 19.0.0-next.1
  package.json
  yarn.lock
Labels: target: major, action: merge, area: build & ci

#28267 fix(@angular/ssr): add missing peer dependency on `@angular/platform-server`
  packages/angular/ssr/package.json
  yarn.lock
Labels: target: major, action: merge, area: @angular/ssr

#28270 build: update dependency webpack to v5.94.0
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_webpack/package.json
  packages/ngtools/webpack/package.json
  packages/ngtools/webpack/src/ivy/plugin.ts
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#28272 ci: run modules and packages tests using a single bazel invocation
  .github/workflows/ci.yml
  .github/workflows/pr.yml
Labels: target: patch, action: merge, area: build & ci

#28268 feat(@schematics/angular): add option to export component as default
  packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
  packages/schematics/angular/component/index_spec.ts
  packages/schematics/angular/component/schema.json
Labels: area: @schematics/angular, action: merge, target: minor, detected: feature

#28284 refactor(@schematics/angular): move `@angular/ssr` dependency to server schematic
  packages/schematics/angular/server/index.ts
  packages/schematics/angular/ssr/index.ts
Labels: area: @schematics/angular, target: major, action: merge

#28286 refactor(@angular/ssr): relocate Node.js Request and Response Helpers to `/node` entry point
  packages/angular/ssr/BUILD.bazel
  packages/angular/ssr/node/src/request.ts
  packages/angular/ssr/node/src/response.ts
  packages/angular/ssr/node/test/BUILD.bazel
  packages/angular/ssr/node/test/request_spec.ts
  packages/angular/ssr/node/test/response_spec.ts
Labels: target: major, action: merge, area: @angular/ssr

#28288 build: prevent rollup from bundling `@angular/ssr` in `@angular/ssr/node`
  packages/angular/ssr/BUILD.bazel
Labels: target: major, action: merge, area: build & ci

#28294 build: update webpack to `5.94.0`
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/src/ivy/plugin.ts
  yarn.lock
Labels: target: patch, action: merge, area: build & ci

#28305 Bump version to "v19.0.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: target: major, action: merge

#28285 refactor(@angular/ssr): Add Utility Function for route extraction and tree creation
  packages/angular/ssr/private_export.ts
  packages/angular/ssr/src/routes/ng-routes.ts
  packages/angular/ssr/src/routes/router.ts
Labels: target: major, action: merge, area: @angular/ssr

#28313 fix(@angular-devkit/build-angular): upgrade webpack to `5.94.0`
  .circleci/dynamic_config.yml
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/named-chunks_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/stats-json_spec.ts
  packages/angular_devkit/build_angular/src/tools/webpack/plugins/builder-watch-plugin.ts
  packages/angular_devkit/build_angular/src/tools/webpack/plugins/common-js-usage-warn-plugin.ts
  packages/angular_devkit/build_angular/src/tools/webpack/plugins/styles-webpack-plugin.ts
  packages/ngtools/webpack/src/ivy/plugin.ts
  packages/ngtools/webpack/src/ivy/system.ts
  yarn.lock
Labels: action: merge, target: lts

#28315 fix(@angular-devkit/build-angular): clear context in Karma by default for single run executions
  packages/angular_devkit/build_angular/src/builders/karma/index.ts
  packages/schematics/angular/config/files/karma.conf.js.template
Labels: type: bug/fix, area: @angular-devkit/build-angular, target: patch, action: merge, devkit/build-angular:karma

#28318 Bump version to "v18.2.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#28319 docs: release notes for the v18.2.2 release
  CHANGELOG.md
Labels: area: docs, action: merge

#28316 fix(@angular-devkit/build-angular): clear context in Karma by default for single run executions
  packages/angular_devkit/build_angular/src/builders/karma/index.ts
  packages/schematics/angular/config/files/karma.conf.js.template
Labels: action: merge, target: lts

#28317 fix(@angular-devkit/build-angular): clear context in Karma by default for single run executions
  packages/angular_devkit/build_angular/src/builders/karma/index.ts
  packages/schematics/angular/config/files/karma.conf.js.template
Labels: action: merge, target: lts

#28320 Bump version to "v16.2.15" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#28322 docs: release notes for the v16.2.15 release
  CHANGELOG.md
Labels: area: docs, action: merge

#28323 Bump version to "v17.3.9" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#28324 docs: release notes for the v17.3.9 release
  CHANGELOG.md
Labels: area: docs, action: merge

#28306 refactor(@schematics/angular): remove explicit TypeScript lib option for new projects
  packages/schematics/angular/workspace/files/tsconfig.json.template
Labels: area: @schematics/angular, target: major, action: merge

#28328 test: update ssr UT to zoneless
  packages/angular/ssr/package.json
  packages/angular/ssr/test/BUILD.bazel
  packages/angular/ssr/test/app-engine_spec.ts
  packages/angular/ssr/test/app_spec.ts
  packages/angular/ssr/test/assets_spec.ts
  packages/angular/ssr/test/testing-utils.ts
  yarn.lock
Labels: target: major, action: merge, area: @angular/ssr
