Repository angular/angular-cli, pull requests merged in 2024-03, with the labels that each got.

#27184 refactor(@angular-devkit/build-angular): disable Piscina timing information recording
  packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
  packages/angular_devkit/build_angular/src/builders/prerender/index.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/parallel-compilation.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/i18n-inliner.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer.ts
  packages/angular_devkit/build_angular/src/tools/webpack/plugins/javascript-optimizer-plugin.ts
  packages/angular_devkit/build_angular/src/utils/action-executor.ts
  packages/angular_devkit/build_angular/src/utils/server-rendering/prerender.ts
Labels: action: merge, target: minor

#27183 fix(@angular-devkit/build-angular): avoid marking component styles as media with no output media directory
  packages/angular_devkit/build_angular/src/builders/application/tests/options/output-path_spec.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts
Labels: target: patch, action: merge

#27197 refactor(@angular-devkit/build-angular): use TextDecoder for index reading during index HTML generation
  packages/angular_devkit/build_angular/src/utils/index-file/index-html-generator.ts
  packages/angular_devkit/build_angular/src/utils/strip-bom.ts
Labels: action: merge, target: minor

#27198 refactor(@angular-devkit/build-angular): use async pipeline helper in HTML rewriting stream
  packages/angular_devkit/build_angular/src/utils/index-file/html-rewriting-stream.ts
Labels: action: merge, target: minor

#27199 refactor(@angular-devkit/build-angular): use Node.js builtin instead of custom removeColor helper
  packages/angular_devkit/build_angular/src/tools/webpack/utils/stats.ts
  packages/angular_devkit/build_angular/src/utils/color.ts
Labels: action: merge, target: minor

#27200 refactor(@angular-devkit/build-angular): remove extra exist check when purging stale build caches
  packages/angular_devkit/build_angular/src/utils/purge-cache.ts
Labels: action: merge, target: minor

#27079 typo fix
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/tools/webpack/plugins/typescript.ts
Labels: area: docs, target: patch, action: merge

#27202 refactor(@angular-devkit/build-angular): remove vite deprecation warning
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
Labels: action: merge, target: minor

#27204 build: lock file maintenance
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/core/src/json/schema/registry_spec.ts
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27170 Update CSS/Sass import/use specifiers in application migration
  packages/schematics/angular/migrations/update-17/css-import-lexer.ts
  packages/schematics/angular/migrations/update-17/use-application-builder.ts
  packages/schematics/angular/migrations/update-17/use-application-builder_spec.ts
Labels: action: merge, target: minor, detected: feature

#27193 fix(@angular-devkit/build-angular): disable `deployUrl` when using vite dev-server
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
Labels: target: patch, action: merge

#27210 refactor(@angular-devkit/build-angular): remove Webpack helpers from application builder option normalization
  packages/angular_devkit/build_angular/src/builders/application/options.ts
Labels: action: merge, target: minor

#27208 refactor(@angular-devkit/build-angular): remove unneeded relative URL modification for public path
  packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/global-styles.ts
Labels: action: merge, target: minor

#27214 ci: disable auto updates for `critters`
  renovate.json
Labels: action: merge, target: minor

#27216 Bump version to "v17.2.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27219 build: update dependencies for version 17.3.0
  packages/angular/pwa/package.json
  packages/angular/ssr/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/angular/utility/latest-versions/package.json
Labels: action: merge, area: build & ci, target: minor

#27222 Configure next branch to receive major changes for v18.0.0-next.0
  package.json
Labels: action: merge, target: minor

#27206 refactor(@schematics/angular): remove private `/components` API
  packages/schematics/angular/app-shell/index.ts
  packages/schematics/angular/package.json
  packages/schematics/angular/private/components.ts
  packages/schematics/angular/private/standalone.ts
  packages/schematics/angular/private/standalone_spec.ts
  packages/schematics/angular/service-worker/index.ts
  packages/schematics/angular/utility/ng-ast-utils.ts
Labels: target: major, action: merge

#27207 refactor(@angular-devkit/build-angular): remove Sass legacy implementation
  packages/angular_devkit/build_angular/src/tools/sass/sass-service-legacy.ts
  packages/angular_devkit/build_angular/src/tools/sass/worker-legacy.ts
  packages/angular_devkit/build_angular/src/tools/webpack/configs/styles.ts
  packages/angular_devkit/build_angular/src/utils/environment-options.ts
  tests/legacy-cli/e2e/tests/build/styles/scss-legacy.ts
Labels: target: major, action: merge, detected: breaking change

#27226 build: remove usage of built package from build script
  scripts/build.ts
Labels: action: merge, area: build & ci, target: minor

#27232 build: update TypeScript version to `~5.4.2`
  packages/angular_devkit/schematics_cli/blank/project-files/package.json
  packages/angular_devkit/schematics_cli/schematic/files/package.json
  packages/schematics/angular/utility/latest-versions/package.json
Labels: target: rc, action: merge, area: build & ci

#27215 Revert "ci: disable auto updates for `critters`"
  renovate.json
Labels: action: merge, target: minor

#27240 build: reduce amount of dev tsconfig paths entries
  tsconfig.json
Labels: action: merge, area: build & ci, target: minor

#27235 fix(@angular-devkit/build-angular): ensure proper display of build logs in the presence of warnings or errors
  packages/angular_devkit/build_angular/src/builders/application/build-action.ts
  packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
  packages/angular_devkit/build_angular/src/builders/application/index.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/bundler-execution-result.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
Labels: target: patch, action: merge

#27238 build: update dependencies for version 18.0.0
  packages/angular/pwa/package.json
  packages/angular/ssr/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
Labels: target: major, action: merge, area: build & ci

#27205 refactor(@angular-devkit/build-angular): add warnings for unsupported vite options
  packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/schema.json
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/disable-host-check_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/public-host_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
Labels: target: rc, action: merge

#27243 refactor(@angular-devkit/build-angular): improve i18n project option validation
  packages/angular_devkit/build_angular/src/utils/i18n-options.ts
Labels: action: merge, target: minor

#27242 refactor(@angular-devkit/build-angular): reduce usage of @angular-devkit/core types
  packages/angular_devkit/build_angular/src/builders/application/build-action.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
  packages/angular_devkit/build_angular/src/utils/normalize-asset-patterns.ts
  packages/angular_devkit/build_angular/src/utils/normalize-file-replacements.ts
  packages/angular_devkit/build_angular/src/utils/supported-browsers.ts
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
Labels: action: merge, target: minor

#27250 build: update dependency webpack-dev-server to v5
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build-assets_spec.ts
  packages/angular_devkit/build_angular/src/tools/webpack/configs/dev-server.ts
  packages/angular_devkit/build_webpack/package.json
  yarn.lock
Labels: target: major, action: merge, area: build & ci

#27255 build: update less-loader to v12.2.0
  package.json
  packages/angular_devkit/build_angular/package.json
  renovate.json
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27253 fix(@angular-devkit/build-angular): provide better error message when server option is required but missing
  packages/angular_devkit/build_angular/src/builders/application/options.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
Labels: target: patch, action: merge

#27263 refactor(@angular-devkit/build-angular): properly display errors originating in ESM loader hooks
  packages/angular_devkit/build_angular/src/utils/server-rendering/load-esm-from-memory.ts
  packages/angular_devkit/build_angular/src/utils/server-rendering/render-page.ts
  packages/angular_devkit/build_angular/src/utils/server-rendering/render-worker.ts
  packages/angular_devkit/build_angular/src/utils/server-rendering/routes-extractor-worker.ts
Labels: target: patch, action: merge

#27241 build: add infrastructure to build local-variant package outputs to main build script
  scripts/build-packages-dist.mts
Labels: action: merge, area: build & ci, target: minor

#27254 build: remove template string helpers from validation scripts
  scripts/validate-build-files.ts
  scripts/validate.ts
Labels: action: merge, area: build & ci, target: minor

#27266 feat(@schematics/angular): use TypeScript bundler module resolution for new projects
  packages/schematics/angular/workspace/files/tsconfig.json.template
Labels: target: major, action: merge, detected: feature

#27274 build: bump framework dependencies for minor release
  packages/angular/pwa/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/angular/utility/latest-versions/package.json
Labels: target: rc, action: merge, area: build & ci

#27275 build: bump `@angular/ssr` framework versions
  docs/process/release.md
  packages/angular/ssr/package.json
Labels: target: rc, action: merge, area: build & ci

#27276 Bump version to "v17.3.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27277 docs: release notes for the v17.3.0 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27283 refactor: remove `forceConsistentCasingInFileNames` from tsconfig files
  packages/schematics/angular/workspace/files/tsconfig.json.template
  tests/legacy-cli/e2e/assets/15.0-project/tsconfig.json
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/tsconfig.json
Labels: target: patch, action: merge

#27287 build: address issue with snapshot publishing due to non existing property
  scripts/snapshots.mts
Labels: target: major, action: merge, area: build & ci

#27288 build: address issue with snapshot publishing due incorrect property access
  scripts/snapshots.mts
Labels: target: major, action: merge, area: build & ci

#27294 refactor .idea directory
  .idea/angular-cli.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/runConfigurations/Large_Tests.xml
  .idea/runConfigurations/Large_Tests__Debug_.xml
  .idea/runConfigurations/Tests.xml
  .idea/runConfigurations/Tests__Debug_.xml
  .idea/vcs.xml
Labels: target: patch, action: merge

#27293 perf(@angular-devkit/build-angular): avoid transforming empty component stylesheets
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/angular-host.ts
Labels: target: patch, action: merge

#27303 build: update ng-dev config to work with Node.js 18.19
  .ng-dev/commit-message.mjs
  .ng-dev/release.mjs
  .ng-dev/tsconfig.json
  lib/packages.mjs
  package.json
  packages/angular/cli/src/commands/command-config.ts
  packages/angular_devkit/schematics/tasks/package-manager/link-task.ts
  scripts/release-checks/dependency-ranges/index.mts
  scripts/release-checks/dependency-ranges/peer-deps-check.mts
Labels: target: patch, action: merge, area: build & ci

#27304 refactor(@angular/cli): remove unneeded devkit core tag helper usage
  packages/angular/cli/src/command-builder/utilities/schematic-workflow.ts
  packages/angular/cli/src/commands/add/cli.ts
  packages/angular/cli/src/commands/update/schematic/index.ts
Labels: action: merge, target: minor

#27311 fix(@angular-devkit/build-angular): typo in allowedHosts warning for unsupported vite options
  packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
Labels: target: patch, action: merge

#27308 fix(@angular-devkit/build-angular): only generate `server` directory when SSR is enabled
  packages/angular_devkit/build_angular/src/builders/application/build-action.ts
  packages/angular_devkit/build_angular/src/builders/application/tests/options/ssr_spec.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
Labels: target: patch, action: merge

#27312 fix(@schematics/angular): improve Sass format clarity for application style option
  packages/schematics/angular/application/schema.json
Labels: target: patch, action: merge

#27324 docs: release notes for the v17.3.1 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27329 build: a couple of tweaks and fixes to `yarn admin create`.
  scripts/build.mts
  scripts/create.mts
  scripts/devkit-admin.mts
Labels: target: major, action: merge, area: build & ci

#27330 fix(@angular-devkit/build-angular): `Internal server error: Invalid URL` when using a non localhost IP
  packages/angular_devkit/build_angular/src/tools/vite/angular-memory-plugin.ts
Labels: target: patch, action: merge

#27331 Bump version to "v18.0.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge

#27335 fix(@angular-devkit/build-angular): update `webpack-dev-middleware` to `6.1.2`
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge

#27333 fix(@schematics/angular): rename SSR port env variable
  packages/angular_devkit/build_angular/src/builders/ssr-dev-server/index.ts
  packages/angular_devkit/build_angular/src/builders/ssr-dev-server/specs/proxy_spec.ts
  packages/angular_devkit/build_angular/src/builders/ssr-dev-server/specs/ssl_spec.ts
  packages/angular_devkit/build_angular/src/builders/ssr-dev-server/specs/works_spec.ts
  packages/schematics/angular/migrations/update-17/replace-nguniversal-engines.ts
  packages/schematics/angular/migrations/update-17/replace-nguniversal-engines_spec.ts
  packages/schematics/angular/ssr/files/application-builder/server.ts.template
  packages/schematics/angular/ssr/files/server-builder/server.ts.template
  tests/legacy-cli/e2e/assets/18-ssr-project-webpack/server.ts
Labels: target: patch, action: merge

#27332 refactor(@angular-devkit/build-angular): directly configure internal babel plugins for application builder
  packages/angular_devkit/build_angular/src/tools/babel/plugins/index.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer-worker.ts
Labels: action: merge, target: minor

#27352 fix(@angular-devkit/build-angular): service-worker references non-existent named index output
  packages/angular_devkit/build_angular/src/builders/application/execute-post-bundle.ts
  packages/angular_devkit/build_angular/src/builders/application/options.ts
  packages/angular_devkit/build_angular/src/builders/application/tests/options/service-worker_spec.ts
  packages/angular_devkit/build_angular/src/utils/service-worker.ts
Labels: target: patch, action: merge

#27355 fix(@angular-devkit/build-angular): ensure proper resolution of linked SCSS files
  packages/angular_devkit/build_angular/src/tools/sass/rebasing-importer.ts
Labels: target: patch, action: merge

#27357 Bump version to "v15.2.11" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27358 docs: release notes for the v15.2.11 release
  CHANGELOG.md
Labels: action: merge

#27359 Bump version to "v16.2.13" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27360 docs: release notes for the v16.2.13 release
  CHANGELOG.md
Labels: action: merge

#27361 Bump version to "v17.3.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27006 feat(@schematics/angular): replace `assets` with `public` directory
  goldens/public-api/angular_devkit/build_angular/index.md
  packages/angular/pwa/pwa/files/assets/manifest.webmanifest
  packages/angular/pwa/pwa/index.ts
  packages/angular/pwa/pwa/index_spec.ts
  packages/angular_devkit/build_angular/src/builders/application/schema.json
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/schema.json
  packages/angular_devkit/build_angular/src/builders/browser/schema.json
  packages/angular_devkit/build_angular/src/builders/karma/schema.json
  packages/angular_devkit/build_angular/src/builders/server/schema.json
  packages/angular_devkit/build_angular/src/builders/web-test-runner/schema.json
  packages/angular_devkit/build_angular/src/tools/webpack/utils/helpers.ts
  packages/angular_devkit/build_angular/src/utils/normalize-asset-patterns.ts
  packages/schematics/angular/application/files/common-files/public/favicon.ico.template
  packages/schematics/angular/application/files/common-files/src/assets/.gitkeep.template
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/service-worker/files/ngsw-config.json.template
  packages/schematics/angular/service-worker/index.ts
  packages/schematics/angular/service-worker/index_spec.ts
  tests/legacy-cli/e2e/tests/build/assets.ts
  tests/legacy-cli/e2e/tests/build/css-urls.ts
  tests/legacy-cli/e2e/tests/build/multiple-configs.ts
  tests/legacy-cli/e2e/tests/build/prerender/http-requests-assets.ts
  tests/legacy-cli/e2e/tests/commands/add/add-pwa.ts
  tests/legacy-cli/e2e/tests/commands/add/npm-env-vars.ts
  tests/legacy-cli/e2e/tests/commands/add/registry-option.ts
  tests/legacy-cli/e2e/tests/commands/add/secure-registry.ts
  tests/legacy-cli/e2e/tests/commands/add/yarn-env-vars.ts
  tests/legacy-cli/e2e/tests/commands/config/config-get.ts
  tests/legacy-cli/e2e/tests/commands/serve/assets.ts
  tests/legacy-cli/e2e/tests/commands/serve/ssr-http-requests-assets.ts
  tests/legacy-cli/e2e/utils/fs.ts
Labels: target: major, action: merge, detected: feature

#27366 build: address pre-release validation failure
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/angular/utility/latest-versions/package.json
  scripts/release-checks/dependency-ranges/latest-versions-check.mts
Labels: target: major, action: merge, area: build & ci

#27368 refactor(@angular-devkit/build-angular): update babel application preset with new plugin import location
  packages/angular_devkit/build_angular/src/tools/babel/presets/application.ts
Labels: target: major, action: merge

#27370 build: address pre-release validation failure
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/angular/utility/latest-versions/package.json
  scripts/release-checks/dependency-ranges/latest-versions-check.mts
Labels: target: patch, action: merge, area: build & ci

#27372 build: narrow down supported TypeScript versions
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  tests/legacy-cli/e2e/assets/18-ssr-project-webpack/package.json
Labels: target: major, action: merge, area: build & ci

#27382 refactor(@angular-devkit/build-angular): use build version stamping for build cache path creation
  packages/angular_devkit/build_angular/src/utils/normalize-cache.ts
Labels: target: major, action: merge

#27381 refactor(@angular-devkit/build-angular): remove unneeded package version from inline font cache key
  packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
Labels: target: major, action: merge

#27380 build: update @bazel/buildifier to v7.1.0
  package.json
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27388 fix(@schematics/angular): add spaces around eventCoalescing option
  packages/schematics/angular/application/files/standalone-files/src/app/app.config.ts.template
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/utility/standalone/rules_spec.ts
Labels: target: major, action: merge
