Repository angular/angular-cli, pull requests merged in 2024-01, with the labels that each got.

#26775 build: add function type annotation for bazel win32 build support
  packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer-worker.ts
Labels: action: merge, area: build & ci, target: minor

#26766 fix(@angular-devkit/schematics): replace template line endings with platform specific
  packages/angular_devkit/schematics/src/rules/template.ts
Labels: target: patch, action: merge

#26779 build: update all non-major dependencies
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#26780 fix(@angular/cli): add prerender and ssr-dev-server schemas in angular.json schema
  packages/angular/cli/BUILD.bazel
  packages/angular/cli/lib/config/workspace-schema.json
Labels: target: patch, action: merge

#26784 Bump version to "v17.0.9" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#26785 docs: release notes for the v17.0.9 release
  CHANGELOG.md
Labels: area: docs, action: merge

#26787 Bump version to "v17.1.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#26794 ci: disable WTR e2e test on Windows
  tests/legacy-cli/e2e/utils/web-test-runner.ts
Labels: target: rc, action: merge, area: build & ci

#26791 ci: add `ci-*` to GitHub actions config
  .github/workflows/ci.yml
Labels: target: patch, action: merge, area: build & ci

#26790 refactor: remove `process.cwd` from Web Test Runner builder
  packages/angular_devkit/build_angular/src/builders/web-test-runner/index.ts
Labels: target: rc, action: merge

#26795 ci: fix `sauce-connect-proxy` version
  yarn.lock
Labels: target: rc, action: merge, area: build & ci

#26796 fix(@angular-devkit/build-angular): show diagnostic messages after build stats
  packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/bundler-execution-result.ts
Labels: target: rc, action: merge

#26802 refactor(@schematics/angular): update server schematic to use new dependency utility
  packages/schematics/angular/server/index.ts
Labels: target: patch, action: merge

#26805 fix(@angular-devkit/build-angular): fix normalization of the application builder extensions
  packages/angular_devkit/build_angular/src/builders/application/index.ts
Labels: target: rc, action: merge

#26814 refactor(@angular-devkit/build-angular): add experimental builder selector extension for dev-server
  goldens/public-api/angular_devkit/build_angular/index.md
  packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
Labels: target: rc, action: merge

#26820 ci: remove daily CI run for v13.x
  .circleci/config.yml
Labels: action: merge, target: lts

#26821 ci: remove daily CI run for v14.x
  .circleci/dynamic_config.yml
Labels: action: merge, target: lts

#26824 Revert "build: update dependency webpack-dev-middleware to v7"
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: action: merge, target: minor

#26827 build: update zone.js to 0.14.3
  packages/schematics/angular/utility/latest-versions/package.json
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/package.json
Labels: target: rc, action: merge, area: build & ci

#26835 refactor(@angular/cli): change Twitter icon in the application schematic
  packages/schematics/angular/application/files/common-files/src/app/app.component.html.template
Labels: target: patch, action: merge

#26838 Bump version to "v17.0.10" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#26840 docs: release notes for the v17.0.10 release
  CHANGELOG.md
Labels: area: docs, action: merge

#26842 Bump version to "v17.1.0-rc.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#26843 docs: release notes for the v17.1.0-rc.1 release
  CHANGELOG.md
Labels: area: docs, action: merge

#26815 feat(@angular-devkit/build-angular): provide default and abbreviated build target support for dev-server and extract-i18n
  goldens/public-api/angular_devkit/architect/index.md
  packages/angular_devkit/architect/src/api.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/options.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/schema.json
  packages/angular_devkit/build_angular/src/builders/extract-i18n/options.ts
  packages/angular_devkit/build_angular/src/builders/extract-i18n/schema.json
Labels: action: merge, target: minor, detected: feature

#26852 fix: ignore custom Jest configuration file and warn if one is found
  packages/angular_devkit/build_angular/src/builders/jest/index.ts
  packages/angular_devkit/build_angular/src/builders/jest/jest.config.mjs
  tests/legacy-cli/e2e/tests/jest/custom-config.ts
Labels: type: bug/fix, action: merge, target: minor, devkit/build-angular:jest

#26861 refactor(@angular-devkit/build-angular): allow internal Angular compilation control of diagnostic modes
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/angular-compilation.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/aot-compilation.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/index.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/jit-compilation.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/parallel-compilation.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/parallel-worker.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
  packages/angular_devkit/build_angular/src/utils/environment-options.ts
Labels: action: merge, target: minor

#26871 fix(@angular-devkit/build-angular): alllow `OPTIONS` requests to be proxied when using `vite`
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
Labels: target: rc, action: merge

#26890 build: update Angular version ranges for stable v17.1
  package.json
  packages/angular/pwa/package.json
  packages/angular/ssr/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/angular/utility/latest-versions/package.json
  yarn.lock
Labels: target: rc, action: merge, area: build & ci

#26891 Bump version to "v17.1.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#26892 docs: release notes for the v17.1.0 release
  CHANGELOG.md
Labels: area: docs, action: merge

#26903 refactor(@angular-devkit/build-angular): move Angular memory Vite plugin into separate file
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
  packages/angular_devkit/build_angular/src/tools/vite/angular-memory-plugin.ts
Labels: target: patch, action: merge

#26919 fix(@angular-devkit/build-angular): update dependency vite to v4.5.2
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: action: merge, target: lts

#26915 fix(@angular-devkit/build-angular): `ENOENT: no such file or directory` on Windows during component rebuild
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/component-stylesheets.ts
Labels: target: patch, action: merge

#26920 fix(@angular-devkit/build-angular): do not add internal CSS resources files in watch
  packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/css-resource-plugin.ts
Labels: target: patch, action: merge

#26913 fix(@angular-devkit/build-angular): pre-transform error when using vite with SSR
  packages/angular_devkit/build_angular/src/tools/vite/angular-memory-plugin.ts
Labels: target: patch, action: merge

#26923 fix(@angular-devkit/build-angular): allow package file loader option with Vite prebundling
  packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/external-packages-plugin.ts
Labels: target: patch, action: merge

#26924 fix(@angular/cli): update regex to validate the project-name
  packages/angular/cli/lib/config/workspace-schema.json
Labels: target: patch, action: merge

#26930 fix(@angular-devkit/build-angular): update dependency vite to v5.0.12
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge

#26929 fix(@schematics/angular): retain trailing comma when adding providers to app config
  packages/schematics/angular/utility/standalone/rules.ts
  packages/schematics/angular/utility/standalone/rules_spec.ts
Labels: target: patch, action: merge

#26936 refactor(@angular-devkit/build-angular): update Vite client code loading for v5
  packages/angular_devkit/build_angular/src/tools/vite/angular-memory-plugin.ts
Labels: action: merge, target: minor

#26944 docs: release notes for the v16.2.12 release
  CHANGELOG.md
Labels: area: docs, action: merge

#26945 Bump version to "v17.1.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#26931 fix(@angular-devkit/build-angular): return 404 for assets that are not found
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build-assets_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
  packages/angular_devkit/build_angular/src/tools/vite/angular-memory-plugin.ts
Labels: target: patch, action: merge

#26952 build: update angular to 17.2.0-next
  package.json
  packages/angular/pwa/package.json
  packages/angular/ssr/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions.ts
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#26954 Bump version to "v17.2.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge

#26963 refactor: simplify husky setup
  .husky/commit-msg
  .husky/pre-commit
  .husky/prepare-commit-msg
  package.json
Labels: action: merge, target: minor

#26956 fix(@angular-devkit/build-angular): add `required` modules as externals imports
  packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts
Labels: target: patch, action: merge

#26957 refactor(@angular-devkit/build-angular): disable SW and index generation during i18n extraction
  packages/angular_devkit/build_angular/src/builders/extract-i18n/application-extraction.ts
Labels: target: patch, action: merge

#26955 refactor(@angular-devkit/build-angular): increase type safety in bundle-context
  packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts
Labels: target: patch, action: merge

#26965 refactor(@angular-devkit/core): remove single usage of const enum
  goldens/public-api/angular_devkit/core/index.md
  packages/angular_devkit/core/src/virtual-fs/host/interface.ts
Labels: action: merge, target: minor

#26966 refactor: remove outdated namespace syntax usage
  goldens/public-api/angular_devkit/architect/index.md
  goldens/public-api/angular_devkit/core/index.md
  packages/angular_devkit/architect/src/jobs/index.ts
  packages/angular_devkit/architect/src/jobs/strategy.ts
  packages/angular_devkit/architect/src/jobs/strategy_spec.ts
  packages/angular_devkit/core/src/virtual-fs/host/index.ts
  packages/angular_devkit/core/src/virtual-fs/host/record_spec.ts
  packages/angular_devkit/core/src/virtual-fs/host/test.ts
  packages/angular_devkit/core/src/virtual-fs/host/test_spec.ts
  packages/angular_devkit/schematics/src/tree/interface.ts
Labels: action: merge, target: minor

#26973 fix(@angular-devkit/build-angular): resolve absolute `output-path` when using esbuild based builders
  packages/angular_devkit/build_angular/src/builders/application/options.ts
Labels: target: patch, action: merge

#26974 fix(@angular-devkit/build-angular): correctly handle glob negation in proxy config when using vite
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/proxy-config_spec.ts
  packages/angular_devkit/build_angular/src/utils/load-proxy-config.ts
Labels: target: patch, action: merge

#26971 refactor(@angular-devkit/build-angular): remove dependency on `text-table`
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/tools/webpack/utils/stats.ts
  yarn.lock
Labels: action: merge, target: minor

#26975 fix(@angular-devkit/build-angular): handle regular expressions in proxy config when using Vite
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/proxy-config_spec.ts
  packages/angular_devkit/build_angular/src/utils/load-proxy-config.ts
Labels: target: patch, action: merge

#26880 refactor(@schematics/angular): remove private `/components` API
  packages/schematics/angular/package.json
  packages/schematics/angular/private/components.ts
Labels: action: merge, target: minor

#26990 refactor(@angular-devkit/build-angular): remove babel core runtime imports from `pure-toplevel-functions` build optimizer pass
  packages/angular_devkit/build_angular/src/tools/babel/plugins/pure-toplevel-functions.ts
Labels: action: merge, target: minor

#26989 refactor(@angular-devkit/build-angular): remove babel core runtime imports from `elide-angular-metadata` build optimizer pass
  packages/angular_devkit/build_angular/src/tools/babel/plugins/elide-angular-metadata.ts
Labels: action: merge, target: minor

#27000 feat(@angular-devkit/build-angular): support using custom postcss configuration with application builder
  packages/angular_devkit/build_angular/src/builders/application/options.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/compiler-plugin-options.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/global-styles.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/bundle-options.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts
  packages/angular_devkit/build_angular/src/utils/postcss-configuration.ts
Labels: action: merge, target: minor, detected: feature

#26995 feat(@angular-devkit/build-angular): add JSON build logs when using the application builder
  packages/angular_devkit/build_angular/src/builders/application/build-action.ts
  packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
  packages/angular_devkit/build_angular/src/builders/application/index.ts
  packages/angular_devkit/build_angular/src/builders/application/options.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/bundler-execution-result.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/global-scripts.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
  packages/angular_devkit/build_angular/src/utils/environment-options.ts
Labels: action: merge, target: minor, detected: feature

#27009 Bump version to "v17.1.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27011 docs: release notes for the v17.1.2 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27012 Bump version to "v17.2.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge
