Repository angular/angular-cli, pull requests merged in 2024-05, with the labels that each got.

#27564 fix(@angular/cli): add `@angular/build` package to update group
  packages/angular/cli/package.json
Labels: target: rc, action: merge

#27574 docs: release notes for the v18.0.0-rc.0 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27572 build: replace `@angular/build` version with archive in local builds
  packages/angular_devkit/build_angular/BUILD.bazel
Labels: target: rc, action: merge, area: build & ci

#27566 fix(@schematics/angular): add postcss dependency in application migration if needed
  packages/schematics/angular/migrations/use-application-builder/migration.ts
  packages/schematics/angular/migrations/use-application-builder/migration_spec.ts
  packages/schematics/angular/utility/latest-versions/package.json
Labels: target: rc, action: merge

#27575 fix(@angular-devkit/architect): resolve builder aliases from containing package
  packages/angular_devkit/architect/node/node-modules-architect-host.ts
Labels: target: rc, action: merge

#27578 build: update all non-major dependencies
  package.json
  packages/angular/build/package.json
  packages/angular/build/src/tools/sass/worker.ts
  packages/angular/cli/package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: rc, action: merge, area: build & ci

#27579 fix(@angular/build): add a maximum rendering timeout for SSG
  packages/angular/build/src/utils/server-rendering/render-page.ts
  packages/angular_devkit/build_angular/src/builders/app-shell/render-worker.ts
Labels: target: rc, action: merge

#27581 fix(@angular/build): only generate shallow preload links for initial files
  packages/angular/build/src/tools/esbuild/bundler-context.ts
  packages/angular/build/src/tools/esbuild/index-html-generator.ts
Labels: target: rc, action: merge

#27582 Bump version to "v18.0.0-rc.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27583 docs: release notes for the v18.0.0-rc.1 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27592 fix(@angular/build): decode URL pathname decoding during SSG fetch
  packages/angular/build/src/utils/server-rendering/fetch-patch.ts
  tests/legacy-cli/e2e/tests/build/prerender/http-requests-assets.ts
Labels: target: rc, action: merge

#27594 fix(@angular-devkit/build-angular): decode URL pathname decoding during SSG fetch
  packages/angular_devkit/build_angular/src/utils/server-rendering/fetch-patch.ts
  tests/legacy-cli/e2e/tests/build/prerender/http-requests-assets.ts
Labels: target: patch, action: merge

#27597 build: replace lodash.template with lodash v4.17.21
  package.json
  scripts/templates.mts
  scripts/validate-user-analytics.mts
  yarn.lock
Labels: target: rc, action: merge, area: build & ci

#27599 refactor(@schematics/angular): link for ignoring files
  packages/schematics/angular/workspace/files/__dot__gitignore.template
Labels: target: patch, action: merge

#27602 fix(@angular/build): format sizes using decimal byte units consistently
  packages/angular/build/src/utils/bundle-calculator_spec.ts
  packages/angular/build/src/utils/format-bytes.ts
  packages/angular/build/src/utils/format-bytes_spec.ts
  packages/schematics/angular/application/index.ts
Labels: target: rc, action: merge

#27604 ci: update Renovate configuration: replace `matchPackagePatterns` with `matchDepPatterns`
  renovate.json
Labels: target: rc, action: merge, area: build & ci

#27608 refactor(@angular/build): show unexpected Sass import resolution errors
  packages/angular/build/src/tools/sass/rebasing-importer.ts
  packages/angular/build/src/tools/sass/worker.ts
Labels: target: rc, action: merge

#27614 Bump version to "v17.3.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27615 docs: release notes for the v17.3.7 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27617 Bump version to "v18.0.0-rc.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27618 docs: release notes for the v18.0.0-rc.2 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27620 fix(@angular/build): ensure recreated files are watched
  packages/angular/build/src/builders/application/build-action.ts
  packages/angular/build/src/builders/application/tests/behavior/rebuild-general_spec.ts
Labels: target: rc, action: merge

#27622 fix(@angular/build): properly rebase Sass url() values with leading interpolations
  packages/angular/build/src/builders/application/tests/behavior/stylesheet-url-resolution_spec.ts
  packages/angular/build/src/tools/sass/rebasing-importer.ts
Labels: target: rc, action: merge

#27627 refactor(@angular/build): use piscina-based worker pool for Sass rendering
  packages/angular/build/src/tools/sass/sass-service.ts
  packages/angular/build/src/tools/sass/worker.ts
Labels: target: rc, action: merge

#27630 fix(@angular/cli): clarify optional migration instructions during ng update
  packages/angular/cli/src/commands/update/cli.ts
Labels: target: patch, action: merge

#27632 refactor(@angular/build): remove orphane file
  packages/angular/build/src/utils/index-file/style-nonce.ts
  packages/angular/build/src/utils/index-file/style-nonce_spec.ts
Labels: target: rc, action: merge

#27634 refactor: replace angular.io link with angular.dev
  packages/angular/build/src/tools/esbuild/commonjs-checker.ts
  packages/angular_devkit/build_angular/src/tools/webpack/plugins/common-js-usage-warn-plugin.ts
Labels: target: rc, action: merge

#27641 refactor(@angular/build): add error as part of error notes
  packages/angular/build/src/tools/esbuild/stylesheets/css-inline-fonts-plugin.ts
Labels: target: rc, action: merge

#27642 perf(@angular/build): improve rebuild time for file loader usage with prebundling
  packages/angular/build/src/builders/dev-server/vite-server.ts
  packages/angular/build/src/tools/esbuild/external-packages-plugin.ts
Labels: target: rc, action: merge

#27644 fix(@angular-devkit/schematics): `SchematicTestRunner.runExternalSchematic` fails with "The encoded data was not valid for encoding utf-8"
  packages/angular_devkit/schematics/src/rules/template.ts
  packages/angular_devkit/schematics/src/tree/host-tree.ts
Labels: target: patch, action: merge

#27646 refactor(@angular-devkit/schematics): reduce direct rxjs usage in filter host tree
  packages/angular_devkit/schematics/src/tree/host-tree.ts
Labels: target: rc, action: merge

#27647 fix(@angular/build): add console note about development server raw file size
  packages/angular/build/src/builders/dev-server/vite-server.ts
Labels: target: rc, action: merge

#27648 refactor(@angular/build): cleanup persistent JS transformer cache on plugin dispose
  packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
Labels: target: rc, action: merge

#27653 build: update angular
  .github/workflows/assistant-to-the-branch-manager.yml
  .github/workflows/ci.yml
  .github/workflows/dev-infra.yml
  .github/workflows/feature-requests.yml
  package.json
  packages/angular/build/src/utils/index-file/add-event-dispatch-contract_spec.ts
  packages/ngtools/webpack/package.json
  tests/legacy-cli/e2e/ng-snapshot/package.json
  yarn.lock
Labels: target: rc, action: merge, area: build & ci

#27655 fix(@angular/cli): change update guide link to angular.dev
  README.md
  packages/angular/build/src/utils/version.ts
  packages/angular/cli/src/commands/update/cli.ts
  packages/angular/cli/src/commands/update/long-description.md
  scripts/templates/readme.ejs
Labels: target: rc, action: merge

#27656 refactor(@angular/cli): use prompt helper functions in analytics and completion commands
  packages/angular/cli/src/analytics/analytics.ts
  packages/angular/cli/src/utilities/completion.ts
Labels: target: rc, action: merge

#27667 fix(@angular/build): correctly wrap class expressions with static properties or blocks emitted by esbuild
  packages/angular/build/src/tools/babel/plugins/adjust-static-class-members.ts
  packages/angular/build/src/tools/babel/plugins/adjust-static-class-members_spec.ts
Labels: target: rc, action: merge

#27669 refactor: replace vite `server.ws.send` usages
  packages/angular/build/src/builders/dev-server/vite-server.ts
Labels: target: rc, action: merge

#27671 Bump version to "v18.0.0-rc.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27672 docs: release notes for the v18.0.0-rc.3 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27673 fix(@angular/cli): only add --version option on default command
  packages/angular/cli/src/command-builder/command-runner.ts
  tests/legacy-cli/e2e/tests/commands/help/help-json.ts
Labels: target: rc, action: merge

#27681 Bump version to "v17.3.8" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27682 docs: release notes for the v17.3.8 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27683 build: update Angular packages to v18 stable
  package.json
  packages/angular/build/package.json
  packages/angular/ssr/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions/package.json
  tests/legacy-cli/e2e/assets/18-ssr-project-webpack/package.json
  yarn.lock
Labels: target: rc, action: merge, area: build & ci

#27685 docs: release notes for the v18.0.0 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27687 fix(@angular/build): only import persistent cache store with active caching
  packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
Labels: target: patch, action: merge

#27692 fix(@angular/build): avoid rebasing URLs with function calls
  packages/angular/build/src/tools/sass/rebasing-importer.ts
  tests/legacy-cli/e2e/tests/build/styles/bootstrap.ts
Labels: target: patch, action: merge

#27696 fix(@angular/build): handle esbuild-browser `polyfills` option as `string` during `ng serve`
  packages/angular/build/src/builders/dev-server/vite-server.ts
Labels: target: patch, action: merge

#27694 fix(@schematics/angular): use angular.dev in readme
  packages/schematics/angular/library/files/README.md.template
  packages/schematics/angular/workspace/files/README.md.template
Labels: target: patch, action: merge

#27697 fix(@angular/build): disable persistent disk caching inside webcontainers by default
  packages/angular/build/src/utils/normalize-cache.ts
Labels: target: patch, action: merge

#27699 Bump version to "v18.0.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27701 docs: release notes for the v18.0.1 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27703 fix(@angular/build): support valid self-closing SVG tags in HTML index file
  packages/angular/build/src/utils/index-file/augment-index-html.ts
  packages/angular/build/src/utils/index-file/valid-self-closing-tags.ts
Labels: target: patch, action: merge

#27707 fix(@schematics/angular): check both application builder packages in SSR schematic
  packages/schematics/angular/ssr/index.ts
  packages/schematics/angular/utility/standalone/util.ts
  packages/schematics/angular/utility/workspace-models.ts
Labels: target: patch, action: merge

#27704 ci: always run snapshot E2E tests on main CI
  .github/workflows/ci.yml
Labels: target: patch, action: merge, area: build & ci

#27725 fix(@angular/build): disable Worker wait loop for Sass compilations in web containers
  packages/angular/build/src/tools/sass/sass-service.ts
Labels: target: patch, action: merge

#27732 fix(@angular/build): print Sass `@warn` location
  packages/angular/build/src/tools/esbuild/stylesheets/sass-language.ts
Labels: target: patch, action: merge

#27741 Bump version to "v18.0.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27744 build: update framework packages to 18.1.0-next.0
  package.json
  packages/angular/build/package.json
  packages/angular/pwa/package.json
  packages/angular/ssr/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions/package.json
  tests/legacy-cli/e2e/tests/build/material.ts
  tests/legacy-cli/e2e/tests/commands/add/add-material.ts
  tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27746 Bump version to "v18.1.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge

#27745 test: remove E2E tests that are covered by integration tests
  tests/legacy-cli/e2e/tests/build/deploy-url.ts
  tests/legacy-cli/e2e/tests/build/json.ts
Labels: target: patch, action: merge

#27740 perf(@angular/build): enable dependency prebundling for server dependencies
  packages/angular/build/src/builders/application/setup-bundling.ts
  packages/angular/build/src/builders/dev-server/vite-server.ts
Labels: action: merge, target: minor

#27758 fix(@angular/build): disable JS transformer persistent cache on web containers
  packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
Labels: target: patch, action: merge

#27759 fix(@schematics/angular): generate new projects with ECMAScript standard class field behavior
  modules/testing/builder/projects/hello-world-app/tsconfig.json
  packages/angular_devkit/build_angular/src/builders/browser/specs/lazy-module_spec.ts
  packages/schematics/angular/workspace/files/tsconfig.json.template
  tests/legacy-cli/e2e/tests/misc/safari-15-class-properties.ts
  tests/legacy-cli/e2e/tests/misc/third-party-decorators.ts
Labels: action: merge, target: minor
