Repository angular/angular-cli, pull requests merged in 2024-04, with the labels that each got.

#27397 build: add missing dep in test to fix CI
  tests/legacy-cli/e2e/assets/18-ssr-project-webpack/package.json
Labels: action: merge, area: build & ci, target: minor

#27398 build: add missing dep in test to fix CI
  tests/legacy-cli/e2e/assets/17-ssr-project-webpack/package.json
Labels: target: patch, action: merge, area: build & ci

#27399 Revert "fix(@schematics/angular): rename SSR port env variable"
  packages/angular_devkit/build_angular/src/builders/ssr-dev-server/index.ts
  packages/angular_devkit/build_angular/src/builders/ssr-dev-server/specs/proxy_spec.ts
  packages/angular_devkit/build_angular/src/builders/ssr-dev-server/specs/ssl_spec.ts
  packages/angular_devkit/build_angular/src/builders/ssr-dev-server/specs/works_spec.ts
  packages/schematics/angular/migrations/update-17/replace-nguniversal-engines.ts
  packages/schematics/angular/migrations/update-17/replace-nguniversal-engines_spec.ts
  packages/schematics/angular/ssr/files/application-builder/server.ts.template
  packages/schematics/angular/ssr/files/server-builder/server.ts.template
  tests/legacy-cli/e2e/assets/18-ssr-project-webpack/server.ts
Labels: target: patch, action: merge

#27401 Bump version to "v17.3.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27402 docs: release notes for the v17.3.3 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27407 Bump version to "v18.0.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27408 ci: disable updating `build_bazel_rules_nodejs`
  renovate.json
Labels: target: major, action: merge, area: build & ci

#27429 build: update `vite` and `undici`
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: target: patch, action: merge, area: build & ci

#27430 fix(@angular-devkit/build-angular): update vite to `4.5.3`
  package.json
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: action: merge, target: lts

#27431 fix(@angular-devkit/build-angular): ensure esbuild-based builders exclusively produce ESM output
  packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
Labels: target: patch, action: merge

#27428 build: update all non-major dependencies
  WORKSPACE
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/tools/sass/sass-service.ts
  packages/angular_devkit/build_angular/src/tools/sass/worker.ts
  packages/angular_devkit/schematics/package.json
  yarn.lock
Labels: target: major, action: merge, area: build & ci

#27434 build: remove `eslintignore` file
  .eslintignore
  .eslintrc.json
Labels: target: major, action: merge, area: build & ci

#27435 refactor(@angular-devkit/architect): allow aliasing builder names in package builder manifest
  packages/angular_devkit/architect/node/node-modules-architect-host.ts
  packages/angular_devkit/architect/src/builders-schema.json
Labels: target: major, action: merge

#27442 docs: fix image url for completion command
  packages/angular/cli/src/commands/completion/long-description.md
Labels: area: docs, target: major, action: merge

#27444 build: update dependency http-proxy-middleware to v3
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
  packages/angular_devkit/build_angular/src/builders/ssr-dev-server/index.ts
  packages/angular_devkit/build_angular/src/utils/load-proxy-config.ts
  yarn.lock
Labels: target: major, action: merge, area: build & ci

#27443 fix(@angular-devkit/build-angular): do not generate an `index.html` file in the browser directory when using SSR.
  packages/angular_devkit/build_angular/src/builders/application/options.ts
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/index-preload-hints_spec.ts
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-errors_spec.ts
  packages/angular_devkit/build_angular/src/builders/application/tests/options/index_spec.ts
  packages/schematics/angular/ssr/files/application-builder/server.ts.template
Labels: target: major, action: merge, detected: breaking change

#27450 refactor(@angular-devkit/build-angular): directly resolve asset files in application builder
  packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
  packages/angular_devkit/build_angular/src/utils/resolve-assets.ts
Labels: target: major, action: merge

#27455 Bump version to "v16.2.14" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27457 docs: release notes for the v16.2.14 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27458 Bump version to "v17.3.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27459 docs: release notes for the v17.3.4 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27448 refactor(@angular-devkit/build-angular): split Webpack-specific functionality from i18n option creation
  packages/angular_devkit/build_angular/src/builders/browser/index.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/webpack-server.ts
  packages/angular_devkit/build_angular/src/builders/server/index.ts
  packages/angular_devkit/build_angular/src/utils/action-executor.ts
  packages/angular_devkit/build_angular/src/utils/i18n-inlining.ts
  packages/angular_devkit/build_angular/src/utils/i18n-options.ts
  packages/angular_devkit/build_angular/src/utils/i18n-webpack.ts
  packages/angular_devkit/build_angular/src/utils/output-paths.ts
  packages/angular_devkit/build_angular/src/utils/process-bundle.ts
  packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
Labels: target: major, action: merge

#27456 feat(@angular-devkit/build-angular): enhance Sass rebasing importer for resources URL defined in variables and handling of external paths
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/stylesheet-url-resolution_spec.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/css-resource-plugin.ts
  packages/angular_devkit/build_angular/src/tools/sass/rebasing-importer.ts
Labels: target: major, action: merge, detected: feature

#27465 refactor(@angular-devkit/build-angular): reduce Webpack specific overlap in stats table generation
  goldens/circular-deps/packages.json
  packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
  packages/angular_devkit/build_angular/src/tools/webpack/utils/stats.ts
  packages/angular_devkit/build_angular/src/utils/bundle-calculator.ts
  packages/angular_devkit/build_angular/src/utils/format-bytes.ts
  packages/angular_devkit/build_angular/src/utils/stats-table.ts
Labels: target: major, action: merge

#27460 refactor(@angular-devkit/build-angular): reduce Webpack specific overlap in bundle budget calculator
  packages/angular_devkit/build_angular/src/tools/webpack/plugins/any-component-style-budget-checker.ts
  packages/angular_devkit/build_angular/src/utils/bundle-calculator.ts
  packages/angular_devkit/build_angular/src/utils/bundle-calculator_spec.ts
Labels: target: major, action: merge

#27481 refactor: replace vite `server.ws.send` usages
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
Labels: action: merge, target: minor

#27482 fix(@angular-devkit/build-angular): remove `type="text/css"` from `style` tag
  packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
Labels: target: patch, action: merge

#27472 test: move builder testing infrastructure to separate bazel target module
  .eslintrc.json
  .github/workflows/ci.yml
  .prettierignore
  modules/testing/builder/BUILD.bazel
  modules/testing/builder/projects/hello-world-app/.browserslistrc
  modules/testing/builder/projects/hello-world-app/.editorconfig
  modules/testing/builder/projects/hello-world-app/.gitignore
  modules/testing/builder/projects/hello-world-app/README.md
  modules/testing/builder/projects/hello-world-app/angular.json
  modules/testing/builder/projects/hello-world-app/e2e/app.e2e-spec.ts
  modules/testing/builder/projects/hello-world-app/e2e/app.po.ts
  modules/testing/builder/projects/hello-world-app/e2e/tsconfig.e2e.json
  modules/testing/builder/projects/hello-world-app/karma.conf.js
  modules/testing/builder/projects/hello-world-app/protractor.conf.js
  modules/testing/builder/projects/hello-world-app/src/app/app.component.css
  modules/testing/builder/projects/hello-world-app/src/app/app.component.html
  modules/testing/builder/projects/hello-world-app/src/app/app.component.spec.ts
  modules/testing/builder/projects/hello-world-app/src/app/app.component.ts
  modules/testing/builder/projects/hello-world-app/src/app/app.module.server.ts
  modules/testing/builder/projects/hello-world-app/src/app/app.module.ts
  modules/testing/builder/projects/hello-world-app/src/assets/.gitkeep
  modules/testing/builder/projects/hello-world-app/src/favicon.ico
  modules/testing/builder/projects/hello-world-app/src/index.html
  modules/testing/builder/projects/hello-world-app/src/locale/messages.xlf
  modules/testing/builder/projects/hello-world-app/src/main.server.ts
  modules/testing/builder/projects/hello-world-app/src/main.ts
  modules/testing/builder/projects/hello-world-app/src/ngsw-config.json
  modules/testing/builder/projects/hello-world-app/src/polyfills.ts
  modules/testing/builder/projects/hello-world-app/src/spectrum.png
  modules/testing/builder/projects/hello-world-app/src/styles.css
  modules/testing/builder/projects/hello-world-app/src/tsconfig.app.json
  modules/testing/builder/projects/hello-world-app/src/tsconfig.server.json
  modules/testing/builder/projects/hello-world-app/src/tsconfig.spec.json
  modules/testing/builder/projects/hello-world-app/src/typings.d.ts
  modules/testing/builder/projects/hello-world-app/tsconfig.json
  modules/testing/builder/src/builder-harness.ts
  modules/testing/builder/src/builder-harness_spec.ts
  modules/testing/builder/src/file-watching.ts
  modules/testing/builder/src/index.ts
  modules/testing/builder/src/jasmine-helpers.ts
  modules/testing/builder/src/test-utils.ts
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/named-chunks_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/execute-fetch.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/jasmine-helpers.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/proxy-config_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/setup.ts
  packages/angular_devkit/build_angular/src/testing/index.ts
  packages/angular_devkit/build_angular/src/testing/test-utils.ts
Labels: target: major, action: merge

#27487 Bump version to "v17.3.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27488 docs: release notes for the v17.3.5 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27480 feat(@angular-devkit/build-angular): inject event-dispatcher in SSR HTML page
  packages/angular_devkit/build_angular/src/builders/application/execute-post-bundle.ts
  packages/angular_devkit/build_angular/src/builders/browser/index.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/index-html-generator.ts
  packages/angular_devkit/build_angular/src/tools/webpack/plugins/index-html-webpack-plugin.ts
  packages/angular_devkit/build_angular/src/utils/index-file/add-event-dispatch-contract.ts
  packages/angular_devkit/build_angular/src/utils/index-file/add-event-dispatch-contract_spec.ts
  packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html.ts
  packages/angular_devkit/build_angular/src/utils/index-file/index-html-generator.ts
  packages/angular_devkit/build_angular/src/utils/index-file/nonce.ts
  packages/angular_devkit/build_angular/src/utils/index-file/nonce_spec.ts
Labels: target: major, action: merge, detected: feature

#27489 Bump version to "v18.0.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27486 feat(@angular-devkit/build-angular): support native async/await when app is zoneless
  packages/angular_devkit/build_angular/src/builders/application/tests/behavior/browser-support_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
  packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
Labels: target: major, action: merge, detected: feature

#27493 refactor: remove v17 migrations
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-17/add-browser-sync-dependency.ts
  packages/schematics/angular/migrations/update-17/add-browser-sync-dependency_spec.ts
  packages/schematics/angular/migrations/update-17/replace-nguniversal-builders.ts
  packages/schematics/angular/migrations/update-17/replace-nguniversal-builders_spec.ts
  packages/schematics/angular/migrations/update-17/replace-nguniversal-engines.ts
  packages/schematics/angular/migrations/update-17/replace-nguniversal-engines_spec.ts
  packages/schematics/angular/migrations/update-17/update-workspace-config.ts
  packages/schematics/angular/migrations/update-17/update-workspace-config_spec.ts
  packages/schematics/angular/migrations/use-application-builder/css-import-lexer.ts
  packages/schematics/angular/migrations/use-application-builder/migration.ts
  packages/schematics/angular/migrations/use-application-builder/migration_spec.ts
Labels: target: major, action: merge

#27497 build: adjust create project script to ensure all built packages are used
  scripts/create.mts
Labels: target: major, action: merge, area: build & ci

#27517 fix(@angular/build): properly configure headers for media resources and HTML page
  packages/angular/build/src/builders/dev-server/tests/options/headers_spec.ts
  packages/angular/build/src/builders/dev-server/vite-server.ts
Labels: action: merge, target: minor

#27516 build: remove bootstrap and jquery from dev dependencies
  package.json
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/src/builders/browser/specs/styles_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser/tests/options/allowed-common-js-dependencies_spec.ts
  yarn.lock
Labels: target: major, action: merge, area: build & ci

#27518 fix(@angular-devkit/build-angular): properly configure headers for media resources and HTML page
  packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/headers_spec.ts
  packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
Labels: target: patch, action: merge

#27519 feat(@angular-devkit/build-angular): move i18n extraction for application builder to new build system package
  goldens/public-api/angular/build/index.md
  packages/angular/build/BUILD.bazel
  packages/angular/build/builders.json
  packages/angular/build/src/builders/extract-i18n/application-extraction.ts
  packages/angular/build/src/builders/extract-i18n/builder.ts
  packages/angular/build/src/builders/extract-i18n/index.ts
  packages/angular/build/src/builders/extract-i18n/options.ts
  packages/angular/build/src/builders/extract-i18n/schema.json
  packages/angular/build/src/index.ts
  packages/angular/cli/BUILD.bazel
  packages/angular/cli/lib/config/workspace-schema.json
Labels: target: major, action: merge, detected: feature

#27520 feat(@schematics/angular): allow application migration to use new build package in projects where possible
  packages/schematics/angular/migrations/use-application-builder/migration.ts
Labels: target: major, action: merge, detected: feature

#27524 refactor(@angular/build): move less stylesheet preprocessor to an optional peer dependency
  packages/angular/build/package.json
  packages/angular/build/src/tools/esbuild/stylesheets/less-language.ts
Labels: target: major, action: merge

#27525 refactor(@angular/build): remove Webpack-specific options from Vite-only dev-server
  goldens/public-api/angular/build/index.md
  packages/angular/build/src/builders/dev-server/builder.ts
  packages/angular/build/src/builders/dev-server/options.ts
  packages/angular/build/src/builders/dev-server/schema.json
  packages/angular/build/src/builders/dev-server/tests/options/allowed-hosts_spec.ts
  packages/angular/build/src/builders/dev-server/tests/options/disable-host-check_spec.ts
  packages/angular/build/src/builders/dev-server/tests/options/force-esbuild_spec.ts
  packages/angular/build/src/builders/dev-server/tests/options/public-host_spec.ts
Labels: target: major, action: merge

#27530 feat(@angular/cli): support for Node.js v22
  .github/workflows/ci.yml
  WORKSPACE
  constants.bzl
  package.json
  packages/angular/cli/src/commands/version/cli.ts
  tools/toolchain_info.bzl
Labels: action: merge, target: minor, detected: feature

#27529 fix(@angular/build): emit error for invalid self-closing element in index HTML
  packages/angular/build/src/utils/index-file/augment-index-html.ts
  packages/angular/build/src/utils/index-file/augment-index-html_spec.ts
Labels: target: major, action: merge

#27533 test: update regexp in ssr-error-stack E2E test for Node.js 22 on Windows
  tests/legacy-cli/e2e/tests/vite/ssr-error-stack.ts
Labels: target: major, action: merge

#27521 docs: add explanation of how to set up a new NPM package in Wombat
  docs/process/release.md
Labels: area: docs, target: patch, action: merge

#27535 Bump version to "v17.3.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27536 docs: release notes for the v17.3.6 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27537 Bump version to "v18.0.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27538 fix(@angular/build): check both potential build packages in Angular version check
  packages/angular/build/src/utils/version.ts
Labels: target: major, action: merge

#27543 fix(@angular/build): add missing `ansi-colors` and `picomatch` dependencies
  packages/angular/build/BUILD.bazel
  packages/angular/build/package.json
Labels: target: major, action: merge

#27545 build: correctly set `@angular/build` version in snapshots
  constants.bzl
  tests/legacy-cli/e2e/utils/project.ts
Labels: target: major, action: merge, area: build & ci

#27547 Bump version to "v18.0.0-next.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27549 refactor(@angular/build): update private exports for additional usage
  packages/angular/build/src/private.ts
Labels: target: rc, action: merge

#27559 fix(@schematics/angular): add less dependency in application migration if needed
  packages/schematics/angular/migrations/use-application-builder/migration.ts
  packages/schematics/angular/migrations/use-application-builder/migration_spec.ts
  packages/schematics/angular/utility/latest-versions/package.json
Labels: target: rc, action: merge

#27561 refactor(@angular/build): move postcss stylesheet processor to an optional peer dependency
  packages/angular/build/package.json
  packages/angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts
Labels: target: rc, action: merge
