Repository angular/angular-cli, pull requests merged in 2024-07, with the labels that each got.

#27968 build: update all non-major dependencies
  package.json
  packages/angular/build/package.json
  packages/angular/build/src/tools/esbuild/application-code-bundle.ts
  packages/angular/cli/package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/schematics_cli/package.json
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27972 fix(@angular/build): allow top-level await in zoneless applications
  packages/angular/build/src/tools/esbuild/utils.ts
Labels: target: rc, action: merge

#27970 test: re-enable localize warning check
  tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts
Labels: target: rc, action: merge

#27977 fix(@angular-devkit/build-angular): rollback terser to `5.29.2`
  package.json
  packages/angular_devkit/build_angular/package.json
  renovate.json
  yarn.lock
Labels: target: rc, action: merge

#27979 fix(@angular/build): support import attributes in JavaScript transformer
  package.json
  packages/angular/build/BUILD.bazel
  packages/angular/build/package.json
  packages/angular/build/src/tools/esbuild/javascript-transformer-worker.ts
  yarn.lock
Labels: target: rc, action: merge

#27980 build: update @discovery/json-ext to v0.6.0
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/tools/webpack/plugins/json-stats-plugin.ts
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27973 feat(@angular/build): support WASM/ES Module integration proposal
  packages/angular/build/src/builders/application/tests/behavior/wasm-esm_spec.ts
  packages/angular/build/src/tools/esbuild/application-code-bundle.ts
  packages/angular/build/src/tools/esbuild/wasm-plugin.ts
  packages/angular/build/src/tools/esbuild/wasm.d.ts
  tests/legacy-cli/e2e.bzl
  tests/legacy-cli/e2e/tests/build/wasm-esm.ts
Labels: target: rc, action: merge, detected: feature

#27986 Bump version to "v18.0.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27987 docs: release notes for the v18.0.7 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27989 Bump version to "v18.1.0-rc.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#27990 docs: release notes for the v18.1.0-rc.1 release
  CHANGELOG.md
Labels: area: docs, action: merge

#27992 fix(@angular/build): check inlineSourceMap option with isolated modules optimization
  packages/angular/build/src/tools/angular/compilation/aot-compilation.ts
  packages/angular/build/src/tools/angular/compilation/parallel-worker.ts
  packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
Labels: target: rc, action: merge

#27995 refactor: use explicit coercion of exitCode to number.
  scripts/devkit-admin.mts
Labels: target: rc, action: merge

#28008 build: remove unused bazel rules
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#27988 feat(@schematics/angular): use isolatedModules in generated project
  packages/schematics/angular/workspace/files/tsconfig.json.template
Labels: action: merge, target: minor, detected: feature

#28010 refactor(@angular/build): remove direct usage of undici dependency for SSR
  packages/angular/build/BUILD.bazel
  packages/angular/build/package.json
  packages/angular/build/src/utils/server-rendering/fetch-patch.ts
  packages/angular_devkit/build_angular/BUILD.bazel
  packages/angular_devkit/build_angular/package.json
  yarn.lock
Labels: action: merge, target: minor

#28012 fix(@angular/build): read WASM file from script location on Node.js
  packages/angular/build/src/tools/esbuild/wasm-plugin.ts
  tests/legacy-cli/e2e/tests/build/wasm-esm.ts
Labels: target: rc, action: merge

#28017 refactor(@angular/cli): use Node.js CommonJS wrapping for schematic encapsulation
  packages/angular/cli/src/command-builder/utilities/schematic-engine-host.ts
Labels: action: merge, target: minor

#28020 ci: allow terser to be updated by renovate
  renovate.json
Labels: action: merge, area: build & ci, target: minor

#28021 build: update Angular dependencies to version 18.1.0
  package.json
  packages/angular/build/package.json
  packages/angular/build/src/builders/application/tests/behavior/browser-support_spec.ts
  packages/angular/pwa/package.json
  packages/angular/ssr/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions/package.json
  yarn.lock
Labels: target: rc, action: merge, area: build & ci

#28023 Bump version to "v18.1.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#28024 docs: release notes for the v18.1.0 release
  CHANGELOG.md
Labels: area: docs, action: merge

#28022 build: update Angular dependencies to version 18.2.0-next.0
  package.json
  packages/angular/build/package.json
  packages/angular/build/src/builders/application/tests/behavior/browser-support_spec.ts
  packages/angular/pwa/package.json
  packages/angular/ssr/package.json
  packages/angular_devkit/build_angular/package.json
  packages/ngtools/webpack/package.json
  packages/schematics/angular/utility/latest-versions/package.json
  yarn.lock
Labels: action: merge, area: build & ci, target: minor

#28025 Bump version to "v18.2.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge

#28029 refactor(@angular/build): use `listr2` for spinner and color support
  packages/angular/build/BUILD.bazel
  packages/angular/build/package.json
  packages/angular/build/src/builders/application/options.ts
  packages/angular/build/src/tools/esbuild/utils.ts
  packages/angular/build/src/utils/color.ts
  packages/angular/build/src/utils/spinner.ts
  tests/legacy-cli/e2e/tests/build/progress-and-stats.ts
  yarn.lock
Labels: action: merge, target: minor

#28031 test: use Node.js argument parser for E2E test runner
  tests/legacy-cli/BUILD.bazel
  tests/legacy-cli/e2e.bzl
  tests/legacy-cli/e2e/initialize/500-create-project.ts
  tests/legacy-cli/e2e/initialize/BUILD.bazel
  tests/legacy-cli/e2e/utils/BUILD.bazel
  tests/legacy-cli/e2e/utils/project.ts
  tests/legacy-cli/e2e_runner.ts
Labels: action: merge, target: minor

#28037 fix(@angular-devkit/build-angular): skip undefined files when generat…
  packages/angular/build/src/tools/esbuild/budget-stats.ts
Labels: target: patch, action: merge

#28040 feat(@angular/build): support import attribute based loader configuration
  packages/angular/build/src/builders/application/tests/behavior/loader-import-attribute_spec.ts
  packages/angular/build/src/tools/esbuild/application-code-bundle.ts
  packages/angular/build/src/tools/esbuild/loader-import-attribute-plugin.ts
Labels: action: merge, target: minor, detected: feature

#28039 fix(@angular/build): remove Vite "/@id/" prefix for explicit external dependencies
  packages/angular/build/src/builders/dev-server/tests/behavior/build-external-dependencies_spec.ts
  packages/angular/build/src/builders/dev-server/vite-server.ts
  packages/angular/build/src/tools/vite/id-prefix-plugin.ts
Labels: target: patch, action: merge

#28056 build: run async task in concurrent
  scripts/templates.mts
Labels: target: patch, action: merge, area: build & ci

#28060 refactor: rename internal vite plugin name.
  packages/angular/build/src/tools/vite/id-prefix-plugin.ts
Labels: action: merge, target: minor

#28065 Bump version to "v18.1.1" with changelog.
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#28066 docs: release notes for the v18.1.1 release
  CHANGELOG.md
Labels: area: docs, action: merge

#28067 Bump version to "v18.2.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: minor

#28070 ci: remove unused `dependency-review-config.yml`
  .github/dependency-review-config.yml
  .github/workflows/pr.yml
Labels: action: merge, area: build & ci, target: minor

#28072 fix(@angular/build): prevent redirection loop
  packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts
Labels: target: patch, action: merge

#28080 fix(@angular/build): account for HTML base HREF for dev-server externals
  packages/angular/build/src/builders/dev-server/tests/behavior/build-external-dependencies_spec.ts
  packages/angular/build/src/tools/vite/id-prefix-plugin.ts
Labels: action: merge, target: minor

#28076 refactor(@angular/build): provide structured application builder result types
  packages/angular/build/src/builders/application/build-action.ts
  packages/angular/build/src/builders/application/execute-build.ts
  packages/angular/build/src/builders/application/index.ts
  packages/angular/build/src/builders/application/results.ts
  packages/angular/build/src/builders/application/tests/options/output-path_spec.ts
  packages/angular/build/src/builders/dev-server/vite-server.ts
  packages/angular/build/src/builders/extract-i18n/application-extraction.ts
  packages/angular/build/src/builders/extract-i18n/builder.ts
  packages/angular/build/src/private.ts
  packages/angular/build/src/tools/esbuild/bundler-execution-result.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/assets_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/delete-output-path_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/deploy-url_spec.ts
  packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/main_spec.ts
  packages/angular_devkit/build_angular/src/builders/extract-i18n/application-extraction.ts
  packages/angular_devkit/build_angular/src/builders/extract-i18n/builder.ts
  packages/angular_devkit/build_angular/src/builders/web-test-runner/index.ts
Labels: action: merge, target: minor

#28085 fix(@angular/build): account for HTML base HREF for dev-server externals
  packages/angular/build/src/builders/dev-server/tests/behavior/build-external-dependencies_spec.ts
  packages/angular/build/src/tools/vite/id-prefix-plugin.ts
Labels: target: patch, action: merge

#28069 fix(@angular/build): serve HTML files directly
  packages/angular/build/src/tools/vite/middlewares/index-html-middleware.ts
Labels: target: patch, action: merge

#28086 fix(@angular/build): correctly detect comma in Sass URL lexer
  packages/angular/build/src/tools/sass/lexer.ts
  packages/angular/build/src/tools/sass/lexer_spec.ts
Labels: target: patch, action: merge

#28106 Bump version to "v18.1.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#28107 docs: release notes for the v18.1.2 release
  CHANGELOG.md
Labels: area: docs, action: merge

#28108 Bump version to "v18.2.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#28115 fix(@angular/build): resolve error with `extract-i18n` builder for libraries
  packages/angular/build/src/builders/extract-i18n/builder.ts
  packages/angular_devkit/build_angular/src/builders/extract-i18n/builder.ts
Labels: target: patch, action: merge

#28114 fix(@angular/build): add CSP `nonce` attribute to script tags when inline critical CSS is disabled
  packages/angular/build/src/builders/application/tests/behavior/csp-nonce_spec.ts
  packages/angular/build/src/utils/index-file/index-html-generator.ts
Labels: target: patch, action: merge

#28131 ci: replace `matchDepPatterns` with `matchPackageNames`
  renovate.json
Labels: action: merge, area: build & ci, target: minor

#28116 fix(@angular/build): prevent build failures with remote CSS imports when Tailwind is configured
  packages/angular/build/src/tools/esbuild/stylesheets/bundle-options.ts
  packages/angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts
  tests/legacy-cli/e2e/tests/build/styles/tailwind-v3.ts
Labels: target: patch, action: merge

#28144 Bump version to "v18.1.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#28145 docs: release notes for the v18.1.3 release
  CHANGELOG.md
Labels: area: docs, action: merge

#28146 Bump version to "v18.2.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge
